CHANGELOG.md, package.json, src/apolloServer.js, test/testApolloServer.js
=> update graphql version

CONTRIBUTING.md, DESIGN.md, ROADMAP.md
Outlines a roadmap and possible designs for upcoming features. Pull requests for those features are very welcome!
=> Design docs + roadmap

package.json
=> Add RC to version

CHANGELOG.md, package.json, src/index.ts, src/integrations/connectApollo.test.ts, src/integrations/connectApollo.ts, src/integrations/expressApollo.ts, src/test/tests.ts, typings.json
This PR adds support for connect by making a few minor changes to the express version
TODO:
=> Add support for connect

src/index.ts
=> add missing graphiql export for Koa

package.json
=> Move some dependencies to devDependencies

src/index.ts, src/integrations/expressApollo.test.ts, src/integrations/expressApollo.ts, src/integrations/integrations.test.ts, src/integrations/koaApollo.test.ts, src/integrations/koaApollo.ts, src/modules/operationStore.test.ts
Does what it says 🎈 
Working through the list in #62
=> More tests

package.json
=> update hapi version to 14.0.0

.travis.yml, package.json
fix post install for projects that are not using typescript
=> fix post install

README.md, src/index.ts, typings.json
=> update TypeScript dependencies and documentation

src/core/runQuery.ts
=> move request.end before formatResponse

CHANGELOG.md, package.json
=> Version 0.2.5

CHANGELOG.md, README.md, src/index.ts
=> Expose OperationStore

README.md
=> Fix connect import on README

README.md
=> Align ApolloHAPI instructions with current version on NPM & apollostack.com

package.json
=> Moved boom to dependencies

CHANGELOG.md, README.md
Fixing the readme example for connect, along with https://github.com/apollostack/tools-docs/pull/17
TODO:
=> Fix readme example for using connect.js

src/integrations/hapiApollo.ts, src/integrations/integrations.test.ts
@stubailo @helfer This fixes the following issue: #158 
TODO:
=> fix initial introspection query for Hapi

CHANGELOG.md, package.json, packages/graphql-server-express/src/apolloServerHttp.test.ts
=> Update Graphql-js to 0.8.1 (fixes test)

CHANGELOG.md, packages/graphql-server-module-graphiql/src/renderGraphiQL.ts
=> chore(package): update graphiql version from 0.7.1 to 0.8.0

README.md
small docs change, might help other users realize what dependencies there are
=> Update README with koa body parser dependency

README.md
TODO:
Added body-parser import..
=> Improved express sample in README.md

README.md
Exact versions commented after imports.
=> updated README to show versions of dependencies required for graphql-server-koa

CHANGELOG.md, lerna.json
=> Version 0.4.4

lerna.json, packages/graphql-server-core/package.json, packages/graphql-server-express/package.json, packages/graphql-server-hapi/package.json, packages/graphql-server-integration-testsuite/package.json, packages/graphql-server-koa/package.json, packages/graphql-server-module-graphiql/package.json, packages/graphql-server-module-operation-store/package.json
Still learning lerna. Should be all good now.
=> Real 0.4.4

README.md
@helfer :)
i suggest to do it for the reset of the repos.
also i think a fix for package.json is needed as well..
=> chore(package):fix badges in readme after org rename.

lerna.json, package.json, packages/graphql-server-express/package.json, packages/graphql-server-hapi/package.json, packages/graphql-server-integration-testsuite/package.json, packages/graphql-server-integration-testsuite/src/index.ts, packages/graphql-server-koa/package.json, packages/graphql-server-lambda/package.json, packages/graphql-server-restify/package.json
lerna's devDep patch is finally merged. :)
=> Update internal depencies & update lerna back to upstream npm

README.md
As suggested by @helfer in https://github.com/apollographql/graphql-server/issues/217#issuecomment-285598429
TODO:
=> Update README with an application/graphql example

CHANGELOG.md, packages/graphql-server-module-graphiql/src/renderGraphiQL.ts
=> Fix broken endpointURL

packages/graphql-server-module-graphiql/src/renderGraphiQL.ts
=> add back passHeader

lerna.json
=> Update lerna to latest version

packages/graphql-server-hapi/src/hapiApollo.ts
@helfer this should fix the master branch which got broken because of the typings change.
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/f20d1e1c2c8811b1db46a3cc2f082f30e4503c7c
this is the commit of the breaking change.
=> chore(hapi): fix typings rename

packages/graphql-server-express/src/apolloServerHttp.test.ts, packages/graphql-server-express/src/expressApollo.ts, packages/graphql-server-hapi/src/hapiApollo.ts
This is still WIP (I have to leave to pick up my kid from preschool). I'll continue working on this tomorrow, but I wanted to get a few eyes on it to see if I'm heading in the right direction. 
Closes #313
=> Pass through unknown errors

packages/graphql-server-lambda/README.md
=> Fix README typos

README.md
=> Use const instead of var

packages/graphql-server-integration-testsuite/src/index.ts
=> Fix typings to correct promise return type

CHANGELOG.md, lerna.json, packages/apollo-server-express/src/expressApollo.ts
=> Revert calling next in middleware

README.md
Just documentation updates - no actual code changes.
Added graphiqlKoa example, as other examples had graphiql examples.
=> add graphiqlKoa example to README

CHANGELOG.md, packages/apollo-server-micro/package.json
=> updated zeit/micro to 8.0.1

packages/apollo-server-express/README.md
No CHANGELOG update required as this is only a doc update.
=> Name changes that were missed

CHANGELOG.md, README.md, packages/apollo-server-restify/README.md, packages/apollo-server-restify/package.json, packages/apollo-server-restify/src/restifyApollo.test.ts
Update restify lib for apollo-server-restify. Referring to issue: #472
=> Update restify lib

packages/apollo-server-module-graphiql/src/renderGraphiQL.ts
Missing code documentation for PR #484
=> Add documentation for GraphiQL editorTheme

packages/apollo-server-lambda/README.md
=> Recommend to use the latest node version for Lambda

CHANGELOG.md, packages/apollo-server-lambda/README.md
=> Update README: Rename graphql-server-lambda -> apollo-server-lambda 

README.md
quick readme addition to explain how to use graphiql
=> docs: add graphiql usage to express example code

README.md
AWS Lambda doc link included
TODO:
=> Docs: Update AWS Lambda supported Node versions

packages/apollo-server-core/package.json
Reverts apollographql/apollo-server#602
=> Revert "fix(deps): update dependency apollo-tracing to ^0.0.8"

README.md
Fixes https://github.com/apollographql/apollo-server/issues/664
Tested in https://github.com/apollographql/apollo-engine-js/pull/31/commits/83fd88ce2f27b322f275e79a5e29d4a43275d8e8
(All N/A as this is just a documentation change?)
=> apollo-server-express: document query middleware

README.md, packages/apollo-server-adonis/.npmignore, packages/apollo-server-adonis/README.md, packages/apollo-server-adonis/package.json, packages/apollo-server-adonis/src/adonisApollo.test.ts, packages/apollo-server-adonis/src/adonisApollo.ts, packages/apollo-server-adonis/src/index.ts, packages/apollo-server-adonis/tsconfig.json, packages/apollo-server-core/src/runHttpQuery.ts, test/tests.js
Implementation for [Adonis Framework](http://adonisjs.com/)
=> add server for adonis framework

CHANGELOG.md, packages/apollo-server-micro/package.json
=> chore: update peerDependencies version for micro

CONTRIBUTING.md, README.md, docs/_config.yml, docs/source/example.md, docs/source/graphiql.md, docs/source/index.md, docs/source/requests.md, docs/source/servers/adonis.md, docs/source/servers/azure-functions.md, docs/source/servers/express.md, docs/source/servers/hapi.md, docs/source/servers/koa.md, docs/source/servers/lambda.md, docs/source/servers/micro.md, docs/source/servers/restify.md, docs/source/setup.md, packages/apollo-server-adonis/README.md, packages/apollo-server-azure-functions/README.md, packages/apollo-server-core/README.md, packages/apollo-server-express/README.md, packages/apollo-server-hapi/README.md, packages/apollo-server-koa/README.md, packages/apollo-server-lambda/README.md, packages/apollo-server-micro/README.md, packages/apollo-server-module-graphiql/README.md, packages/apollo-server-module-operation-store/README.md, packages/apollo-server-restify/README.md
Total overhaul of the docs. Notable improvements:
1. Added sidebar pages for all of the servers, by symlinking the READMEs
2. Added a complete end-to-end example you can copy-paste and run right away
3. Added much better API docs for server options
=> Docs improvements

CHANGELOG.md, lerna.json, package.json, packages/apollo-server-adonis/package.json, packages/apollo-server-azure-functions/package.json, packages/apollo-server-core/package.json, packages/apollo-server-core/src/runQuery.test.ts, packages/apollo-server-express/package.json, packages/apollo-server-express/src/apolloServerHttp.test.ts, packages/apollo-server-hapi/package.json, packages/apollo-server-integration-testsuite/package.json, packages/apollo-server-koa/package.json, packages/apollo-server-lambda/package.json, packages/apollo-server-micro/package.json, packages/apollo-server-module-graphiql/package.json, packages/apollo-server-module-operation-store/package.json, packages/apollo-server-module-operation-store/src/operationStore.test.ts, packages/apollo-server-restify/package.json, packages/graphql-server-core/package.json, packages/graphql-server-express/package.json, packages/graphql-server-hapi/package.json, packages/graphql-server-koa/package.json, packages/graphql-server-lambda/package.json, packages/graphql-server-micro/package.json, packages/graphql-server-module-graphiql/package.json, packages/graphql-server-module-operation-store/package.json, packages/graphql-server-restify/package.json
=> Update to graphql@0.12

docs/source/index.md
TODO:
* [NA] Update CHANGELOG.md with your change (include reference to issue & this PR)
* [NA] Make sure all of the significant new logic is covered by tests
* [NA] Make sure all tests and linter rules pass
=> Fixed the link to the requests doc

docs/_config.yml
=> Improve related docs section

docs/source/essentials/server.md
This introduces the changes for the "Running a server" portion of the Apollo Server does in preparation for `apollo-server` 2.0! (#979).  This PR is targeted toward #942.
=> docs: Essentials / Server (now, with middleware!)

packages/apollo-server-lambda/README.md
Hello 👋
This PR just fixes a small typo in the Lambda package documentation. The word _name_ accidentally appeared twice.
=> docs: Fix typo in lambda package README

docs/source/best-practices/performance.md, docs/source/best-practices/schema-design.md, docs/source/best-practices/security.md, docs/source/essentials/schema.md
This is just a partial pass, but thought it would be better to get the
merge conflicts in soon rather than later.
=> docs: Editorial Pass

docs/package.json, docs/source/essentials/data.md
I added a couple notes on places I'm not sure about.
=> [Work in Progress] docs: essentials > data

docs/source/best-practices/schema-design.md, docs/source/essentials/data.md, docs/source/essentials/querying.md, docs/source/essentials/schema.md, docs/source/essentials/server.md, docs/source/features/resolvers.md, docs/source/schemas/organization.md
=> Restructured essentials

docs/source/migration-two-dot.md
=> Change grammar

docs/_config.yml
=> Fix broken links on apollo engine, graphql-tools

docs/source/api/apollo-server.html, docs/source/api/apollo-server.md
=> Add registerServer method

docs/source/getting-started.md
=> Fix the link

docs/source/essentials/server.md
=> [wip] fix Server Essentials for new API.

docs/source/essentials/server.md
=> refactor code on server essentials page

docs/source/features/schema-delegation.md, docs/source/whats-new.md, docs/source/why-apollo-server.md
Adds code snippets and features in what's new
Also includes case studies
=> Code snippets/features in whats new docs and add case studies

docs/source/graphiql.md
=> fix graphiql docs for hapi

docs/source/setup.md
Two tiny typos fixed in this tiny PR.
=> Fix typos in setup.md

docs/source/api/apollo-server.md, docs/source/features/errors.md, docs/source/migration-two-dot.md
=> Update Apollo Server docs, gql, middleware

docs/_config.yml, docs/source/api/apollo-server.md, docs/source/features/logging.md, docs/source/getting-started.md, docs/source/migration-two-dot.md
Adds logging section and fleshes out the middlware transition guide
fixes #1117
=> Apollo Server 2: Additional Docuementation

docs/source/migration-two-dot.md
=> Change  to  in new pattern of using apollo server 2

docs/source/features/errors.md, packages/apollo-server-core/src/errors.test.ts, packages/apollo-server-core/src/errors.ts, packages/apollo-server-core/src/index.ts, packages/apollo-server/src/exports.ts
Changes made to code and the docs. Once this is merged, I will update the medium blog post too!
=> Rename BadUserInputError to UserInputError

docs/source/features/data-sources.md, packages/apollo-server-caching/README.md, packages/apollo-server-memcached/README.md, packages/apollo-server-memcached/__tests__/Memcached.test.ts, packages/apollo-server-memcached/src/index.ts, packages/apollo-server-redis/README.md, packages/apollo-server-redis/__tests__/Redis.test.ts, packages/apollo-server-redis/src/index.ts
Also provides direction for the community to implement `KeyValueCache` to implement their own cache.
=> [WIP] Add documentation for using Redis/Memcached with Data Sources

packages/apollo-server-core/package.json
=> Add missing apollo-upload-server dependency

docs/source/deployment/lambda.md
=> Apollo Server Lambda Docs

docs/_config.yml
=> Add lambda deployment to sidebar

docs/source/whats-new.md
=> Add Performance Monitoring to what's new for visibility

docs/source/example.md
=> Use apollo-server v1 in example relating to v1

docs/source/features/cdn.md, docs/source/features/data-sources.md, docs/source/features/file-uploads.md, docs/source/features/metrics.md, docs/source/schemas/types.md
Ref: https://docs-docs.netlify.com/docs/docs/formatting.html#sentence-case
=> docs: Use sentence case for title names.

docs/source/features/subscriptions.md
=> Clarify docs for hybrid connections with middleware

packages/apollo-server-core/src/index.ts, packages/apollo-server-express/src/index.ts, packages/apollo-server-hapi/src/index.ts, packages/apollo-server-koa/src/index.ts, packages/apollo-server-lambda/src/index.ts, packages/apollo-server-micro/src/index.ts, packages/apollo-server/src/index.ts
=> Enable GraphQLUpload for Apollo Server 2.0

docs/source/whats-new.md
=> Add CDN and APQ to What's new

docs/_config.yml
=> Add redirect to File Uploads Guide

docs/source/getting-started.md
=> Add Server Port Change instructions

docs/_config.yml
=> add version to _config.yml

CHANGELOG.md
Because VS Code likes to auto-format files
=> Consistent lists in CHANGELOG.md

docs/source/features/unions-interfaces.md
Fixed header at `L#78` from `Intersection` to `Interface` !
=> Fixed Wrong Header at unions-interfaces

docs/_config.yml, docs/source/features/subscriptions.md
=> Cleanup subscriptions link

docs/source/api/apollo-server.md
Add info about disabled introspection in production
TODO:
=> Add disabled introspection info

docs/source/migration-two-dot.md
=> Typo in doc "Migrating to v2.0"

CHANGELOG.md, packages/apollo-server-core/src/playground.ts
=> Update default version of graphql-playground

docs/source/best-practices/security.md, docs/source/essentials/server.md, docs/source/features/subscriptions.md
Documentation update only. Added description and sample code for using SSL with GraphQL server and subscriptions.
=> Documentation update: Added description and sample code for enabling SSL

docs/source/features/directives.md
See original [spec](http://facebook.github.io/graphql/draft/#sec--deprecated)
TODO:
=> update @deprecated to use "reason"

docs/source/api/graphql-tools.md
=> Small grammatical fix ("a" as opposed to "an")

docs/source/api/apollo-server.md
=> Add express import in middleware apollo-server-express example

docs/source/schemas/types.md
=> Add Non-Nullable type example

docs/source/schemas/types.md
=> Fix type for a mutation example

docs/source/best-practices/organization.md
TODO:
While not necessary, you can help organize our pull requests by labeling this issue when you open it.  To add a label automatically, simply [x] mark the appropriate box below:
=> Use gql tag in typeDef examples and fix typo in require

README.md
=> Add Koa to the list of Apollo Server integrations

docs/source/best-practices/authentication.md, docs/source/best-practices/schema-design.md, docs/source/deployment/heroku.md, docs/source/deployment/lambda.md, docs/source/essentials/server.md
I only fixed some typos in the docs.
=> fixed typos in docs

docs/source/api/graphql-tools.md
=> fixed arbitrarily

CHANGELOG.md, README.md
=> fix typo in README of Koa example

docs/source/features/metrics.md
=> Fix typo in metrics documentation

docs/source/features/metrics.md
=> Fixed typo in code example

packages/apollo-server-cache-memcached/src/index.ts, packages/apollo-server-cache-redis/src/index.ts, packages/apollo-server-caching/src/InMemoryLRUCache.ts, packages/apollo-server-caching/src/KeyValueCache.ts
Includes:
* InMemory
* Redis
* Memcached
=> Add `delete` implementations to the various cache store implementations.

package-lock.json, package.json, packages/apollo-engine-reporting-protobuf/reports.proto, packages/apollo-engine-reporting/src/__tests__/extension.test.ts, packages/apollo-engine-reporting/src/agent.ts, packages/apollo-engine-reporting/src/extension.ts, packages/apollo-server-core/package.json, packages/apollo-server-core/src/ApolloServer.ts, packages/apollo-server-core/src/requestPipeline.ts, packages/apollo-server-core/src/requestPipelineAPI.ts, packages/apollo-server-core/src/types.ts, packages/apollo-server-core/src/utils/schemaHash.ts, packages/apollo-server-integration-testsuite/src/ApolloServer.ts, packages/graphql-extensions/src/index.ts
@abernix @martijnwalraven this PR should include the changes we need to report client identity and schema awareness back to engine
=> Engine reporting improvements

packages/apollo-engine-reporting-protobuf/reports.proto, packages/apollo-engine-reporting/src/agent.ts, packages/apollo-engine-reporting/src/extension.ts, packages/apollo-server-integration-testsuite/src/ApolloServer.ts
@abernix this should be a lot more clear 👍
=> change clientId => clientReportingId and schemaBranch => schemaTag

packages/apollo-server-cloud-function/README.md
=> Update README.md with the latest package name

docs/_config.yml, docs/source/features/test-utils.md
These are docs to accompany the `apollo-server-testing` utils
TODO:
=> added apollo-server-testing docs

packages/apollo-server-core/src/ApolloServer.ts
There was a typo in the error message.
TODO:
=> ApolloServer: fix uploads error message

docs/source/features/errors.md
**In this release:**
- Fix hyperlink for masking and logging errors. 93d1bc67ce71babde4e5185fad7b5691ccac7e35
**Contributors:**
@pratiknikam
**Date:**
11/27/2018, 9:32:22 AM
=> Fix hyperlink for masking and logging errors.

docs/source/essentials/data.md, docs/source/features/creating-directives.md, docs/source/features/mocking.md, docs/source/features/scalars-enums.md, docs/source/features/subscriptions.md, docs/source/features/unions-interfaces.md, docs/source/schemas/types.md
Hey guys,
I've noticed that some of the gql examples are indented differently than the rest and I think that consistent indentation and formatting makes it easier to read and comprehend.
Let me know what you think, thanks.
=> Make gql example consistent and easier to read

docs/source/features/scalars-enums.md
**Before**: allows the addition custom
**After**: allows the addition of custom
=> Fix grammar error (missing preposition)

docs/source/whats-new.md
between schema stitching and file uploads
TODO:
=> warn readers about incompatibility

packages/apollo-server-lambda/README.md
I think 'this' is better than 'the'
TODO:
=> docs: update apollo-server-lambda/README

docs/source/essentials/data.md
Just corrected `obj` to `parent`.
TODO:
=> Minor typo

docs/source/essentials/data.md
=> 📚 update link to dataloader suggestions

docs/source/getting-started.md
Recommend the recent node version to be (6+) to (8+)
TODO:
=> Updated Node.js version to 8+

docs/source/features/scalars-enums.md
Changed it to lowercase so that it will take us to the heading as expected.
TODO:
=> Broken anchor

docs/source/essentials/data.md
=> To assist in on-boarding new users.

docs/source/features/metrics.md
=> Fixed syntax in example code

docs/gatsby-config.js, docs/package-lock.json, docs/package.json, netlify.toml
This branch upgrades the docs theme to v0.3 for better version handling, and ensures the netlify `_redirects` file gets moved to the right place.
=> Upgrade docs theme to 0.3

docs/source/whats-new.md
=> syntax correction

packages/apollo-server-integration-testsuite/src/ApolloServer.ts
By testing to make sure we don't default to the query-based signature,
rather than the calculated signature when an error condition occurs within
`didResolveOperation`.
Ref: #2711.
=> tests: Regression test for #2711.

docs/source/deployment/lambda.md
The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions.
=> Change node runtime parameter to v8.10

packages/apollo-server-express/src/__tests__/expressApollo.test.ts, packages/apollo-server-express/src/expressApollo.ts
Hey folks 👋 First time contributor to Apollo here! I was reading through the source code for `apollo-server-express` and I saw a comment `//TODO: Test this` so I figured, 'Hey I can test this!'
It's a super simple PR so I hope I didn't mess anything up. I don't believe there's any previous issues referencing this. Thanks for your time!
=> fix: test handling of multiple args in graphqlExpress

docs/source/federation/core-concepts.md
=> Fix typos in core-concepts.md

docs/source/federation/federation-spec.md
Two small typos.
One more significant change (`Service` => `_Service`) because it might affect the spec meaning.
=> Typo in the Federation docs

docs/source/features/caching.md
=> Small documentation typo

packages/apollo-federation/src/composition/__tests__/tsconfig.json, packages/apollo-federation/src/composition/validate/postComposition/__tests__/externalMissingOnBase.test.ts, packages/apollo-federation/src/composition/validate/postComposition/__tests__/externalTypeMismatch.test.ts, packages/apollo-federation/src/composition/validate/postComposition/__tests__/externalUnused.test.ts, packages/apollo-federation/src/composition/validate/postComposition/__tests__/keyFieldsMissingOnBase.test.ts, packages/apollo-federation/src/composition/validate/postComposition/__tests__/keyFieldsSelectInvalidType.test.ts, packages/apollo-federation/src/composition/validate/postComposition/__tests__/providesFieldsMissingExternals.test.ts, packages/apollo-federation/src/composition/validate/postComposition/__tests__/providesFieldsSelectInvalidType.test.ts, packages/apollo-federation/src/composition/validate/postComposition/__tests__/providesNotOnEntity.test.ts, packages/apollo-federation/src/composition/validate/postComposition/__tests__/requiresFieldsMissingExternals.test.ts, packages/apollo-federation/src/composition/validate/postComposition/__tests__/requiresFieldsMissingOnBase.test.ts, packages/apollo-federation/src/composition/validate/postComposition/__tests__/tsconfig.json, packages/apollo-federation/src/composition/validate/preComposition/__tests__/externalUsedOnBase.test.ts, packages/apollo-federation/src/composition/validate/preComposition/__tests__/keyFieldsMissingExternal.test.ts, packages/apollo-federation/src/composition/validate/preComposition/__tests__/requiresUsedOnBase.test.ts, packages/apollo-federation/src/composition/validate/preComposition/__tests__/reservedFieldUsed.test.ts, packages/apollo-federation/src/composition/validate/preComposition/__tests__/rootFieldUsed.test.ts, packages/apollo-federation/src/composition/validate/preComposition/__tests__/tsconfig.json, packages/apollo-federation/src/composition/validate/preComposition/keyFieldsMissingExternal.ts, packages/apollo-federation/src/snapshotSerializers/graphqlErrorSerializer.ts, packages/apollo-federation/src/snapshotSerializers/index.ts
The purpose of this PR is to introduce stability to the error codes we use via the snapshots that are already in place.
I realized the need for this when I made changes to error codes in this PR: https://github.com/apollographql/apollo-server/pull/2783. These error codes may be depended on programatically, so we should ensure they are stable within our testing suite.
I created a new serializer for `GraphQLError`s in order to display the error codes we attach to `GraphQLError.extensions.code`. This serializer should be used wherever we're displaying `GraphQLErrors` _that we create_ (not from the `graphql-js` library.
=> [Federation] Add error codes to snapshot results

docs/source/deployment/netlify.md
=> fix missing images

package-lock.json, packages/apollo-engine-reporting/package.json, packages/apollo-federation/package.json, packages/apollo-gateway/package.json
This PR updates the Apollo tooling dependencies to latest
=> Update tooling dependencies

docs/source/federation/core-concepts.md
=> [Federation] Document duplicate enum and scalar values

packages/apollo-gateway/src/datasources/RemoteGraphQLDatasource.ts
=> Make RemoteGraphQLDataSource extension methods public

docs/source/federation/federation-spec.md
@key is allowed on both OBJECT or INTERFACE, the docs should reflect that.
=> Add documentation for @key directive in federation spec

packages/apollo-gateway/src/__tests__/__fixtures__/schemas/accounts.ts
=> Fix test error related to time zones

docs/source/whats-new.md
=> fix broken link

packages/apollo-federation/src/composition/utils.ts, packages/apollo-federation/src/composition/validate/postComposition/__tests__/externalUnused.test.ts, packages/apollo-federation/src/composition/validate/postComposition/externalUnused.ts
Fixes two cases for validation of @external fields
1. If the `@external` field is referenced in a `@provides` on _another type_.
2. If the `@external` field is referenced in a nested selection set within a `@requires`
resolves #2772
=> Fix @external validation for complex provides/requires

package-lock.json, packages/apollo-engine-reporting/package.json, packages/apollo-federation/package.json, packages/apollo-gateway/package.json
Latest `apollo-graphql` has fixes for federated schema construction, let's pull those in 😄
=> Update apollo-graphql dependency

packages/apollo-gateway/src/index.ts, packages/apollo-gateway/src/loadServicesFromRemoteEndpoint.ts
=> Add config hook for federation introspection query

docs/source/federation/federation-spec.md
=> minor grammar fix

docs/source/whats-new.md
Replace Slack reference with Spectrum as per:
- https://blog.apollographql.com/goodbye-slack-hello-spectrum-8fa6b979645b
=> Replace Slack reference with Spectrum

packages/apollo-gateway/src/__tests__/integration/multiple-key.test.ts
I merged PR #2943 without first rebasing and re-running tests. This snapshot
needed to be updated as well.
=> Update snapshots after PR 

packages/apollo-gateway/CHANGELOG.md, packages/apollo-gateway/src/QueryPlan.ts, packages/apollo-gateway/src/__tests__/__fixtures__/schemas/accounts.ts, packages/apollo-gateway/src/__tests__/__fixtures__/schemas/books.ts, packages/apollo-gateway/src/__tests__/integration/mutations.test.ts, packages/apollo-gateway/src/__tests__/integration/variables.test.ts, packages/apollo-gateway/src/buildQueryPlan.ts, packages/apollo-gateway/src/executeQueryPlan.ts
Arguments should be removed from downstream fetches when a
defaultValue exists in the schema and the variable isn't provided
by the client executing the query.
=> [Federation] Handle schema defaultVariables correctly within downstream fetches

packages/apollo-federation/src/composition/validate/postComposition/__tests__/providesNotOnEntity.test.ts, packages/apollo-federation/src/composition/validate/postComposition/providesNotOnEntity.ts
=> Fix @provide on list and non-null types

docs/source/federation/errors.md
We were missing docs for some of the newer validation errors that were added in #2829, #2878, and #2910 :)
=> Updated the docs for schema validation errors

packages/apollo-server-azure-functions/README.md, packages/apollo-server-cloud-functions/README.md, packages/apollo-server-express/README.md, packages/apollo-server-fastify/README.md, packages/apollo-server-hapi/README.md, packages/apollo-server-koa/README.md, packages/apollo-server-lambda/README.md, packages/apollo-server-micro/README.md
The frontmatter in these Readmes were displaying incorrectly [on NPM](https://www.npmjs.com/package/apollo-server-express). Since the docs no longer use this, it should be safe to remove!
=> Remove Readme Frontmatter for AS integrations

packages/graphql-extensions/package.json
=> [graphql-extensions] Move apollo-server-env to dependencies

packages/apollo-server-core/src/playground.ts
=> Fix playground config typing error when in strictNull

packages/apollo-server-core/src/ApolloServer.ts, packages/apollo-server-core/src/types.ts
=> Allow array-type resolvers

docs/source/federation/introduction.mdx
change implemention => implementation
=> fixed typo in introduction.mdx

docs/source/federation/implementing.md
=> Docs: Update to point to managed federation & add some details 

packages/apollo-server-integration-testsuite/src/ApolloServer.ts
Update expected error message in tests.
In response to:
https://github.com/apollographql/apollo-server/commit/e8cb9bfbf61cc2854fb9155dcf839e71c1820ea1
=> Update expected error message in tests

docs/source/features/data-sources.md
=> Add docs section for community data sources

docs/source/federation/federation-spec.md, packages/apollo-federation/src/composition/__tests__/compose.test.ts, packages/apollo-federation/src/composition/__tests__/composeAndValidate.test.ts, packages/apollo-federation/src/composition/normalize.ts, packages/apollo-federation/src/composition/utils.ts, packages/apollo-federation/src/composition/validate/sdl/possibleTypeExtensions.ts, packages/apollo-federation/src/directives.ts
Interface extension is something that's supported by our federation utilities, however there is currently no equivalent support for those using the `@extends` directive.
i.e.
```graphql
extend interface Product @key(fields: "upc") {
...
}
```
and its equivalent:
```graphql
interface Product @extends @key(fields: "upc") {
...
}
```
The first commit demonstrates the issue via a failing test, with the following commit adding the desired functionality. (and another for a docs update)
=> [Federation] Support @extends directive for interfaces 

docs/source/features/data-sources.md
=> Fix typo in data-sources.md

docs/source/api/apollo-server.md
Just added links to @koa/cors and koa-bodyparser for their respective options in `applyMiddleware`
=> Add Koa links to applyMiddleware documentation

.github/CODEOWNERS
=> Add StephenBarlow as codeowner for docs/

docs/source/getting-started.md
We currently link to a nonexistent repo for a code sample.
=> Remove broken link to example code

packages/apollo-server/README.md
Updated the URL which points to SDL section in the docs website. This basically changes the fragment from `sdl` to `schema-definition-language`.
=> Fixed SDL link

docs/source/federation/advanced-features.md
Add missing `extend` on User type.
=> docs: add `extend` on User type

package-lock.json, packages/apollo-gateway/package.json, packages/apollo-gateway/tsconfig.json
In trying to update our infrastructure to the latest version of `@apollo/gateway`, I found that the project wouldn't build due to the missing `graphql-extensions` dependency which is required here:
https://github.com/apollographql/apollo-server/blob/e6ccd8bc41e51089ca428c408be2bcd0a8e3796d/packages/apollo-gateway/src/datasources/LocalGraphQLDataSource.ts#L9
Still trying to determine why our own repository doesn't pick up on the missing dep (monorepo setup?), but at least our infrastructure did!
=> Add missing graphql-extensions dependency

.circleci/config.yml
> Note: Using CircleCI 2.1 configuration files requires toggling a radio box
on the "Advanced Settings" of the project to enable "Pipelines".  For
example, on Apollo Server, this setting is here:
>
>  https://circleci.com/gh/apollographql/apollo-server/edit#advanced-settings
This commit changes Apollo Server usage of YAML Anchors & Aliases to a more
versatile pattern which can, when published as Orbs, be reused across
projects.
One of the limitations of the [YAML Anchors and Aliases][1] which prompted
this change is that they can't be used to expand lists with additional
parameters.  That's to say that, it wasn't possible to add to an
alias/anchor if the desire was to add an additional step to the array of
`steps` (defined within an alias) which take place in a CircleCI workflow.
That's a …
=> Switch to CircleCI 2.1 config with reusable `commands` and `executors`.

docs/source/features/metrics.md
Resolving a couple old broken links.
=> Fix broken links on metrics page

docs/source/performance/apq.md
=> Fix package name in docs for APQ

packages/apollo-gateway/src/loadServicesFromStorage.ts
This commit appropriately names a string constant to correctly match its related env variable.
This code borrows a pattern from the operation registry plugin and appears to be the result
of an incomplete refit of a copy/paste.
=> Rename misnamed env constant

package-lock.json, packages/apollo-engine-reporting/package.json, packages/apollo-federation/package.json, packages/apollo-gateway/package.json
This commit updates the apollo-graphql package to the latest
version. This includes a fix for a bug that currently breaks
minification. For reference, see:
https://github.com/apollographql/apollo-tooling/pull/1551
Fixes #3335
=> Update apollo-graphql package to latest

packages/apollo-engine-reporting-protobuf/README.md, packages/apollo-engine-reporting/README.md, packages/apollo-engine-reporting/package.json, packages/apollo-engine-reporting/src/agent.ts, packages/apollo-server-core/src/ApolloServer.ts, packages/apollo-server-integration-testsuite/src/ApolloServer.ts, packages/apollo-tracing/README.md
This does not rename anything that is specifically Apollo Engine
Reporting, the Engine config, or Apollo Engine proxy, but changes other
mentions to align with rebranding.
=> Modify mentions of Engine to Graph Manager (in error messages, docs, etc.)

docs/source/data/file-uploads.md
- `Upload scalar` should be `scalar Upload`
=> docs: fixes typos in file upload section

docs/source/api/apollo-gateway.mdx, docs/source/federation/implementing.md
Unresolved feedback from https://github.com/apollographql/apollo-server/pull/3377
=> Incorporate unresolved feedback from abernix

docs/source/federation/implementing.md
=> Fix example in implementing.md

docs/gatsby-config.js, docs/source/features/plugins.md, docs/source/integrations/plugins.md
@abernix Would love your feedback on this rewrite-in-progress! So far I'm down to line 205; everything below that still needs editing and/or reorganizing.
Once we get this into a totally-good state, I can either reopen it against your open PR or we can replace it with this one wholesale.
=> Edits from @StephenBarlow to "Plugins" article

docs/source/federation/core-concepts.md
=> update "its" to "their"

docs/source/features/schema-stitching.md
Added missing code to the basic example.
=> fixed code in basic example

v3/package.json, v3/src/execution/__tests__/__snapshots__/execution.test.ts.snap, v3/src/execution/__tests__/execution.test.ts, v3/src/execution/index.ts, v3/src/snapshotSerializers/astSerializer.ts, v3/src/snapshotSerializers/index.ts
This commit introduces baseline functionality for GraphQL request execution in AS v3.
**A few goals which I had in mind while putting this together:**
* Patterns and conventions with structure and naming.
* Documentation - this is an exploration into using TSDoc for our new code. Adhering to this now unlocks some tooling for us in the future, and is useful currently in IDEs like VS Code with hovering.
* Compartmentalization and testability: parsing, validation, and execution are each their own piece of the `processGraphqlRequest` function. This allows us to introduce complexity to the individual bits over time without the main function becoming clouded or difficult to follow. This allows us to easily unit test the behavior of each of these moving parts, as well as integration-level tests. …
=> Initial v3 Execution work

packages/apollo-server-express/README.md
=> fix minor spell error

CHANGELOG.md, package-lock.json, packages/apollo-engine-reporting-protobuf/package.json, packages/apollo-engine-reporting-protobuf/src/index.js
The `@apollo/protobufjs` fork has a TS build error that is affecting consumers of the `apollo-engine-reporting` package (but not perceived by this repo's build step, for some reason?). Reverting this change for now while we resolved the issue within the fork.
=> Revert switch to `@apollo/protobufjs` fork

packages/apollo-server-hapi/src/__tests__/hapiApollo.test.ts
In the same spirit as 9ffb4a847e1503ea2ab1f3fcd47837daacf40870 did in #2033, this uses an ephemeral port picked randomly by the operating system rather than a specific port that may be used by other applications (for example, Gatsby uses 8000 by default, so this can be a common reason for tests to fail when I'm running them locally.
=> Use an ephemeral port, rather than port 8000, for Hapi tests.

docs/source/deployment/lambda.md
With `nodejs8.10` will get error: 
```
An error occurred: GraphqlLambdaFunction - The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 82c12052-3ecd-4435-b2ce-a4bc306e4f45).
```
just changing to `nodejs12.x` it works!
=> Update nodejs runtime version

packages/apollo-gateway/CHANGELOG.md, packages/apollo-gateway/src/__tests__/executeQueryPlan.test.ts, packages/apollo-gateway/src/__tests__/gateway/buildService.test.ts, packages/apollo-gateway/src/executeQueryPlan.ts
Use graphql-js's `stripIgnoredCharacters` utility function to minimize query body size over the wire from the gateway to downstream services.
This change is very straightforward. I tested the effects on a couple files and saw significant improvements in the resulting sizes, especially for larger queries.
11 KB -> 7 KB
93 KB -> 23 KB
=> Gateway: minimize downstream requests

packages/apollo-federation/src/composition/rules.ts
This update is in response to the following PRs:
https://github.com/graphql/graphql-js/pull/2400
https://github.com/graphql/graphql-js/pull/2413
cc @IvanGoncharov, thank you for the changes in ^2413!
=> Update `UniqueDirectivesPerLocation` import

docs/source/testing/graphql-playground.md
Added a full stop at the end of a sentence.
=> docs: add full stop

docs/gatsby-config.js, docs/source/federation/implementing.md
This content feels better a little earlier in the category
=> Edits to the service/gateway federation article

docs/source/federation/other-servers.md
This PR adds [Ariadne](https://ariadnegraphql.org/blog/2020/02/11/ariadne-0-10-0) to the list of libraries that have built-in support for Apollo Federation.
=> Add Ariadne to the list of libraries that support Apollo Federation

packages/apollo-gateway/src/__tests__/integration/nockMocks.ts, packages/apollo-gateway/src/index.ts, packages/apollo-gateway/src/make-fetch-happen.d.ts
Provide a non-default `user-agent` header (`apollo-gateway/{version}`) which identifies the gateway.
=> Gateway: provide `user-agent` header to fetcher

docs/source/api/apollo-gateway.mdx
Follows-up: https://github.com/apollographql/apollo-server/pull/3783
Follows-up: https://github.com/apollographql/apollo-server/pull/3829
=> docs: Document new `fetcher` on `@apollo/gateway`.

.circleci/config.yml
Fix GitHub link.
The original link is a broken link.
=> docs(circle): fix GitHub link

packages/apollo-server-micro/README.md
Inline with other packages, update the link for the CI status badge in readme for aollo-server-micro
So that it doesn't show the misleading build failing badge on readme. Moreover that badge is pointing to wrong package.
=> fix broken CI status link for apollo-server-micro

docs/source/federation/other-servers.md
`async-graphql` is GraphQL server library implemented by rust, fully supports federation. 😁
Example
==========
```shell
git clone https://github.com/sunli829/async-graphql
cd async-graphql
yarn install --cwd examples/federation
cd examples && ./start-feceration.sh
```
=> Add async-graphql to Federation third-party support

packages/apollo-gateway/src/__tests__/__fixtures__/schemas/documents.ts, packages/apollo-gateway/src/__tests__/buildQueryPlan.test.ts
Regression test for #3832. Fails for `@apollo/gateway v0.11.0` and passes on `v0.14.0`
=> Regression test for #3832

docs/source/integrations/plugins.md
Adding missing comma in the code example.
=> docs: Add comma to fix syntax error in "plugins"

docs/source/federation/other-servers.md
This PR adds a link to caliban a scala graphql library which recently added support for federation.
cc/ @ghostdogpr
=> Add caliban to the list of federation support

docs/source/schema/creating-directives.md
=> Fix link to SchemaDirectiveVisitor

docs/source/data/resolvers.mdx
This is a micro-minor change improving readability of the code as unneded quotes are removed. Purely cosmetic
=> docs: Finetune code example in resolvers.mdx

CHANGELOG.md, packages/apollo-engine-reporting/src/schemaReporter.ts
We've set up a new sub-domain specifically for schema reporting at `edge-server-reporting.api.apollographql.com`. This PR accordingly updates the schema reporting URL in `schemaReporter.ts`.
=> schema-reporting: Update URL for schema reporting

packages/apollo-engine-reporting/src/agent.ts
This PR makes the schema-reporting startup logging for options a bit cleaner (the main change being not printing out the entire schema in the log when a schema override is present).
=> schema-reporting: Update startup logging for options

docs/source/federation/migrating-from-stitching.md
=> Follow up on changes to stitching migration doc

docs/source/deployment/azure-functions.md
Fix incorrect url for http://localhost:7071/api/graphql?name=Apollo which incorrectly points to http://localhost:7071/api/apollo-example?name=Apollo.
=> docs: Fix wrong url

netlify.toml
=> Remove NPM_VERSION variable for docs build env

packages/apollo-federation/CHANGELOG.md, packages/apollo-federation/src/csdlDirectives.ts, packages/apollo-federation/src/service/__tests__/printComposedSdl.test.ts, packages/apollo-federation/src/service/printComposedSdl.ts
Currently the CSDL is technically invalid, as it has directive usages without matching definitions. This adds all of the new directive definitions to the output.
=> feat(gateway): Include directive definitions in CSDL

packages/apollo-tracing/src/index.ts
Our team pointed this out in code review when we used this file as a base for our own custom tracing plugin.
=> polish: remove always false condition

docs/source/data/file-uploads.md
The linked issue says the problem was resolved.
=> Remove obsolete note about schema stitching

docs/source/data/resolvers.mdx, docs/source/getting-started.md, docs/source/schema/schema.md
=> Update code samples

docs/static/_redirects
=> Don't need full docs URL in redirects

docs/source/performance/apq.md, packages/apollo-server-core/src/requestPipeline.ts
Plenty of the article left to go, but I reached a nice, review-manageable stopping point
=> Initial edits to APQ docs

docs/source/data/subscriptions.mdx
=> Added to the PubSub libraries list

docs/source/performance/apq.md
The APQ docs provide an invalid link, the `/graphql` path is missing.
=> Update APQ docs follow up CLI request URL

docs/source/data/data-sources.md
Adding a link to the Google Firebase Firestore DataSource I wrote based on the CosmosDB one listed on the page. Certainly room for improvement so any feedback on the datasource itself is very welcome as issues in its repo.
=> DataSources: Add apollo-datasource-firestore link

packages/apollo-server-plugin-response-cache/src/ApolloServerPluginResponseCache.ts
Add a space for better coding style.
=> chore: add space for better coding style

package-lock.json, package.json, packages/apollo-server-fastify/package.json
=> Update to latest version of Fastify packages.

docs/source/api/apollo-server.md, docs/source/monitoring/metrics.md
=> docs: encourage setting APOLLO_GRAPH_ID

docs/source/data/data-sources.mdx
Proofread tiny typo
Apollo does not provide **official** support for community-maintained libraries. 
Previously off*ii*cal
Per issue #5281
no offal
=> docs(data-sources.mdx): proofread typo to official from offiical

packages/apollo-server-core/src/requestPipeline.ts
This used to do graphql-extensions stuff, but we removed that on
release-3.0.
=> Remove empty try/finally

docs/source/data/data-sources.mdx
Add the new community datasource https://github.com/StarpTech/apollo-datasource-http
=> add new community datasource

CHANGELOG.md, packages/apollo-server-azure-functions/src/azureFunctionApollo.ts, packages/apollo-server-core/src/runHttpQuery.ts, packages/apollo-server-express/src/ApolloServer.ts, packages/apollo-server-fastify/src/ApolloServer.ts, packages/apollo-server-hapi/src/ApolloServer.ts, packages/apollo-server-integration-testsuite/src/index.ts, packages/apollo-server-koa/src/ApolloServer.ts, packages/apollo-server-micro/src/microApollo.ts
This PR is for https://github.com/apollographql/apollo-server/issues/5288 and makes the following changes:
- Uncomment `statusCode` in the `ApolloServerHttpResponse` type, allowing it to be added to `responseInit` objects
- Set `responseInit.status` to `response.http.status` (if it exists) in `runHttpQuery`
- In each of the server implementations, set the status code to `responseInit.status` or 200 if `responseInit.status` is not set, keeping the default behaviour the same as the existing behaviour
- Add test to cover all server implementations
=> 5288 - Allow setting response status

packages/apollo-server/src/index.ts
- We're on a newer `@types/node` so we can implement the TODO.
- Remove part of comment claiming `url` is mostly used for test suite
(it's in the tutorial!)
- Move require to top of file as import (this function is always run).
=> apollo-server: Clean up createServerInfo

CHANGELOG.md, docs/source/data/file-uploads.md, docs/source/migration.md
=> wip: write migration guide for AS3

docs/source/testing/testing.md
=> Fix small typo in docs

docs/gatsby-config.js, docs/source/api/plugin/cache-control.md, docs/source/builtin-plugins.md
=> docs: reference for cache control plugin

docs/gatsby-config.js, docs/source/api/plugin/landing-pages.md, docs/source/builtin-plugins.md, docs/source/testing/build-run-queries.mdx
=> docs: add landing page reference

docs/gatsby-config.js, docs/static/_redirects
No content here, just preparing for display
=> Prepare to add AS3 preview docs to nav

docs/source/data/subscriptions.mdx
=> docs: Mention graphql-ws

docs/source/migration.mdx
=> docs: mention apollo-cache-control package in migration

docs/source/migration.mdx
=> docs: migration: link to exports section from subs/uploads

docs/source/data/file-uploads.md
Adding documentation for Fastify as requested in https://github.com/apollographql/apollo-server/issues/4975
=> Add fastify example for file uploads

docs/source/testing/mocking.md
This should help copy+paste code from the documentation.
=> Typo: missing camelCase

docs/source/api/plugin/usage-reporting.md, packages/apollo-server-errors/src/index.ts
Signed-off-by: Rui Chen <rui@chenrui.dev>
update `GraphQLError.ts` refs
=> docs: fix GraphQLError.ts refs

CHANGELOG.md
Signed-off-by: Rui Chen <rui@chenrui.dev>
Fix the migration guide references
=> docs: fix broken links for migration guide

docs/source/data/subscriptions.mdx
=> docs: note error in subscriptions doc

docs/source/deployment/lambda.md
Fixed missing closing tag for code block that made formatting for the rest of the page all weird
=> Update lambda.md in docs/source/deployment

docs/source/testing/mocking.md
=> fix link src for introspection query

docs/source/data/subscriptions.mdx, docs/source/migration.mdx
=> docs: Fix subscriptions + context documentation

docs/source/migration.mdx
* ✏️ Explain your pull request
Add closing `)`
=> docs(migration): add closing `)`

docs/source/data/subscriptions.mdx
the link was broke - I think this is where it is supposed to go
=> broken github link for subscriptions

docs/source/data/subscriptions.mdx
Replicating #5590 against `main`
=> Fix broken github link for subscriptions

docs/gatsby-config.js, docs/source/api/graphql-tools.md, docs/source/installing-graphql-tools.md, docs/source/schema/creating-directives.md, docs/source/schema/creating-directives.mdx, docs/source/schema/directives.md
Includes a few supporting edits to lay some foundation
=> First batch of edits to custom directives article

docs/source/api/plugin/inline-trace.md, docs/source/deployment/azure-functions.md
made corrections to the typos i have found in the documentations.
=> Fix typos in docs

.gitignore, docs/gatsby-config.js, docs/package-lock.json, docs/package.json, netlify.toml
=> Upgrade docs theme for new search experience

packages/apollo-server-azure-functions/src/__tests__/azureFunctionApollo.test.ts, packages/apollo-server-core/src/plugin/usageReporting/__tests__/stats.test.ts
Small clean, just saw this pattern in the code 🧹
=> Switch `for (let $ of` to `for (const $ of`

CHANGELOG.md, docs/source/migration.mdx
=> fix: Update migration guide and changelog for `executionDidEnd`

docs/source/data/data-sources.mdx
=> docs: Explain `encodeURIComponent` usages

docs/source/data/resolvers.mdx, docs/source/index.mdx, docs/source/schema/schema.md
This branch replaces instances of 'data graph' in our docs with 'graph' to be more in line with the language that we use in our marketing these days.
cc @jchesterman
=> docs: Replace 'data graph' with 'graph'

docs/source/data/file-uploads.mdx
=> Update fastify example to remove deprecated reply.res

packages/apollo-datasource-rest/package.json, packages/apollo-datasource/package.json, packages/apollo-reporting-protobuf/package.json, packages/apollo-server-azure-functions/package.json, packages/apollo-server-cache-memcached/package.json, packages/apollo-server-cache-redis/package.json, packages/apollo-server-caching/package.json, packages/apollo-server-cloud-functions/package.json, packages/apollo-server-core/package.json, packages/apollo-server-env/package.json, packages/apollo-server-errors/package.json, packages/apollo-server-express/package.json, packages/apollo-server-fastify/package.json, packages/apollo-server-hapi/package.json, packages/apollo-server-integration-testsuite/package.json, packages/apollo-server-koa/package.json, packages/apollo-server-lambda/package.json, packages/apollo-server-micro/package.json, packages/apollo-server-plugin-base/package.json, packages/apollo-server-plugin-operation-registry/package.json, packages/apollo-server-plugin-response-cache/package.json, packages/apollo-server-types/package.json, packages/apollo-server/package.json
=> Switching to a new email inbox for author

docs/source/data/subscriptions.mdx
=> docs: fix subscriptions invalid use of server.graphqlPath

.circleci/config.yml
Ref: apollographql/CircleCI-Orbs#5
=> chore(deps): bump circleci orb apollo/oss-ci-cd-tooling to 0.0.20

docs/source/integrations/middleware.mdx
This PR does the following,
- updates the example for `apollo-server-fastify` to import the ` ApolloServerPlugin` interface from `apollo-server-plugin-base`
This should address https://github.com/apollographql/apollo-server/issues/5943
=> Updated middleware.tsx file for fastify example

docs/source/data/data-sources.mdx
=> Fix link render in data-sources

docs/source/data/file-uploads.mdx
=> Fixed typo in file-uploads.mdx

ROADMAP.md, cspell-dict.txt
=> Roadmap updates Jan 2022

docs/source/data/subscriptions.mdx
I wrote a PubSub implementation that uses Firebase Realtime Database as a message broker, I recently broke it out of the project where it's been in production for a while and polished it up a little, and it should do its job well enough. I'd be happy to have it included in the list of PubSub implementation if you deem it fits
=> docs: add graphql-firebase-subscriptions

docs/source/data/subscriptions.mdx
Adding another integration for pubsub.
=> Adding Azure SignalR Service pubsub implementation

docs/source/schema/creating-directives.mdx
In `Example: Uppercasing strings` section, the top defines directive to `uppercase`, but in ApolloServer define to: `upper`.
so I change bottom one for work right
=> Hi, I found a little syntax error

docs/source/api/apollo-server.mdx, docs/source/api/plugin/usage-reporting.md, package-lock.json, package.json, packages/apollo-server-core/package.json, packages/apollo-server-core/src/ApolloServer.ts, packages/apollo-server-core/src/__tests__/ApolloServerBase.test.ts, packages/apollo-server-core/src/__tests__/logger.test.ts, packages/apollo-server-core/src/graphqlOptions.ts, packages/apollo-server-core/src/plugin/schemaReporting/schemaReporter.ts, packages/apollo-server-core/src/plugin/traceTreeBuilder.ts, packages/apollo-server-core/src/plugin/usageReporting/operationDerivedDataCache.ts, packages/apollo-server-core/src/plugin/usageReporting/options.ts, packages/apollo-server-core/src/utils/pluginTestHarness.ts, packages/apollo-server-core/src/utils/schemaManager.ts, packages/apollo-server-types/src/index.ts
The `Logger` interface has been ported over to the `apollo-utils` repo since it's a generic interface used by both server and gateway. This PR migrates `Logger` usages to that one and stops exporting it from `apollo-server-types`.
Also updated references to docs over to the `Logger` README.
Fixes https://github.com/apollographql/apollo-server/issues/6056
Fixes #6262
=> Replace `Logger` with equivalent @apollo/utils logger interface

package-lock.json, package.json, packages/server-types/src/types.ts, packages/server/package.json, packages/server/src/ApolloServer.ts, packages/server/src/__tests__/ApolloServer.test.ts, packages/server/src/__tests__/logger.test.ts, packages/server/src/__tests__/pluginTestHarness.ts, packages/server/src/plugin/schemaReporting/schemaReporter.ts, packages/server/src/plugin/traceTreeBuilder.ts, packages/server/src/plugin/usageReporting/operationDerivedDataCache.ts, packages/server/src/plugin/usageReporting/options.ts, packages/server/src/types.ts, packages/server/src/utils/schemaManager.ts
The `Logger` interface has been ported over to the `apollo-utils` repo since it's a generic interface used by both server and gateway. This PR migrates `Logger` usages to that one and stops exporting it from `apollo-server-types`.
Also updated references to docs over to the `Logger` README.
Fixes https://github.com/apollographql/apollo-server/issues/6056
=> Replace `Logger` with equivalent @apollo/utils logger interface (v4)

docs/source/data/subscriptions.mdx
=> Link to subscriptions migration steps

docs/source/deployment/lambda.md
=> Update AWS CLI Docs Links

packages/server/src/plugin/usageReporting/plugin.ts
As of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58693, this cast is no longer needed
=> Remove no-longer-needed fetch typings cast (v4)

docs/source/data/subscriptions.mdx
Adding Azure ServiceBus PubSub implementation using Topics.
=> Adding Azure ServiceBus pubsub implementation

docs/source/api/plugin/usage-reporting.md
`sendVariableValues: { all: true }` almost never a good idea. can we switch the example to a more common config option like `fieldLevelInstrumentation`?
=> docs: dont use antipattern in usage report config

docs/source/data/subscriptions.mdx
=> Fix typo on subscriptions.mdx

docs/source/integrations/plugins-event-reference.md
Add extra information due to https://github.com/apollographql/apollo-server/issues/6401
=> Update plugins-event-reference.md with willResolveField running in server mode only

packages/server/src/__tests__/express/expressSpecific.test.ts, packages/server/src/__tests__/integration/apolloFetch.ts, packages/server/src/__tests__/integration/apolloServerTests.ts, packages/server/src/__tests__/integration/httpServerTests.ts
Follow up for #6420
The `/graphql` path no longer applies, so we can remove them from our tests.
=> Remove `/graphql` paths from test cases

packages/server/src/__tests__/express/integration.test.ts, packages/server/src/__tests__/integration/apolloServerTests.ts, packages/server/src/__tests__/integration/httpServerTests.ts, packages/server/src/__tests__/integration/index.ts, packages/server/src/__tests__/standalone/integration.test.ts
Follow-up to PR comment: https://github.com/apollographql/apollo-server/pull/6420#discussion_r870832347
=> Update testsuite to use URLs instead of `http.Server`

docs/source/data/subscriptions.mdx
Addresses https://github.com/apollographql/apollo-server/issues/6323
=> Add section about switching from `subscriptions-transport-ws` to `graphql-ws`

docs/source/data/file-uploads.mdx, docs/source/security/cors.mdx
Related:
https://github.com/apollographql/apollo-server/security/advisories/GHSA-2p3c-p3qw-69r4
Update the docs with respect to `graphql-upload`'s security vulnerability when used with Apollo Server (v3)
V2 docs in a separate PR #6476.
=> CSRF Security Advisory docs updates

packages/server/src/__tests__/standalone/integration.test.ts, packages/server/src/__tests__/standalone/standaloneSpecific.test.ts, packages/server/src/index.ts, packages/server/src/standalone/index.ts
=> Simplify `standaloneServer` API (v4)

docs/source/migration.mdx
Closes #6492
Recommend to provide validationRules to match apollo-server v2's way of instantiating the Subscription Server
https://github.com/apollographql/apollo-server/blob/ae444b2916deb2fa37dbd8fa091201235dc2ec6d/packages/apollo-server-core/src/ApolloServer.ts#L1048-L1051
While `subscriptions-transport-ws` is no longer maintained, someone upgrading from apollo-server v2 should get proper guidance.
I also modified the snippet of code to create the SubscriptionServer because there's a cyclic dependency between ApolloServer and SubscriptionServer and that code just wouldn't compile as-is
=> Migration to apollo-server v3 SubscriptionServer validationRules

packages/server/src/ApolloServer.ts, packages/server/src/__tests__/ApolloServer.test.ts, packages/server/src/__tests__/integration/apolloServerTests.ts, packages/server/src/__tests__/integration/httpServerTests.ts, packages/server/src/__tests__/logger.test.ts, packages/server/src/__tests__/mockLogger.ts
=> Feedback / followups for #6514 (v4)

CHANGELOG.md, package-lock.json, packages/apollo-server-core/package.json, packages/apollo-server-core/src/ApolloServer.ts, packages/apollo-server-core/src/__tests__/UnboundedCache.test.ts, packages/apollo-server-core/src/__tests__/documentStore.test.ts, packages/apollo-server-core/src/utils/UnboundedCache.ts
This introduces a simple `Map`-backed, unbounded, in-memory cache
which implements TTLs. This lets us remove the dependency on
`keyv` and `@apollo/utils.keyvadapter` for a thing that we're going
to actively tell people not to use anyway.
=> Implement simple `UnboundedCache`

docs/source/config.json
Optionally, should we remove this and the gateway entry? I don't think it's bad that they're here. It wouldn't be so strange for someone in server docs to want to check out the API for those packages.
=> Update docs API link `@apollo/federation` -> `@apollo/subgraph`

docs/source/security/cors.mdx
While reading docs about CORS I found a mismatched sentence with provided information about the response header.
PR fixes the typo
=> Fix typo about request/response in CORS documentation

packages/server/src/ApolloServer.ts, packages/server/src/__tests__/ApolloServer.test.ts
We've added an addPlugin API that lets you add plugins after the
constructor, so it's no longer appropriate to do "have you added a usage
reporting plugin?" checks in the constructor. Instead we do it in
start().
This also means this code can be async, which means we can have it do
runtime deep imports soon...
While changing a test for this, add a bunch of missing server.stop()s to
tests.
Fixes #6552.
=> Move default plugin setup to start()

docs/source/api/plugin/cache-control.md
Max age param is in seconds not milliseconds
=> Fix mistake in docs

docs/source/performance/cache-backends.mdx
=> Caching docs: fix links, add highlighting, and additional tweaks

packages/server/package.json, packages/server/plugin/cacheControl/package.json, packages/server/plugin/disabled/package.json, packages/server/plugin/drainHttpServer/package.json, packages/server/plugin/inlineTrace/package.json, packages/server/plugin/landingPage/default/package.json, packages/server/plugin/landingPage/graphqlPlayground/package.json, packages/server/plugin/schemaReporting/package.json, packages/server/plugin/usageReporting/package.json, smoke-test/smoke-test.cjs, smoke-test/smoke-test.cts, smoke-test/smoke-test.mjs, smoke-test/smoke-test.mts
=> Fix `exports` and incorrect nested `package.json` files (version 4)

docs/source/api/plugin/landing-pages.md
#6628 
https://github.com/apollographql/apollo-server/pull/6628#discussion_r915101150
https://github.com/apollographql/apollo-server/pull/6628#discussion_r910210168
- Updated types of variables in the docs to Record<string, any>
=> NEBULA-1385: Sandbox initial state cleanup

packages/apollo-server-core/src/ApolloServer.ts
"without going through" is repeated twice
=> fix: "without going through" typo

.changeset/config.json, .changeset/great-hats-rhyme.md, .changeset/pre.json, .changeset/small-cycles-hammer.md, .envrc, .gitignore, package-lock.json, packages/integration-testsuite/CHANGELOG.md, packages/integration-testsuite/package.json, packages/plugin-response-cache/CHANGELOG.md, packages/plugin-response-cache/package.json, packages/server/CHANGELOG.md, packages/server/package.json, packages/usage-reporting-protobuf/CHANGELOG.md, packages/usage-reporting-protobuf/package.json
=> Get v4 initial alpha ready for release

cspell-dict.txt, docs/source/migration.mdx
@rkoron007 and I merged the last migration edit PR, but here's more! Flesh out most of the TODO sections, a few random edits, etc.
=> More migration edits

docs/source/config.json, docs/source/integrations/building-integrations.md
=> Integration authorship docs (version 4)

docs/source/index.mdx, docs/source/migration.mdx
Also fix link to migration guide.
=> docs: clarify scope of alpha

docs/source/getting-started.mdx
Just some small tweaks to the getting started guide to have it match Trevor's feedback from: https://github.com/apollographql/docs-examples/pull/46/files
=> Update "Getting Started" to match Trevor feedback from example

docs/source/data/data-sources.mdx, docs/source/data/errors.mdx, docs/source/data/file-uploads.mdx, docs/source/data/resolvers.mdx, docs/source/data/subscriptions.mdx, docs/source/schema/creating-directives.mdx, docs/source/schema/custom-scalars.md, docs/source/schema/directives.md, docs/source/schema/schema.md, docs/source/schema/unions-interfaces.md
Adding the v3 docs for an easier review process
=> Add v3 docs for an easier review process

docs/source/data/errors.mdx, docs/source/data/resolvers.mdx, docs/source/data/subscriptions.mdx, docs/source/getting-started.mdx, docs/source/integrations/building-integrations.md, docs/source/migration.mdx
Fixing some broken links and adding the "Getting Started" code sandbox example back in (now that it works!)
=> Fix Broken AS4 links

.circleci/config.yml
Noticed we were still running tests against node v17
=> Test against node v18

docs/source/api/apollo-server.mdx, docs/source/api/express-middleware.mdx, docs/source/api/plugin/drain-http-server.mdx, docs/source/api/plugin/landing-pages.mdx, docs/source/api/plugin/usage-reporting.mdx, docs/source/data/errors.mdx, docs/source/data/resolvers.mdx, docs/source/data/subscriptions.mdx, docs/source/getting-started.mdx, docs/source/index.mdx, docs/source/integrations/building-integrations.md, docs/source/integrations/plugins-event-reference.mdx, docs/source/migration.mdx, docs/source/monitoring/metrics.mdx, docs/source/performance/cache-backends.mdx, docs/source/performance/caching.md, docs/source/security/authentication.mdx, docs/source/security/cors.mdx, docs/source/security/terminating-ssl.mdx, docs/source/testing/testing.mdx, docs/source/workflow/build-run-queries.mdx, docs/source/workflow/requests.md
=> Address TODO(AS4) - Fixing links and removing unnecessary callouts 

docs/source/integrations/building-integrations.md, docs/source/testing/testing.mdx
Addressing @trevor-scheer's great point from: https://github.com/apollographql/apollo-server/pull/6907#discussion_r973400397
=> Move test suite note to integration article 

docs/source/data/fetching-rest.mdx
=> fix: s/Sever/Server

docs/source/workflow/generate-types.mdx
Based on feedback from: https://github.com/apollographql/apollo-server/pull/6904
=> Tweak Generating Types article based on feedback

docs/source/workflow/generate-types.mdx
https://github.com/apollographql/apollo-server/pull/6904
=> TypeGen article second pass to incorporate additional feedback from #6904

package-lock.json, package.json, packages/apollo-server-core/src/plugin/usageReporting/plugin.ts, packages/apollo-server-core/src/requestPipeline.ts, packages/apollo-server-core/src/runHttpQuery.ts, packages/apollo-server-core/src/utils/pluginTestHarness.ts, renovate.json5
Similar to https://github.com/ardatan/graphql-tools/pull/4382, but these didn't turn up in the 4.7 upgrade.
Likely related to https://github.com/microsoft/TypeScript/issues/49489.
Solution is to constrain our generics appropriately.
=> Upgrade `typescript` version and resolve "unconstrained generic" errors

package-lock.json, package.json
See https://github.com/microsoft/TypeScript/issues/50959
=> Roll back typescript to 4.7

docs/source/api/plugin/drain-http-server.mdx, docs/source/config.json, docs/source/data/resolvers.mdx, docs/source/deployment/heroku.md, docs/source/getting-started.mdx, docs/source/index.mdx, docs/source/integrations/building-integrations.md, docs/source/integrations/integration-index.mdx, docs/source/integrations/plugins-event-reference.mdx, docs/source/security/authentication.mdx
Took a shot at whipping up a basic integration page!
=> Adding a basic integration index page of AS4

docs/source/integrations/plugins-event-reference.mdx
=> docs: document new plugin hooks

docs/source/integrations/integration-index.mdx
=> Add Fastify to intergrations list

docs/source/integrations/plugins-event-reference.mdx
Feedback from https://github.com/apollographql/apollo-server/pull/7001
=> Add feedback for #7001

docs/source/api/apollo-server.mdx, docs/source/integrations/plugins.mdx, docs/source/monitoring/health-checks.mdx, docs/source/workflow/requests.md
Addressing @glasser's additional feedback from: https://github.com/apollographql/apollo-server/pull/6863
=> Add feedback from 6863

docs/source/config.json
Related docs change: https://github.com/apollographql/docs/pull/250
=> Update algolia filters in the docs to match new docset format

docs/source/api/plugin/landing-pages.mdx
=> docs: correct name and link to playground plugin

cspell-dict.txt, docs/source/integrations/integration-index.mdx
Add a reference to the new h3/nuxt apollo server integration https://www.npmjs.com/package/@as-integrations/h3.
Btw, developing the integration is way more convenient and easy with v4 than it was with v3. Good job on simplifying the process considerably!
=> Add nuxt/h3 integration to docs

cspell-dict.txt, docs/source/config.json, docs/source/data/fetching-data.mdx, docs/source/data/fetching-rest.mdx, docs/source/data/resolvers.mdx, docs/source/security/authentication.mdx
=> Add AS4 Fetching data article 

docs/source/migration.mdx
Don't merge this until https://github.com/apollographql/apollo-server/pull/6949 is merged in!
=> Adding information about RESTDataSource to the migration page and fix highlighting 

docs/source/deployment/azure-functions.mdx, docs/source/migration.mdx
Add note about migrating from AS2 to 3 and my linter removed some extra whitespace.
=> Add note about migrating from AS2 to 3

docs/source/security/cors.mdx
Incorporating feedback from an excellent comment by @glasser!
=> Correct and expand CORS origin note

.changeset/famous-glasses-study.md, package-lock.json, packages/gateway-interface/package.json
This doesn't really need to be here and will only cause additional major version woes when we upgrade to utils v2 packages that drop support for node v12.
=> Remove `engines` constraint on types-only gateway interface package

docs/source/schema/custom-scalars.mdx
Fix document error in `docs/source/schema/custom-scalars.mdx`
=> Docs: ReferenceError: GraphQLJSON is not defined

docs/source/previous-versions.mdx
There's been some apparent confusion around what EOL means for AS 2/3. Concerned folks seem to be under the impression that they need to migrate away immediately as if the software is going to disappear out from under them, so we should make it clear that's not the case, even if we recommend strongly against using EOL software.
=> Add note about EOL packages

.codesandbox/ci.json, package.json
CS:CI has reported that node 18 is now supported, meaning we should be able to simplify some config and remove a workaround.
Also add missing packages to the ci.json.
=> Update CS:CI config

docs/source/api/apollo-server.mdx
This tripped up a customer, and we only document the values for the first argument below.
=> docs: demo `contextValue` in `executeOperation`

docs/source/data/errors.mdx
=> docs: Fix typo in page "Error handling"

docs/source/data/fetching-rest.mdx
Updates for correctness based on upcoming v5 changes
=> RESTDataSource docs updates

docs/source/_redirects
=> Add redirects to v3 docs for serverless deploys

docs/source/data/errors.mdx
I just fixed a simple type to make the sentence correct.
=> A simple typo fixed

.gitignore, docs/source/data/file-uploads.md, docs/source/data/subscriptions.mdx, docs/source/testing/graphql-playground.mdx
Part of https://github.com/apollographql/apollo-server/issues/7332
=> Update v2 docs with official EOL messaging

docs/source/previous-versions.mdx
Fixes https://github.com/apollographql/apollo-server/issues/7332 (in tandem with #7335)
=> Update EOL messaging around v2 features which are no longer supported

docs/source/config.json, docs/source/getting-started.mdx, docs/source/index.mdx
Missed updating the banner in #7335, and there are a couple spots that actually duplicate the banner (so I removed them).
=> Remaining v2 EOL notice updates

CHANGELOG.md, cspell.yaml, package-lock.json, packages/apollo-reporting-protobuf/generated/protobuf.d.ts, packages/apollo-reporting-protobuf/generated/protobuf.js, packages/apollo-reporting-protobuf/src/reports.proto, packages/apollo-server-core/src/plugin/usageReporting/__tests__/plugin.test.ts, packages/apollo-server-core/src/plugin/usageReporting/plugin.ts, packages/apollo-server-core/src/plugin/usageReporting/stats.ts
Related: #7411
Smoke test is failing for the `v0.50.1` gateway in the mentioned PR, likely due to incompatible protobufs (v0 gateway installs `apollo-reporting-protobuf` instead of the more current `@apollo/usage-reporting-protobuf`) so this needs to be updated and published first.
=> Update protobuf (version-3)

docs/source/api/apollo-server.mdx
=> Update `plugins` documentation

packages/server/src/plugin/landingPage/default/types.ts
Follow up typings fix to https://github.com/apollographql/apollo-server/pull/7431
=> pre release fixup: never on both ends

docs/source/api/plugin/landing-pages.mdx
Docs for https://github.com/apollographql/apollo-server/commit/7cc163ac88e801324a24ba7d7e11c38796f52bb4
=> Docs ✏️ : landing page updates

docs/source/api/express-middleware.mdx
Had some confusion reading this in the way it was formatted, any other suggestions welcome.
=> Change formatting/wording to be more explicit in express-middleware.mdx

docs/source/schema/custom-scalars.mdx
Add links to the `@specifiedBy` directive
=> [docs] Update custom-scalars with specified by

docs/source/using-federation/api/apollo-gateway.mdx, docs/source/using-federation/apollo-gateway-setup.mdx, docs/source/using-federation/apollo-subgraph-setup.mdx
=> docs: update links

docs/source/api/apollo-server.mdx
Fixes an invalid table structure added in https://github.com/apollographql/apollo-server/pull/7916
=> docs: fix table

docs/source/performance/apq.md
Just removing a link that is not working anymore
=> Update apq.md and remove a link that is not working

docs/source/deployment/netlify.md, docs/source/index.mdx, docs/source/testing/graphql-playground.mdx
Link fixes and minor formatting changes for new platform
=> docs: v2 docs update

docs/source/migration.mdx, docs/source/previous-versions.mdx
Corrects link in https://github.com/apollographql/apollo-server/pull/7947
=> docs: update launch stage links

netlify.toml
Remove Netlify deploy preview of old docs
=> docs: remove monodocs deploy preview

netlify.toml
Removes unnecessary netlify.toml
=> docs: remove netlify.toml

docs/source/integrations/mern.mdx, docs/source/performance/apq.mdx
This PR adds links to relevant repositories in the apollosolutions organization.
https://github.com/apollographql/docs-rewrite/pull/343 must merge first since it adds a shared component used in this PR.
=> docs: add solutions repo links

.changeset/tasty-cameras-wash.md, .github/ISSUE_TEMPLATE/config.yml, .github/workflows/lock.yml, packages/server/README.md
Replace Discord with Discourse links since the Discourse Community Forum there is becoming our focus.
=> Replace Discord with Discourse

docs/source/security/proxy-configuration.md
Docs review for the Proxy Configuration page for AS5!
=> AS5 proxy configuration docs suggestions
