- src/apolloServer.js
- test/testApolloServer.js
Previously mocks would overwrite any resolvers. Includes test. As discussed in https://github.com/apollostack/graphql-tools/issues/53.
> Allows resolvers to be used with mocks

- src/apolloServer.js
- test/testApolloServer.js
Support adding resolvers to JS Schema
> Apply Resolvers to JS schema in apolloServer

- src/apolloServer.js
- test/testApolloServer.js
Attaches connectors even if schema is (partially) mocked. Adds tests.
> Attaches connectors to mocked schema

- CHANGELOG.md
- src/apolloServer.js
@helfer do you want changelog / tests for this change as well?
> update tracer mock report to be function and add mock of submit

- src/apolloServer.js
Fixes https://github.com/apollostack/apollo-server/issues/30
> fix spelling error

- package.json
- src/core/runQuery.ts
- src/index.ts
- src/integrations/expressApollo.test.ts
- src/integrations/expressApollo.ts
- src/integrations/hapiApollo.ts
- tsconfig.json
- typings.json
This PR get a basic working HAPI server into the core refactor branch. It also, includes a change to the runQuery module that allows us to build with es6 enabled but it will run in Node 4 LTS.
I have a project that I use to test using the core-refactor branch from an external project running in Node 4 LTS. If you would like to use it:
clone https://github.com/nnance/express-hapi-graphql
npm install {directory of your local apollo-server project}
npm run build
npm run dev:express or dev:hapi
> Core refactor hapi

- DESIGN.md
> initial design document for apollo server

- src/integrations/expressApollo.ts
- src/integrations/integrations.test.ts
@helfer found this bug in the new express implementation when swapi-apollo.  I will make sure this isn't broken in HAPI
> Add context support to Express

- DESIGN.md
- src/index.ts
- src/integrations/expressApollo.test.ts
- src/integrations/hapiApollo.test.ts
- src/integrations/hapiApollo.ts
- src/integrations/integrations.test.ts
- src/test/tests.ts
@helfer this PR is ready for review.  All the integration tests now pass for HAPI and Express.   I have asked @wookiehangover to help with the HAPI review.
> Apollo hapi

- CHANGELOG.md
- src/integrations/expressApollo.ts
For example, it's necessary to have the response object for mutations that set/clear cookies
(note that we do already have access to the response via `req.res`, but passing it via the options callback is a bit less surprising)
> Expose the Express response object to the options callback

- CHANGELOG.md
- src/core/runQuery.test.ts
- src/core/runQuery.ts
> log server events to logFunction

- src/integrations/integrations.test.ts
OK I hope I did it right this time.
I only added a failing test for file upload. @helfer let me know if it is OK ;)
TODO:
> Add failing test for file upload

- CHANGELOG.md
- src/integrations/hapiApollo.ts
- src/integrations/integrations.test.ts
The hapi integration didn't correctly check to see if a query was batched or not.
TODO:
> Fix query batching for single queries for hapi integration.

- CHANGELOG.md
- package.json
- src/core/runQuery.test.ts
- src/core/runQuery.ts
- src/integrations/apolloOptions.ts
- src/integrations/expressApollo.ts
- src/integrations/hapiApollo.ts
- src/integrations/integrations.test.ts
- src/integrations/koaApollo.ts
- typings.json
> Output stack trace for errors in debug mode

- CHANGELOG.md
- src/integrations/expressApollo.ts
- src/modules/renderGraphiQL.ts
This passes the Meteor login token in the authorization header so magically we are connected with the logged in user in GraphiQL.
-----
I wanted to make a solution that fits all types of Apps, not only Meteor. But I couldn't find a non-hacky way to pass headers to the fetch function.
So as a second option we could pass a string to renderGraphiQL (setting it in the options when creating the server) that we later put into the GraphiQL document string, like this:
```js
createApolloServer({
/* schema and resolvers */
}, {
graphiqlOptions: {
passHeader: "'Authorization': localStorage['Meteor.loginToken']"
}
})
```
```js
headers: {
'Accept': 'application/json',
'Content-Type': 'application/json',
${passHeader}
},
```
I don't like this solution very much but it works with non Meteor Apps
> Pass custom header in GraphiQL

- CHANGELOG.md
- src/integrations/koaApollo.ts
This is a breaking change. We need to mention this in the changelog.
TODO:
> Pass ctx instead of ctx.request to koa options function

- CHANGELOG.md
- src/integrations/expressApollo.ts
- src/integrations/hapiApollo.ts
- src/integrations/integrations.test.ts
- src/integrations/koaApollo.ts
This lets users distinguish multiple queries in a batch. It also
protects against users modifying the context in one query and
affecting another. (Although modifications to existing properties
of the context object will still be visible in other queries because
we only shallow copy.)
This replaced #177
> Shallow clone the `context` object for each query in a batch.

- README.md
Just seen that NPM badge is for the old package.
since this is built from couple of packages, i think it makes sense to point it to core...
> Update NPM Badge

- packages/graphql-server-core/package.json
- packages/graphql-server-express/package.json
- packages/graphql-server-hapi/package.json
- packages/graphql-server-integration-testsuite/package.json
- packages/graphql-server-koa/package.json
- packages/graphql-server-module-operation-store/package.json
Fixes #234
Changelog already has "Upgrade to GraphQL-js 0.8.1.".
> Allow to install graphql@0.8

- CHANGELOG.md
- lerna.json
- packages/graphql-server-core/package.json
- packages/graphql-server-core/src/graphqlOptions.ts
- packages/graphql-server-core/src/runQuery.ts
- packages/graphql-server-core/tsconfig.json
- packages/graphql-server-express/package.json
- packages/graphql-server-express/src/expressApollo.ts
- packages/graphql-server-express/tsconfig.json
- packages/graphql-server-hapi/package.json
- packages/graphql-server-hapi/src/hapiApollo.ts
- packages/graphql-server-hapi/tsconfig.json
- packages/graphql-server-integration-testsuite/package.json
- packages/graphql-server-integration-testsuite/tsconfig.json
- packages/graphql-server-koa/package.json
- packages/graphql-server-koa/src/koaApollo.ts
- packages/graphql-server-koa/tsconfig.json
- packages/graphql-server-module-operation-store/package.json
- packages/graphql-server-module-operation-store/src/operationStore.ts
- packages/graphql-server-module-operation-store/tsconfig.json
> Switch typings

- CHANGELOG.md
- README.md
- packages/graphql-server-core/src/graphqlOptions.ts
- packages/graphql-server-core/src/index.ts
- packages/graphql-server-core/src/runHttpQuery.ts
- packages/graphql-server-express/package.json
- packages/graphql-server-express/src/apolloServerHttp.test.ts
- packages/graphql-server-express/src/connectApollo.test.ts
- packages/graphql-server-express/src/expressApollo.ts
- packages/graphql-server-hapi/src/hapiApollo.test.ts
- packages/graphql-server-hapi/src/hapiApollo.ts
- packages/graphql-server-integration-testsuite/src/index.ts
- packages/graphql-server-koa/src/koaApollo.test.ts
- packages/graphql-server-koa/src/koaApollo.ts
> feat: support for GET method for existing servers

- CHANGELOG.md
- packages/graphql-server-express/src/expressApollo.ts
- packages/graphql-server-hapi/src/hapiApollo.test.ts
- packages/graphql-server-hapi/src/hapiApollo.ts
- packages/graphql-server-integration-testsuite/src/index.ts
- packages/graphql-server-koa/src/koaApollo.ts
> Use graphiql option variables if query variables are not supplied

- CHANGELOG.md
- packages/graphql-server-core/src/runHttpQuery.ts
- packages/graphql-server-express/src/apolloServerHttp.test.ts
- packages/graphql-server-integration-testsuite/src/index.ts
> Run batching queries in parallel (#176)

- CHANGELOG.md
- packages/graphql-server-core/package.json
- packages/graphql-server-express/package.json
- packages/graphql-server-hapi/package.json
- packages/graphql-server-integration-testsuite/package.json
- packages/graphql-server-koa/package.json
- packages/graphql-server-module-operation-store/package.json
- packages/graphql-server-restify/package.json
> allow graphql@0.9.0 as peerDependency

- package.json
- packages/graphql-server-core/package.json
- packages/graphql-server-core/tsconfig.json
- packages/graphql-server-express/tsconfig.json
- packages/graphql-server-hapi/tsconfig.json
- packages/graphql-server-integration-testsuite/tsconfig.json
- packages/graphql-server-koa/tsconfig.json
- packages/graphql-server-module-graphiql/tsconfig.json
- packages/graphql-server-module-operation-store/package.json
- packages/graphql-server-module-operation-store/tsconfig.json
- packages/graphql-server-restify/tsconfig.json
@DxCx now we don't have to include `@types/es6-shim`
> Use TypeScript es6 lib

- CHANGELOG.md
- packages/graphql-server-restify/src/restifyApollo.ts
Follow up to https://github.com/apollostack/graphql-server/pull/189
- Added next() calls and type annotation for restify.Next.  In order for restify’s "after" event to fire (like triggering a call to auditLogger), next() needs to be called after sending a response. From http://restify.com/#routing: "Note the use of next(). You are responsible for calling next() in order to run the next handler in the chain."
- I also discovered something with Restify’s bodyParser that results in an inconsistent response in a particular scenario vs. Koa and Express (didn’t check Hapi).  Restify’s bodyParser returns undefined (vs. Express & Koa returning {}) if body parser is used but no request body is sent.  This test https://github.com/apollostack/graphql-server/blob/master/packages/graphql-server-integra …
> Restify: Fix for calling next()

- packages/graphql-server-module-graphiql/src/renderGraphiQL.ts
I have just spent a couple of hours trying to get deprecation directives (among other things) working in `graphql-server`. The last of these issues had me wondering why  https://github.com/graphql/graphiql/issues/273 was closed but seemingly not working/implemented, even after upgrading to the latest package versions of graphql-server, graphiql, graphql-tools etc.
The issue is that the locally installed GraphQL implementation is not used at all and `graphql-server` seems to do its own dependency management instead. 
Is it possible to just `import 'graphiql'`? and add `graphiql` as a peer dependency to `graphql-server`? What edge cases was the current implementation intending to fix?
In the meantime, is it reasonable to just upgrade the GraphiQL version like this? There appear to have been …
> Update GraphiQL version to 0.9.1

- CHANGELOG.md
- README.md
- packages/graphql-server-lambda/.npmignore
- packages/graphql-server-lambda/README.md
- packages/graphql-server-lambda/package.json
- packages/graphql-server-lambda/src/index.ts
- packages/graphql-server-lambda/src/lambdaApollo.test.ts
- packages/graphql-server-lambda/src/lambdaApollo.ts
- packages/graphql-server-lambda/tsconfig.json
- test/tests.js
This adds the AWS lambda integration for Apollo Server. This requires a Lambda function that is attached to an API Gateway using the Lambda Proxy Integration. I had to add another parameter to the server to pass in headers. Headers to allow cross origin calls cannot be set when using Lambda Proxy Integration mode and must be passed in when calling the callback function.
To allow for the tests to pass I had to mock out the req and res objects that are required by the test suite. I thought this was easier than copying all the tests. I still get errors printed out, from uncaught exceptions, still looking into why.
I will add an example and some documentation to the README file and complete all the todo tasks below.
Closes #101
TODO:
> AWS Lambda Integration

- test/tests.js
Newer versions of Koa use features of ES6 that are not supported in
nodejs v4. This commits enables the Koa integration test only when run
on nodejs v6 or newer.
Stacktrace of error on nodejs v4:
```
/home/travis/build/apollographql/graphql-server/packages/graphql-server-koa/node_modules/koa/lib/response.js:47
const { res } = this;
^
SyntaxError: Unexpected token {
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Module.replacementCompile (/home/travis/build/apollographql/graphql-server/node_modules/append-transform/index.js:58:13)
at Module._extensions..js (module.js:416:10)
at Object.<anonymous> (/home/travis/build/apollographql/graphql-server/node_modules/append-transform/index.js:62:4)
at Module.load (module.js:343:32)
at Function.Module._load …
```
> Disable Koa integration test for NodeJS v4

- packages/graphql-server-lambda/README.md
This commit adds examples for modifying the response headers, to enable CORS, and how to read the event and context variables using an options function.
The lack of documentation has been brought up in the original PR and in this issue:
https://github.com/apollographql/graphql-server/issues/315
TODO:
> Update Lambda README to include more examples

- lerna.json
- package.json
- packages/graphql-server-core/package.json
- packages/graphql-server-express/package.json
- packages/graphql-server-hapi/package.json
- packages/graphql-server-integration-testsuite/package.json
- packages/graphql-server-koa/package.json
- packages/graphql-server-lambda/package.json
- packages/graphql-server-module-graphiql/package.json
- packages/graphql-server-module-operation-store/package.json
- packages/graphql-server-restify/package.json
Looks like there was a release without lerna pipe, this causes confusion as boostraping takes npm versions and not local versions.
I've aligned everything again so lerna will work as expected.
from now on, please use `npm run release` to release new versions.
TODO - Not needed i assume?:
will be taken out of #308
> Lerna release pipeline

- package.json
- packages/graphql-server-core/src/index.ts
- packages/graphql-server-core/src/runQuery.test.ts
- packages/graphql-server-lambda/src/index.ts
- tslint.json
- Fix missing semicolons
- Fix missing trailing commas
- Disable no-unused-expression for runQuery test
- expect uses unused expressions as an api Ex. expect('foo').to.be.equal();
- Disable no-use-before-declare since it requires type checking and project
file to be defined.
Closes #342 
TODO:
> Update ts-lint to version 5.0

- packages/graphql-server-core/src/graphqlOptions.ts
- packages/graphql-server-core/src/index.ts
- packages/graphql-server-core/src/runHttpQuery.ts
will be taken out of #308
TODO:
> generic options resolve function

- README.md
None of the other list items are links, so I thought it best to remove this one as well. Alternatively we could also turn them all into links, but I don't think that's necessary and might even be distracting.
> Remove link for consistency

- CHANGELOG.md
- packages/graphql-server-module-graphiql/src/renderGraphiQL.ts
Closes https://github.com/apollographql/graphql-server/issues/386. I can put this behind an option flag if needed. I'm pretty indifferent about actually disabling the behaviour (I can see it being useful), but can do that instead if that's a better decision.
TODO:
> Append `location.hash` to history navigation

- CHANGELOG.md
- packages/graphql-server-core/package.json
- packages/graphql-server-express/package.json
- packages/graphql-server-hapi/package.json
- packages/graphql-server-integration-testsuite/package.json
- packages/graphql-server-koa/package.json
- packages/graphql-server-lambda/package.json
- packages/graphql-server-micro/package.json
- packages/graphql-server-module-graphiql/src/renderGraphiQL.ts
- packages/graphql-server-module-operation-store/package.json
- packages/graphql-server-restify/package.json
Also updated `subscriptions-transport-ws` version to the latest.
TODO:
> chore(deps): updated graphql-js version to support 0.10.0

- packages/graphql-server-koa/tsconfig.json
- packages/graphql-server-restify/tsconfig.json
Had to do this to get things to compile with tsc. Otherwise I'd get duplicate typings.
> Do not include types in koa, restify

- CHANGELOG.md
- packages/graphql-server-core/src/runHttpQuery.ts
- packages/graphql-server-core/src/runQuery.test.ts
- packages/graphql-server-core/src/runQuery.ts
- packages/graphql-server-express/src/apolloServerHttp.test.ts
- packages/graphql-server-restify/src/restifyApollo.test.ts
- test/tests.js
hi @helfer 
i was trying out your `graphql-disable-introspection` module,
and then got into debug session why it's not working to find out GET Queries was not passing validation pipe.
this patch will make sure GET requests will go through validation as well.
TODO:
> [Security] get queries did not run through validation

- packages/graphql-server-integration-testsuite/src/index.ts
- packages/graphql-server-lambda/src/lambdaApollo.test.ts
- packages/graphql-server-micro/README.md
- packages/graphql-server-micro/package.json
- packages/graphql-server-micro/src/microApollo.test.ts
- packages/graphql-server-micro/src/microApollo.ts
The handler was not returning `httpRunQuery`'s Promise, causing micro to send empty responses and leaving Node with unhandled Promise rejections when that Promise tried to write headers.
I also used `return` and `throw` instead of manipulating the response directly.  This allows wrapping middleware to intercept responses if desired.
> Fix Micro server handler

- CHANGELOG.md
- packages/graphql-server-express/src/expressApollo.ts
- packages/graphql-server-express/src/index.ts
- packages/graphql-server-hapi/src/hapiApollo.ts
- packages/graphql-server-hapi/src/index.ts
- packages/graphql-server-integration-testsuite/src/index.ts
- packages/graphql-server-koa/src/index.ts
- packages/graphql-server-koa/src/koaApollo.ts
- packages/graphql-server-lambda/src/index.ts
- packages/graphql-server-lambda/src/lambdaApollo.ts
- packages/graphql-server-micro/src/index.ts
- packages/graphql-server-micro/src/microApollo.ts
- packages/graphql-server-module-graphiql/src/index.ts
- packages/graphql-server-module-graphiql/src/resolveGraphiQLString.ts
- packages/graphql-server-restify/src/index.ts
- packages/graphql-server-restify/src/restifyApollo.ts
This is a proposed implementation to address #418.
TODO:
> Allow GraphiQLOptions to be a function

- packages/graphql-server-koa/src/koaApollo.ts
It looks like a recent change broke the graphiql endpoint by no longer returning the promise.
> Fixes broken graphiql endpoint

- packages/graphql-server-micro/README.md
Fixes #449 for now by adding a noop route to the example so that graphiql does not 404.
Note that this is not a code change and as such I have not included it in the changelog. Please let me know if this is incorrect.
> fix(graphql-server-micro): micro-router requires one 200 route

- packages/graphql-server-micro/README.md
- packages/graphql-server-micro/src/microApollo.ts
This solves issue #449 without workarounds on microrouter definitions.
**This is a proposal! Please review the code before merging!** (It's my first experience with typescript, maybe also the README must be reviewed)
I was not able to provide tests for this use case, but the diff consists on a refactor to the graphiql handler. It use an async function so the microroute awaits the execution of the handler before  responds with a 404
> Using await on graphiql handler - Fix graphiql issues

- CHANGELOG.md
- lerna.json
- packages/graphql-server-express/src/expressApollo.ts
This is in relation to [issue 462](https://github.com/apollographql/graphql-server/issues/462)
Logic now matches the logic in the Restify package more closely.
TODO:
> adding in the callback to express package

- packages/apollo-server-express/README.md
- packages/apollo-server-hapi/README.md
- packages/apollo-server-koa/README.md
- packages/apollo-server-restify/README.md
Individual packages don't have separate `CONTRIBUTING.md` and `ROADMAP.md` files so those links were broken.
> Fix links to CONTRIBUTING.md and ROADMAP.md in package readmes

- packages/apollo-server-koa/README.md
As koa@2 seems to now be the norm, the master/latest releases of both koa-bodyparser and koa-router support koa@2 . The `@next` tags/versions needn't be a thing any more.
I also added documentation for the `passHeader` functionality of `graphiqlKoa`. The lack of this almost made me write my own GraphiQL server.
> Update readme for the koa package

- packages/apollo-server-module-graphiql/src/renderGraphiQL.ts
Bumped the GraphiQL version to latest (0.11.2). Just changing the version would have broken the CDN link due to a change in jsDelivr (see [their docs](https://github.com/jsdelivr/jsdelivr/blob/master/README.md)), so I also updated the url structure.
> Update GraphiQL version

- CHANGELOG.md
- packages/apollo-server-module-graphiql/src/renderGraphiQL.ts
- packages/apollo-server-module-graphiql/src/resolveGraphiQLString.ts
Added ability to apply themes to GraphiQL (solves #444).
TODO:
> Add support for GraphiQL editor themes

- CHANGELOG.md
- packages/apollo-server-module-graphiql/src/renderGraphiQL.ts
Changes in this PR:
- Update GraphiQL to use latest packages:
- subscription-transport-ws = 0.8.2
- fetch = 2.0.1
- react = 15.6.1
- use websocket transport `request` method incase endpointURL starts with `ws://`
(Full WebSocket mode)
- keep legacy api (endpointURL=http, subscriptionsEndpoint=ws) working exactly like before.
- bug fix for undefined graphiql variables set into url.
TODO:
> GraphiQL: Allow full websocket mode

- CHANGELOG.md
- packages/apollo-server-core/package.json
- packages/apollo-server-core/src/graphqlOptions.ts
- packages/apollo-server-core/src/runHttpQuery.ts
- packages/apollo-server-core/src/runQuery.test.ts
- packages/apollo-server-core/src/runQuery.ts
- packages/apollo-server-express/package.json
- packages/apollo-server-hapi/package.json
- packages/apollo-server-integration-testsuite/package.json
- packages/apollo-server-koa/package.json
- packages/apollo-server-lambda/package.json
- packages/apollo-server-micro/package.json
- packages/apollo-server-module-operation-store/package.json
- packages/apollo-server-restify/package.json
- tsconfig.json
This is currently blocked because the Typescript GraphQL definition doesn't support this. I'll update the DefinetelyTyped definition and then this can be merged.
TODO:
> Add ability to provide default field resolvers

- README.md
It is my understanding that `POST` to `/graphiql` will never occur since GraphiQL will talk to `/graphql` directly. Since this is not needed I suggest we to remove it to avoid confusion.
> Remove unnecessary route in Koa example

- CHANGELOG.md
- README.md
- packages/apollo-server-core/package.json
- packages/apollo-server-core/src/graphqlOptions.ts
- packages/apollo-server-core/src/runHttpQuery.ts
- packages/apollo-server-core/src/runQuery.ts
- packages/apollo-server-express/package.json
- packages/apollo-server-hapi/package.json
- packages/apollo-server-integration-testsuite/package.json
- packages/apollo-server-koa/package.json
- packages/apollo-server-lambda/package.json
- packages/apollo-server-micro/package.json
- packages/apollo-server-module-operation-store/package.json
- packages/apollo-server-restify/package.json
This PR adds a `tracing` option to Apollo Server to collect and expose trace data in the [Apollo Tracing format](https://github.com/apollographql/apollo-tracing).
When set to true, the server will include resolver timings and other execution information as part of the `extensions` field of the GraphQL response, and tools can extract this data from the response to give more insight into individual requests, and to track server performance and schema usage over time.
The format is work in progress. We're collaborating with others in the GraphQL community to make it available in different server environments, and to build awesome tools on top of it!
[Apollo Optics](https://www.apollodata.com/optics/) will use Apollo Tracing as a replacement for the current agent architecture.
> Add tracing support

- README.md
- packages/apollo-server-azure-functions/.npmignore
- packages/apollo-server-azure-functions/README.md
- packages/apollo-server-azure-functions/package.json
- packages/apollo-server-azure-functions/src/azureFunctionsApollo.test.ts
- packages/apollo-server-azure-functions/src/azureFunctionsApollo.ts
- packages/apollo-server-azure-functions/src/index.ts
- packages/apollo-server-azure-functions/tsconfig.json
- test/tests.js
~~Some stuff works and some don't. I seem to need some help here, I have used the Lamda implementation as a base but I seem to be doing something wrong when I pass stuff to `runHttpQuery`.~~
~~All tests pass, I have to find another type definition for Azure Functions or just write my own.~~
Changed to @christopheranderson's lib for the types. I'm not sure what you want me to write in the CHANGELOG and if it is a new version or how this works.
TODO:
> Azure Functions bindings

- packages/apollo-server-module-graphiql/src/resolveGraphiQLString.ts
I noticed when using in production the query will not be undefined, but null. This doesn't work with default arguments.
TODO:
> fix default query case when query value null is provider

- CHANGELOG.md
- packages/apollo-server-module-graphiql/src/renderGraphiQL.ts
See Discussion: https://github.com/apollographql/apollo-server/issues/514
TODO:
> Move from credentials: 'include' to 'same-origin'

- CHANGELOG.md
- packages/apollo-server-hapi/src/hapiApollo.ts
Hi there!
I've added the option to add a vhost to the endpoint, as it should be allowed by Hapi [route configuration](https://hapijs.com/api#route-configuration).
TODO:
> Added vhost option for Hapi

- README.md
- packages/apollo-server-hapi/README.md
Thanks for sharing `apollo-server`, it's a great project.
I think it would be nice to add debug info to the `Hapi.server` call in the `README`, as people will be cutting and pasting this information from the docs and elsewhere whenever they start a new project (I know I do). Since there isn't an up-to-date and complete starter project, people are prone to making silly errors during setup. Adding this debug info is a very simple change that can cut debugging time (and potential frustration levels) down considerably. Especially for people who are new to development, or hapi, or graphql, or apollo in particular.
I am able to quickly figure things out on my own, but someone else may not be able to. Having debugging on "by default" will help get people up and going faster, and easier. It will …
> Add debug to Hapi code sample

- packages/apollo-server-express/src/expressApollo.ts
Sending a content-length header allows CloudFront to gzip compress the response.
> Send content length header.

- packages/apollo-server-module-graphiql/src/renderGraphiQL.ts
I found current `GraphiQL` is missing checking `wss` which is secure protocol for websocket. But mostly site is under `https` now, and cannot communicate with non-secure service. So it's very important to add this support.
> Adding support for wss

- README.md
Launchpad is a great location for people to start looking at a working implementation of Apollo Server. I found that trying to setup a simple example from the readme wasn't clear(needs babel and nodemon), so I ended up just downloading the hello world pad.
From a newbie's point of view, it's also not clear that some sort of build step is necessary for the examples. I'll add a disclaimer in another PR.
> Add Launchpad link to README

- packages/apollo-server-module-graphiql/src/renderGraphiQL.ts
In current implementation of `apollo-server-module-graphiql`, it pushes useless `null` values of `variables` and `operationName` to URL string, so it usually becomes like
> example.com/graphiql?query=something&**operationName=null&variables=null**
This hasn't any useful value, and this behavior even causes [bugs like this](https://github.com/graphql/graphiql/issues/234) (filled under unrelated another repo, though) (read [this comment](https://github.com/graphql/graphiql/issues/234#issuecomment-312109591) about how to reproduce).
This PR fixes that.
> Make only truthy values to be in URL in GraphiQL

- CHANGELOG.md
- packages/apollo-server-core/src/runQuery.test.ts
- packages/apollo-server-core/src/runQuery.ts
By creating a promise out of the execution flow the ability to trace the
async call stack is lost.
TODO:
> Fix apollo-server-core runQuery breaks async_hook tracking

- .gitmodules
- docs/.gitignore
- docs/README.md
- docs/_config.yml
- docs/package.json
This PR is part of a series of mostly-automated PRs whose primary goal is to replace the Hexo theme, which has historically been provided with a Git submodule to the [theme repository](https://github.com/meteor/hexo-theme-meteor), with a theme installed via the [`meteor-theme-hexo`](https://github.com/hexo-theme-meteor) package ([npm](https://npm.im/meteor-theme-hexo)) which was created after the re-convergence of the (previously-separated) Apollo and Meteor themes which took place in https://github.com/meteor/hexo-theme-meteor/pull/51. 
I (@abernix) will check each of these automated PRs' Netlify deploy previews and comment on the PR once it is ready to be merged.
**Please do not merge this until I've updated with confirmation.**
The Apollo repositories which are receiving this PR are …
> [docs] Use package-based Hexo theme, rather than a Git submodule.

- CONTRIBUTING.md
- DESIGN.md
- docs/source/migration.md
- packages/apollo-server-express/package.json
- packages/graphql-server-express/package.json
For reasons unbeknownst to me, the changes below were only being complained
about in the CI environment but _not_ when I ran `npm run lint` locally.
It seems partially related to the OS its ran on, so I imagine there might be
some other sub-dependency at play here.  In an effort to fix this, I just
spawned a Ubuntu docker image, checked out this repository and ran the same
`npm run lint`.  This produced identical results to Travis, so I ran
`npm run lint-fix`, then saved the `git diff` results and have applied this
locally.
This should allow us to re-enable `prettier` in CI, though I have plans to
separate that from the actual `npm test` runs.  This should result in a better
workflow for managing PRs.
> Tick off Prettier checkmarks, which were present on CI but not locally.

- package.json
With a lack of comments and a fairly strict structure, it's arguable if JSON
files were ever meant to be pretty, but the method we're using right now is
a bit futile, especially considering that tools that we use to automatically
update JSON (specifically, package.json) don't run prettier themselves.
The most problematic rule is the 80 characters line limit.
Lines in JSON can be wrapped in, at most, one place: after the colon in the
key.  This means that as soon as a single npm-script declaration exceeds the
line-length rule a second time, it can't be wrapped again, resulting in a
violation of the very rule being enforced.
Clearly, I've always thought that prettying JSON is a bit silly, but the
straw that broke the camel's back here is automated package.json changes by
bots which update …
> Stop `prettier`-ing JSON files.

- CHANGELOG.md
- packages/apollo-server-module-graphiql/src/renderGraphiQL.ts
This just bumps the version of of GraphiQL to the latest bugfix release.
TODO:
> GRAPHIQL_VERSION 0.11.2 → 0.11.11

- CHANGELOG.md
- packages/apollo-server-adonis/README.md
- packages/apollo-server-azure-functions/README.md
- packages/apollo-server-core/README.md
- packages/apollo-server-express/README.md
- packages/apollo-server-hapi/README.md
- packages/apollo-server-koa/README.md
- packages/apollo-server-lambda/README.md
- packages/apollo-server-micro/README.md
- packages/apollo-server-module-graphiql/README.md
- packages/apollo-server-module-operation-store/README.md
- packages/apollo-server-restify/README.md
- packages/graphql-server-core/README.md
- packages/graphql-server-express/README.md
- packages/graphql-server-hapi/README.md
- packages/graphql-server-koa/README.md
- packages/graphql-server-lambda/README.md
- packages/graphql-server-micro/README.md
- packages/graphql-server-module-graphiql/README.md
- packages/graphql-server-module-operation-store/README.md
- packages/graphql-server-restify/README.md
There were many missing releases and bullet points as well as inaccurate
ones. For example, it was impossible to figure out that users of Hapi 16 who
want to use Apollo Cache Control needed to use precisely version 1.2.0 of
apollo-server-hapi (which wasn't even mentioned).
Link to CHANGELOG from all READMEs. Add READMEs for the graphql-server-*
packages. Add an explanation of our versioning system to the top of
CHANGELOG.md.
> Update CHANGELOG for all releases back to v1.1.3

- renovate.json
Renovate v12 introduces a default of `pinVersions=false` and removes the hardcoded `peerDependencies.pinVersions=false` setting. This repository's root level `pinVersions=true` therefore then trickles down to `peerDependencies` as well. This PR updates Renovate config to use a preset that pins everything except `peerDependencies`.
TODO:
> chore(renovate): disable pinning for peerDependencies

- packages/apollo-server-express/src/expressApollo.ts
This change seems necessary in order to meet the new type definitions for
`res.setHeader` which mandate that the argument be a string, or an array of
strings.  Those type definitions were introduced via the `@types/node@9`
series of typing updates provided in ([0]), ([1]), ([2]).
With any luck, this will fix the failures being exhibited in CircleCI
tests ([3]) after we landed those typing updates.
[0]: https://github.com/apollographql/apollo-server/pull/907
[1]: https://github.com/apollographql/apollo-server/pull/927
[2]: https://github.com/apollographql/apollo-server/pull/939
[3]: https://circleci.com/gh/apollographql/apollo-server/1587
> Convert `Buffer.byteLength` to string before assigning to `Content-Length`.

- CHANGELOG.md
- packages/apollo-server-adonis/src/adonisApollo.ts
#Issue #867
Responses from apollo-server-adonis shall have a Content-Type: application/json header set.
Responses have Content-Type: text/plain; charset=utf-8 header set.
The module apollo-server-adonis calls response.json(gqlResponse) after it gets the output from runHttpQuery.
However, gqlResponse is already stringified (see link 1). The only reason .json method works, is because it is an "alias" to .send and uses heuristics to determine the content type in the end, regardless of the response method used. Adonis has it's own response object, with a similar interface to Express but a different implementation.
Continue returning gqlResponse as-is, but use send method and manually set the content type header to application/json. The easiest to implement.
> FIX: Incorrect Content-Type for apollo-server-adonis

- CHANGELOG.md
- packages/apollo-server-azure-functions/README.md
- packages/apollo-server-azure-functions/src/azureFunctionsApollo.ts
Still a WIP. Addresses  #684.
TODO:
> Added fixes to apolloAzureFunctions.js and sample functions for the GraphQL API and for GraphiQL

- packages/apollo-server-adonis/src/adonisApollo.ts
- packages/apollo-server-azure-functions/src/azureFunctionsApollo.ts
- packages/apollo-server-express/src/expressApollo.ts
- packages/apollo-server-koa/src/koaApollo.ts
- packages/apollo-server-lambda/src/lambdaApollo.ts
- packages/apollo-server-micro/src/microApollo.ts
- packages/apollo-server-restify/src/restifyApollo.ts
It's making the investigation of performance issues easier.
**New Relic**
**Chrome Dev Tool (express-graphql but I'm considering moving to apollo-server)**
Related to:
- https://github.com/i18next/i18next-express-middleware/pull/144
- https://github.com/helmetjs/helmet/pull/165
- https://github.com/getsentry/raven-node/pull/424
> Use a named function for the middleware over an anonymous

- packages/apollo-server-core/src/graphqlOptions.ts
This small patch adds optional support for tighter typing on the context of GraphQLServerOptions, to match the equivalent ones in graphql-tools. There's still a gap as `GraphQLSchemaConfig`, `GraphQLObjectType` and `getFields` are all still typed as `any`, but it at least allows a demonstration of consistency between the resolvers passed to makeExecutableSchema and the context that will be supplied by parameterising them both with a common type. The param defaults to any and is backwards compatible.
TODO:
/label types
> Tighter context typing for GraphQLServerOptions

- packages/apollo-server-core/src/runQuery.test.ts
- packages/apollo-server-express/src/apolloServerHttp.test.ts
- packages/apollo-server-integration-testsuite/src/index.ts
- packages/apollo-server-module-operation-store/src/operationStore.test.ts
This change was introduced by the changes in apollographql/apollo-server#802 but first showed its head in apollographql/apollo-server#908.  The reason that violations in new type definitions aren't being found until subsequent PRs isn't entirely clear but, ignoring that CI-related annoyance, the problem itself here is very concrete.
It traces back to a major version update to `@types/mocha` via [Exhibit A], which makes it unacceptable to return anything besides a `Promise` or _nothing_ from a Mocha test factory.
I agree with this change in principle, since generally speaking there can be multiple `expect` statements in each test and there is no particular reason that the last one's value should be getting returned as Mocha doesn't do anything functional with it.
More than anything, this …
> Stop violating types by returning assertions from Mocha tests.

- packages/apollo-server-core/src/runHttpQuery.ts
- packages/apollo-server-integration-testsuite/src/index.ts
Apollo Persisted Queries is a standard for sending queries as short hashes
instead of full strings, designed to work well with GET requests. It is
implemented by servers including the Apollo Engine Proxy, and by the
apollo-link-persisted-query client.
A common configuration is to set up persisted queries on production servers but
not in development. It is still convenient to leave apollo-link-persisted-query
always on, though. While apollo-link-persisted-query can detect that servers
don't support PQs, it works better if the server actually says it doesn't
support the PQ, instead of trying to process a request without a query and
potentially printing a confusing stack trace.  This commit makes apollo-server
directly return PersistedQueryNotSupported instead of allowing confusing stack …
> core: return PersistedQueryNotSupported for Apollo Persisted Queries

- .circleci/config.yml
npm 6 deprecates support for Node.js 4, which is still LTS until the end of the week.
It's probably best to take a moment and ensure that npm@6 is actually working as we desire too, so this is just to make sure that we don't end up with a bunch of PRs that need to be re-based/re-tested, which seems to already be happening.
> Pin npm to 5, at least for the time-being.

- docs/source/api/apollo-server.md
Beginnings of `apollo-server` API docs, but not the end.
> [Work in Progress] docs: API > `apollo-server`.

- docs/_config.yml
- docs/source/essentials/data.md
- docs/source/essentials/querying.md
- docs/source/essentials/schema.md
- docs/source/essentials/server.md
- docs/source/index.md
* Bury Best Practices, for the time being.
* Bury Schema, but leave it on disk.
* Introduce new Querying section.
* Move "Why Apollo Server?" into "Index".
* ...to be refined.
* Remove no-longer-helpful "Getting Started" from "Index".
cc @stubailo @evans @peggyrayzis @JakeDawkins @unicodeveloper @jbaxleyiii
> docs: Iteration from Docs workshop.

- docs/source/schemas/mocking.md
Adds mocking to the docs, according to the changes found in #1006
> docs: add mocking to apollo-server from graphql-tools

- packages/apollo-server-core/CHANGELOG.md
- packages/apollo-server-core/src/runQuery.test.ts
- packages/apollo-server-core/src/runQuery.ts
Removes stack trace printing coupling to `debug` option and include response in the log function.
> Remove stack traces print and include response in logging function

- docs/.gitignore
- docs/_config.yml
- docs/package.json
- docs/public/_redirects
This uses `hexo-versioned-netlify-redirects`[0], a package I wrote just for this purpose (on Meteor) a few months back.
With any luck, this will do the trick for Apollo too.
[0]: https://github.com/meteor/hexo-versioned-netlify-redirects
> Enable version support via Netlify redirects.

- docs/source/migration-two-dot.md
- Added no breaking changes to the intro
- Changed explanation of `gql` tag
> Minor edits to the migration guide

- .circleci/config.yml
- CHANGELOG.md
- packages/apollo-server-core/CHANGELOG.md
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/errors.ts
- packages/apollo-server-core/src/graphqlOptions.ts
- packages/apollo-server-core/src/index.ts
- packages/apollo-server-core/src/logging.ts
- packages/apollo-server-core/src/runHttpQuery.ts
- packages/apollo-server-core/src/runQuery.test.ts
- packages/apollo-server-core/src/runQuery.ts
- packages/apollo-server-express/src/apolloServerHttp.test.ts
- packages/apollo-server-integration-testsuite/src/index.ts
- packages/apollo-server-koa/package.json
This PR allows the context option in apollo-server-core's runQuery/runHttpQuery to be an async function, which would be common in authentication fetching scenarios.
Additionally, this PR increases the capture and formatting of errors during the creation of the options and context.
> Enables context creation to be async and capture errors with opt-in logging

- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/types.ts
- packages/apollo-server/src/index.ts
This renames the engine parameter in listen to engineProxy and overloads the parameter as the launch options. If true, the server assumes that the proxy is already in place. Otherwise if an object is passed as engineProxy, then the proxy is launched as a parallel process.
The PR also makes the schemaDirectives parameter optional in addition to the healthcheck parameters.
> engine -> engineProxy in listen, fix engineLauncherOptions, and make unrequired parameters optional

- CHANGELOG.md
- packages/apollo-server-module-graphiql/src/renderGraphiQL.ts
The newer subscription client has a more forgiving default ka timeout
TODO:
> bump version of subscriptions-transport-ws for graphiql

- packages/apollo-server-core/CHANGELOG.md
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/types.ts
- packages/apollo-server-express/src/ApolloServer.ts
- packages/apollo-server/CHANGELOG.md
- packages/apollo-server/package.json
- packages/apollo-server/src/index.ts
This moves the options for the default apollo-server from the constructor into the listen function. The goals is to keep the server constructor the same across all environments. Additional functionality is added in other function, such as `listen` or `registerServer`.
Additionally, @thepwagner found a bug, where `registerServer` was not called when `disableHealthCheck` was true on [this line](https://github.com/apollographql/apollo-server/compare/refactor-2.0...server-2.0/default-impl-params?expand=1#diff-c635668124bc43d28885aa7d04c99342R52) and requested the ability to configure the body parser of express.
> AS2: Move default options into listen function and add bodyParserConfig

- packages/apollo-server-hapi/README.md
- packages/apollo-server-hapi/package.json
- packages/apollo-server-hapi/src/ApolloServer.ts
- packages/apollo-server-hapi/src/hapiApollo.ts
- packages/apollo-server-hapi/src/index.ts
This defines the hapi plugin for the new apollo server 2 interface.
> Apollo server 2 for hapi

- .circleci/config.yml
Node.js 9, as with odd numbered Node.js versions, is no longer longer being
actively maintained with the release of (even numbered) Node.js 10.
Node.js 4 will no longer be receiving any additional updates from the
Node.js foundation.
For more details see the LTS schedule and Node.js blog posts:
Ref: https://medium.com/the-node-js-collection/april-2018-release-updates-from-the-node-js-project-71687e1f7742
Ref: https://github.com/nodejs/LTS
> tests: Update Node.js testing versions.

- packages/apollo-server-core/src/ApolloServer.test.ts
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/types.ts
Moves http options, such as `port` and `host`, under key in `listenOptions`.
> apollo-server-core: move http options under own key in listenOptions

- packages/apollo-server-hapi/src/ApolloServer.ts
Adds options to `registerServer` that will construct a hapi server if none is passed in as to the `app` field.
> apollo-server-hapi: add options parameter to create a server

- docs/source/index.md
Adds a pointer to v2 docs from the v1 documentation
> docs: add pointer to apollo server 2 documentation

- packages/apollo-server-express/src/ApolloServer.ts
- packages/apollo-server-hapi/src/ApolloServer.ts
- packages/apollo-server/src/index.ts
Moves health check into the server variants from default apollo-server. Adds support for health check in apollo-server-hapi. 
Additionally adds the cors option to apollo-server default's listen function.
> Move health check into the server variants

- packages/apollo-server/src/index.ts
This removes the healthcheck, body parser, and cors from the `listen` configurations in the default apollo-server. Since the `listen` interface is shared across all standalone node integrations, it was quite important to make the listen interface cleaner. The defaults are generous, with cors set to * and body parser limit to 50mb to allow large file uploads.
> apollo-server: remove extra configuration of registerServer from listen

- packages/apollo-server-express/package.json
- packages/apollo-server-express/src/ApolloServer.test.ts
- packages/apollo-server/package.json
- packages/apollo-server/src/index.test.ts
- test/tests.js
Adds basic apollo-server and express integration tests. Including the constructor, registerServer, healthchecks, and basic querying
> Basic apollo-server and express integration tests

- packages/apollo-server-adonis/src/adonisApollo.ts
- packages/apollo-server-azure-functions/src/azureFunctionsApollo.ts
- packages/apollo-server-cloudflare/src/cloudflareApollo.ts
- packages/apollo-server-core/package.json
- packages/apollo-server-core/src/ApolloServer.test.ts
- packages/apollo-server-core/src/runHttpQuery.test.ts
- packages/apollo-server-core/src/runHttpQuery.ts
- packages/apollo-server-express/src/expressApollo.ts
- packages/apollo-server-hapi/src/hapiApollo.ts
- packages/apollo-server-koa/src/koaApollo.ts
- packages/apollo-server-lambda/src/lambdaApollo.ts
- packages/apollo-server-micro/src/microApollo.ts
- packages/apollo-server-restify/src/restifyApollo.ts
This adds the request as an argument to runHttpQuery, so that we have access to it in reporting.
This is a breaking change for `apollo-server-core`
> apollo-server-core: add request to runHttpQuery for access to headers

- README.md
- packages/apollo-server-core/CHANGELOG.md
- packages/apollo-server-core/src/runHttpQuery.ts
- packages/apollo-server-core/src/runQuery.test.ts
- packages/apollo-server-core/src/runQuery.ts
- packages/apollo-server-integration-testsuite/package.json
- packages/apollo-server-integration-testsuite/src/index.ts
This places the parsing of the AST into runQuery and removes the ability to send an AST to the server. The removal of this functionality is a breaking change considered a bug fix. It fits with Apollo Server 2's theme of enforcing best practices with sensible defaults. Sending an AST over the wire is certainly not recommended.
> Always only parse query in runQuery and don't accept AST over the wire

- packages/apollo-server-adonis/src/adonisApollo.ts
- packages/apollo-server-core/CHANGELOG.md
- packages/apollo-server-core/package.json
- packages/apollo-server-core/src/ApolloServer.test.ts
- packages/apollo-server-core/src/index.ts
- packages/apollo-server-core/src/nodeHttpToRequest.ts
- packages/apollo-server-core/src/runHttpQuery.ts
- packages/apollo-server-core/src/runQuery.test.ts
- packages/apollo-server-core/src/runQuery.ts
- packages/apollo-server-express/src/ApolloServer.test.ts
- packages/apollo-server-express/src/expressApollo.ts
- packages/apollo-server-hapi/src/hapiApollo.ts
- packages/apollo-server-koa/src/koaApollo.ts
- packages/apollo-server-micro/src/microApollo.ts
- packages/apollo-server-restify/src/restifyApollo.ts
**breaking change** to apollo-server-core that adds a request object into runQuery, so that the extensions have access to the headers, url, and http method.
> runQuery accepts Request object that variants create 

- packages/apollo-server-core/src/ApolloServer.test.ts
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/errors.test.ts
- packages/apollo-server-core/src/errors.ts
- packages/apollo-server-express/src/ApolloServer.test.ts
- packages/apollo-server-express/src/ApolloServer.ts
- packages/apollo-server-express/src/apolloServerHttp.test.ts
Defers throwing of an error during context creation until the thunk containing the result of `context` as a function is called in `runQuery`.
Additionally handles errors that are returned by merged schema, surfacing errors that are hidden by CombinedError in `graphql-tools`.
Fixes #1100 
Related to #1077
> AS2: Fix handling errors from context constructor and merged schemas

- docs/source/setup.md
- packages/apollo-server-adonis/package.json
- packages/apollo-server-azure-functions/package.json
- packages/apollo-server-cloudflare/package.json
- packages/apollo-server-cloudflare/src/ApolloServer.ts
- packages/apollo-server-core/package.json
- packages/apollo-server-core/src/ApolloServer.test.ts
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/graphqlOptions.ts
- packages/apollo-server-core/src/nodeHttpToRequest.ts
- packages/apollo-server-core/src/runHttpQuery.ts
- packages/apollo-server-core/src/runQuery.test.ts
- packages/apollo-server-core/src/runQuery.ts
- packages/apollo-server-core/src/types.ts
- packages/apollo-server-express/package.json
- packages/apollo-server-express/src/ApolloServer.ts
- packages/apollo-server-hapi/package.json
- packages/apollo-server-hapi/src/ApolloServer.ts
- packages/apollo-server-integration-testsuite/package.json
- packages/apollo-server-koa/package.json
- packages/apollo-server-lambda/package.json
- packages/apollo-server-micro/package.json
- packages/apollo-server-restify/package.json
- packages/apollo-server/package.json
I started with #934 by @sebas5384 (which allows you to pass in your own extensions) and updated it for a new graphql-extensions API.
- Actually call validationDidStart and parsingDidStart.
- Use new graphql-extensions API which:
- replaces fooDidEnd with a handler returned by fooDidStart
- adds options to various methods
- has a new willSendResponse method
- requires you to construct the extension objects yourself
- Make a better effort at consistently calling end handlers even on error
> Allow user-defined GraphQLExtensions, add apollo-engine-reporting

- README.md
Since koa@2 has been published for a long time, and almost all the middlewares migrated to koa@2.
It's no need to add extra dist names for koa and koa middlewares.
> readme: remove dist names about koa

- packages/apollo-server-core/package.json
- packages/apollo-server-core/src/errors.ts
- packages/apollo-server-core/src/logging.ts
- packages/apollo-server-core/src/runQuery.test.ts
- packages/apollo-server-core/src/runQuery.ts
This requires a slightly newer graphql-extensions beta which has more arguments
to requestDidStart.
Also make it ok to not pass logFunction to formatApolloErrors.
> Factor out runQuery's use of logFunction into an extension

- packages/apollo-server-core/src/ApolloServer.test.ts
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-express/src/ApolloServer.test.ts
Ensures that Apollo Server 2's context can be async
> Enable Apollo Server 2 to have async context + test

- docs/source/features/scalars-enums.md
The previous custom scalar section used to use import and should instead use requires, which is supported without a build step in node
@rgbkrk if you feel more documentation is necessary, please PR it in
Fixes #1145
> Docs: Convert import to requires

- docs/source/api/apollo-server.md
- docs/source/essentials/server.md
- docs/source/migration-two-dot.md
- packages/apollo-server-cloudflare/src/ApolloServer.ts
- packages/apollo-server-cloudflare/src/index.ts
- packages/apollo-server-core/src/ApolloServer.test.ts
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/types.ts
- packages/apollo-server-express/src/ApolloServer.test.ts
- packages/apollo-server-express/src/ApolloServer.ts
- packages/apollo-server-express/src/index.ts
- packages/apollo-server-hapi/README.md
- packages/apollo-server-hapi/src/ApolloServer.ts
- packages/apollo-server-hapi/src/hapiApollo.ts
- packages/apollo-server-hapi/src/index.ts
- packages/apollo-server/src/index.ts
This PR creates ApolloServer classes for the hapi, express, and cloudflare integrations. The constructor will continue to stay the same across all environments(ideally there would be a way to programmatically enforce this). The reasons to do this are the ApolloServer class in apollo-server brings the extra dependency on express, which does not work for serverless environments. The presumably more common path is going to be to use apollo-server-{variant}, so that should be equally as understandable/easy as the getting started experience. The arguments the context creation function will be set by the variant and be type safe, see #1110. The new typings should also solve #1140
The downside is that we won't be using the apollo-server package everywhere. I'm unconvinced this will be possible. …
> Integrations export their own ApolloServer

- .circleci/config.yml
- package.json
- packages/apollo-server-core/package.json
- packages/apollo-server-express/package.json
- packages/apollo-server-hapi/package.json
- packages/apollo-server-integration-testsuite/package.json
- packages/apollo-server-module-operation-store/package.json
- tsconfig.json
This readds support for Node 6, since there are still environments that require Node 6, such as GCF. It is also LTS until April 2019
Fixes #1167
> Resupport Node 6

- docs/source/whats-new.md
the url is incorrect: example.com//.well-known/apollo/server-health
TODO:
> remove extra '/' from docs

- docs/source/features/errors.md
Just fixed a missing 'new' operator at examples
> [DOCS] added missing 'new' keyword at error handling examples

- packages/apollo-datasource-rest/src/RESTDataSource.ts
- packages/apollo-datasource-rest/src/__tests__/RESTDataSource.test.ts
Hello,
I'm just begining to play a little bit with Apollo server 2.0, datasourceRest and typescript.
This PR include some little improvements:
- Use generics instead of `any` to permit to type the response easily
- Use the full type from `URLSearchParams` to be more precise about the possibilities of the API
- Add `PATCH` method
> Apollo server 2.0 - DatasourceREST - Improve types

- docs/source/migration-two-dot.md
- packages/apollo-datasource-rest/src/HTTPCache.ts
- packages/apollo-server-caching/src/InMemoryLRUCache.ts
- packages/apollo-server-core/src/index.ts
- packages/apollo-server-core/src/runHttpQuery.test.ts
- packages/apollo-server-core/src/runHttpQuery.ts
- packages/apollo-server-core/src/runQuery.test.ts
- packages/apollo-server-core/src/types.ts
- packages/apollo-server-express/src/ApolloServer.test.ts
- packages/apollo-server-express/src/ApolloServer.ts
- packages/apollo-server-express/src/apolloServerHttp.test.ts
- packages/apollo-server-express/src/connectApollo.test.ts
- packages/apollo-server-express/src/datasource.test.ts
- packages/apollo-server-express/src/expressApollo.test.ts
- packages/apollo-server-express/src/expressApollo.ts
- packages/apollo-server-hapi/src/ApolloServer.ts
- packages/apollo-server-hapi/src/hapiApollo.test.ts
- packages/apollo-server-hapi/src/hapiApollo.ts
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
- packages/apollo-server-integration-testsuite/src/index.ts
- packages/apollo-server-memcached/src/index.ts
- packages/apollo-server-redis/src/index.ts
- packages/apollo-server/src/index.test.ts
- packages/apollo-server/src/index.ts
- tsconfig.json
This removes exModuleInterop, which was breaking some builds with TS #1182 
Additionally adds in support for strings passed directly to gql and adds the documentation requested by #1194. For example: 
```js
const typeDefinitions = readFileSync(join(__dirname, "../../schema.graphql"), "utf8");
export default gql`
${typeDefinitions}
`;
//vs 
const typeDefinitions = gql(readFileSync(join(__dirname, "../../schema.graphql"), "utf8"));
// app file
const apolloServer = new ApolloServer({ typeDefs, resolvers });
```
> Typescript Improvements and esModuleInterop fix

- packages/apollo-server-express/src/ApolloServer.test.ts
- packages/apollo-server-hapi/src/ApolloServer.test.ts
- packages/apollo-server-hapi/src/ApolloServer.ts
- packages/apollo-server-hapi/src/hapiApollo.ts
This fixes the gui option in hapi, which dereferenced this, which was undefined, since we missed a bind call. 
Additionally, the extra express tests now use it's own `ApolloServer` class rather than the one from `apollo-server`
> Hapi: fix gui option, improve types, add tests

- packages/apollo-datasource-rest/src/RESTDataSource.ts
- packages/apollo-datasource-rest/src/__tests__/RESTDataSource.test.ts
- packages/apollo-server-core/package.json
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/errors.test.ts
- packages/apollo-server-core/src/index.ts
- packages/apollo-server-core/src/runHttpQuery.ts
- packages/apollo-server-core/src/runQuery.ts
- packages/apollo-server-errors/.npmignore
- packages/apollo-server-errors/package.json
- packages/apollo-server-errors/src/index.ts
- packages/apollo-server-errors/tsconfig.json
This PR introduces better error handling for data sources in Apollo Server 2.0.
Fetch methods will call the `didReceiveErrorResponse` lifecycle method on the datasource for non-success responses, which can either throw an error or return a response itself. That opens the door for custom fallbacks and retries.
```typescript
protected async didReceiveErrorResponse<TResult = any>(
response: Response,
): Promise<TResult>
```
The default implementation in `RESTDataSource` throws specific errors based on the status code.
- An `AuthenticationError` for a 401
- A `ForbiddenError` for a 403
- An `ApolloError` as a fallback
We may want to introduce a more specific error type for backend errors, like a `SERVICE_UNAVAILABLE`.
In order to get this working, I had to extract errors from core into their …
> Error handling for data sources

- packages/apollo-server-lambda/.npmignore
- packages/apollo-server-lambda/README.md
- packages/apollo-server-lambda/package.json
- packages/apollo-server-lambda/src/ApolloServer.ts
- packages/apollo-server-lambda/src/index.ts
- packages/apollo-server-lambda/src/lambdaApollo.test.ts
- packages/apollo-server-lambda/src/lambdaApollo.ts
- packages/apollo-server-lambda/tsconfig.json
- test/tests.js
AWS Lambda integration for Apollo Server 2
Demo: https://4z36935dne.execute-api.eu-west-1.amazonaws.com/production
> Apollo Server 2.0: AWS Lambda Integration

- CHANGELOG.md
- docs/source/features/scalars-enums.md
> Fix Typo resovers -> resolvers

- packages/apollo-server-cloudflare/package.json
- packages/apollo-server-express/package.json
- packages/apollo-server-hapi/package.json
- packages/apollo-server-lambda/package.json
> Add graphql dependency to server integrations

- packages/apollo-server-core/src/runHttpQuery.ts
- packages/apollo-server-integration-testsuite/src/index.ts
This updates the error handling for persisted queries during a batch with tests updated. Thanks @ralmo for bringing it up!
Fixes #1193
> AS2: Support APQ for Batches

- docs/source/whats-new.md
Hello! This just fixes a small typo in the whats new documentation (_hat_ => _that_).
> docs: fix typo in whats new documentation

- packages/apollo-server-errors/src/index.ts
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
- packages/apollo-server-integration-testsuite/src/index.ts
Fixes an issue brought up by @wKovacs64
> Ensures formatError gets a value that passes instanceof Error

- docs/source/deployment/lambda.md
- packages/apollo-server-lambda/README.md
Added `graphql` dependency in AWS Lambda docs.
> Apollo Server 2.0: AWS Lambda, graphql dependency in docs

- docs/source/features/data-sources.md
I updated the DataSource docs to use a constructor in the class to set the `baseURL` instead of using `baseURL = '...'`, since that's a proposed syntax, and only usable in TS or with build tooling.
TODO:
> [docs] fixed datasource examples

- docs/source/features/data-sources.md
Per request in #1242, I added a very simple example of all of the different methods to handle different forms of HTTP requests in the DataSource docs.
TODO:
> Added other HTTP methods to DataSource Docs

- docs/source/features/subscriptions.md
- packages/apollo-server-hapi/src/ApolloServer.ts
- packages/apollo-server/src/index.ts
Documents subscriptions, bumps hapi graphql playground version and improves subscriptions info for apollo-server.
Fixes #1248
> Improve Subscriptions Dev/Docs Experience

- docs/source/api/apollo-server.md
- docs/source/features/metrics.md
- docs/source/whats-new.md
Syncs the documentation with apollographql/engine-docs#196 and add the engine reporting api
> Engine Reporting API and pass Engine API key in constructor

- packages/apollo-server-core/src/index.ts
- packages/apollo-server-errors/package.json
- packages/apollo-server-express/package.json
- packages/apollo-server-express/src/index.ts
- packages/apollo-server-hapi/package.json
- packages/apollo-server-hapi/src/index.ts
- packages/apollo-server-integration-testsuite/package.json
- packages/apollo-server-lambda/package.json
- packages/apollo-server-lambda/src/index.ts
- packages/apollo-server/package.json
This fixes #1251 by adding the `graphql-tools` and `graphql-subscriptions` dependencies to integrations to allow `export * from 'graphql-tools'` and `export * from 'graphql-subscriptions'` from them. 
> **NOTE:** `graphql-subscriptions` was only added to and exported from those integrations that support subscriptions.
Also, we are not exporting everything from `graphql-tools` and `graphql-subscriptions` from the `apollo-server-core` package anymore (no consumer of it was using any of those exports). If there's any objection with this, I can revert that commit.
> Fix dependencies and exports

- docs/source/features/subscriptions.md
Pulls in the information from apollographql/subscriptions-transport-ws and address the feedback from #1255
> Further improves subscriptions docs

- docs/_config.yml
I Added a section on the sidebar with links to related guides.
I chose `Monitoring`, `Versioning`, `Access Control`, and `Security` as I thought those were the most relevant guides to server developers.
> [V2 Docs] Related Guides

- packages/apollo-server-errors/src/index.ts
- packages/apollo-server-integration-testsuite/package.json
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
In order to support errors thrown during GraphQL resolution that include nested errors, we need to keep the structure of the errors, rather than flattening them. The reason why the flattening code was present for `mergeSchemas` from `graphql-tools`, which returns a combinedError when ever an error is thrown from a remoteSchema.
> Removes flattening of Errors inside of formatApolloErrors

- __mocks__/apollo-server-env.ts
- packages/apollo-datasource-rest/src/RESTDataSource.ts
- packages/apollo-datasource-rest/src/__tests__/RESTDataSource.test.ts
This PR adds callbacks to `RESTDataSource` that allow for asynchronous and dynamic configuration of data sources. It addresses #1181 and #1238.
It allows a data source to specify `baseURL`, `defaults` and `defaultParams` either as simple properties, properties that return a `Promise`, or as a function that takes `RequestOptions` and returns either a value or a `Promise`.
So you could implement the example from https://github.com/apollographql/apollo-server/issues/1181#issuecomment-398871456 as follows:
```typescript
class FooAPI extends RESTDataSource {
baseURL = (options: RequestOptions) => {
return new Promise<string>((resolve, reject) => {
dns.resolveSrv(options.path.split("/")[1] + ".service.consul", (err, addresses) => {
err ? reject(err) : resolve("http://" + addresses[0].name + ":" …
```
> [2.0] Allow dynamic configuration of data sources

- packages/apollo-engine-reporting/README.md
- packages/apollo-server-caching/README.md
- packages/apollo-server-core/README.md
- packages/apollo-server-express/README.md
- packages/apollo-server-express/src/apolloServerHttp.test.ts
- packages/apollo-server-hapi/README.md
- packages/apollo-server-memcached/README.md
- packages/apollo-server-redis/README.md
- packages/apollo-server/README.md
- packages/graphql-extensions/README.md
- test/tests.js
fix some wrong links in readme.
> fix some badge links

- packages/apollo-server-micro/.npmignore
- packages/apollo-server-micro/README.md
- packages/apollo-server-micro/package.json
- packages/apollo-server-micro/src/ApolloServer.test.ts
- packages/apollo-server-micro/src/ApolloServer.ts
- packages/apollo-server-micro/src/index.ts
- packages/apollo-server-micro/src/microApollo.test.ts
- packages/apollo-server-micro/src/microApollo.ts
- packages/apollo-server-micro/src/types.ts
- packages/apollo-server-micro/tsconfig.json
- test/tests.js
Hi all - here's my pass at the Apollo Server 2 [Micro](https://github.com/zeit/micro) integration (sorry for the delay @evans! 😳). This integration should be pretty much feature complete, based on the functionality offered by `apollo-server-express`. A few comments:
- Since Micro is intended to be used to create focused microservices, the `ApolloServer.applyMiddleware` approach doesn't quite fit. Micro doesn't have middleware capabilities, so passing a Micro instance into `ApolloServer`, to make sure additional functionality is included during the request/response chain, won't work (well, we could make it work, but it would require a bit of questionable hacking). For this reason, instead of passing a Micro instance into `ApolloServer`, I'm building an `async` function in `ApolloServer` …
> Apollo Server 2 Micro integration

- packages/apollo-server-koa/.npmignore
- packages/apollo-server-koa/README.md
- packages/apollo-server-koa/package.json
- packages/apollo-server-koa/src/ApolloServer.test.ts
- packages/apollo-server-koa/src/ApolloServer.ts
- packages/apollo-server-koa/src/apolloServerHttp.test.ts
- packages/apollo-server-koa/src/datasource.test.ts
- packages/apollo-server-koa/src/index.ts
- packages/apollo-server-koa/src/koaApollo.test.ts
- packages/apollo-server-koa/src/koaApollo.ts
- packages/apollo-server-koa/tsconfig.json
- test/tests.js
Todo:
Implement it based on express one.
> Apollo Server 2 Koa integration

- docs/source/api/apollo-server.md
See https://github.com/apollographql/apollo-server/blob/version-2/packages/apollo-server-core/src/ApolloServer.ts#L177 
Upload is only added when not setting the schema manually.
> Hint about Upload scalar when setting schema manually

- docs/source/api/apollo-server.md
- packages/apollo-engine-reporting/src/agent.ts
- packages/apollo-server-lambda/README.md
- packages/apollo-server-lambda/package.json
- packages/apollo-server-lambda/src/ApolloServer.ts
- packages/apollo-server-lambda/src/lambdaApollo.ts
This PR adds the ability to report from a stateless environment by adding the option to disable the interval that the engine reporting agent uses.
Ideally there would be a way to determine when the lambda is spinning down and gracefully send a report, however a quick skim of the documentation does not illicit any nice hook. @adnsio if you have any advice, I'd love to hear your thoughts.
> Enable engine reporting in Lambda

- packages/apollo-datasource-rest/src/RESTDataSource.ts
Issue [#1324](https://github.com/apollographql/apollo-server/issues/1324)
TODO:
> Rest data source did recieve response

- docs/source/api/apollo-server.md
- packages/apollo-server-express/src/index.ts
- packages/apollo-server/src/index.test.ts
- packages/apollo-server/src/index.ts
This places a cors option inside of apollo-server's constructor. In order to get to create a production server, cors must be configurable. To get to production, we should not have to use an alternative integration, so while this removes the universal constructor, it's a necessary change.
Fixes #1326
> Expose Cors option from vanilla ApolloServer constructor

- packages/apollo-datasource-rest/src/RESTDataSource.ts
- packages/apollo-datasource-rest/src/__tests__/RESTDataSource.test.ts
Would love some feedback on this. Not sure if my solution is optimal as I'm not that familiar with this.
When using RESTDataSource while setting up apollo-server and learning GraphQL, I had trouble getting my POST requests to work. Looking through the sources, I saw that the fetch method in RESTDataSource was running JSON.stringify on my FormData, causing our backend server to reject them.
I don't think this should be by design? I saw that there was coded in an exception for ArrayBuffer, but to add FormData would perhaps require pulling in the `form-data` dependency, which isn't very practical. So I thought we might as well only serialize body values that are javascript objects. (`constructor === Object`) Does this make sense?
> Do not serialize body values that aren't objects (like FormData)

- packages/apollo-server-koa/package.json
- packages/apollo-server-koa/src/ApolloServer.ts
Use exported `bodyParser.Options` type instead of inferred type.
close #1213
> [apollo-server-koa] use exported bodyParser.Options type 

- docs/source/features/subscriptions.md
> Fixed a couple typos

- packages/apollo-server-core/src/caching.ts
- packages/apollo-server-core/src/graphqlOptions.ts
- packages/apollo-server-core/src/runHttpQuery.ts
The calculation of the headers from cacheControl currently mirrors the Engine Proxy. There does not need to be another way to configure the headers, since all major CDN vendors support `cache-control`. If you need access to this method, please open an issue and we'll discuss a way to expose it for your use case.
> Remove calculate headers as a function from cacheControl

- docs/source/api/apollo-server.md
- docs/source/features/metrics.md
- docs/source/migration-two-dot.md
- docs/source/setup.md
- packages/apollo-server-core/src/graphqlOptions.ts
- packages/apollo-server-core/src/runHttpQuery.ts
- packages/apollo-server-core/src/types.ts
This removes `formatParams`, because it is an internal implementation detail of the new Apollo Server as opposed to a first class functionality as in the middleware.  It was originally used to implement a form of persisted queries, which is now unnecessary.
In the future, we are planning to move to a more extensible request pathway inside of Apollo Server that should provide the functionality that was originally provided by `formatParams`. If you are dependent on the behavior of `formatParams`, please open an issue and we can continue discussions there. In the meantime, the release candidate(rc.7) provides a stop-gap measure.
> Apollo Server 2: Remove formatParams

- packages/apollo-server/src/index.ts
`applyMiddleware` is not a public api for `apollo-server`, so it should not be used an direct people to the apollo-server-express integration.
> Throw error in applyMiddleware for vanilla apollo-server

- docs/source/index.md
- docs/source/migration-one-dot.md
This updates all blog URLs in the documentation to use blog.apollographql.com
as the domain, rather than dev-blog.apollodata.com.
> docs: Update blog URLs to reference blog.apollographql.com.

- packages/apollo-datasource-rest/src/HTTPCache.ts
- packages/apollo-datasource-rest/src/types/http-cache-semantics/index.d.ts
- packages/apollo-server-core/src/runHttpQuery.ts
- packages/apollo-server-env/src/fetch.d.ts
In a response from httpCache, some props are missing (`url`, `ok` etc.)
https://github.com/apollographql/apollo-server/blob/version-2/packages/apollo-server-env/src/fetch.d.ts#L85-L90
While only `url` is cached:
https://github.com/kornelski/http-cache-semantics/blob/master/index.js#L67:14
I add it to the response.
TODO:
> fix: add url for cached response

- packages/apollo-server-cloudflare/src/index.ts
- packages/apollo-server-core/src/index.ts
- packages/apollo-server-core/src/playground.ts
- packages/apollo-server-express/src/index.ts
- packages/apollo-server-hapi/src/index.ts
- packages/apollo-server-koa/src/index.ts
- packages/apollo-server-lambda/src/ApolloServer.ts
- packages/apollo-server-lambda/src/index.ts
- packages/apollo-server-micro/src/index.ts
- packages/apollo-server/src/exports.ts
- packages/apollo-server/src/index.ts
> Fix and Export Extension and Playground Types 

- packages/apollo-datasource-rest/src/HTTPCache.ts
- packages/apollo-datasource-rest/src/RESTDataSource.ts
- packages/apollo-datasource-rest/src/__tests__/HTTPCache.test.ts
- packages/apollo-datasource-rest/src/__tests__/RESTDataSource.test.ts
- packages/apollo-datasource-rest/src/index.ts
- packages/apollo-datasource-rest/src/types/http-cache-semantics/index.d.ts
- packages/apollo-datasource/src/index.ts
- packages/apollo-server-core/src/runHttpQuery.ts
This PR enhances `RESTDataSource` with support for custom cache keys, overriding of TTLs, and request deduplication.
> [2.0] Data source enhancements

- packages/apollo-server-lambda/README.md
- packages/apollo-server-lambda/src/ApolloServer.ts
Fixes lambda's behavior with cors allowedHeaders to reflect the default in the express configuration. Now when a request come and requests access for specific headers apollo-server-lambda will mirror them if no allowedHeaders are specified directly.
> Lambda: fix cors documentation and default allowed headers

- packages/apollo-server-express/README.md
It is no longer necessary to use the `rc` dist-tag when installing the `apollo-server-express` integration.
> docs: Remove `@rc` dist-tag from `apollo-server-express` README.md.

- CHANGELOG.md
- packages/apollo-engine-reporting-protobuf/.circleci/config.yml
- packages/apollo-engine-reporting-protobuf/.envrc
- packages/apollo-engine-reporting-protobuf/.gitignore
- packages/apollo-engine-reporting-protobuf/.npmignore
- packages/apollo-engine-reporting-protobuf/README.md
- packages/apollo-engine-reporting-protobuf/package-lock.json
- packages/apollo-engine-reporting-protobuf/package.json
- packages/apollo-engine-reporting-protobuf/reports.proto
- packages/apollo-engine-reporting-protobuf/tsconfig.json
- packages/apollo-engine-reporting/README.md
Adds in apollo-engine-reporting-protobuf and changes apollo-engine-reporting to indicate the correct level of production readiness.
> Import engine reporting protobuf and fix reporting readme

- CHANGELOG.md
- packages/apollo-server-express/src/ApolloServer.ts
- packages/apollo-server-koa/src/ApolloServer.ts
> express, koa: don't continue past playground render

- CHANGELOG.md
Hello,
This just fixes a typo (`fromatParams` -> `formatParams`) in CHANGELOG.md
> docs: fix typo in CHANGELOG

- docs/source/features/data-sources.md
It is no longer necessary to use the `rc` tag when installing `apollo-datasource-rest`, so this `dist-tag` should be removed! As of this writing, the npm `latest` tag is now 0.1.1.
> docs: Remove `rc` dist-tag designation from `apollo-datasource-rest` instruction.

- CHANGELOG.md
- packages/apollo-server-lambda/src/ApolloServer.ts
See here: https://docs.aws.amazon.com/lambda/latest/dg/eventsources.html#eventsources-api-gateway-request
TODO:
> Look in event.path first when selecting endpoint for GraphQL Playground on Lambda, and check for null

- package-lock.json
- packages/apollo-server-core/package.json
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/index.ts
- packages/apollo-server-core/src/types/apollo-upload-server.d.ts
- packages/apollo-server-express/package.json
- packages/apollo-server-express/src/ApolloServer.ts
- packages/apollo-server-hapi/package.json
- packages/apollo-server-hapi/src/ApolloServer.ts
- packages/apollo-server-koa/package.json
- packages/apollo-server-koa/src/ApolloServer.ts
- packages/apollo-server-micro/package.json
- packages/apollo-server-micro/src/ApolloServer.ts
As reported in https://github.com/apollographql/apollo-server/issues/1542, the `apollo-upload-server` package (v5.0.0, which `apollo-server` relies on) is no longer able to provide a `core-js` package because of change that was outside of its control in a Babel release.
The problem is resolved in newer versions of `apollo-upload-server`, however, regrettably, the newer versions of that package (notably, v6 and v7) drop support for Node.js 6 — one of two versions of Node.js that are currently under the terms of the Node.js Foundation's Long-Term-Support (LTS) agreements.
Since Apollo Server aims to support versions of Node.js which are under LTS (and will drop support for Node.js 6 in April 2019, per Node.js' schedule) the current, immediate solution is to fork the `apollo-upload-server` …
> Switch to a fork of `apollo-upload-server` to fix missing `core-js` dependency.

- packages/apollo-server-cloud-function/package.json
- packages/apollo-server-cloud-function/src/ApolloServer.ts
- packages/apollo-server-cloud-function/src/googleCloudApollo.test.ts
- packages/apollo-server-cloud-function/src/googleCloudApollo.ts
I was working on a separate feature and the build was failing locally with several implicit `any` type warnings from the merge of #1446, so I decided to fix them.
Google cloud functions appears to use express internally, so I used those type definitions to type the `req` / `res` params.
I didn't look to see why this would have originally passed CI without any issues.
> Fix implicit any types in apollo-server-cloud-function

- packages/apollo-server-cloudflare/src/index.ts
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/types/apollo-upload-server.d.ts
- packages/apollo-server-env/package.json
- packages/apollo-server-env/src/index.browser.js
This PR removes some Node dependencies to allow Apollo Server to run in edge environments like Cloudflare Workers and fly.io.
Because `apollo-upload-server` requires Node, we only import it when uploads are enabled and don't export `GraphQLUpload` from the `apollo-server-cloudflare` package. We currently configure bundling for edge to skip `apollo-upload-server`, but we should find a more principled way to avoid the dependency.
> [2.0] Remove Node dependencies for edge environments

- CHANGELOG.md
- docs/source/best-practices/authentication.md
This PR adds a link to the `this example` link that was missing a URL.
TODO:
> Fix example link

- CHANGELOG.md
- docs/source/api/apollo-server.md
- packages/apollo-engine-reporting/src/agent.ts
- packages/apollo-engine-reporting/src/extension.ts
- packages/apollo-server-core/src/runHttpQuery.ts
- packages/apollo-server-core/src/runQuery.ts
- packages/graphql-extensions/src/index.ts
Adds the createClientInfo to apollo-engine-reporting, which enables the
differentiation of clients based on the request, operation, and
variables. This could be extended to include the response. However for
the first release. It doesn't quite make sense.
TODO:
> Provide ability to specify client info in traces

- CHANGELOG.md
- package-lock.json
- packages/apollo-engine-reporting/src/extension.ts
When using the `privateHeaders` option in the constructor, not all expected headers were being reported to Engine.
This was caused because the loop iterating over the headers had a `break` where it should have had a `continue`, causing the loop to be cut short.
Note: This bug didn't cause any private headers to get reported, so no worries there 😄
TODO:
> Fix header misreporting to engine

- docs/source/features/directives.md
The schema directive example [here](https://www.apollographql.com/docs/apollo-server/v2/features/directives.html) doesn't work. The package being imported was meant to be an _example_, unworking directive. This is confusing for people trying to run this example, so I replaced it with a real one.
TODO:
> [DOCS] Make schema directive example clearer

- package-lock.json
- package.json
- packages/apollo-server-cloud-function/package.json
- packages/apollo-server-core/package.json
- packages/apollo-server-express/package.json
- packages/apollo-server-hapi/package.json
- packages/apollo-server-koa/package.json
- packages/apollo-server-lambda/package.json
- packages/apollo-server/package.json
I'm reverting apollographql/apollo-server#1698 not because it's been problematic in any way, but because I'd like to give it a bit more thought and don't want this to accidentally get cut into a release prior to that consideration.
More specifically: The `graphql-tools` update on its own shouldn't really cause any problems, but the [4.x version of `graphql-tools`](https://github.com/apollographql/graphql-tools/releases/tag/4.0.0) is intended to support and enable the latest `graphql@14` which contains [breaking changes](https://github.com/graphql/graphql-js/releases/tag/v14.0.0).
I believe most of those breaking changes would be show-stoppers and the failures would surface immediately (meaning that servers would completely fail to start, rather than being a surprise in other, more delayed …
> Revert #1698 renovate/graphql tools 4.x

- CHANGELOG.md
Since we’ve moved to independent versioning the statement about every package within this repository being at the same version is no longer true.  While we’ll need to improve our `CHANGELOG.md` story a bit to account for this, it’s best that we remove this statement to avoid confusing library consumers.
> Remove CHANGELOG.md note regarding versioning.

- docs/source/migration-two-dot.md
The file included in the documentation caused the following error:
```js
const gql = String.raw;
^
SyntaxError: Identifier 'gql' has already been declared
```
TODO:
> Docs: fix the example for "Using an Existing Schema"

- docs/source/features/errors.md
> More nuanced handling of stack traces in errors

- docs/source/essentials/schema.md
Fix grammar, and hopefully make the explanation a bit clearer.
It could also be said like this (for a smaller diff) ;-)
"By allowing the consumer of the API to see the full possibilities that an API can *deliver*, developers can"...
> Suggestion: change wording

- packages/apollo-server-cloud-function/src/ApolloServer.ts
- packages/apollo-server-cloud-function/src/googleCloudApollo.ts
- packages/apollo-server-cloudflare/src/ApolloServer.ts
- packages/apollo-server-express/src/ApolloServer.ts
- packages/apollo-server-hapi/src/ApolloServer.ts
- packages/apollo-server-integration-testsuite/src/index.ts
- packages/apollo-server-koa/src/ApolloServer.ts
- packages/apollo-server-lambda/src/ApolloServer.ts
- packages/apollo-server-micro/src/ApolloServer.ts
This commit follows-up on #1795, which introduced the new request pipeline, and implements the triggers for its new life-cycle hooks within the various integration packages.  Previously, the only implementation was within the `apollo-server` package and didn't get triggered for those invoking the `applyMiddleware` method on integrations (e.g. `apollo-server-express`, `...-hapi` and `...-koa`).
While in an ideal world, ALL existing `applyMiddleware` functions would be marked as `async` functions and allow us to `await ApolloServer#willStart`, in practice the only `applyMiddleware` which is currently `async` is the one within the Hapi implementation.  Therefore, we'll instead kick off the `willStart` lifecycle hook as soon as `applyMiddleware` is started, return as quickly as we have before …
>  Triggers and tests for `serverWillStart` lifecycle hook.

- CHANGELOG.md
- package-lock.json
- packages/apollo-server-cloud-function/package.json
- packages/apollo-server-core/src/playground.ts
- packages/apollo-server-express/package.json
- packages/apollo-server-hapi/package.json
- packages/apollo-server-koa/package.json
- packages/apollo-server-lambda/package.json
- packages/apollo-server-micro/package.json
In addition to updating the `@apollographql/graphql-playground-html` fork,
which is necessary to avoid bundling `graphql-config` which had been
problematic in serverless environments, this updates the version number
which is served from the CDN.
I've just published `@apollographql/graphql-playground-html@1.6.4`.
Closes: https://github.com/apollographql/apollo-server/issues/1746
Ref: https://github.com/apollographql/graphql-playground/pull/2
Ref: https://github.com/apollographql/graphql-playground/pull/1
Thanks for @javlund for kicking off some of this work!
> Update to GraphQL Playground latest.

- CHANGELOG.md
- docs/source/api/apollo-server.md
- packages/apollo-engine-reporting/src/agent.ts
- packages/apollo-server-env/src/fetch.d.ts
- packages/apollo-server-env/src/global.d.ts
This PR fixes #1836.
This PR enables developers to inject the http agent to be used on the network requests to apollo engine endpoint.
TODO:
> feature(apollo-engine-reporting): Add custom http agent support

- docs/source/images/index-get-started.svg
the image is used in this page
https://www.apollographql.com/docs/apollo-server/
> centralized “Get Started” Image in the doc

- packages/apollo-server-cloud-function/src/googleCloudApollo.ts
- packages/apollo-server-cloudflare/src/ApolloServer.ts
- packages/apollo-server-cloudflare/src/cloudflareApollo.ts
- packages/apollo-server-core/src/graphqlOptions.ts
- packages/apollo-server-core/src/runHttpQuery.ts
- packages/apollo-server-core/src/types.ts
- packages/apollo-server-express/src/ApolloServer.ts
- packages/apollo-server-express/src/expressApollo.ts
- packages/apollo-server-hapi/src/hapiApollo.ts
- packages/apollo-server-koa/src/ApolloServer.ts
- packages/apollo-server-koa/src/koaApollo.ts
- packages/apollo-server-lambda/src/lambdaApollo.ts
- packages/apollo-server-micro/src/ApolloServer.ts
- packages/apollo-server-micro/src/microApollo.ts
- packages/apollo-server-plugin-base/src/index.ts
This mostly reverts fd34771 along with a number of slight adjustments to avoid other typing luxuries which were introduced with TypeScript 3.x, as they resulted in test failures in our own internal smoke testing.
While the generic `ServerOptionFunction` types and `HandlerArguments` generic rest argument type were certainly welcome additions to the codebase, they present a backwards compatibility problem for consumers of Apollo Server 2.x who have not yet updated their own projects to use TypeScript 3.x since attempting to use the definition files which were generated from these types would result in typescript compilation failures from `tsc@2.x`.
Therefore, we'll roll these back, since these were _intended_ to land in a minor release of Apollo Server.  With any luck, when we eventually …
> Preserve TypeScript 2 Backwards compatibility until Semver Major

- docs/source/api/apollo-server.md
- docs/source/features/metrics.md
Provides information on how to enable client awareness in Apollo Server. 
May end up having some overlap with: https://github.com/apollographql/apollo/pull/226, though I'm happy with the overlap for now, since the docs are still evolving.
> Add client awareness reference api and some docs

- packages/apollo-server-core/src/utils/schemaHash.ts
We expect introspection queries to behave in an synchronous manner since
they do not have any resolvers which return Promises.  This expectation
seems to also be had by `graphql-js` which utilizes `graphqlSync`, rather
than `graphql` for execution of introspection queries.  In fact, this may be
one of the entire reasons that `graphqlSync` exists: to fulfill a contract
for synchronous execution of server introspection.  The introspection tests
within `graphql-js` seem to support this theory[[0]].
Utilities which wrap GraphQL resolvers should take care to maintain the
execution dynamics of what they are wrapping, or they should avoid wrapping
introspection types entirely by checking the type with the
`isIntrospectionType` predicate function from `graphql/type`[[1]].
[0]: …
> Throw an error on asynchronous introspection query behavior.

- renovate.json
This updates the `renovate.json` to remove a version pinning of `lint-staged` which clearly didn't work since the current version of `lint-staged` is newer than `v7`.
> Update Renovate Configuration: Remove ineffective limitation.

- renovate.json
This updates `renovate.json` to use a shared, base configuration rather than repeating the same defaults across multiple repositories.
That base configuration lives at https://github.com/apollographql/renovate-config-apollo-open-source and is published to npm as `renovate-config-apollo-open-source` (https://npm.im/renovate-config-apollo-open-source).  It is referenced here by its short name `apollo-open-source`.
For more information on sharable Renovate config presets, see https://renovatebot.com/docs/config-presets/.
> Update Renovate Configuration: Use shared base configuration.

- docs/source/features/subscriptions.md
for the context it needs to return a connection.context and not a {}.
TODO:
> Example code snippet does not work

- docs/source/api/graphql-tools.md
- docs/source/essentials/data.md
- docs/source/features/authentication.md
- docs/source/features/directives.md
- docs/source/features/mocking.md
- docs/source/features/scalars-enums.md
- docs/source/why-apollo-server.md
- packages/apollo-server-core/src/__tests__/runQuery.test.ts
- packages/apollo-server-integration-testsuite/src/index.ts
- packages/apollo-server-micro/README.md
In an effort to maintain consistency and semantically correct meaning,
this changes (only in documentation and internal Apollo Server tests) the
name of the first argument in resolver signatures to use `parent` rather
than `root`.
While `root` certainly makes sense when the resolver is belonging to the
root `Query` or `Mutation` type, once nested field resolvers begin getting
called, the more semantically correct term would seem to be `parent`.
Since `parent` still makes sense at the root level, and since resolvers
frequently get copied and pasted into more deeply-nested positions, putting
this pattern in place for apps which are just beginning might just help
someone more clearly understand the relationship in the future — without
incorrectly thinking that a nested resolver is accessing …
> Consistently use `parent`, rather than `root`, as first resolver argument.

- packages/apollo-server-caching/src/InMemoryLRUCache.ts
This is mandated by [`lru-cache`](https://npm.im/lru-cache) v5 and surfaced in [the CircleCI failures](https://circleci.com/gh/apollographql/apollo-server/22537) on #2004 (which updates the `lru-cache` dependency):
```
TypeError: Class constructor LRUCache cannot be invoked without 'new'
```
Luckily, this is a private implementation detail of Apollo Server's `InMemoryLRUCache` so no additional changes should be necessary and we should be able to update to `lru-cache` 5.0.0 in a semver minor respectful way.
> Instantiate `lru-cache` class using `new` in `InMemoryLRUCache`.

- CHANGELOG.md
- package-lock.json
- packages/apollo-server-azure-functions/package.json
- packages/apollo-server-cloud-functions/package.json
- packages/apollo-server-core/package.json
- packages/apollo-server-express/package.json
- packages/apollo-server-hapi/package.json
- packages/apollo-server-koa/package.json
- packages/apollo-server-lambda/package.json
- packages/apollo-server-micro/package.json
With any luck, we will no longer necessitate our fork which removed the
`graphql-config` dependency thanks to the work done in:
https://github.com/prisma/graphql-playground/pull/874
:tada:
Most notably though, this fixes a documentation scrolling problem with
Safari.
> Update `@apollographql/graphql-playground-html` to latest version.

- CHANGELOG.md
- packages/apollo-server-micro/README.md
[ApolloServer v2 does not support `OPTION` request](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/runHttpQuery.ts#L185-L213). Updated the micro example to reflect this.
TODO:
> Remove invalid HTTP method from apollo-server-micro example

- packages/apollo-server-core/src/__tests__/runQuery.test.ts
This test harness is intended to be relatively temporary, but it seems
fruitful to start picking from where these types are already defined rather
than re-implementing them in multiple places.
This change came up in a larger feature implementation and should otherwise be
a no-op but was worth surfacing as its own commit in case that feature never
lands.
> chore: DRY-up `runQuery` test interface via Pick'd `GraphQLOptions`.

- packages/apollo-server-core/src/requestPipeline.ts
These are a few low-hanging fruit commits in a never-ending pursuit to streamline the request pipeline.
These should be effective no-ops, but are more relevant given another PR which I'm in the process of staging.  Whether or not that PR lands, I think these should still be drops in the _improvements_ bucket. 🥝📈
> chores: Request pipeline readability/DRYing.

- packages/apollo-server-cache-memcached/src/__tests__/Memcached.test.ts
- packages/apollo-server-cache-memcached/src/index.ts
- packages/apollo-server-cache-redis/src/__tests__/Redis.test.ts
- packages/apollo-server-cache-redis/src/index.ts
- packages/apollo-server-caching/README.md
- packages/apollo-server-caching/src/InMemoryLRUCache.ts
- packages/apollo-server-caching/src/KeyValueCache.ts
- packages/apollo-server-caching/src/__tests__/InMemoryLRUCache.test.ts
- packages/apollo-server-caching/src/__tests__/testsuite.ts
This PR contains a number of commits which make the existing `InMemoryLRUCache` more whole.  The `InMemoryLRUCache` — which crutches almost entirely on the excellent [`lru-cache`](https://npm.im/lru-cache) library — is the currently the default cache store which is used for [REST Data Sources](https://www.apollographql.com/docs/apollo-server/features/data-sources.html) (i.e. `RESTDataSource`) and persisted queries — though both of those can be provided more complex cache stores (e.g. distributed cache stores such as Redis/Memcached).
In many cases though, the `InMemoryLRUCache` is an arguably less complex, yet still powerful, piece of machinery which can still be used to increase the performance of Apollo Server and seems deserving of a more consistent interface with the distributed …
> Improve InMemoryLRUCache implementation.

- packages/apollo-cache-control/src/__tests__/cacheControlExtension.test.ts
- packages/apollo-cache-control/src/index.ts
Fixes apollographql/apollo-cache-control#11
TODO:
> Fix cache policy calculation

- CHANGELOG.md
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/index.ts
- packages/apollo-server-core/src/processFileUploads.ts
- packages/apollo-server-core/src/utils/runtimeSupportsUploads.ts
- packages/apollo-server-core/src/utils/supportsUploadsInNode.ts
I'm working on a `apollo-server-flyio` package to use in fly.io apps. The fly app environment is not node, it's much closer to the browser, which means no access to `fs`, which means `graphql-upload` blows up on require. 
This PR makes the Node version check more strict — if there are no node process details it avoids requiring the `graphql-upload` package for non-node runtimes. This is useful for me, obviously, but should also improve the Cloud Flare worker build experience and help with any future Deno efforts.
TODO:
> More strict check for node version for `graphql-upload`

- CHANGELOG.md
- packages/apollo-server/src/index.ts
When the request pipeline was initially introduced, the integrations had yet to be updated to call the new life-cycle events.  Now, the integrations have all caught up, but `apollo-server` is still calling `willStart`, despite the fact that its dependency which provides the actual server implementation — `apollo-server-express` – is _also_ calling it, resulting in double invocation of this event.
I suspect some follow-up work should guard against this possibility, but for
now this should remove the duplication.
> Remove `willStart` from `apollo-server`, already called via `…-express`.

- docs/source/features/scalars-enums.md
This is just a quick fix for a typo that threw me for a loop when testing out this example.
> Fix a typo in the "Custom `GraphQLScalarType` instance" example

- package-lock.json
- package.json
- renovate.json
Reverts apollographql/apollo-server#2283
This was causing the following error on the `master` branch after #2283 was merged — even though the original PR passed.  It seems to repeatedly bisect back to this commit but I haven't looked into it further.  Leaving `master` in an unusable state for the weekend didn't seem ideal.
This also disables Renovate `automerge` which, while nice in theory, would probably just put this back in place.
> Revert "chore(deps): update dependency @types/aws-lambda to v8.10.19"

- packages/apollo-server-core/package.json
The only usage of lodash was removed by @martijnwalraven in commit a09d514e596b297f6a62acbbff653bd33fb1028c.
> Remove unused lodash dependency from apollo-server-core.

- packages/apollo-server-core/src/ApolloServer.ts
When `getEngineServiceId` does not return a truthy value, we can save memory and startup time by avoiding importing `apollo-engine-reporting`, which (among its other dependencies) imports the `protobuf.js` implementation.
> Require apollo-engine-reporting only if EngineReportingAgent used.

- CHANGELOG.md
- packages/apollo-server-core/src/requestPipeline.ts
`extensionStack`'s executionDidEnd handler (the callback function returned from `executionDidStart`) was being called before `graphql.execute` finishes running
This PR adds an `await` before the return so code in `finally` runs after `graphql.execute` finishes 
TODO:
> Await on graphql.execute() before calling executionDidEnd handler (AS-59)

- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
Follow up to https://github.com/apollographql/apollo-server/pull/2298
This compares a trace's top-level duration (total duration) to ensure that it's longer than the duration from when its resolver first started to when when its resolvers last ends
> Add test to ensure "total duration" > "duration of resolvers" - AS-59

- packages/apollo-server-azure-functions/jest.config.js
- packages/apollo-server-azure-functions/src/__tests__/tsconfig.json
These missing configurations, which weren't identified in the original implementation of `apollo-server-azure-functions` in #1926, are responsible for the failures which have surfaced in the #2228, which updates Jest to v24.x.
Un-blocks #2228.
> azure-functions: Add missing test configuration files.

- CHANGELOG.md
- packages/apollo-server-core/src/types.ts
- packages/apollo-server-express/src/ApolloServer.ts
- packages/apollo-server-express/src/index.ts
- packages/apollo-server/src/index.ts
This was an issue brought up in https://github.com/apollographql/apollo-server/issues/1593
This PR should provide more accurate typing information for apollo-server and apollo-server-express
- `ContextFunction` can return a new context object synchronously
- `context` for apollo-server and apollo-server-express will contain `req` and `res` 
TODO:
> Provide more accurate types for apollo-server-expresse's ContextFunction

- renovate.json
While there are newer types available for newer Node.js APIs, the `8.x` range still gets most of the important updates via back-ports on the `DefinitelyTyped` repository.  I believe it'll be safer to limit the types to the version which we intend on developing for most directly, which is Node.js 8.  Node.js 10 has newer APIs but until we can drop Node.js 8 support (which is not at all anytime soon), we should try to stick to the `8.x` API types.
We will drop Node.js 6 support in the next major version of Apollo Server since it will end it's "Long-Term Support" coverage [in April 2019](https://github.com/nodejs/LTS/).
Hopefully this will auto-close #2302. 😉
> Keep `@types/node` types at v8.

- README.md
- packages/apollo-server-cloud-functions/README.md
- packages/apollo-server-express/README.md
- packages/apollo-server-fastify/README.md
- packages/apollo-server-hapi/README.md
- packages/apollo-server-koa/README.md
- packages/apollo-server-lambda/README.md
- packages/apollo-server-micro/README.md
As we're moving the community from Slack to Spectrum, its time to update these shields from our project README files (which show on npm and in GitHub) to reflect the new home for conversation.
If you haven't already joined the new Apollo community on Spectrum.chat, visit [spectrum.chat/apollo](https://spectrum.chat/apollo/) to join the discussion!
For more details on the move, checkout the Apollo blog post by @hwillson:
https://blog.apollographql.com/goodbye-slack-hello-spectrum-8fa6b979645b
[![Join the community on Spectrum](https://withspectrum.github.io/badge/badge.svg)](https://spectrum.chat/apollo)
> Replace Slack shields in project `README.md`s with Spectrum shields.

- CHANGELOG.md
- packages/apollo-server-core/src/formatters.ts
- packages/apollo-server-core/src/graphqlOptions.ts
- packages/apollo-server-core/src/requestPipeline.ts
- packages/apollo-server-errors/src/index.ts
Related to https://github.com/apollographql/apollo-server/issues/2294
This updates the typings for formatError to specify that it accepts an GraphQLError as an argument, and expects a GraphQLFormattedError to be returned
TODO:
> Add more accurate typings to formatError

- CHANGELOG.md
- packages/apollo-server-core/src/types.ts
- packages/apollo-server-express/src/ApolloServer.ts
- packages/apollo-server/src/__tests__/index.test.ts
Inspired by https://github.com/apollographql/apollo-server/pull/2346 , this PR fixes the problem introduced by https://github.com/apollographql/apollo-server/pull/2330 and should be solve the problem brought up in https://github.com/apollographql/apollo-server/issues/1593
The two significant changes are
- Type parameters for context function are now separate from the context it produces https://github.com/apollographql/apollo-server/blob/d08569ef9aaeb8a05aa15fe8438253fde182959d/packages/apollo-server-core/src/types.ts#L33-L35 (so apollo-server-express can say the context function will receive `req` and, but the resulting context doesn't need to contain (or only contain) `req`)
- The type parameter for the Context object is updated from `any` to `object` …
> Type parameters for context function separately from the context it produces

- CHANGELOG.md
- packages/apollo-server-express/src/ApolloServer.ts
- packages/apollo-server-express/src/__tests__/ApolloServer.test.ts
- packages/apollo-server-express/src/__tests__/connectApollo.test.ts
- packages/apollo-server-express/src/__tests__/expressApollo.test.ts
Original: #2349
Kept some tiny stuff that has very little value now, but anyway 🤷‍♂️ 
---
TODO:
> Express context

- packages/apollo-server-core/src/utils/createSHA.ts
- packages/apollo-server-core/src/utils/isNode.ts
- packages/apollo-server-core/src/utils/isNodeLike.ts
- packages/apollo-server-core/src/utils/runtimeSupportsUploads.ts
Previously, in order to only load dependencies which only work on Node.js and fail in non-Node.js environments, we introduced a check which did a string-comparison of `process.release.name` to see if it is was `node`.
This was first introduced in 9c563fae5048f5e77ca2716e3aa3d47044861abf as part of #2054, but has gone on to be useful for other purposes as well.
Some Node.js forks such as NodeSource's N|Solid, which is a fork of Node.js which follows-up each Node.js release with a custom build that includes additional native addons but is otherwise the same, override this value with their own name.  This means that N|Source returns `nsolid`, despite the fact
that it is almost entirely the same as Node.js.
Luckily, N|Solid leaves the base version of its Node.js in `process.versions.node` …
> Allow Node.js-like runtimes to identify as Node.js as well.

- docs/source/schemas/types.md
As easy as that :)
(unless Apollo doc is using 1000 years old English where "alway" is correct...)
> Schema types doc: fix a typo

- CHANGELOG.md
- packages/apollo-server-express/src/ApolloServer.ts
- packages/apollo-server/src/index.ts
Fixes problem brought up in https://github.com/apollographql/apollo-server/pull/2330#discussion_r259773834 - cors options can only be applied to the standalone apollo-server's constructor, for apollo-server-express, their constructor can't contain cors settings, the option is only read from `applyMiddleware`
TODO:
> Fix: Remove incorrect cors option type from apollo-server-express's constructor

- docs/source/essentials/server.md
Small documentation fix - coming across the phrase "encrypted WSS socket" and it's a bit odd when you're mentally expanding it to: "encrypted web socket secure socket"
> Small documentation update 

- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
- packages/apollo-server/src/__tests__/index.test.ts
Follow up to https://github.com/apollographql/apollo-server/pull/2350/files
This PR only affects tests, and only with organization of tests. No logic inside tests have been changed
- Tests added in https://github.com/apollographql/apollo-server/pull/2350/files have been copied to integration testsuite
- Tests relating to context that are already in the testsuite have been moved inside `describe('context field')`
The reason that the old tests weren't removed is that their main function is to trigger type errors if our provided typing doesn't match what is expected. The integration test suite's `createApolloServer` function uses the `ApolloServerBase` typing, which is still useful to test, but we do still want to test the typing from the `ApolloServer` constructor as well
> Move tests for context types from apollo-server into integration testsuite

- packages/apollo-datasource-rest/src/RESTDataSource.ts
- packages/apollo-server-env/src/index.d.ts
- packages/apollo-server-env/src/typescript-utility-types.d.ts
- packages/apollo-server-plugin-base/src/index.ts
We do the same in `apollo-env`, which this package will likely be merged with when we drop Node 6 support.
> Extract TypeScript utility types to `apollo-server-env`

- packages/apollo-server-azure-functions/src/azureFunctionApollo.ts
- packages/apollo-server-azure-functions/src/azureFunctions.ts
- packages/apollo-server-cloud-functions/src/googleCloudApollo.ts
- packages/apollo-server-cloudflare/src/cloudflareApollo.ts
- packages/apollo-server-core/src/graphqlOptions.ts
- packages/apollo-server-core/src/requestPipeline.ts
- packages/apollo-server-core/src/runHttpQuery.ts
- packages/apollo-server-core/src/types.ts
- packages/apollo-server-express/src/expressApollo.ts
- packages/apollo-server-fastify/src/fastifyApollo.ts
- packages/apollo-server-hapi/src/hapiApollo.ts
- packages/apollo-server-integration-testsuite/src/index.ts
- packages/apollo-server-koa/src/koaApollo.ts
- packages/apollo-server-lambda/src/lambdaApollo.ts
- packages/apollo-server-micro/src/microApollo.ts
- packages/apollo-server-plugin-base/src/index.ts
Now that the `ValueOrPromise` and `WithRequired` types are more ubiquitously available after @martijnwalraven's #2415 which brought them to `apollo-server-env`, we can change the existing cases where we've used these patterns or depended on them from less-than-ideal modules (like `apollo-server-plugin-base`).
> Propagate new `ValueOrPromise`/`WithRequired` types from `apollo-server-env`.

- packages/apollo-datasource-rest/src/HTTPCache.ts
- packages/apollo-server-cache-memcached/src/index.ts
- packages/apollo-server-cache-redis/src/index.ts
- packages/apollo-server-caching/src/InMemoryLRUCache.ts
- packages/apollo-server-caching/src/KeyValueCache.ts
- packages/apollo-server-caching/src/PrefixingKeyValueCache.ts
- packages/apollo-server-caching/src/__tests__/PrefixingKeyValueCache.test.ts
- packages/apollo-server-caching/src/__tests__/testsuite.ts
- packages/apollo-server-caching/src/index.ts
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/requestPipeline.ts
apollo-server's caching uses the pattern of sharing a single KeyValueCache
object across multiple "features", using a prefix to ensure that the features'
data doesn't conflict. This change makes this pattern explicit rather than
implicit by introducing a PrefixingKeyValueCache class which handles the
prefixing for you.
In addition, it pulls the dangerous reset() operation out of KeyValueCache and
doesn't implement it in PrefixingKeyValueCache. Because reset is typically
implemented by sending a cache server a "drop all data" operation, and servers
may not implement "drop all data with a given prefix", we would not want actual
production code for a particular apollo-server cache-related feature to ever
call reset(). This PR moves that method (and close()) to a TestableKeyValueCache …
> apollo-caching: add PrefixingKeyValueCache, TestableKeyValueCache

- packages/apollo-server-azure-functions/src/__tests__/azureFunctionApollo.test.ts
- packages/apollo-server-fastify/src/__tests__/ApolloServer.test.ts
- apollo-server-azure-functions: a test was failing (expectedResult needed to
have {data:} and be converted to string) but it was happening in an unhandled
promise. Restructure test to fail, then fix the test.
- apollo-server-fastify: after the upgrade in #2418, Jest started warning that
async describe blocks were bad. Fix that.
> Make some tests run properly

- CHANGELOG.md
- docs/_config.yml
- docs/package-lock.json
- docs/source/api/apollo-server.md
- docs/source/features/caching.md
- docs/source/whats-new.md
- package-lock.json
- package.json
- packages/apollo-cache-control/src/__tests__/collectCacheControlHints.ts
- packages/apollo-cache-control/src/index.ts
- packages/apollo-engine-reporting/src/extension.ts
- packages/apollo-server-caching/src/KeyValueCache.ts
- packages/apollo-server-core/src/requestPipeline.ts
- packages/apollo-server-core/src/requestPipelineAPI.ts
- packages/apollo-server-core/src/utils/dispatcher.ts
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
- packages/apollo-server-plugin-base/src/index.ts
- packages/apollo-server-plugin-response-cache/.npmignore
- packages/apollo-server-plugin-response-cache/CHANGELOG.md
- packages/apollo-server-plugin-response-cache/README.md
- packages/apollo-server-plugin-response-cache/jest.config.js
- packages/apollo-server-plugin-response-cache/package.json
- packages/apollo-server-plugin-response-cache/src/ApolloServerPluginResponseCache.ts
- packages/apollo-server-plugin-response-cache/src/__tests__/ApolloServerPluginResponseCache.test.ts
- packages/apollo-server-plugin-response-cache/src/__tests__/tsconfig.json
- packages/apollo-server-plugin-response-cache/src/index.ts
- packages/apollo-server-plugin-response-cache/tsconfig.json
- packages/graphql-extensions/src/index.ts
- tsconfig.build.json
- tsconfig.test.json
Implements a full query cache for Apollo Server in the new package `apollo-server-plugin-response-cache`. This has similar functionality to the caching feature of the deprecated Engine proxy.
Supporting this required:
- GraphQLRequestContext new fields:
- overallCachePolicy
- documentText
- metrics
- New plugin hook responseForOperation.
- new GraphQLExtension hook didResolveOperation, identical to the same hook in
the Plugin API.  Change apollo-engine-reporting to use this hook instead of
executionDidStart, because executionDidStart doesn't run if the cache
short-circuits execution.
- apollo-engine-reporting: report whether the request was a cache hit. Also use
the new requestContext.metrics object to report persisted query hit/register
instead of specific extension options (though those …
> Full query response cache plugin

- docs/source/features/graphql-playground.md
This branch fixes a broken image in the GraphQL Playground page. Here's what it looks like:
Due to the way that our multi-version docs theme works, this change will be made live in prod when a new version of `apollo-server` is made and the tag is pushed to master.
> Fix playground image

- packages/apollo-engine-reporting/src/agent.ts
While running my app in a new machine missing all sorts of credentials to different providers, I couldn't differentiate Apollo Engine's errors from the others.
This PR won't let others wonder what kind of "engine" they are messing with.
> clarify where the reports are being sent to

- docs/package.json
This branch removes the `--prefix-paths` option in the docs `npm start` script to make development simpler.
> [Docs] Don't prefix paths in development

- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
This one very important 115-line test:
https://github.com/apollographql/apollo-server/blob/c85c6d286df2e918225681ae42020ea0eb08215c/packages/apollo-server-integration-testsuite/src/ApolloServer.ts#L528-L643
...has grown to a point where it's a bit conflated.  Rather than becoming a new test with a separate concern, it's been added to as we've continued to expand observability features.
When looking at #1639, I was tempted to do the same thing, but felt it was worth breaking out the test into various helpers for reusability in new (upcoming!) tests.
There are two main changes here:
* Rename the `error` field which is used amongst many of the tests to something more recognizable, particularly since `error` itself is a protobuf property which these tests exercise: …
> tests: Expand helper for trace tests.

- packages/apollo-tracing/package.json
All other packages in this repository specify `graphql@^14.0.0` which
allows minor and patch releases of `graphql`. But the `apollo-tracing`
package only allows `graphql@14.2.x` which covers only patch releases.
This commit changes the peer dependency range of `graphql` in the
`apollo-tracing` package to contain the same ranges as all other
packages in this repository (`^0.12.0 || ^0.13.0 || ^14.0.0`).
Technically this would be a breaking change, because before it allowed `0.10.x - 14.2.x`,
so if that is a concern we could also change the range to include `0.10.x` and `0.11.x` (`^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0`) but I figured being consistent with the other packages is more important and since none of the other packages allow `0.10.x - 0.11.x` this packages shouldn't …
> Align peer dependency range in apollo-tracing with other packages

- packages/apollo-engine-reporting/src/extension.ts
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
The full-query caching feature implemented in #2437 originally took the additional steps of  changing the `apollo-engine-reporting` module to utilize the new request pipeline available in Apollo Server as of #1795. (_See also #2441, https://github.com/apollographql/apollo-server/pull/2441#discussion_r266852582_)
While that would have been nice, there was still some uncertainty about some of the life-cycle hooks that would be necessary to make that happen and it wasn't worth blocking the implementation of full-query caching on those stalled decisions.
Therefore, the changes to utilize new functionality in the request pipeline, including what would have been a simplification of the way that `apollo-engine-reporting` would have obtained the `operationName` (something that is available via …
> [release-2.5.0] Fix missing `operationName` in `apollo-engine-reporting`.

- docs/gatsby-config.js
- docs/source/features/apq.md
This brings back the Automatic Persisted Queries (APQ) article that was
previously moved to the Platform documentation but is currently unlisted
there.
> Revive Automatic Persisted Queries article.

- package-lock.json
- package.json
- packages/apollo-engine-reporting/package.json
- packages/apollo-server-core/package.json
- packages/graphql-extensions/package.json
Using the current versions of these dependencies rather than the alphas (from an alpha branch of the server repo) is causing multiple versions of some of these dependencies to appear in our platform repo's `release-federation` branch. I'm not certain this is the actual problem, but I do feel it brings us one step closer to resolving it.
The error we're seeing in CI looks something like this, which leads me to suspect `apollo-env` (and other non-alpha apollo- packages):
```
Trevors-MacBook-Pro-2:apollo-platform-commercial trevorscheer$ npm run clean && npm ci
> apollo-platform-commercial-monorepo@ clean /Users/trevorscheer/Desktop/Repos/apollo-platform-commercial
> git clean -dfqX -- ./node_modules **/{dist,node_modules}/ ./packages/*/tsconfig.tsbuildinfo
npm WARN tar ENOENT: no such file …
```
> Update apollo package dependencies

- CHANGELOG.md
- packages/apollo-datasource-rest/src/RESTDataSource.ts
When calling `new Headers(undefined)` in IE11 an `Invalid argument` exception is thrown.
With this in place, we'll call it with an empty object, resulting in an empty Headers object.
TODO:
Edit:
I mistakenly wrote `null`, where I meant to write `undefined`.
> Fix Headers bug in IE11

- docs/source/features/errors.md
Update docs to use `rewriteError` instead of `formatError`.
TODO:
> Update docs for rewriteError.

- package-lock.json
- package.json
- packages/apollo-engine-reporting/package.json
- packages/apollo-server-core/package.json
- packages/graphql-extensions/package.json
With the release of federation features within the Apollo Tooling repo, we can now update `apollo-server` and friends over to use the `latest` packages from that repo, rather than the `alpha`s.
TODO:
> Transition Apollo Tooling deps to latest from alpha

- packages/apollo-engine-reporting/src/agent.ts
Ran a quick transformation on these comments in the
`apollo-engine-reporting` package to change them to `tsdoc` format.
By using the C-style `tsdoc` comments, these descriptions will actually be
displayed within editors that support JSDoc (i.e. most).
> chore: Switch Apollo Engine Reporting comments to `tsdoc`.

- CHANGELOG.md
- packages/apollo-engine-reporting/src/extension.ts
- packages/apollo-server-core/src/requestPipeline.ts
- packages/graphql-extensions/src/index.ts
Currently we don't set the parsed document in extensions immediately,
which means that apollo-engine-reporting is forced to return a full signature
instead of the normalized signature. This leads to cardinality
explosion. This ensures that we report with a normalized signature and
report errors that occur in the requestPipeline.
TODO:
> extensions: add setParsed and capture error in extensions

- packages/apollo-server-lambda/src/ApolloServer.ts
Disable callbackWaitsForEmptyEventLoop for HTTP OPTIONS request since ApolloServer already disable callbackWaitsForEmptyEventLoop for POST request. (https://github.com/apollographql/apollo-server/blob/1ec2890397ca306350b0e1f33eec7b5f3f951d8d/packages/apollo-server-lambda/src/lambdaApollo.ts#L33)
Otherwise is lambda event loop is not empty, subsequence HTTP OPTIONS request will be hang and even timeout without throwing proper error.
TODO:
> disable callbackWaitsForEmptyEventLoop

- packages/apollo-engine-reporting/src/extension.ts
This makes no actual changes to the function, but it moves this rather
large block of code out of the `constructor` for `EngineReportingExtension`.
> chore: Move default client signature generation into its own function.

- docs/source/api/apollo-server.md
The link is dead because the case is incorrect.
> 📚 update link for EngineReportingOptions config options

- packages/apollo-server-core/src/requestPipeline.ts
The `WithRequired` typing declarations throughout the request pipeline API
are meant to provide integrations with type safety for their hook
implementations: a contract between plugins and Apollo Server itself.
We've added some additional properties to the `requestContext` that the
request pipeline API (already) receives but, up until this commit, those
properties haven't been explicitly marked as `WithRequired` by the request
pipeline.
I'd love to say this was my own observation but, full disclosure, while
these are not TypeScript compilation errors (in the eyes of `tsc`) this was
prompted by some new red-squiggles in my editor which hadn't been present
before.  Upon investigation, it appears that it's right!
This updates the internal request pipeline types to match that of the …
> Extend the typing contracts for  the request pipeline hooks.

- packages/apollo-cache-control/package.json
- packages/apollo-engine-reporting/package.json
- packages/apollo-engine-reporting/src/__tests__/agent.test.ts
- packages/apollo-engine-reporting/src/__tests__/extension.test.ts
- packages/apollo-engine-reporting/src/agent.ts
- packages/apollo-engine-reporting/src/extension.ts
- packages/apollo-server-azure-functions/package.json
- packages/apollo-server-cloud-functions/package.json
- packages/apollo-server-cloudflare/package.json
- packages/apollo-server-core/package.json
- packages/apollo-server-core/src/requestPipeline.ts
- packages/apollo-server-express/package.json
- packages/apollo-server-fastify/package.json
- packages/apollo-server-hapi/package.json
- packages/apollo-server-integration-testsuite/package.json
- packages/apollo-server-koa/package.json
- packages/apollo-server-lambda/package.json
- packages/apollo-server-micro/package.json
- packages/apollo-server-plugin-base/package.json
- packages/apollo-server-plugin-response-cache/package.json
- packages/apollo-server-testing/package.json
- packages/apollo-server/package.json
- packages/apollo-tracing/package.json
- packages/graphql-extensions/package.json
This moves the Apollo Engine Reporting signature calculation (which the
Apollo Cloud uses to aggregate similar operations) to perform
asynchronously, after the response has been returned to the client, and also
caches the signature for use by additional operations which match the same
`queryHash` (which is an exact SHA-256 hex digest of the operation body
received from the client).
While the signature calculation is relatively quick on small operations, with
sustained load and more complex operations, this recurring calculation can
be more costly.
As a bit of validation to the success of this change, on a very basic
performance benchmark, using a schema with 1000 `String` fields (i.e.  a
`type Query` with `Field_1: String` through `Field_1000: String`) and an
incoming operation which …
> Defer and cache calculation of Engine reporting signature.

- packages/apollo-server-core/src/requestPipeline.ts
This re-implements the triggering of `didEncounterErrors` during `willResolveOperation` errors which occur in the request pipeline, but in a more common code-path where it probably should have been getting called already anyway.
This re-implements part of the #2659 functionality (which is currently not included on the 2.6.0 branch) in a different manner, with the additional piece — still not included in this PR — to be included in a follow-up commit.
> engine-reporting: Handle errors within `didResolveOperation` life-cycle hook.

- packages/apollo-engine-reporting/src/extension.ts
This is another take on #2659 which has been otherwise excluded from the
2.6.0 release.
The work in #2659 was meant to ensure that the `document` and
`operationName` were set at the appropriate locations within the lifecycle
events for the `graphql-extensions` module, specifically when an error had
been thrown within `didResolveOperation` of the new request pipeline.
While the solution in #2659 certainly works, it introduced a new life-cycle
method for details which we could also calculate without adding to the
API surface area by using information which was already exposed.
Even though `graphql-extensions` is no longer really being supported,
avoiding growth on the API surface area of `graphql-extensions` is still
important for any API!
Ref: …
> engine-reporting: Capture `operationName` and `document` within errors.

- CHANGELOG.md
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/__tests__/isDirectiveDefined.ts
- packages/apollo-server-core/src/utils/isDirectiveDefined.ts
This PR adds a utility function `isDirectiveDefined` and uses it to guard against duplicate directives when the user's schema already contains a directive (in this case, cacheControl)
TODO:
> Avoid duplicate `cacheControl` directives via `isDirectiveDefined`

- packages/apollo-server-core/src/requestPipelineAPI.ts
- packages/apollo-server-core/src/runHttpQuery.ts
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
**Note:** This currently only covers error conditions.  Read below for details.
This commit aims to provide user-configurable opt-in to mapping GraphQL-specific behavior to HTTP status codes under error conditions, which are not always a 1:1 mapping and often implementation specific.
HTTP status codes — traditionally used for a single resource and meant to represent the success or failure of an entire request — are less natural to GraphQL which supports partial successes and failures within the same response.
For example, some developers might be leveraging client implementations which rely on HTTP status codes rather than checking the `errors` property in a GraphQL response for an `AuthenticationError`.  These client implementations might necessitate a 401 status code.  Or as another …
> Allow plugins to modify the HTTP status code under ERROR conditions.

- CHANGELOG.md
- packages/apollo-cache-control/src/__tests__/cacheControlExtension.test.ts
- packages/apollo-cache-control/src/index.ts
Closes https://github.com/apollographql/apollo-cache-control/issues/12
Adds a check for `errors` and for `data` before setting the `Cache-Control` header. This change is aligned with the logic in the `apollo-server-plugin-response-cache` package:
https://github.com/apollographql/apollo-server/blob/7db109efed2a193e0b459030ccd748d1f329fc82/packages/apollo-server-plugin-response-cache/src/ApolloServerPluginResponseCache.ts#L243-L261
> Prevent Cache-Control header from being set if response has errors

- packages/apollo-server-core/src/requestPipeline.ts
- packages/apollo-server-core/src/requestPipelineAPI.ts
- packages/apollo-server-plugin-base/src/index.ts
(As I mentioned at the bottom of https://github.com/apollographql/apollo-server/pull/2714)
This adds a new life-cycle event to the new request pipeline API called `didEncounterErrors`, which receives `requestContext`'s **unformatted** `errors`.  (The `requestContext` represents an individual request within Apollo Server.)  These `errors` give access to potentially different `errors` than those received within `response.errors`, which are sent to the client and available on the `willSendResponse` life-cycle hook, since they are **not** passed through the `formatError` transformation.  This can allow plugin implementers to take advantage of the actual errors and properties which may be pruned from the error before transmission to the client.
While most other request pipeline life-cycle …
> Add `didEncounterErrors` to request pipeline API.

- docs/source/features/authentication.md
This PR fixes a typo in authentication.md. It's the same as PR #2717 but with the changes requested by @abernix. I closed PR #2717 because I prematurely deleted my fork and couldn't edit the PR anymore.
@abernix Would it be better to also edit this comment that's above the code snippet where I changed `[]` to `null`?
> In this case, we'll pretend there is no data when we're not logged in.
I think saying "no data" here specifically refers to an empty array, which we just replaced `null`. I'm not sure how to improve this comment though, or if it even needs to be improved. What do you suggest?
> docs: fix typo in authentication.md

- packages/apollo-server-express/src/__tests__/ApolloServer.test.ts
- packages/apollo-server-express/src/__tests__/datasource.test.ts
- packages/apollo-server-hapi/src/__tests__/ApolloServer.test.ts
- packages/apollo-server-koa/src/__tests__/ApolloServer.test.ts
- packages/apollo-server-koa/src/__tests__/datasource.test.ts
- packages/apollo-server/src/__tests__/index.test.ts
Currently, if any of the ports used in tests are taken by some other services running locally, the tests will fail.
This PR is to use 0 as port values so that the operating system will assign an arbitrary unused port. https://nodejs.org/api/net.html#net_server_listen_port_host_backlog_callback
TODO:
> Testing: Use 0 as port in so an arbitrary unused port will be assigned by system

- docs/gatsby-config.js
- docs/source/servers/adonis.md
- docs/source/servers/azure-functions.md
- docs/source/servers/express.md
- docs/source/servers/hapi.md
- docs/source/servers/koa.md
- docs/source/servers/lambda.md
- docs/source/servers/micro.md
- docs/source/servers/restify.md
This branch removes unused pages from the docs that were causing the build to hang on Netlify due to the way they handle (or don't handle) symlinks. Issue here: https://github.com/netlify/netlifyctl/issues/49
All of the deleted files still exist in the apollo-server version 1 docs, where they are still linked to and used.
This branch also re-enables versioning so that version 1 docs are visible again.
> Remove old docs

- docs/source/federation/core-concepts.md
This branch capitalizes the word "Federation" in the opening paragraph of the Core Concepts page for consistency with other instances of "Apollo Federation"
> Capitalize the F in Federation

- packages/apollo-gateway/CHANGELOG.md
- packages/apollo-gateway/src/utilities/__tests__/deepMerge.test.ts
- packages/apollo-gateway/src/utilities/deepMerge.ts
The purpose of this PR is to resolve a security issue within `@apollo/gateway`. The `deepMerge` function is open to a known attack vector called [prototype pollution](https://medium.com/intrinsic/javascript-prototype-poisoning-vulnerabilities-in-the-wild-7bc15347c96). Prototype pollution allows a user to "pollute" `Object.prototype`, thereby polluting all `Objects` with `Object.prototype` in their prototype chain.
This function is currently only in use by the new `@apollo/gateway`.
Vulnerable versions of `@apollo/gateway` include all `<=0.6.1`. A release of version `0.6.2` will follow the merging of this PR shortly and resolve the issue.
> Ignore __proto__ fields in deepMerge()

- packages/apollo-engine-reporting-protobuf/src/reports.proto
- packages/apollo-engine-reporting/src/extension.ts
- packages/apollo-server-core/src/requestPipelineAPI.ts
This PR updates `reports.proto`, adds `forbiddenOperation` and `registeredOperation` boolean fields to `GraphQLRequestMetrics`, and sets those fields on the outgoing trace
The intention is for the operation registry plugin to set these values on requestContext.metrics
> Add forbidden and registered operations to requestContext.metrics - AP-478

- CHANGELOG.md
- packages/apollo-server-lambda/src/ApolloServer.ts
This PR resolves an invalid use of `Object.fromEntries`. This function is currently only supported by Node 12. See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries
I created a small, hand validation of this change for my own confirmation here:
https://runkit.com/trevor-scheer/5cf933b15f7a26001ba9a9c6
Closes #2775
> Remove Object.fromEntries usage (node 12 only)

- .circleci/config.yml
- docs/source/api/apollo-federation.mdx
- docs/source/api/apollo-gateway.mdx
- docs/source/federation/federation-spec.md
- docs/source/federation/implementing.md
- packages/apollo-gateway/src/index.ts
- grammar, punctuation, typos (including a random typo in code)
- document the `name` field on `serviceList`, twice
- clarify that `debug` controls startup messages, not errors
- reorder list at top of federation-spec to match page order
- `Query._entities` is removed if `_Entity` is
- fix a link that would have been caught by the link checker if it was
appropriately internal
- add links to forward references to `@requires` and `@provides`
- stop running a no-op Docs CircleCI task; the test script was removed
in #2394
> docs: more federation docs tweaks

- packages/apollo-federation/CHANGELOG.md
- packages/apollo-federation/src/composition/validate/preComposition/__tests__/keyFieldsMissingExternal.test.ts
- packages/apollo-federation/src/composition/validate/preComposition/keyFieldsMissingExternal.ts
The keyFieldsMissingExternal validator should permit standard
directives just like we do in composition everywhere else. Otherwise,
we'll throw validation errors for using `@deprecated`.
> [Federation] Allow specified directives during validation

- CHANGELOG.md
- packages/apollo-engine-reporting/src/extension.ts
Marking of operations as registered and forbidden in traces happens too early in the request pipeline, so this PR places the condition check at the end of the request
> reporting: fix forbidden/unregistered op reporting

- packages/apollo-federation/src/service/__tests__/buildFederatedSchema.test.ts
- packages/apollo-federation/src/service/printFederatedSchema.ts
> Preserve docstrings in SDL of federated services.

- packages/apollo-server-core/src/requestPipelineAPI.ts
Currently due to core-package not allowing queryHash
You have the following error when building an ApolloGateway with Typescript.
```
Property 'executor' in type 'ApolloGateway' is not assignable to the same property in base type 'GraphQLService'.
Type '<TContext>(requestContext: WithRequired<GraphQLRequestContext<TContext>, "document" | "operation" | "queryHash">) => Promise<GraphQLExecutionResult>' is not assignable to type 'GraphQLExecutor<Record<string, any>>'.
Types of parameters 'requestContext' and 'requestContext' are incompatible.
Type 'WithRequired<GraphQLRequestContext<Record<string, any>>, "document" | "operationName" | "operation">' is not assignable to type 'WithRequired<GraphQLRequestContext<Record<string, any>>, "document" | "operation" | "queryHash">'.
Type …
```
> [Federation] Add queryHash to GraphQLExecutor

- CHANGELOG.md
- packages/apollo-gateway/src/datasources/LocalGraphQLDatasource.ts
- packages/apollo-gateway/src/datasources/__tests__/LocalGraphQLDatasource.test.ts
Great work with the federation/gateway!
I would like the context to be passed to the graphql execution function in the localGraphQLDataSource, the same way it is handled in the remoteGraphQLDataSource, this way I can build integration tests that do keep the required context during execution. Currently it is ignored, even though the process method receives it.
Since the change is so tiny I hope it won't be a difficult decision - is there any reason NOT to pass the context in this particular case?
Thanks!
> pass context to localGraphQLDatasource for testing purposes

- packages/apollo-gateway/src/__tests__/executeQueryPlan.test.ts
- packages/apollo-gateway/src/executeQueryPlan.ts
Fixes #2839. This is done by grouping the definitions by name and type, and only printing these once.
> Deduplicate variable definitions for subqueries

- docs/source/federation/advanced-features.md
- packages/apollo-federation/src/composition/validate/postComposition/__tests__/keyFieldsSelectInvalidType.test.ts
- packages/apollo-federation/src/composition/validate/postComposition/keyFieldsSelectInvalidType.ts
- packages/apollo-gateway/src/__tests__/integration/list-key.test.ts
Pretty simple stuff. Just had to remove the guard that disallowed lists, and the rest fell into place.
> Allow list-type entity @key's 

- packages/apollo-gateway/src/__tests__/__fixtures__/schemas/accounts.ts
- packages/apollo-gateway/src/__tests__/executeQueryPlan.test.ts
- packages/apollo-gateway/src/executeQueryPlan.ts
> Always send variables required for query

- CHANGELOG.md
- packages/apollo-server-core/src/ApolloServer.ts
Followup to fix unintended side effect of https://github.com/apollographql/apollo-server/pull/2685 that David discovered where setting `engine: false` would no longer ignore the `ENGINE_API_KEY` environment variable
> fix: restore allow setting `engine: false` to ignore env var

- packages/apollo-engine-reporting/src/extension.ts
- packages/apollo-server-core/src/requestPipeline.ts
- packages/apollo-server-core/src/requestPipelineAPI.ts
- packages/graphql-extensions/src/index.ts
The full query caching change (#2437) intended to introduce didResolveOperation
to the old graphql-extensions API used by apollo-engine-reporting ("backporting"
it from the newer plugin API). However, that change accidentally forgot to
invoke didResolveOperation from the request pipeline! This meant that the
operation name never got reported.
The change was backed out in #2557. But this unfortunately re-introduced the
exact bug that the change in #2437 was intended to fix: operationName was no
longer set when a result is served from the cache! Additionally, it was not set
if a *plugin* didResolveOperation call threw, which is what happens when the
operation registry plugin forbids an operation.
While we could have fixed this by reintroducing the didResolveOperation
extension API, there …
> Simplify apollo-engine-reporting operationName capturing

- docs/source/features/authentication.md
`AuthorizationError` -> `AuthenticationError`
I couldn't find an instance of `AuthorizationError` but elsewhere in the documentation (for similar reasons) it instructed the use of `AuthorizationError`.
> fix error handling typo

- packages/apollo-federation/README.md
- packages/apollo-gateway/README.md
first draft of some readmes for gateway and federation. definitely open for edits.
> First draft of readmes

- packages/apollo-federation/src/composition/__tests__/compose.test.ts
- packages/apollo-federation/src/composition/__tests__/composeAndValidate.test.ts
- packages/apollo-federation/src/composition/compose.ts
- packages/apollo-federation/src/composition/rules.ts
- packages/apollo-federation/src/composition/types.ts
- packages/apollo-federation/src/composition/validate/sdl/__tests__/possibleTypeExtensions.test.ts
- packages/apollo-federation/src/composition/validate/sdl/index.ts
- packages/apollo-federation/src/composition/validate/sdl/possibleTypeExtensions.ts
- packages/apollo-gateway/src/__tests__/executeQueryPlan.test.ts
Previously, when building federated services, composition allowed you to `extend` a type without ever defining it in another service. This PR removes that :) 
There were a few changes that needed to be made to make this work.
1. remove the block of code in `compose.ts` that enabled this behavior to begin with.
2. Add empty `Query` and optional `Mutation` definitions to the `definitionsMap`. This is needed because the old block used to add the query and mutation definitions for us. Query and Mutation definitions found in a service are always treated as _extensions_ to make sure they never have an `owner`.
3. I added a validation rule to make sure this is properly erroring. It checks for 2 things: 
1. To make sure there is a definition for any extension
2. make sure the extension is of the …
> [Federation] Disallow extensions without base definitions

- packages/apollo-gateway/src/index.ts
Add support for polling to OSS. The code is mainly taken from enterprise-gateway, but with the support for dynamically adding and removing listeners removed, as it complicates the code significantly and I'm not sure what the use case is. Happy to add it back if needed.
> Add polling support

- CHANGELOG.md
- docs/source/api/apollo-server.md
- packages/apollo-engine-reporting/src/__tests__/agent.test.ts
- packages/apollo-engine-reporting/src/__tests__/extension.test.ts
- packages/apollo-engine-reporting/src/agent.ts
- packages/apollo-engine-reporting/src/extension.ts
Reopening: https://github.com/apollographql/apollo-server/pull/2847
After the revert: https://github.com/apollographql/apollo-server/pull/2930
> feat(apollo-engine-reportoing): `sendVariableValues` and `sendHeaders`.

- packages/apollo-gateway/src/index.ts
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/types.ts
This is an attempt to implement @glasser's desired API for create gateway. As stated in the comments of AS-105:
```js
import { createGateway } from "@apollo/gateway";
const server = new ApolloServer({
gateway: await createGateway({ serviceList })
});
console.log(print(server.schema));  // readonly!
```
> Add createGateway helper function

- packages/apollo-gateway/CHANGELOG.md
- packages/apollo-gateway/src/__tests__/__fixtures__/schemas/books.ts
- packages/apollo-gateway/src/__tests__/__fixtures__/schemas/product.ts
- packages/apollo-gateway/src/__tests__/__fixtures__/schemas/reviews.ts
- packages/apollo-gateway/src/__tests__/executeQueryPlan.test.ts
- packages/apollo-gateway/src/executeQueryPlan.ts
While dogfooding, we ran into an error. Looking into the error with @trevor-scheer, we found that the gateway did not support two use cases we had for `requires`(internally called representations): returning null values and returning arrays. This PR adds the support for those two cases. 
Fixes #2925
> gateway: fix @requires bug preventing array and null values

- packages/apollo-federation/CHANGELOG.md
- packages/apollo-federation/src/composition/utils.ts
- packages/apollo-gateway/src/__tests__/integration/single-service.test.ts
- packages/apollo-gateway/src/buildQueryPlan.ts
- packages/apollo-gateway/src/utilities/array.ts
- packages/apollo-gateway/src/utilities/predicates.ts
This was a bug with the query planner when collecting fields in a selection set. It would remove __typename even if it was added by the end operation as the only field.
> [Federation] Support __typenames if defined by an incoming operation

- docs/source/federation/federation-spec.md
Whilst looking at supporting Federation via a PostGraphile plugin, I noticed a couple things that could be improved. There was a couple missing underscores which I've added, and I've also simplified the `@key` directive declaration into a single declaration.
I'm not sure if defining the `@key` directive twice is allowed in GraphQL, I know the spec says that ["directives are unique per location"](https://graphql.github.io/graphql-spec/draft/#sec-Directives-Are-Unique-Per-Location) but this refers to directives themselves (`@skip(if: ...)`) rather than directive _definitions_. Either way, defining it on one line is simpler and definitely correct according to [the GraphQL spec](https://graphql.github.io/graphql-spec/draft/#sec-Type-System.Directives) so I figured it made sense.
> Fix minor issues in Apollo Federation Spec

- packages/apollo-gateway/src/__tests__/buildQueryPlan.test.ts
- packages/apollo-gateway/src/__tests__/integration/mutations.test.ts
- packages/apollo-gateway/src/buildQueryPlan.ts
It's easier to read a query plan if four steps that'll go in sequence are
written Sequence(a, b, c, d) rather than Sequence(a, Sequence(b, Sequence(c,
d))).
> @apollo/gateway: flatten SequenceNodes and ParallelNodes

- docs/source/features/apq.md
Small fixes in this docs page: [Automatic persisted queries - Apollo Docs](https://www.apollographql.com/docs/apollo-server/features/apq/)
> Fix small grammar issues in Automatic Persisted Queries docs

- CONTRIBUTING.md
Link to a newer spectrum community in Contribution Guidelines instead of slack channel.
> docs: link to spectrum community instead of slack channel

- packages/apollo-server-core/src/__tests__/errors.test.ts
- packages/apollo-server-errors/src/index.ts
Fixes #1456.
Can't seem to find a way to test this, as `apolloFetch` does it's own formatting of errors that circumvents the issue.
Test:
```
formatError: error => {
return new Error("hello");
}
```
previously, the error would be rendered as `{}`, now, the message is preserved.
> Make `Error`'s returned by formatError printable

- packages/apollo-gateway/CHANGELOG.md
- packages/apollo-gateway/src/__tests__/executeQueryPlan.test.ts
- packages/apollo-gateway/src/executeQueryPlan.ts
In the gateway, we currently squash all errors from a single service
into a single `Error` with a generic message, such as `Error while
fetching subquery from service "registry"`. In other words, the gateway
globally overwrites errors from the underlying services and the original
errors are appended to `Error.extensions.downstreamErrors`.
https://github.com/apollographql/apollo-server/blob/9208e14ba1b96aea663f101e1089b40ca17790c2/packages/apollo-gateway/src/executeQueryPlan.ts#L242
This changes to behavior, so that the errors are proxied in their same
form rather than nested into a single error. Ultimately the underlying
services are better equipped than the gateway to expose/mask their own
errors with `formatErrors` and this removes the gateway as the
bottleneck of configuration. The …
> gateway: proxy downstream service errors

- CHANGELOG.md
- docs/source/api/apollo-server.md
- package-lock.json
- package.json
- packages/apollo-server-express/package.json
- packages/apollo-server-express/src/ApolloServer.ts
- packages/apollo-server-express/src/expressApollo.ts
- packages/apollo-server-koa/README.md
- packages/apollo-server-koa/src/ApolloServer.ts
This reverts commit 4149a97d134f96be17a34b78e9e262cf35b49700 from #2435,
which has resulted in a change to middleware endpoints which I need to think about a bit more and just caught _just_ before the graduation of the 2.7.0 release to `latest`.
In a nutshell 🌰: While this affects the `apollo-server-express` and `apollo-server-koa` integrations directly, the previous pattern allowed the `path` to function in a wildcard-y/glob-y manner which also allowed, e.g., `/graphql-literally-anything` to work as the GraphQL endpoint (for both GraphQL Playground and actual GraphQL execution).  In reality, I don't think that should have been permitted, but if anyone had inadvertently leveraged this pattern, they might be surprised by this change.  In particular, the `apollo-server` package, which …
> Revert "Expose composed middleware via getMiddleware()"

- docs/source/essentials/schema.md
Just that the string is not a valid JSON string. It has extra brackets.
> extra brackets

- docs/source/api/apollo-gateway.mdx
* Add the `introspectionHeaders` option documentation for `ApolloGateway`
> Add introspectionHeaders documentation to gateway

- docs/source/deployment/netlify.md
While going through [this section](https://www.apollographql.com/docs/apollo-server/deployment/netlify/#set-up-apollo-server), I couldn't get the GraphQL Playground to show up until I added `playground: true` on the ApolloServer options object (thanks to this [thread on Spectrum](https://spectrum.chat/zeit/general/apollo-server-get-query-missing~ae8d5ca5-2faf-4c8d-8097-c3f6e25cad56)).
I thought I'd add this to the docs so others don't get stuck.
> [docs]: Update Deploying with Netlify Functions

- package-lock.json
- package.json
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
It shouldn't be necessary to bring this entire `yup` dependency just to test
compatibility with the shape of a `yup` (https://npm.im/yup) error.
Ref: https://github.com/apollographql/apollo-server/pull/1288
> chore: Mock `yup` error shape in tests in lieu of full dependency.

- docs/source/index.mdx
This branch removes an undefined `Button` component within the `ButtonLink` on the docs index page.
> [docs] Remove undefined component

- docs/package.json
This branch adds a `name` field to the docs' package.json
> [docs] Give the docs a package.json name field

- packages/apollo-server-lambda/README.md
i was trying out @stubailo's tutorial here https://blog.apollographql.com/deploy-a-fullstack-apollo-app-with-netlify-45a7dfd51b0b and noticed that the playground no longer shows up when hitting the raw endpoint. this must have been a breaking change made somewhere, I can't track it down. it took a while to figure out what the right config was, which seems to be passing `defaultPlaygroundOptions`. I'm hoping to update the docs so future me's wont wonder about this.
> [Docs] [apollo-server-lambda] document usage of playground and defaultPlaygroundOptions

- docs/source/federation/implementing.md
Hello There 👋 
First off all: thank you for the documentation. It makes getting started with Apollo a lot easier! 
I'm playing around with the Federation product at the moment and found some minor copy & paste code improvements on the Federation implementation docs. Let me know what you think :)
- The example federated service does not have a "start server" statement. I've added that
- Later-on in the docs we assume that the server is running on port 4001, so I added the port to the federated service :)
- When first starting the Gateway service you are presented with an error: 
```
Error: Cannot define both `subscriptions` and `gateway`. Set `subscriptions: false` in Apollo Server's config to use gateway.
```
I've applied the fix in the code. Hope this is the right workaround 🙈 
- The …
> Docs: Federation Implementation Touchups

- docs/source/features/errors.md
Fixes #2898
There is no info in docs about what `formatError` [function](https://www.apollographql.com/docs/apollo-server/features/errors/#masking-and-logging-errors) argument is.
`err` argument type is `GraphQLError`, which doesn't allow checks like `instanceof AuthenticationError`, because it is not an original error thrown in resolver.
I think it should be explicitly said about that in docs.
> docs(error-handling): add originalError property description

- packages/apollo-gateway/src/__tests__/gateway/queryPlanCache.test.ts
- packages/apollo-gateway/src/index.ts
We were caching the query plan based on only the query hash, which gave problems when operationName was different for the same query.
> Fix causing multiple operations to sometimes be incorrectly executed

- CHANGELOG.md
- packages/apollo-engine-reporting/src/agent.ts
Among other things, this fixes logs in our test suite of 'Possible EventEmitter
memory leak detected'.
> apollo-engine-reporting: clean up SIGINT/SIGTERM handlers on stop

- CHANGELOG.md
- package-lock.json
- packages/apollo-engine-reporting/src/federatedExtension.ts
- packages/apollo-engine-reporting/src/treeBuilder.ts
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
The extension stack executionDidEnd method gets called before didEncounterErrors
for GraphQL errors returned from execution (although confusingly the plugin
executionDidEnd method gets called after), which caused the assertion that
nothing gets added to the EngineReportingTreeBuilder after stopTiming to
fail. Fix by moving stopTiming to the last possible moment: format().
Actually test error reporting, including both kinds of rewriting.
Add a comment noting that backend parse and validation errors don't get
reported.
Fixes #3052.
> apollo-engine-reporting: fix reporting errors from backends

- docs/source/features/data-sources.md
I assume it's not `apolllo-datasource` but `apollo-datasource`
> Typo in server documentation

- CHANGELOG.md
- packages/apollo-gateway/src/index.ts
When the Apollo Gateway is configured in so-called "managed mode", it uses a
`setInterval` timer to periodically check for updates from the Apollo Graph
Manager (also known as Apollo Engine).
However, since the Timer's `unref` method wasn't invoked, the timer would
continue to place tasks on the event loop, even when the server had been
requested to be shutdown.  By calling `unref`, Node.js switches the timer to
an internal timer which doesn't block the event-loop.
While we could alternatively use a `process.on` event to detect when a
shutdown signal had been received and invoke the Gateway's `stop` method
accordingly, this should be sufficient for this particular implementation.
(As opposed to the implementation in `apollo-engine-reporting`  which does
exactly this since it needs to …
> fix(@apollo/gateway) Call `unref` on the federated gateway's `setInterval`.

- CHANGELOG.md
- packages/apollo-engine-reporting/src/treeBuilder.ts
- packages/apollo-gateway/src/index.ts
- packages/apollo-server-core/src/requestPipeline.ts
Specifically, we found that some network errors talking to federated backends
could have a string path.
> apollo-engine-reporting: don't fail if errors have non-array 'path'

- docs/source/features/metrics.md
Schema tags (variants) have become a central part of interacting with the data in Engine. This helps users set up tags more easily, earlier in their process.
> Add `schemaTag` option to Engine setup example

- packages/apollo-gateway/CHANGELOG.md
- packages/apollo-gateway/src/__tests__/__fixtures__/schemas/books.ts
- packages/apollo-gateway/src/__tests__/__fixtures__/schemas/reviews.ts
- packages/apollo-gateway/src/__tests__/executeQueryPlan.test.ts
- packages/apollo-gateway/src/executeQueryPlan.ts
This is a follow-up / additional fix to PR #2928.
This resolves an oversight (of my own) in handling the case where source is null.
1) The `source` parameter was typed incorrectly (missing `| null`)
2) We tried to access a key on source in various locations within that code
path that resulted in a runtime error when `source === null`
This PR also adds a test case in order to exercise the new `source === null` code path.
> [Federation] Handle `null` @requires selections correctly during execution

- packages/apollo-gateway/CHANGELOG.md
- packages/apollo-gateway/src/__tests__/gateway/lifecycle-hooks.test.ts
- packages/apollo-gateway/src/__tests__/integration/networkRequests.test.ts
- packages/apollo-gateway/src/index.ts
- packages/apollo-gateway/src/loadServicesFromRemoteEndpoint.ts
- packages/apollo-gateway/src/loadServicesFromStorage.ts
- packages/apollo-server-core/src/types.ts
This PR aims to add experimental observability functions to `@apollo/gateway` and add the ability to poll/overwrite service fetching logic. These abilities are not intended for production usage, as they are still experimental and APIs may change in future versions.
The following functions can all be used as additions to the `ApolloGateway` constructor.
- `experimental_pollInterval`
- used to add polling to any service definition lookup. This can be used with the default lookup logic or with a custom service definition lookup function, defined below.
- it is NOT recommended to use this interval when fetching sdl from a running endpoint. 
- `experimental_updateServiceDefinitions`
- This allows users to provide their own means of preparing the information necessary to run the gateway. It’s …
> [gateway] Adds experimental observability functions

- docs/source/api/apollo-server.md
- docs/source/deployment/heroku.md
- docs/source/deployment/now.md
- docs/source/essentials/data.md
- docs/source/features/errors.md
- docs/source/features/metrics.md
- docs/source/migration-engine.md
- docs/source/whats-new.md
Doesn't change option/variable names (for obvious reasons), nor does it rename the deprecated "engine proxy".
> Change instances of Engine to Graph Manager

- docs/source/features/metrics.md
Holding off on modifying the Logging section of this article until #2008 lands.
> Edits on Apollo Server metrics article

- CHANGELOG.md
- packages/apollo-federation/src/service/__tests__/buildFederatedSchema.test.ts
- packages/apollo-federation/src/service/buildFederatedSchema.ts
Support older input formats for building a schema from `typeDefs` where `typeDefs` could be either an array of` DocumentNode`s or a single `DocumenNode` attached to an object with a possible resolver map. This shouldn't be supported in the next major version of `ApolloServer` when we have a more structured approach to modules, but for now this makes migration to federated services much easier for teams that have an existing set of `typeDefs` generated from their project (often in `.graphql` files).
> Support older input formats for building a schema

- CHANGELOG.md
- packages/apollo-server-core/src/playground.ts
Via an upstream PR provided by @spencersteers, this fixes a regression in
GraphQL Playground which prevented the resizing of the schema panel.  This
regression seems to have been introduced by
https://github.com/prisma/graphql-playground/pull/1001, which removed the
relevant binding.
See referenced issues for additional details into the change.
Ref: https://github.com/apollographql/graphql-playground/pull/19
Fixes: https://github.com/apollographql/apollo-server/issues/2529
> Update Playground to fix #2529.

- CHANGELOG.md
- packages/apollo-server-express/src/ApolloServer.ts
The TypeScript compiler is inferring the return type of this method
accurately, but emitting `import("express-serve-static-core")` directly into
the `apollo-server-express` type definitions.
Looking at the `package-lock.json` for the Apollo Server repository, I have
a working theory that there are multple `@types/express`'s within this project
and that, when resolving the imports in the delcarations, a copy of
`express-serve-static-core` is not quite in the right resolution path —
potentially due to some package hoisting and module resolution.
To be honest, it's just a theory and I only spent about 3 or 4 minutes
looking at this, but I hope that this will address #3222 (intentionally not
using the keyword "Fixes" here because we'll wait for validation!)
cc @CallMeLaNN
> types: Use explicit return type of `express.Router` on `getMiddleware`.

- CHANGELOG.md
- package-lock.json
- packages/apollo-server-koa/package.json
`apollo-server-koa` will incorrectly throw `request size did not match content length` from `raw-body` dependency when a well form request with `content-length` header is followed by well formed request without a `content-length` header i.e. (chunked encoding) 
`koa-bodyparser` creates singleton options objects for `co-body` [on this line](https://github.com/koajs/bodyparser/blob/master/index.js#L62), the version of `co-body` that Apollo server koa resolves to will mutate that options object [fixed in this commit](https://github.com/cojs/co-body/commit/39d2e74b6e112a26607009cdf53d1060cf4099ba) when `content-length` header is present the value is persisted in the singleton. So _any_ follow-up request that might not contain `content-length` will use the previous value.
1. Make _any_ request …
> Update koa-bodyparser to ^4.2.1 (Fixes content-length mismatch)

- packages/apollo-federation/src/service/printFederatedSchema.ts
- packages/apollo-gateway/src/executeQueryPlan.ts
- packages/apollo-server-types/src/index.ts
We previously assumed an execution result's value would never be null. This is not true, and enforced in graphql@>14.5.4
> Fixup typings for graphql@>14.4.5

- CHANGELOG.md
- packages/apollo-server-koa/src/__tests__/ApolloServer.test.ts
- packages/apollo-server-koa/src/__tests__/datasource.test.ts
- packages/apollo-server-koa/src/__tests__/koaApollo.test.ts
**Support for Koa on Node.js v6 was dropped as of `apollo-server-koa@2.9.2` when `koa-bodyparser` was updated in #3229.**   _This PR only stops **testing** Koa on Node.js v6, which took a bit more work in order to continue testing on Koa on newer versions of Node.js while maintaining testing Node.js v6 for non-Koa frameworks._
Since Node.js v6 is no longer supported by the Node.js Foundation, it was going to come to this sooner or later since transitive packages are inching their ECMAScript compilation targets to more and more recent versions of the language.
While Apollo Server itself will drop support for Node.js v6 in 3.x, the current Koa integration necessitates a more immediate exception since, after bringing #3229 (2dd0592e), the `koa-bodyparser` package was updated to a new major …
> Stop testing Koa on Node.js v6 in order to update `koa-bodyparser`.

- package-lock.json
- packages/apollo-server-express/package.json
The [literal `import`-ing of `express` in `ApolloServer.ts`][1] isn't new but, prior to #3047, it had only been a typing dependency — not an actual runtime dependency — since the TypeScript compiler doesn't emit `require`s when only types are utilized.
To see this first hand, see [the emitted `dist/ApolloServer.js` in `apollo-server-express@2.8.2`][2] compared to [the same file in `apollo-server-express@2.9.0`][3].  (Hard to decipher, but check around like 15 and search for `"express"` in the second link.)
Now that we actually utilize `express.Router` to build the composition of middleware in #3047 , it's true that `express` is no longer just a type dependency, but does warrant being a regular dependency as well!
Since this has never been the case before during the entirety of the v2 …
> apollo-server-express: Add direct dependency on `express`.

- CHANGELOG.md
- package-lock.json
- packages/apollo-server-lambda/package.json
The typings provided by `aws-types` are used on public methods within the `apollo-server-express` package and, therefore, must be included as direct (not development) dependencies to ensure they are available to packages which utilize it since we don't publish types separately (e.g. via DefinitelyTyped).
For example, these usages:
https://github.com/apollographql/apollo-server/blob/aa3e23de9fbcde41a1bd3cca9c2eacf734bae582/packages/apollo-server-lambda/src/lambdaApollo.ts#L16-L18
https://github.com/apollographql/apollo-server/blob/aa3e23de9fbcde41a1bd3cca9c2eacf734bae582/packages/apollo-server-lambda/src/ApolloServer.ts#L100-L104
And seen in the emitted type declarations here:
https://unpkg.com/apollo-server-lambda@2.9.0/dist/ApolloServer.d.ts …
> types: Add `@types/aws-lambda` as a dependency of `apollo-server-lambda`.

- docs/source/features/apq.md
It seems as if the actual `link` variable declaration is missing.
> Add missing variable assignment.

- packages/apollo-federation/CHANGELOG.md
- packages/apollo-federation/src/composition/__tests__/compose.test.ts
- packages/apollo-federation/src/composition/compose.ts
The purpose of this PR is to prune federation directives from the composed schema. These are only needed _during_ composition, as all of the directives are effectively consumed / transformed into metadata on the schema nodes.
> Remove federation directives from composed schema

- package-lock.json
- package.json
- types/qs-middleware/index.d.ts
These weren't available when this was first introduced, but it appears they are now!
> Switch from local to DefinitelyTyped types for `qs-middleware`.

- packages/apollo-server-express/src/ApolloServer.ts
- packages/apollo-server-express/src/index.ts
- packages/apollo-server-fastify/src/ApolloServer.ts
- packages/apollo-server-fastify/src/index.ts
- packages/apollo-server-hapi/src/ApolloServer.ts
- packages/apollo-server-hapi/src/index.ts
- packages/apollo-server-koa/src/ApolloServer.ts
- packages/apollo-server-koa/src/index.ts
This cleans up some pre-release cruft which is no longer necessary.
The `registerServer` method was the pre-release name for today's `applyMiddleware` method in early (again, pre-release) versions of Apollo Server.
It's been `throw`ing since the first _stable_ release of Apollo Server so this isn't a breaking change.
> Remove deprecated `registerServer` function.

- types/fast-json-stable-stringify/index.d.ts
This merely removes the unnecessary local (and incomplete) set of the types which were already being installed from DefinitelyTyped since 90572878561.
> Remove local `fast-json-stable-stringify` types installed via DefinitelyTyped.

- docs/source/api/apollo-gateway.mdx
This updates the documentation for the `serviceList` attribute on the Apollo Gateway constructor to note that it should **not** be provided when using [managed federation][1], since it is set automatically.
Additionally, this adds a suggestion that a managed configuration should be used as a single source of truth to avoid configuration flapping during a roll-out of a new service list.
[1]: https://www.apollographql.com/docs/platform/federation/#managed-configuration
> docs(apollo-gateway): `serviceList` must be unset with managed federation.

- packages/apollo-federation/CHANGELOG.md
- packages/apollo-federation/src/composition/rules.ts
The previous technique for deciding which validation rules from `specifiedSDLRules` to by-pass during composition was leveraging a string-comparison against `Function.prototype.name`.
As shown in https://github.com/apollographql/apollo-server/issues/3335, that technique breaks down under minification, when function names are often munged to shorter alternatives.
As an alternative, we can import the rules and check them for reference equality with greater success, since those will not be affected by minification.
While the actual bug in #3335 was _not_ in this code, this code poses the same hazard and would likely be affected as well (eventually, at least).
> Use reference-equality when omitting validation rules during composition.

- docs/static/_redirects
Adds a redirect from a former federation page to the one on the graph manager docs
> Federation page redirect

- packages/apollo-gateway/CHANGELOG.md
- packages/apollo-gateway/src/index.ts
This PR fixes a bug where query plan logging only occurred
if `shouldShowQueryPlan` was true. This boolean is only true
under certain conditions during _introspection_, meaning that
this debug log was disabled for all regular queries.
This PR opts to only serialize the query plan if _either_ debugging is enabled, _or_ if the `Apollo-Query-Plan-Experimental` header is set. We then log and/or respond with the query plan as appropriate.
> Fix debug query plan logging

- packages/apollo-gateway/CHANGELOG.md
- packages/apollo-gateway/src/__tests__/gateway/buildService.test.ts
- packages/apollo-gateway/src/index.ts
Currently, buildService is being called twice for each service on
gateway startup. While we _are_ caching the datasources,
we're failing to utilize the cache.
This commit places the creation and caching of datasources in one
place, and indicates this more clearly with an updated function
name.
Fixes #3367
> Fix double instantiation of DataSources

- CHANGELOG.md
- packages/apollo-server-errors/jest.config.js
- packages/apollo-server-errors/src/__tests__/ApolloError.test.ts
- packages/apollo-server-errors/src/__tests__/tsconfig.json
- packages/apollo-server-errors/src/index.ts
- tsconfig.test.json
This PR addresses a bug with `ApolloError`, as well as takes a step towards `GraphQLError` spec compliance.
Bug:
No longer allow the 'properties' (now `extensions`) object to overwrite the error message provided to the ApolloError constructor.
Spec complicance:
Move ApolloError towards GraphQLError spec compliance by using extensions rather than arbitrary properties on the class itself. Previous behavior is still supported, however it's now deprecated in favor of extensions. For more context, please read the large comment block associated with this PR's change set.
> Fix ApolloError bug and GraphQLError spec compliance

- packages/apollo-gateway/CHANGELOG.md
- packages/apollo-gateway/src/index.ts
This commit revisits recent changes from PR #3376 which broke
Playground's ability to detect support for the Query Plan view.
Playground's internals decide that QP is supported based on the
response from the first introspection query. The previously mentioned
PR broke this by not providing any `response.extensions.__queryPlanExperimental`
at all. This makes sense for `debug` mode, but Playground still needs
some form of hint to know that it's supported and continue sending
the `Apollo-Query-Plan-Experimental` header.
> Fix Gateway / Playground Query Plan view

- packages/apollo-gateway/CHANGELOG.md
- packages/apollo-gateway/src/__tests__/integration/networkRequests.test.ts
- packages/apollo-gateway/src/index.ts
This PR removes quite a bit of duplication around the `updateComposition` function of `ApolloGateway`. This consolidates two very similar functions, one anonymous async function being used for polling and the original updateComposition function.
This consolidation fixes a bug where the gateway didn't notify its `onSchemaChange` listeners when the composition was updated.
Behavioral differences as a result of these changes:
1. Previously, the `experimental_didUpdateComposition` hook wouldn't be reliably called unless the `experimental_pollInterval` was set. If it _was_ called, it was sporadic and didn't necessarily mark the timing of an actual composition update. After this change, the `dUC` hook is called on a successful composition update.
2. The `experimental_pollInterval` configuration …
> Gateway schema change listener bug + refactor

- packages/apollo-gateway/CHANGELOG.md
- packages/apollo-gateway/src/index.ts
- packages/apollo-gateway/src/loadServicesFromRemoteEndpoint.ts
This PR addresses a bug in the gateway that prevents it from constructing new `DataSource`s when composition updates and the url of an underlying service changes. Currently the creation of a `DataSource` is cached based on its `serviceName`, but really the caching should depend on both the `serviceName` and `url` of the `ServiceDefinition`.
The bug in question was introduced in #3388.
Note:
This is broken out from its original PR: #3409
In order to separate two unrelated changes and cleanup some unnecessary git madness that I introduced.
> Gateway cached DataSource bug

- packages/apollo-gateway/CHANGELOG.md
- packages/apollo-gateway/src/index.ts
The gateway currently spits out INFO logs about updating schema on both startup and during schema updates. It really should only log "updating schema" if a previous schema exists.
** Also removes extraneous neighboring else block (the same is resolved immediately below)
> Gateway - don't log updates on startup

- CHANGELOG.md
- packages/apollo-server-core/src/graphqlOptions.ts
- packages/apollo-server-core/src/requestPipeline.ts
Previously, the `formatResponse` was only typed as a `Function`.  However, since it's expected that the function return a `GraphQLResponse` (the same thing that it receives, that typing seems a bit too generic.  This changes the typing to more accurately reflect the way it should be used, and also provides it the complete `requestContext` rather than just the cherry-picked `context` property.
> formatResponse: Fix typings and provide full request context.

- packages/apollo-server-core/src/ApolloServer.ts
There doesn't seem to be a naming conflict here, or a reason why this is
aliased to another name rather than using the symbol its exported as, so this really just introduces indirection.
> Stop aliasing `GraphQLServerOptions` to `GraphQLOptions`.

- CHANGELOG.md
- packages/apollo-server-core/src/runHttpQuery.ts
If variables is an empty string than JSON.parse(variables) will throw an error.
So anyone sending a request with variables = '' will get an unnecessary error.
> Don't parse empty `extensions` or `variables` as JSON

- docs/source/data/subscriptions.md
Looking through the `Fetching data` section, this was the only bit that added types. Removing them avoids confusion and adds consistency across the docs.
> Remove TS types from subscriptions.md

- CHANGELOG.md
- package-lock.json
- packages/apollo-engine-reporting-protobuf/package.json
- packages/apollo-engine-reporting-protobuf/src/index.js
Reinstate the `@apollo/protobufjs` fork after resolving TS build issues in a patch release.
For reference:
#3535 
#3530
Closes #3312
> Reinstate `@apollo/protobufjs` fork

- packages/apollo-gateway/CHANGELOG.md
- packages/apollo-gateway/src/FieldSet.ts
- packages/apollo-gateway/src/__tests__/integration/unions.test.ts
- packages/apollo-gateway/src/buildQueryPlan.ts
This PR adds some granularity to how fields are keyed when we group them within a selection set. Previously, the field name was considered sufficient for merging selections (and it almost always is!). However, in the case that the `parentType` of these same-named fields is _different_, we most certainly should not group selections as it will result in invalid query plans.
The new test illustrates this edge case via two `union`ed types that share a same top-level field name. The gateway was incorrectly grouping these separate fields into the same `selectionSet` under the `media` field. By keying on `parentType:responseName` instead, the gateway will know better than to group two distinct `media` fields of different types.
> Gateway over-merging fields of unioned types 

- docs/source/integrations/plugins.md
The `didEncounterErrors` event fires only once during the lifecycle of a request and fires regardless of whether the error(s) happened during parsing, validation, or execution. Here's a small edit to the docs to make that a little more clear
> Clarify `didEncounterErrors` documentation

- CHANGELOG.md
- package-lock.json
- package.json
- packages/apollo-server-core/src/utils/dispatcher.ts
This commit updates our typescript version to latest. It also incorporates related fixes (read: workarounds?) that have blocked the upgrade since 3.6.3. I haven't yet been able to identify the underlying issue, but this seems like a TS regression that's over my head.
The _symptom_ is that within each of our `invoke*` functions, `method` is no longer benefiting from the `typeof method === 'function'` check. Within the `if` block, `method` is being inferred as a `T[TMethodName]` rather than a `T[TMethodName] & Function` - hence `method.apply` was now considered invalid (as `method` is no longer also a `Function` according to TS). 
The fixes proposed here do limit some of the genericness of the Dispatcher class and its functions, however I'd argue that the level of said genericness is …
> Upgrade TS to 3.7.3

- CHANGELOG.md
- packages/apollo-server-caching/README.md
- packages/apollo-server-caching/src/KeyValueCache.ts
> Note that KeyValueCache ttl is in seconds

- CHANGELOG.md
- packages/apollo-server-cloud-functions/src/ApolloServer.ts
Headers are not sent to the client. Moved the response set command a few lines ahead.
> cloud-functions: Send CORS headers on OPTIONS requests.

- CHANGELOG.md
- package-lock.json
- packages/apollo-engine-reporting/package.json
- packages/apollo-engine-reporting/src/treeBuilder.ts
- packages/apollo-engine-reporting/tsconfig.json
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
The fix in #3614 changed behavior which was not surfacing errors to the extensions and request pipeline plugins when those errors occurred during APQ negotiation.
However, it failed to consider - nor were there any tests - which ensured that the `apollo-engine-reporting`'s mechanism didn't receive an error earlier in the request pipeline than previously allowed.
This applies a fix which special-cases the APQ error in this case, and avoids reporting it to Apollo Graph Manager (which is the same behavior as before).
Fixes: https://github.com/apollographql/apollo-server/issues/3627
> Fix regression caused by #3614 when using APQ with Graph Manager reporting.

- CHANGELOG.md
- packages/apollo-server-cache-memcached/src/index.ts
- packages/apollo-server-cache-redis/src/RedisCache.ts
- packages/apollo-server-cache-redis/src/RedisClusterCache.ts
- packages/apollo-server-cache-redis/src/__mocks__/ioredis.ts
- packages/apollo-server-caching/src/KeyValueCache.ts
- packages/apollo-server-caching/src/PrefixingKeyValueCache.ts
- packages/apollo-server-caching/src/__tests__/testsuite.ts
- packages/apollo-server-caching/src/index.ts
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/graphqlOptions.ts
- packages/apollo-server-core/src/requestPipeline.ts
- packages/apollo-server-integration-testsuite/src/index.ts
Previously, while it was possible to set very high TTL values on individual `set`s, it was not possible to say "Do not assign a TTL value.".  This adds that possibility.
Furthermore, this allows the persisted query cache configuration (and its options `PersistedQueryOptions`) in Apollo Server to specify a setting and, when specified, to pass that option into the `set` used in `ApolloServer`.
Of course, that still necessitates passing a default that's isolated to Apollo Server itself, rather than a default that's able to be specified when constructing the cache. 
There's another approach to solving this problem which might be worth (still? in partial replacement of?) allowing, but I couldn't convince myself of the approach.
The alternate pattern would allow the instantiation of the cache …
> Allow infinite TTL (time-to-live) on KeyValueCache's set.

- docs/source/integrations/plugins.md
This PR builds on #2008 and adds documentation for request lifecycle event end hooks and the new `responseForOperation` event.
> Docs for request lifecycle end hooks and responseForOperation

- docs/gatsby-config.js
This branch changes the version config options for the docs to strings rather than ints.
> Change version options to strings

- packages/apollo-gateway/src/__tests__/__fixtures__/schemas/product.ts
- packages/apollo-gateway/src/__tests__/__fixtures__/schemas/reviews.ts
- packages/apollo-gateway/src/__tests__/executeQueryPlan.test.ts
Deps: #3582 
@trevor-scheer. I've simplified the cases where the previous code was misbehaving into three straightforward tests, which I'm merging into the [branch](https://github.com/apollographql/apollo-server/tree/jbaxleyiii/reduce-interface-expansion). Both pull requests are ready to go in my head.
> Add tests to 'Reduce interface expansion for types contained to a single service'

- packages/apollo-gateway/CHANGELOG.md
- packages/apollo-gateway/src/__tests__/__fixtures__/schemas/product.ts
- packages/apollo-gateway/src/__tests__/__fixtures__/schemas/reviews.ts
- packages/apollo-gateway/src/__tests__/executeQueryPlan.test.ts
- packages/apollo-gateway/src/__tests__/integration/abstract-types.test.ts
- packages/apollo-gateway/src/buildQueryPlan.ts
The purpose of this PR is to take a first step towards minimizing query plans and their requests to downstream services. Currently, querying fields that return an abstract type result in large query plans because the planner expands these fields into an inline fragment on every implementing type.
This work targets an optimization concerning the over-expansion of abstract types. Previously, any query that asked for a field on an interface would be expanded to a selection of type conditions for all possible types. This would result in overly large operations sent to downstream services. If every field of an interface and its implementors belong to a single service, we can optimize the query plan by not expanding all possible types when building queries for fields that return an interface …
> Reduce interface expansion for types contained to a single service

- packages/apollo-gateway/CHANGELOG.md
- packages/apollo-gateway/src/index.ts
- packages/apollo-gateway/src/loadServicesFromStorage.ts
In its current state, the gateway uses a global fetcher, meaning the
fetcher and its cache is shared among all gateways within the same
runtime. This change attaches a single fetcher to the instance of the
gateway and utilizes its own fetcher for all requests to GCS. The
global fetcher was fortunately not depended on by anything else, so
the change is relatively minimal.
I made a few consolidations so as not to pass the fetcher around between
many small functions. The functions I removed were one-time use, relatively
small, and may have added negligible amounts of indirection anyway.
> Instantiate one CachedFetcher per gateway instance

- package-lock.json
- package.json
`graphql` includes TS typings since `14.5.0` release.
@abernix Also without it you can't check TS definitions in `15.0.0`, in #3712
> Remove '@types/graphql' since 'graphql' already includes TS typings

- packages/apollo-gateway/src/datasources/__tests__/tsconfig.json
Previously missing, and thus defaulting to the root `tsconfig.base.json` and
causing a lot of unhappy red-squigglies (on, e.g. `describe`, `it`, `test`) due to the lack of `jest` types being available!
> tests: Bring `tsconfig.json` for `@apollo/gateway`'s `datasources` directory.

- packages/apollo-federation/CHANGELOG.md
- packages/apollo-federation/src/composition/__tests__/composeAndValidate.test.ts
- packages/apollo-federation/src/composition/compose.ts
- packages/apollo-federation/src/composition/utils.ts
> Strip all Type System Directives during composition

- CHANGELOG.md
- docs/source/api/apollo-gateway.mdx
- docs/source/api/apollo-server.md
- packages/apollo-gateway/CHANGELOG.md
- packages/apollo-gateway/src/index.ts
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/types.ts
This introduces two experimental configuration options for existing internal cache stores:
- `experimental_approximateDocumentStoreSizeMiB` is added to the `ApolloServer` constructor options and controls the _approximate_[1] size, in MiB, of the request pipeline document store, which is used to avoid repeated parsing and validation passes on queries which equate to the same `queryHash`[2].
- `experimental_approximateQueryPlanStoreMiB` is added to the `ApolloGateway` constructor options and controls the _approximate_[1] size of the query plan cache, which is used to avoid recalculation on repeated queries which equate to the same `queryHash`[2].
These are currently _experimental_ because a more flexible, zero-config approach could more effortlessly account for memory of various internal …
> experimental: Allow query plan & parsed/validated document cache config

- docs/source/performance/apq.md
> Edits to APQ edits

- packages/apollo-federation/CHANGELOG.md
- packages/apollo-federation/src/composition/__tests__/composeAndValidate.test.ts
- packages/apollo-federation/src/composition/utils.ts
This commit resolves a breaking and unintentional change from #3736.
While type-system directives _should_ be removed, @deprecated is a
special case which can and should be left in.
> Federation: Preserve @deprecated type-system directives

- packages/apollo-gateway/CHANGELOG.md
- packages/apollo-gateway/src/QueryPlan.ts
- packages/apollo-gateway/src/__tests__/buildQueryPlan.test.ts
- packages/apollo-gateway/src/__tests__/integration/networkRequests.test.ts
- packages/apollo-gateway/src/__tests__/integration/nockMocks.ts
- packages/apollo-gateway/src/buildQueryPlan.ts
- packages/apollo-gateway/src/executeQueryPlan.ts
- packages/apollo-gateway/src/index.ts
- packages/apollo-gateway/src/snapshotSerializers/queryPlanSerializer.ts
For large queries (esp. ones that leverage many nested fragments), queries to downstream services can blow up astronomically because the gateway expands everything during a downstream request. For example, we've seen a ~700 line query making heavy use of fragments become over 200k lines (formatted) due to this expansion.
This PR has the gateway build fragments on the fly for the selection sets that it encounters and reuses them whenever possible. This is an heavy-handed and simple implementation, but with tangible wins for large queries. More complex and correct solutions exist and are currently being discussed. If anyone feels so inclined to solve this interesting problem, please reach out to us - we'd be happy to discuss approach and entertain a contribution here.
This is currently …
> Gateway(experimental): compress downstream requests via generated fragments

- packages/apollo-server-express/src/__tests__/datasource.test.ts
- packages/apollo-server-koa/src/__tests__/datasource.test.ts
Similar to e7949d62c0f2a3f096573f1ee07f146d7aabd8af in #3622, this further eradicates explicit port usage in our tests -- which create confusion in local development when those ports are in-use by other applications -- by switching to ephemeral ports which are randomly selected by the operating system based on what is free.
In this particular case, I spent at least 60 minutes chasing down a test failure which could certainly have been related to a change in the implementation being tested, only to find out eventually that it was due to a server that I'd started in another terminal on Friday and forgot to shutdown!  It was even more perplexing since the application that I started (the federation demo application) uses ports 4001-4003, and these two tests use port 4001 and 4002 …
> tests: Use an ephemeral port, rather than port 4001/4002.

- packages/apollo-gateway/src/index.ts
Follows-up https://github.com/apollographql/apollo-server/pull/3783.
These types are compatible, but this change is necessary to account for the fact that, while we have provided types for `make-fetch-happen` which matter during development of Apollo Server, we don't include those types in the distribution.  We could do that, of course, but as I'll note in a minute, we want something more generic anyhow.
The omission of the types in the published package (currently, before this commit) results in typing errors for consumers of `@apollo/gateway` since the `import` statement for the `Fetcher` type from `make-fetch-happen` is still emitted (see attached [Screenshot]).
Switching to the type that `apollo-serve-env` already provides via its `fetch` implementation (literally, `typeof fetch`) …
> Switch to existing `fetch` type, rather than that of `make-fetch-happen`.

- CHANGELOG.md
- docs/package-lock.json
- docs/package.json
- packages/apollo-federation/CHANGELOG.md
- packages/apollo-gateway/CHANGELOG.md
- packages/apollo-gateway/src/__tests__/gateway/executor.test.ts
- packages/apollo-gateway/src/__tests__/gateway/lifecycle-hooks.test.ts
- packages/apollo-gateway/src/index.ts
- packages/apollo-gateway/src/loadServicesFromRemoteEndpoint.ts
- packages/apollo-gateway/src/loadServicesFromStorage.ts
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/runHttpQuery.ts
- packages/apollo-server-core/src/types.ts
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
These are just a couple small improvements to the behavior of Apollo Gateway during error conditions which arise while attemtping to update the schema.
Most notably, this removes a previously trapped error which should be propogated up the call stack.
I believe these small bits are the very lowest hanging of fruit and that these updates are orthongonal/complimentary to additional retry functionality and improved usability of the Gateway which is something @trevor-scheer is currently looking at.
> gateway: Small improvements to error messages and behavior during updates.

- CHANGELOG.md
- packages/apollo-server/src/index.ts
- This new feature adds a new server configuration option so that the developer can disable information that is reported in the response header (like `x-powered-by`) on Express server - #3812
> apollo-server: Disable "x-powered-by" header

- packages/apollo-gateway/CHANGELOG.md
- packages/apollo-gateway/src/__tests__/loadServicesFromRemoteEndpoint.test.ts
- packages/apollo-gateway/src/loadServicesFromRemoteEndpoint.ts
Previously, when attempting to compose a schema from a downstream service in
unmanaged mode, the unavailability of a service would not cause composition
to fail.
Given a condition when the remaining downstream services are still
composable (e.g. they do not depend on the unavailable service and it does
not depend on them), this could still render a valid, but unintentionally
partial schema.
While a partial schema is in many ways fine, it will cause any client's
queries against that now-missing part of the graph to suddenly become
queries which will no longer validate, despite the fact that they may have
previously been designed to fail gracefully during degradation of the service.
Rather than simply logging errors with `console.error` in those conditions,
we will now `throw` the errors. …
> Fail to compose when a service's federated SDL cannot be retrieved.

- packages/apollo-gateway/CHANGELOG.md
- packages/apollo-gateway/src/__tests__/integration/networkRequests.test.ts
- packages/apollo-gateway/src/index.ts
To help address the configuration when a local configuration is provided and
one is also available in the cloud, warn the user of the dual-configuration
to avoid what is a common unintended mode of operation.
> gateway: Warn when both local and remote configurations are present.

- packages/graphql-extensions/package.json
Avoids links with 404 on npm and yarn websites. Follows package migration to the monorepo.
---
It'd be great if someone also updated [CHANGELOG.md](https://github.com/apollographql/apollo-server/blob/master/packages/graphql-extensions/CHANGELOG.md) before the next release 🙏  I’m currently seeing that I need to bump from  `^0.10.10`  to   `^0.11.0` and I don’t know if there are any breaking changes to expect.
> Fix repository path for graphql-extensions

- packages/apollo-gateway/src/index.ts
- packages/apollo-server-core/src/requestPipeline.ts
- packages/apollo-server-core/src/types.ts
- packages/apollo-server-plugin-base/src/index.ts
- packages/apollo-server-types/src/index.ts
This makes it easier to reason about the types and to keep things DRY, in addition to preserving a more real stacking of types as the stages of server life-cycles progress.  E.g., `validationDidStart` will have a super-set of `Required` properties which were present in the `parsingDidStart` phase.  Now, rather than actually repeating them verbosely, they will be intersected.
These new explicit types will live in `apollo-server-types` where they can also be relied upon by `@apollo/gateway` and other packages, but they'll also be exported directly from the `apollo-server-plugin-base` package. Reason being: The overall concept of `apollo-server-types` and this `apollo-server-plugin-base` package is that they should NOT depend directly on "core", in order to avoid close coupling of plugin …
> plugins: Declare types rather than use in-line types for life-cycle hooks.

- packages/apollo-federation/package.json
- packages/apollo-gateway/package.json
Using standard identifiers helps downstream folks correctly identify the license your project (and npm packages) are under.
> chore(federation,gateway): use SPDX'd `license` attr. in `package.json`.

- CHANGELOG.md
- package-lock.json
- package.json
- packages/apollo-engine-reporting-protobuf/src/index.js
- packages/apollo-engine-reporting-protobuf/src/reports.proto
- packages/apollo-engine-reporting/src/agent.ts
- packages/apollo-gateway/src/__tests__/gateway/reporting.test.ts
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
Drop fields that have been deprecated and are no longer used by AER. Also create new fields for Unified Reporting. The fields that have been dropped where never used by apollo-server, and only used by old reporting agents such as the `engine-proxy`.
Also rename fields to make them more generic, and add fields that will be used for stats aggregation.
> [Apollo-Engine-Reporting] Update reports.proto

- docs/source/federation/federation-spec.md
This pr just fixes a type in a directive example:
```graphql
directive @requires(fields: _FieldSet!) on FIELD_DEFINITON
```
The directive location is missing an `i`.
> Fixed a little type `FIELD_DEFINITON` to  `FIELD_DEFINITION`

- packages/apollo-gateway/src/__tests__/gateway/lifecycle-hooks.test.ts
- packages/apollo-gateway/src/__tests__/integration/networkRequests.test.ts
- packages/apollo-gateway/src/index.ts
This PR separates the coupling of 2 unrelated concepts within the gateway:
* polling for schema changes
* registering schema change listeners
This coupling has been questionable for some time, but has become problematic with changes from the latest release branch `release-2.12.0`. Disentangling them is finally necessary.
Previously, polling would begin once a schema change listener was registered. This operated independently of the initial `gateway.load` call. This means that if you registered a listener before "loading" the gateway, polling would kickoff before the gateway had initialized.
After these changes, load and polling are coupled while schema change listener registration is completely independent of either. This allows a user/consumer to register listeners with no unexpected …
> fix: Engine config load issue

- CHANGELOG.md
- packages/apollo-engine-reporting/src/extension.ts
This APQ flag reporting was almost surely a mistake from the past, causing this APQ boolean to not be properly set when the request was, in fact, an APQ request, unless `sendHeaders` was enabled - which it is _not_ by default after the change that released it.
Ref: https://github.com/apollographql/apollo-server/pull/2931/files#diff-24ae042112f9dcc18543ac851c4d8f7cR97-R102
> fix: report APQ hit/registration when `sendHeaders` is disabled.

- packages/apollo-server-plugin-base/src/index.ts
Some of the "didStart" request life-cycle hooks permit returning a "didEnd"
function from them which will be invoked upon completion.  This wasn't
always immediately clear by looking at the in-line signature, but providing
named types should make it marginally easier to recognize this in the
typings.
> Use named types for the "DidEnd"  hooks.

- packages/apollo-engine-reporting/src/agent.ts
- packages/apollo-engine-reporting/src/extension.ts
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/utils/schemaHash.ts
- packages/apollo-server-types/src/index.ts
By default, TypeScript uses structural typing (as opposed to nominal typing) Put another way, if it looks like the type and walks like that type, then TypeScript lets it be a type.
That's often okay, but it leaves a lot to be desired since a `string` of one type can just be passed in as `string` for that type and TypeScript won't complain.  Flow offers opaque types which solve this, but TypeScript doesn't offer this (yet?).  This Faux-paque type can be used to gain nominal-esque typing, which is incredibly beneficial during re-factors!
For the `schemaHash`, in particular, this is very much a string representation that serves a very particular purpose.  Passing it incorrectly somewhere could be problematic, but we can avoid that (particularly as I embark on some re-factoring with it …
> chore: Convert `schemaHash` from `string` to a faux-paque type.

- packages/apollo-server-core/src/utils/pluginTestHarness.ts
This test harness is meant to avoid the need to do the more heavy execution which the request pipeline itself does within `processGraphQLRequest` when we test some of our internal plugins.
I'm not prepared to make this a public-facing harness in its current state, but I have reason to believe that it could be beneficial for external plugin authors to take advantage of something like this - possibly within the context of `apollo-server-plugin-base`.
There's perhaps a best-of-both-worlds approach here where the request pipeline could be tested against a more precise plugin API contract, but I'm deferring until later for now.  As it stands right now, this was a requisite for doing the migrations of the `apollo-engine-reporting` and `apollo-cache-control` extensions over to the new plugin …
> Introduce an internal plugin test harness to facilitate plugin testing.

- docs/source/data/resolvers.mdx
This change fixes the error `"Expected Iterable, but did not find one for field \"Book.author\"."`
> Fix error in sample code

- docs/source/federation/implementing-services.mdx
Simply fixing a typo on the docs.
> docs: Fix typo on implementing services

- docs/source/deployment/azure-functions.md
First thing is the URL has `apollo-sample` when the function name is `graphql`. Next, it's best to not install the `graphql` package directly as you may have a version mismatch with what's depended on by apollo. For example, I ended up with `graphql@15` when the dependency is `graphql@14` and as a result hit https://github.com/apollographql/apollo-link/issues/910 in TypeScript.
> docs(azure): Reference correct URI in instructions.

- docs/source/federation/other-servers.md
Hi,
This library is intended to be used with GraphQL Java services: https://github.com/rkudryashov/graphql-java-federation
> docs: add `graphql-java-federation` to server implementation list

- packages/apollo-engine-reporting-protobuf/package.json
fix for #3962 
first of all removed bash invocation and extracted `pbjs` so it is separated from all prepare stuff
preparation of proto file is also divided into two separate commands and because of running silently in OR mode those who will run succecssfully will win
did check this on both windows and ubuntu with and without direct call everything seems to be ok
> fix for #3962 become windows friendly

- packages/apollo-server-env/package.json
Here is a fix for an #3961 issue, instead of unix based `rm` we gonna use git build in clean functionality which is already used in a root package.json
check:
```bash
cd packages\apollo-server-env
git clean -ndX
git clean -ndX -- dist
git clean -fdX -- dist
Removing dist/
```
where:
- `-n` - used to check what will be deleted
- `-f` - used to actually perform deletion
- `-- dist` - used to define place from where to start
> fix for #3961

- docs/source/integrations/plugins.md
- packages/apollo-server-core/src/__tests__/runQuery.test.ts
- packages/apollo-server-core/src/requestPipeline.ts
- packages/apollo-server-integration-testsuite/src/index.ts
- packages/apollo-server-plugin-base/src/index.ts
- packages/apollo-server-types/src/index.ts
This PR targets https://github.com/apollographql/apollo-server/pull/3988 but was prompted by a need identified during review in [this comment](https://github.com/apollographql/apollo-server/pull/3998/files#r414911049) by @glasser.
As noted, this is tangible clunkiness which could make the implementation of the `ensurePreflight` invocations unnecessary.  While I had imagined we might consider this later, after further consideration and validation from that review, I think it makes a lot of sense to bring it into the request pipeline.
Introducing it removes the need for the defensiveness which `ensurePreflight` (in the other PR) was attempting and was only necessary because the extensions API - which #3988 + #3998 aims to render unnecessary - guaranteed the presence of the "source" (the …
> feat(plugins): Intro. `didResolveSource` to indicate availability of "source".

- packages/apollo-gateway/CHANGELOG.md
- packages/apollo-gateway/src/__tests__/buildQueryPlan.test.ts
- packages/apollo-gateway/src/buildQueryPlan.ts
The nested `for` loops within `splitFields` that utilize `groupByResponseName` and `groupByParentType` make a false assumption that the incoming fields are all valid. In this case, an "invalid" field is one with no `possibleTypes`.
In its current state, the `splitFields` function can consume an invalid field, leaving other valid, similarly-grouped fields ignored (only one will be taken). If an invalid field is consumed, the others will be ignored and the invalid field will subsequently be dropped, meaning the valid field is never represented due to the existence of an invalid field.
A field with no `possibleTypes` can be dropped / ignored from the query since the requested field exists within an impossible condition. Thus, we can skip the `collectFields` step altogether for fields which …
> fix(gateway): Correctly handle unions with nested conditions that have no `possibleTypes`

- packages/apollo-federation/CHANGELOG.md
- packages/apollo-federation/src/composition/index.ts
- packages/apollo-federation/src/composition/normalize.ts
- packages/apollo-gateway/CHANGELOG.md
- packages/apollo-gateway/src/__tests__/__fixtures__/schemas/accounts.ts
- packages/apollo-gateway/src/__tests__/buildQueryPlan.test.ts
- packages/apollo-gateway/src/__tests__/executeQueryPlan.test.ts
- packages/apollo-gateway/src/executeQueryPlan.ts
The federation spec allows your backends to use any name for their root
types (not just the standard Query/Mutation/Subscription) but the composed
schema will always use the standard names.
Both Apollo-maintained implementations of federated trace
reporting (apollo-engine-reporting and federation-jvm) include the backend's
potentially nonstandard name in the federated traces sent to the gateway. Then
the gateway continues to use those names in the traces it sends to AGM.
For example, one of AGM's own implementing services uses QueryRoot, so traces
produced by the gateway in front of it have `QueryRoot` on the traces despite
that type not actually being part of the composed schema.
The effect is that field stats (on the schema explorer) for all root fields are
empty!
Because normalizing …
> [AS-252] gateway: normalize root operation types in reporting

- packages/apollo-server-core/src/__tests__/runQuery.test.ts
- packages/apollo-server-core/src/requestPipeline.ts
This introduces a deprecation warning which will be emitted once per extension which is defined in the `extensions` parameter of an Apollo Server configuration.
With the introduction of the last missing integration point (`willResolveField`) via the recently landed https://github.com/apollographql/apollo-server/pull/3988, the new [Plugin API] should now have all of the abilities (a super-set, in fact) of the prior `graphql-extensions` API.
Furthermore, rather than being undocumented, rather untested and largely experimental, the new plugin API is considered stable and well-understood in terms of what it aims to support.  Its documentation and API are now considered part of the Apollo Server API and we will do our best to maintain first-class support for it, including the addition of new …
> Add deprecation warnings for `GraphQLExtension` usage.

- packages/apollo-engine-reporting/src/agent.ts
EngineReportingAgent had three different fields all of which were objects keyed
by executableSchemaId. Their key sets were identical but this was not
represented explicitly in the code. In addition, their TypeScript typings were
of the form `{[x: string]: Foo}`, which means TypeScript will inaccurately
assume that looking up *any* key on the object will return an actual Foo and not
undefined.
This refactor merges the three maps into a single map whose value is a
ReportData with three fields. Additionally, it fixes the type to reflect that
not every executableSchemaId is always in the map.
Mostly this just leads to code whose properties (an executableSchemaId may or
may not have these three pieces of data associated with them, and if they do
then all three are there) can be checked at …
> apollo-engine-reporting: fix TypeError on sendReport("unknown")

- CHANGELOG.md
- docs/source/api/apollo-server.md
Update the change log for https://github.com/apollographql/apollo-server/pull/4084 and also add `graphVariants` to the `api/apollo_sever.md`.
> docs+changelog: For #4084 and `graphVariant`.

- packages/apollo-gateway/CHANGELOG.md
- packages/apollo-gateway/src/datasources/RemoteGraphQLDataSource.ts
- packages/apollo-gateway/src/datasources/__tests__/RemoteGraphQLDataSource.test.ts
add: Ability for the RemoteGraphQLDataSource to accept a fetcher implementation, the same as the Gateway (this is part 1 of 2, I think).  The second sane step would be to use the Gateway's `fetcher` when instantiating a RGDS.  That said, you can do that like so without that additional change:
```
const gateway = new ApolloGateway({
...
buildService({ name, url }) {
return new RemoteGraphQLDataSource({ url, fetcher: myFetcherImplementation });
},
});
```
**Note**: I added a new suite and test for the fetcher for sanity, but I'm seeing snapshot failures unrelated to my work here.  Are these test failures expected right now?
> gateway: Support custom `fetcher` for RemoteGraphQLDataSource.

- CHANGELOG.md
- packages/apollo-engine-reporting/src/__tests__/plugin.test.ts
- packages/apollo-engine-reporting/src/agent.ts
- packages/apollo-engine-reporting/src/plugin.ts
Allow enabling schema reporting via setting `APOLLO_SCHEMA_REPORTING` to true.
> Allow schema reporting via environment variable

- packages/apollo-federation/CHANGELOG.md
- packages/apollo-federation/src/composition/types.ts
- packages/apollo-federation/src/composition/utils.ts
- packages/apollo-federation/src/composition/validate/sdl/matchingUnions.ts
- packages/apollo-federation/src/composition/validate/sdl/uniqueFieldDefinitionNames.ts
- packages/apollo-federation/src/composition/validate/sdl/uniqueTypeNamesWithFields.ts
Closes #4223
Per https://github.com/graphql/graphql-js/pull/2621#issuecomment-641927660, `Maybe` is an internal type for graphql-js, which is why it isn't re-exported from index.d.ts. They [moved it](https://github.com/graphql/graphql-js/pull/2621) from `tsutils` to `jsutils` in v15.1.0 which breaks the deep import in apollo-federation.
This PR solves the issue by defining `Maybe` internally rather than importing it from graphql-js.
> Remove dependency on graphql-js internal Maybe type

- packages/apollo-federation/CHANGELOG.md
- packages/apollo-federation/src/composition/__tests__/compose.test.ts
- packages/apollo-federation/src/composition/__tests__/composeAndValidate.test.ts
- packages/apollo-federation/src/composition/__tests__/normalize.test.ts
- packages/apollo-federation/src/composition/normalize.ts
- packages/apollo-federation/src/composition/utils.ts
This PR adds additional normalization to composition inputs in order to prevent duplicate directive errors when constructing the schema.
The oversight from #4209 that's being corrected by this PR is to _also_ remove specified directive definitions (`@deprecated`, `@skip`, `@include`, and `@specifiedBy`) from composition inputs. Failure to remove them during composition results in duplicate definitions and graphql validation errors if they are included in the composition inputs.
> gateway(feat): Allow complete SDL - follow-up to #4209

- packages/apollo-engine-reporting/src/agent.ts
This PR adds startup logging to schema reporting, specifically logging at `INFO` level the options and the `EdgeServerInfo` object.
> schema-reporting: Add startup logging to schema reporting

- packages/apollo-engine-reporting/src/agent.ts
- packages/apollo-engine-reporting/src/reportingOperationTypes.ts
- packages/apollo-engine-reporting/src/schemaReporter.ts
We return an error type with a message in the backend whenever there is a validation error such as invalid userVersion or serverId. 
We want to bubble those up to users through a log line and then stop the reporter since these errors require fixing the input parameters.
> schema-reporting: Handle input errors

- packages/apollo-server-plugin-operation-registry/CHANGELOG.md
- packages/apollo-server-plugin-operation-registry/package.json
- packages/apollo-server-plugin-operation-registry/src/common.ts
CDN in place, should be ready to go.
Not sure what the release process looks like, so went with `NEXT` in `CHANGELOG.md`.
> feat(apollo-server-plugin-operation-registry): use CDN

- packages/apollo-federation/CHANGELOG.md
- packages/apollo-federation/src/composition/validate/postComposition/__tests__/externalUnused.test.ts
- packages/apollo-federation/src/composition/validate/postComposition/externalUnused.ts
One edge case on the validation of externals being used is when concrete
types need to be defined in multiple services for an interface to be
returned as a type for a field. To return an inteface, you need to
defined its possible implementations to let the schema know what all it
could support but you also need to mark its fields as external (at least
the ones you can resolve) so that you don't try and take over ownership
of an entities fields. The current implementation doesn't take this into
account so you fail validation and can't compose the graph
> fix(gateway): Handle `@external` validation edge case for interface implementors

- docs/source/requests.md
`variables` URL parameter should be a URL-encoded, JSON-stringified object.
Verified the behavior with [the `apollo-link` unit tests](https://github.com/apollographql/apollo-link/blob/26f2df99bee15cac9749c0aaab78eb4a19f11ae4/packages/apollo-link-http/src/__tests__/httpLink.ts#L89) and the [`apollo-link` GET implementation](https://github.com/apollographql/apollo-link/blob/26f2df99bee15cac9749c0aaab78eb4a19f11ae4/packages/apollo-link-http/src/httpLink.ts#L222).
> Correct GET example in docs/source/requests.md

- packages/apollo-gateway/src/__tests__/build-query-plan.feature
I Ported some tests from the existing mutation integration tests (from the gateway). I commented which those were and their corresponding tests from the gateway package (since I changed some names slightly) so we could go back later when we port _all_ tests to cucumber and remove them from this one mega-file (per the discussion [here](https://github.com/apollographql/rust/issues/103#issuecomment-659458895) :)
I also added a simple, barebones, single-service test to make sure mutations build a simple fetch node to begin with
One this is merged, I'll update [this PR](https://github.com/apollographql/rust/pull/106) with the new tests
> Add mutation planning tests to cradle suite

- packages/apollo-federation-integration-testsuite/src/fixtures/accounts.ts
- packages/apollo-federation/CHANGELOG.md
- packages/apollo-federation/src/service/__tests__/printComposedSdl.test.ts
- packages/apollo-federation/src/service/__tests__/printFederatedSchema.test.ts
- packages/apollo-federation/src/service/printComposedSdl.ts
- packages/apollo-gateway/src/__tests__/executeQueryPlan.test.ts
- packages/apollo-gateway/src/__tests__/gateway/reporting.test.ts
- packages/apollo-gateway/src/__tests__/integration/boolean.test.ts
- packages/apollo-gateway/src/__tests__/integration/custom-directives.test.ts
- packages/apollo-gateway/src/__tests__/integration/fragments.test.ts
- packages/apollo-gateway/src/__tests__/integration/provides.test.ts
- packages/apollo-gateway/src/__tests__/integration/variables.test.ts
This fix targets a bug in `printComposedSdl` where `@key` directive `fields` args
weren't being printed with reduced whitespace as `@requires` and `@provides` are,
resulting in an invalid / unparseable graphql document.
To reproduce this fix, I first introduced a nested `@key` into our testing fixtures,
which we should have always had at least one of to begin with. The resulting bug
can be seen in the second commit, and then resolved in the third commit.
I've also added a test to `printComposedSdl` to ensure the output is parseable.
> fix(federation): complex `@key`s result in unparseable CSDL

- packages/apollo-federation/CHANGELOG.md
- packages/apollo-federation/src/composition/validate/sdl/__tests__/uniqueTypeNamesWithFields.test.ts
- packages/apollo-federation/src/composition/validate/sdl/uniqueTypeNamesWithFields.ts
Validations for `Kind` mismatch for value types are currently too relaxed.
For example, composition validations currently allow 2 services to define
(separately) a `scalar DateTime` and a `type DateTime { ... }`. The result of
composing these is unexpected - no warning and no concept of which one you
should expect in your schema.
This bug affects `scalar`, `union`, and `enum` types. Reintroducing those types
to the existing validator works well - we can validate against _all_ type
definitions sharing a name if the `Kind` is different.
> fix(federation): Value type validations - unions, scalars, enums

- docs/source/federation/errors.md
- packages/apollo-federation/CHANGELOG.md
- packages/apollo-federation/src/composition/composeAndValidate.ts
- packages/apollo-federation/src/composition/validate/postComposition/__tests__/keysMatchBaseService.test.ts
- packages/apollo-federation/src/composition/validate/postComposition/externalUnused.ts
- packages/apollo-federation/src/composition/validate/postComposition/index.ts
- packages/apollo-federation/src/composition/validate/postComposition/keysMatchBaseService.ts
A few cases of invalid @key directive arrangements are currently possible
with our current validation suite. This commit adds 3 new validations
to ensure that users are informed of these invalid states and block
composition appropriately.
1. Owning type must specify a `@key`
2. Extending types can't specify multiple `@key`s
3. Extending types must use a `@key` specified by the owning type
Additionally:
These invalid arrangements can result in runtime errors when printing CSDL,
nor is it really valid to return an "attempted" print of CSDL, so the result
of `composedSdl` is now `undefined` in the case that there are composition
errors.
> fix(federation): Create new @key validations

- packages/apollo-federation/src/service/__tests__/printComposedSdl.test.ts
- packages/apollo-federation/src/service/printComposedSdl.ts
As an artifact of composition, CSDL should generally be easily consumed by tooling. The existing
format for a `FieldSet` looks like so: `@key(fields: "id")`. Currently, whenever we
make use of that `@key` in existing (related) implementations, we parse the fields argument,
but not before adding a surrounding `{ ... }` set of curly braces to make the string
valid for parsing by the graphql library.
This is fine in JS, but it's an additional step. In Rust (where we're consuming this format
for the first time), modifying strings like this rather than making use of the original string
slice is not nearly as trivial due to lifetimes and ownership. By making this string parseable
as-is, we eliminate a step for anyone using the CSDL format in tooling and eliminate a number of
ergonomic issues …
> feat(gateway): CSDL - make `fields` directive args parseable

- CHANGELOG.md
- packages/apollo-engine-reporting/src/agent.ts
The Apollo API has recently changed such that `reportServerInfo` will now return error for schemas that don't parse or validate.
This PR changes `apollo-engine-reporting` to check in the `EngineReportingAgent` constructor whether override schemas successfully parse and validate, so that we may return early before talking to the Apollo API.
> schema-reporting: Check whether overrideReportedSchema is parsable/valid

- CHANGELOG.md
- packages/apollo-server-core/src/playground.ts
This includes the fix in https://github.com/apollographql/graphql-playground/commit/1c102692bfbb717688827204186c15cb92629b3a
> Update `graphql-playground-react` version.

- packages/apollo-server-core/src/ApolloServer.ts
it's helpful to have an actionable message when something goes wrong
aside from a simple "contact support" if there is a way to achieve
the action that caused the error. in this case, the user is likely
trying to set up Apollo Studio with their service, which they can do
if they follow along with the documentation. this change adds a link
to said documentation to immediately unblock users who run into this
error.
> updates error when schema reporting is used with federation

- CHANGELOG.md
- packages/apollo-server-core/src/plugin/schemaReporting/__tests__/index.test.ts
- packages/apollo-server-core/src/plugin/schemaReporting/index.ts
In accordance with the [feedback here](https://github.com/apollographql/apollo-server/pull/4492#issuecomment-685264551), this PR adds testing for `overrideReportedSchema`. This PR also fixes a bug in the error message where a space was missing.
> schema-reporting: Fix error message whitespace, add tests for overrideReportedSchema

- examples/acephei/README.md
- examples/acephei/gateway/src/index.ts
- examples/acephei/gateway/tsconfig.json
- examples/acephei/services/accounts/src/index.ts
- examples/acephei/services/accounts/tsconfig.json
- examples/acephei/services/books/src/index.ts
- examples/acephei/services/books/tsconfig.json
- examples/acephei/services/products/src/index.ts
- examples/acephei/services/products/tsconfig.json
- examples/acephei/services/reviews/src/index.ts
- examples/acephei/services/reviews/tsconfig.json
- package-lock.json
- package.json
In #4561 we removed `@apollo/federation` and `@apollo/gateway` from the
apollo-server repo. This means that the acephei example doesn't know where to
import them from. Adding them to examples/acephei/package.json led to very
strange errors so let's just add them as top-level dev dependencies.
Additionally, removing `@apollo/federation` seemed to make it so that TypeScript
can't find `apollo-env` any more, but it also seems like maybe the references to
it in the tsconfig.json lines aren't necessary? Not sure what's going on here
but leaving them in led to build errors and removing them didn't.
Finally, update the uses of `engine:` to use the new post-#4453 APIs, and spell
the version "set up" as two words.
> examples/acephei: update for #4561 and #4453

- CHANGELOG.md
- packages/apollo-server-core/src/plugin/usageReporting/legacyOptions.ts
- packages/apollo-server-core/src/plugin/usageReporting/plugin.ts
- packages/apollo-server-plugin-base/src/index.ts
> A few small follow-up changes from v2.18.0

- CHANGELOG.md
- package-lock.json
- packages/apollo-server-azure-functions/package.json
- packages/apollo-server-cloud-functions/package.json
- packages/apollo-server-cloudflare/package.json
- packages/apollo-server-core/package.json
- packages/apollo-server-express/package.json
- packages/apollo-server-fastify/package.json
- packages/apollo-server-hapi/package.json
- packages/apollo-server-integration-testsuite/package.json
- packages/apollo-server-koa/package.json
- packages/apollo-server-lambda/package.json
- packages/apollo-server-micro/package.json
- packages/apollo-server-testing/package.json
- packages/apollo-server/package.json
The intention of these release branches is to gather changes which are intended to land in a specific version (again, indiciated by the subject of this PR).  Release branches allow additional clarity into what is being staged, provide a forum for comments from the community pertaining to the release's stability, and to facilitate the creation of pre-releases (e.g. `alpha`, …
> Release 2.18.2

- docs/source/api/apollo-server.md
- docs/source/api/plugin/inline-trace.md
- docs/source/api/plugin/schema-reporting.md
- docs/source/api/plugin/usage-reporting.md
Along with other edits, pulled in some edits I'd made to EngineReportingOptions that now apply to this plugin instead
> Edits to usage reporting plugin and AS constructor docs

- CHANGELOG.md
- docs/source/api/plugin/usage-reporting.md
- packages/apollo-cache-control/src/__tests__/cacheControlPlugin.test.ts
- packages/apollo-reporting-protobuf/src/reports.proto
- packages/apollo-server-core/src/plugin/traceTreeBuilder.ts
- packages/apollo-server-core/src/plugin/usageReporting/__tests__/plugin.test.ts
- packages/apollo-server-core/src/plugin/usageReporting/__tests__/signatureCache.test.ts
- packages/apollo-server-core/src/plugin/usageReporting/options.ts
- packages/apollo-server-core/src/plugin/usageReporting/plugin.ts
- packages/apollo-server-core/src/utils/pluginTestHarness.ts
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
This PR changes the apollo usage reporting library to use static identifiers for operation documents that are not able to be executed. 
When users of this module receive many un-executable operation documents, such as a non parse-able operation documents, invalid operation documents, or invalid operation names, every operation document is sent to Apollo Studio. This results in a cardinality explosion within Graph Manager. After a few thousand of these invalid operation names / documents are reported, the UI for the customer is borderline unusable due to the cardinality explosion & schema validation reaches a capacity of operations as well.
In general, we want to avoid storing & exposing personal information in Studio, and in current reporting agents, this is also problematic for …
> [BE-615] AER: use a static identifier for GraphQL validation failures

- CHANGELOG.md
- package-lock.json
- packages/apollo-cache-control/src/__tests__/cacheControlPlugin.test.ts
- packages/apollo-reporting-protobuf/src/reports.proto
- packages/apollo-server-core/package.json
- packages/apollo-server-core/src/plugin/usageReporting/__tests__/addTraceRequestStats.test.ts
- packages/apollo-server-core/src/plugin/usageReporting/__tests__/plugin.test.ts
- packages/apollo-server-core/src/plugin/usageReporting/addTraceRequestStats.ts
- packages/apollo-server-core/src/plugin/usageReporting/plugin.ts
- packages/apollo-server-core/src/utils/pluginTestHarness.ts
We would like to inform users about what schema changes are safe, specifically:
- Can an input object field be safely removed?
- Can an input object field's default value be safely removed?
- Can an input object field's type be safely changed to non-nullable? Will this require the addition of a default value?
- Can an enum value be safely removed?
This PR changes `ApolloServerPluginUsageReporting` to report stats on input object fields and enum values, which helps us answer these questions.
Note that this only changes the plugin to look at request data. There are currently a few bugs in the `didResolveField` hook that make getting enum value stats from the response difficult, so I'm going to put off those changes until later (see #4667 for more info).
> usage-reporting: Report stats about input object fields and enum values

- CHANGELOG.md
- packages/apollo-server-express/src/index.ts
This just exports the `ExpressContext` interface from the index rather than the source, as per #3699.
> Export `ExpressContext` from apollo-server-express #3699

- docs/source/data/resolvers.mdx
The docs states that the req object needs to be destructured, when accessed, which is wrong.
> [Doc] Fixed wrong destructuring in context function documentation

- packages/apollo-server-core/src/requestPipeline.ts
When a response to an operation has a large number of fields, the cumulative cost of some of the lifecycle hooks in `graphql-extensions` adds up (more info in #4889). This PR will avoid calling `enableGraphQLExtensions` on a schema when no extensions are in use.
I didn't see any tests relating to this functionality, and tests are passing for me locally. Happy to contribute a test for this if y'all want, will just need some pointers 😄
> Avoid enabling "graphql-extensions" when none are in use (#4889)

- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
- packages/apollo-server-plugin-response-cache/src/ApolloServerPluginResponseCache.ts
@glasser here is a potential fix to consider for https://github.com/apollographql/apollo-server/issues/4886
> await shouldReadFromCache and shouldWriteToCache options

- docs/source/api/apollo-server.md
- docs/source/data/resolvers.mdx
- docs/source/integrations/plugins.md
- packages/apollo-server/src/index.ts
v2.20 has two changes related to `stop`, so this is a good time to actually
document it!
Fixes #4104.
> docs: document ApolloServer.stop, serverWillStop, willResolveField

- .circleci/config.yml
This brings in a safety check preventing us from publishing prereleases to
`latest`.
> circleci: update orb

- docs/source/data/data-sources.md
Adding a link to the Azure CosmosDB data source I wrote based on the MongoDb one listed here.
Any feedback on the datasource itself (which is VERY welcome) should go as [an issue in that repo](https://github.com/andrejpk/apollo-datasource-cosmosdb/issues), please.
> Add cosmosdb-data-source link to datasource docs

- jest.config.base.js
This should hopefully avoid a ton of warnings like
ts-jest[config] (WARN) The option `tsConfig` is deprecated and will be removed in ts-jest 27, use `tsconfig` instead
with no other effects.
> ts-jest: lowercase C

- docs/source/api/apollo-server.md
- docs/source/schema/directives.md
Setting the stage for editing the much larger custom directives article
> Edits to short directives article

- renovate.json5
The existing `force` statement is not necessary now and actually causes a problem by overriding the existing detected `constraints` in `package.json`. This results in `npm@latest` being installed.
> chore: fix npm constraints for Renovate

- CHANGELOG.md
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/__tests__/ApolloServerBase.test.ts
This is a regression in #4981. If the server start process is begun implicitly
by the execution of an operation (ensureStarted inside graphQLServerOptions)
rather than by an explicit start call (or the implicit start calls in
`apollo-server` or the serverless integrations) and startup throws, the
log-and-redact logic wasn't being invoked.
Note that this case doesn't usually happen in practice, because:
- If you're using `apollo-server`, startup is begun in `listen()` before you can
serve requests
- If you're using a serverless framework integration, startup is begun in the
constructor
- If you're using a non-serverless framework integration, the function you call
to connect it to your framework begins startup with `ensureStarting()`
So mostly this just affects the case that you're running …
> Ensure startup errors are redacted even the first time

- CHANGELOG.md
- packages/apollo-server-azure-functions/package.json
- packages/apollo-server-cloud-functions/package.json
- packages/apollo-server-cloudflare/package.json
- packages/apollo-server-core/package.json
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-express/package.json
- packages/apollo-server-fastify/package.json
- packages/apollo-server-hapi/package.json
- packages/apollo-server-integration-testsuite/package.json
- packages/apollo-server-koa/package.json
- packages/apollo-server-lambda/package.json
- packages/apollo-server-micro/package.json
- packages/apollo-server-testing/package.json
- packages/apollo-server/package.json
> Release 2.22.2

- packages/apollo-reporting-protobuf/package.json
- packages/apollo-reporting-protobuf/src/reports.proto
The usage reporting server now serves a copy of reports.proto that can be
fetched by an npm script. This file has some preprocessing done to it including
removing the `package` directive that we formerly had special scripts to
remove. Now we can just run pbjs directly on the checked-in file.
Running it once brings in some changes:
- Changing tabs to spaces (so, please review ignoring whitespace)
- Adding js_use_toArray option to some fields (to be used by #4142)
- Removing some deprecated fields that were never set by the TypeScript
reporting implementation
- Change the encoding of some repeated number fields that aren't used yet in
apollo-server (they will be used by #4142)
> apollo-reporting-protobuf: script to update proto file

- packages/apollo-server-core/src/plugin/usageReporting/defaultSendOperationsAsTrace.ts
Fortunately, it appears that going back at least to Node 8, there's no
difference between passing "utf8", "uft8" (the typo), or no encoding argument,
so there's no bug here. But it's good to remove the typo (and later versions of
`@types/node` consider this to be an error).
> usage reporting: fix typo in Buffer.byteLength argument

- docs/source/api/apollo-server.md
- package-lock.json
- package.json
- packages/apollo-server-hapi/README.md
- packages/apollo-server-hapi/package.json
- packages/apollo-server-hapi/src/ApolloServer.ts
- packages/apollo-server-hapi/src/hapiApollo.ts
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
- packages/apollo-server-micro/package.json
- packages/apollo-server-micro/src/ApolloServer.ts
This is the latest release, and the only release that supports Node 16, so it
will be the minimum version that we test again.
Also:
- Update `@types/hapi__hapi` to latest version. Note that you can import from
`@hapi/hapi` successfully so adjust an import.
- Update `accept` and `boom` to their latest versions, which now have `@hapi/`
prefix; this includes in apollo-server-micro for some reason.
- release-3.0 couldn't run tests after the last merge from main until this
change was made; this revealed a failing test of a newly merged feature due to
a change in a graphql-js error message. Fix that.
This incorporates suggestions from #3273, #3441, and #4254.
> Update Hapi to 20.1.2

- CHANGELOG.md
- packages/apollo-server-core/src/ApolloServer.ts
This field never worked with gateways.
Fixes #5148.
> apollo-server-core: Remove deprecated ApolloServer.schema field

- .circleci/config.yml
- package-lock.json
- package.json
We had not previously done this because it drops support for Node v8.
Part of #5119.
> Upgrade to latest Lerna

- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-errors/src/index.ts
- packages/apollo-server-errors/tsconfig.json
- packages/apollo-server-hapi/src/ApolloServer.ts
- packages/apollo-server-hapi/tsconfig.json
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
- packages/apollo-server-integration-testsuite/src/index.ts
- packages/apollo-server-integration-testsuite/tsconfig.json
- packages/apollo-server-koa/src/ApolloServer.ts
- packages/apollo-server-koa/tsconfig.json
- packages/apollo-server-micro/src/ApolloServer.ts
- packages/apollo-server-micro/src/microApollo.ts
- packages/apollo-server-micro/tsconfig.json
Review individual commits.
Addresses #5170. Does not fully resolve it because there's a few left in hapi and koa that I'll fix as part of #4966.
> Remove most exceptions to TS strict rules

- package-lock.json
- package.json
- packages/apollo-server-express/src/__tests__/ApolloServer.test.ts
- packages/apollo-server-express/src/__tests__/datasource.test.ts
- packages/apollo-server-fastify/src/__tests__/ApolloServer.test.ts
- packages/apollo-server-fastify/src/__tests__/datasource.test.ts
- packages/apollo-server-hapi/src/__tests__/ApolloServer.test.ts
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
- packages/apollo-server-integration-testsuite/src/apolloFetch.ts
- packages/apollo-server-integration-testsuite/src/index.ts
- packages/apollo-server-koa/src/__tests__/ApolloServer.test.ts
- packages/apollo-server-koa/src/__tests__/datasource.test.ts
- packages/apollo-server-micro/src/__tests__/ApolloServer.test.ts
- packages/apollo-server/package.json
- packages/apollo-server/src/__tests__/index.test.ts
- packages/apollo-server/src/__tests__/tsconfig.json
- tsconfig.test.base.json
Our tests use the deprecated `apollo-fetch` package. This depends on an old
version of the `cross-fetch` polyfill package which itself depends on a version
of `node-fetch` with a minor CVE. This makes `npm audit` noisy, which is sad.
There's no real vulnerability from `node-fetch` here since it's only used in
tests, but it would be nice to quiet `npm audit`. Plus, in #5165 we grudgingly
added `"dom"` to the `lib` in `tsconfig.test.base.json` just to support
`apollo-fetch`.
Updating `cross-fetch` in `apollo-fetch` is not enticing because it does pull in
major version bumps of dependent packages; I wouldn't want to release a new
version of a dead project that makes bad changes in some obscure contexts.
But `apollo-fetch` is a pretty simple package. So instead, I just inlined
`apollo-fetch` …
> tests: make `npm audit` happy by inlining apollo-fetch

- CHANGELOG.md
- packages/apollo-server-express/README.md
- packages/apollo-server-express/package.json
Connect is a pretty old JS web framework; most users (other than Meteor) moved
to Express many years ago.
This PR stops advertising apollo-server-express supports Connect.  It doesn't
actively remove the lines in apollo-server-express which exist for Connect
compatibility and it does continue to test against Connect. However, it does
state that we may choose to remove that compatibility within Apollo Server 3.
Fixes #5172.
> apollo-server-express: don't promise to support Connect

- docs/source/api/apollo-server.md
- docs/source/api/plugin/inline-trace.md
- docs/source/api/plugin/schema-reporting.md
- docs/source/api/plugin/usage-reporting.md
- packages/apollo-server-core/src/determineApolloConfig.ts
- packages/apollo-server-core/src/requestPipeline.ts
- packages/apollo-server-core/src/types.ts
- packages/apollo-server-core/src/utils/pluginTestHarness.ts
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
This branch previously had most references to `engine` options and
`ENGINE_SCHEMA_TAG` removed  but the merge from v2.18 restored some of
them.
Fixes #5191.
> Remove some remaining references to "engine"

- packages/apollo-server-core/src/plugin/schemaReporting/schemaReporter.ts
In this PR, `schemaReporter.ts` is changed to fix a bug where calling `stop()` may not prevent functions from being executed in the future via `setTimeout()`. The specific case is when:
1. `sendOneReportAndScheduleNext()` is suspended while waiting on a response from Studio.
2. `stop()` is called and finishes execution.
3. `sendOneReportAndScheduleNext()` resumes execution, and calls `setTimeout()` to schedule another invocation of `sendOneReportAndScheduleNext()` some time in the future (usually 60 seconds).
4. `sendOneReportAndScheduleNext()` executes in the future, but early-returns because it checks `this.isStopped()`.
The end result is Node being prevented from clean shutdown for ~60 seconds in such cases.
> apollo-server-core: Fix delayed shutdown bug in schemaReporter.ts

- CHANGELOG.md
- packages/apollo-server-core/src/plugin/schemaReporting/index.ts
- packages/apollo-server-core/src/plugin/schemaReporting/schemaReporter.ts
- packages/apollo-server-core/src/plugin/usageReporting/options.ts
- packages/apollo-server-core/src/plugin/usageReporting/plugin.ts
We've gotten feedback that it would be nice for customers to have the ability to override the HTTP client for schema reporting. This PR adds that ability under a new `experimental_fetcher` option in `ApolloServerPluginSchemaReporting` (the syntax is similar to `GatewayConfigBase.fetcher`). Since there's not significant logic changes involved, we may also want to just forgo marking it experimental, although I'll leave that decision to the reviewer.
> apollo-server-core: Add option to specify fetcher for schema reporting

- jest.config.base.js
- jest.setup.js
- packages/apollo-server-cloud-functions/src/__tests__/googleCloudApollo.test.ts
- packages/apollo-server-core/src/plugin/usageReporting/__tests__/plugin.test.ts
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
- packages/apollo-server-plugin-operation-registry/src/__tests__/ApolloServerPluginOperationRegistry.test.ts
When `npm test` prints out a million "starting usage reporting" logs, it
gets in the way of finding failing tests. This change stops tests from
logging and makes them fail if they do log. (You can run with
ALLOW_CONSOLE=t locally to disable this behavior.)
> Enforce that tests don't log

- CONTRIBUTING.md
- packages/apollo-server-cloud-functions/README.md
- packages/apollo-server-express/README.md
- packages/apollo-server-fastify/README.md
- packages/apollo-server-hapi/README.md
- packages/apollo-server-koa/README.md
- packages/apollo-server-lambda/README.md
- packages/apollo-server-micro/README.md
- packages/apollo-server/README.md
The Spectrum community referenced by the documentation no longer exists, so it leads to a subsequent link to the new community forum.
This pull request updates all references to Spectrum and links directly to the new community forum.  I tried to create a badge similar to the one previously used specifically for Spectrum.
I hope this helps and let me know if I could provide any further changes!
> docs: replace spectrum with community forum

- CHANGELOG.md
- docs/source/testing/testing.md
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/__tests__/ApolloServerBase.test.ts
- packages/apollo-server-testing/README.md
The `apollo-server-testing` package exports one small function which is
just a tiny wrapper around `server.executeOperation`. The one main
advantage it provides is that you can pass in operations as ASTs rather
than only as strings.
This extra layer doesn't add much value but does require us to update
things in two places (which cross a package barrier and thus can be
installed at skewed versions). So for example when adding the second
argument to `executeOperation` in #4166 I did not bother to add it to
`apollo-server-testing` too. We've also found that users have been
confused by the `createTestClient` API (eg #5111) and that some linters
get confused by the unbound methods it returns (#4724).
So the simplest thing is to just teach people how to use the real
`ApolloServer` method …
> Deprecate apollo-server-testing; allow ASTs for executeOperation

- CHANGELOG.md
- packages/apollo-cache-control/package.json
- packages/apollo-datasource-rest/package.json
- packages/apollo-reporting-protobuf/package.json
- packages/apollo-server-azure-functions/package.json
- packages/apollo-server-cloud-functions/package.json
- packages/apollo-server-cloudflare/package.json
- packages/apollo-server-core/package.json
- packages/apollo-server-core/src/determineApolloConfig.ts
- packages/apollo-server-express/package.json
- packages/apollo-server-fastify/package.json
- packages/apollo-server-hapi/package.json
- packages/apollo-server-integration-testsuite/package.json
- packages/apollo-server-koa/package.json
- packages/apollo-server-lambda/package.json
- packages/apollo-server-micro/package.json
- packages/apollo-server-plugin-base/package.json
- packages/apollo-server-plugin-operation-registry/package.json
- packages/apollo-server-plugin-response-cache/package.json
- packages/apollo-server-testing/package.json
- packages/apollo-server-types/package.json
- packages/apollo-server/package.json
- packages/apollo-tracing/package.json
- packages/graphql-extensions/package.json
> Release 2.25.0

- docs/source/deployment/lambda.md
Adding a quick edit to the Lambda deployment doc with a link to a tutorial using CDK and SST.
Fixes #5235
> Docs: adding link to CDK SST Lambda tutorial

- docs/source/api/plugin/schema-reporting.md
- docs/source/api/plugin/usage-reporting.md
In #5179, we added a new `fetcher` option for the schema reporting plugin and the usage reporting plugin, but forgot to update the docs. This PR updates the docs to include this option.
> docs: Update schema-reporting.md and usage-reporting.md for fetcher option

- packages/apollo-server-core/src/__tests__/errors.test.ts
- packages/apollo-server-core/src/__tests__/runHttpQuery.test.ts
- packages/apollo-server-core/src/index.ts
- packages/apollo-server-core/src/plugin/usageReporting/options.ts
- packages/apollo-server-core/src/plugin/usageReporting/plugin.ts
- packages/apollo-server-core/src/requestPipeline.ts
- packages/apollo-server-core/src/runHttpQuery.ts
- packages/apollo-server-core/src/utils/pluginTestHarness.ts
- packages/apollo-server-errors/src/index.ts
- packages/apollo-server-hapi/src/ApolloServer.ts
- packages/apollo-server-integration-testsuite/src/index.ts
- packages/apollo-server-types/src/index.ts
Previously, almost every case where the request pipeline called
didEncounterErrors, it also called willSendResponse. But there were
several special cases for historical reasons, where a few errors (mostly
relating to APQs) could call didEncounterErrors without calling
willSendResponse. Among other things, this added a bunch of complexity
to the usage reporting plugin.
This PR:
- Changes all APQ-related errors to go through `sendErrorResponse`
instead of `emitErrorAndThrow` (which can be deleted), so
`willSendResponse` is called for them.
- Removes special-case handling of HTTP status code/headers for
persisted query headers in `runHttpQuery.ts` and of `HttpQueryError`s
thrown by `didResolveOperation` callbacks. Instead, we just make sure
to handle some existing `http` fields more …
> Make error handling around APQs more consistent

- packages/apollo-server-core/src/__tests__/errors.test.ts
- packages/apollo-server-errors/src/__tests__/ApolloError.test.ts
- packages/apollo-server-errors/src/index.ts
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
In Apollo Server 2, we had two different ways to specify extensions to
`ApolloError`:
new ApolloError(message, code, {ext1: value})
new ApolloError(message, code, {extensions: {ext1: value}})
and two different ways to read those extensions back:
error.extensions.ext1
error.ext1
This also meant that the extension values showed up twice in the
user-exposed errors list.
In Apollo Server 3, we have just one way to do it: the first line of
each of those pairs. That is, we treat the third argument to the
ApolloError constructor as "the extensions", not "the extensions or
maybe something wrapping the extensions"; and we only put the extensions
on `error.extensions`, not directly on `error` as well. (Note that the
built in `code` and `exception` extensions already only lived on
`extensions` …
> Only one way of dealing with ApolloError extensions

- docs/source/api/plugin/usage-reporting.md
- docs/source/integrations/plugins.md
- docs/source/monitoring/metrics.md
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/__tests__/logger.test.ts
- packages/apollo-server-core/src/__tests__/runQuery.test.ts
- packages/apollo-server-core/src/plugin/cacheControl/__tests__/cacheControlPlugin.test.ts
- packages/apollo-server-core/src/plugin/cacheControl/index.ts
- packages/apollo-server-core/src/plugin/inlineTrace/index.ts
- packages/apollo-server-core/src/plugin/landingPage/graphqlPlayground/index.ts
- packages/apollo-server-core/src/plugin/usageReporting/plugin.ts
- packages/apollo-server-core/src/requestPipeline.ts
- packages/apollo-server-core/src/runHttpQuery.ts
- packages/apollo-server-core/src/types.ts
- packages/apollo-server-core/src/utils/dispatcher.ts
- packages/apollo-server-core/src/utils/pluginTestHarness.ts
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
- packages/apollo-server-integration-testsuite/src/index.ts
- packages/apollo-server-plugin-base/src/index.ts
- packages/apollo-server-plugin-operation-registry/src/ApolloServerPluginOperationRegistry.ts
- packages/apollo-server-plugin-response-cache/src/ApolloServerPluginResponseCache.ts
- packages/apollo-server-types/src/index.ts
Before this PR, some plugin methods were sync, some were async, and some
returned ValueOrPromise (ie, could be sync or async). This led to a lack
of functionality for the never-async methods, confusing inconsistency,
and generally vagueness as to what types things are.
It's 2021: making a function async is as simple as adding the word
`async` and maybe wrapping a return type in `Promise<>`. This PR
simplifies matters by making almost every plugin and gateway method
always async.
The one exception is `willResolveField`, which is called far more than
any other plugin method. We already know that schema instrumentation has
unfortunate performance overhead so adding to it by adding more Promises
to every field doesn't seem like a good idea for now. We reserve the
write to change …
> Make the plugin (and gateway) API almost entirely async

- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/types.ts
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
`GraphQLService` was a confusing name. It's not related to
`GraphQLServiceContext` (which is the type of the argument to
`serverWillStart`) nor is it related to "service", the old name for a
graph in Studio... or "implementing service", the old name for a
subgraph... It's the type of the `gateway` option, so giving it a
gateway name seems reasonable.
But we keep exporting the old name so that we can have builds of
`@apollo/gateway` that work with both AS2 and AS3.
Fixes #4919.
> Rename GraphQLService to GatewayInterface

- packages/apollo-server-azure-functions/src/ApolloServer.ts
- packages/apollo-server-koa/src/ApolloServer.ts
In Apollo Server 2, some integrations apply `ACAO: *` by default, some
reflect the origin by default, and some do no CORS by default.
In AS3, we've already converted `apollo-server-lambda` and
`apollo-server-cloud-functions` into wrappers around
`apollo-server-express`, which means they now have the same default cors
behavior as ASE (`ACAO: *`). This PR changes two more integrations whose
defaults previously were not `ACAO: *`. Previously,
`apollo-server-azure-functions` defaulted to no CORS headers and
`apollo-server-koa` defaulted to reflecting the origin; now they both
default to `access-control-allow-origin: *`.
Now all of the ApolloServer flavors have the same CORS defaults, except
for two packages which don't allow any CORS configuration at all (Micro
and Cloudflare, the two least …
> Make CORS handling more consistent

- CHANGELOG.md
- package-lock.json
- packages/apollo-server-azure-functions/src/__tests__/azureFunctionApollo.test.ts
- packages/apollo-server-azure-functions/src/azureFunctionApollo.ts
- packages/apollo-server-core/src/__tests__/runHttpQuery.test.ts
- packages/apollo-server-core/src/requestPipeline.ts
- packages/apollo-server-core/src/runHttpQuery.ts
- packages/apollo-server-express/src/ApolloServer.ts
- packages/apollo-server-express/src/__tests__/ApolloServer.test.ts
- packages/apollo-server-fastify/src/__tests__/fastifyApollo.test.ts
- packages/apollo-server-hapi/src/__tests__/hapiApollo.test.ts
- packages/apollo-server-integration-testsuite/src/index.ts
- packages/apollo-server-koa/src/__tests__/koaApollo.test.ts
- packages/apollo-server-micro/package.json
- packages/apollo-server-micro/src/ApolloServer.ts
- packages/apollo-server-micro/src/__tests__/microApollo.test.ts
- packages/apollo-server-micro/src/microApollo.ts
There are a lot of reasons that a supposedly GraphQL request might not
make it to requestPipeline: missing body, bad JSON, bad content-type,
etc. Previously, many of these outcomes resulted in 5xx errors despite
them being client errors (which should be 4xx), and their handling was
pretty inconsistent across the integrations.
Part of the confusion was a particular error message which combined "you
seem to have set up your server wrong by not setting up body parsing
properly" with "there was a problem parsing this request". The former is
reasonable to be 500 but the latter is much more likely to be what's
actually happening (you have to actively disable body parsing to make
that happen!). And the recommendation was ungrammatical and
express-specific despite being in apollo-server-core. But …
> Make early errors more consistent and more 4xxy

- CHANGELOG.md
- package-lock.json
- package.json
- packages/apollo-server-express/package.json
- packages/apollo-server-fastify/package.json
- packages/apollo-server-fastify/src/ApolloServer.ts
- packages/apollo-server-koa/package.json
- packages/apollo-server-koa/src/ApolloServer.ts
- packages/apollo-server-micro/package.json
Notably, have any sort of dependency at all on fastify (and
fast-json-stringify!) from `apollo-server-fastify`.
For now I've chosen the latest version for the peer dependencies because
carefully researching "did every API we are using exist in
fastify@3.0.0" seems like unnecessary work, but we can relax these later
upon request.
I think in practice this shouldn't affect how these packages are used
because you should generally already be using your web framework in your
app.
Fixes #5210. See also #5139.
> Make web framework integrations into peer dependencies

- docs/source/performance/apq.md
- package-lock.json
- package.json
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
- packages/apollo-server-integration-testsuite/src/index.ts
Move from the old separate link packages to `@apollo/client`. Note that
this had been partially done in the docs but (a) only in one of two
relevant places and (b) the one place it was changed didn't include the
newly required `sha256` option.
A major motivation for this is that `apollo-link-persisted-queries` has
a peer dependency on `graphql` that doesn't include v15.
> Update APQ docs and tests to Apollo Client 3

- docs/source/deployment/gcp-functions.md
I spoke with some devs/maintainers on Discord about contributing to documentation, and I was directed to deployment docs such as this one for AWS Lambda: https://www.apollographql.com/docs/apollo-server/deployment/lambda/
I thought it would be nice to add documentation for deploying to Google Cloud Functions, and while I was working on deploying a function of my own in researching for this documentation contribution, I found that there already is documentation for this under the npm package apollo-server-cloud-functions:
https://www.npmjs.com/package/apollo-server-cloud-functions
I realized that this documentation hasn't been ported over to this repository / the official Apollo docs, so I figured I would do that. Please let me know if this is a wanted change / if there are any more …
> apollo docs: add documentation for deploying to GCP

- packages/apollo-server-errors/src/__tests__/ApolloError.test.ts
- packages/apollo-server-errors/src/index.ts
As raised [here](https://github.com/apollographql/apollo-server/issues/5307), currently only `UserInputError` supports passing arbitrary data in the extensions argument but the docs imply all ApolloError's support this.
This MR allows passing the extra extensions argument to the underlying constructor.
I did also attempt to apply this to all the Error classes (except persisted ones) but ran into some typescript errors caused by invalid `sendErrorResponse` calls in `apollo-server-core/src/requestPipeline.ts` so I just applied the changes to `ForbiddenError` and `AuthorizationError`.
Perhaps this inconsistency means the docs should also be updated to clarify which error constructors support extensions too but thought I'd get the ball rolling with this fix MR
> fix: extensions argument ignored by ForbiddenError and AuthorizationError

- package-lock.json
- packages/apollo-reporting-protobuf/.npmignore
- packages/apollo-reporting-protobuf/README.md
- packages/apollo-reporting-protobuf/generated/index.d.ts
- packages/apollo-reporting-protobuf/generated/index.js
- packages/apollo-reporting-protobuf/generated/protobuf.d.ts
- packages/apollo-reporting-protobuf/generated/protobuf.js
- packages/apollo-reporting-protobuf/generated/reports.proto
- packages/apollo-reporting-protobuf/package.json
Today, the `marked` project pushed a minor release that broke Node 12
compatibility: https://github.com/markedjs/marked/issues/2106
`marked` is a dep of `jsdoc` which is a dep of the protobufjs CLI.
Unfortunately it turns out that the protobufjs CLI installs dependencies
including `jsdoc` *at runtime*, *unversioned*. Yikes! See `setup`
https://github.com/apollographql/protobuf.js/blob/master/cli/util.js
I tried changing our fork to not do this and move the deps to be dev
deps of this project (see `@apollo/protobufjs@2.0.0`) but that didn't
work out on the first try. So instead, let's just not require the
protobufjs CLI to work on Node 12, and also start saving time by not
constantly regenerating the code in this package. Now code is only
generated manually (`lerna run generate`) and …
> apollo-reporting-protobuf: check in generated code, regenerate manually

- CHANGELOG.md
- docs/source/deployment/azure-functions.md
- docs/source/deployment/gcp-functions.mdx
- docs/source/deployment/netlify.md
- docs/source/integrations/plugins.md
- docs/source/testing/graphql-playground.mdx
- packages/apollo-server-azure-functions/src/__tests__/azureFunctionApollo.test.ts
- packages/apollo-server-cloud-functions/README.md
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/plugin/index.ts
- packages/apollo-server-core/src/plugin/landingPage/default/index.ts
- packages/apollo-server-core/src/plugin/landingPage/graphqlPlayground/index.ts
- packages/apollo-server-express/src/__tests__/ApolloServer.test.ts
- packages/apollo-server-fastify/src/__tests__/ApolloServer.test.ts
- packages/apollo-server-hapi/src/__tests__/ApolloServer.test.ts
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
- packages/apollo-server-koa/src/__tests__/ApolloServer.test.ts
- packages/apollo-server-micro/src/__tests__/ApolloServer.test.ts
- packages/apollo-server/src/__tests__/index.test.ts
As part of reducing Apollo Server's key dependencies on third-party
software (especially retired software) we are changing the default
landing page from GraphQL Playground to a simple splash page welcoming
the user to Apollo Server and providing them with links to docs, to the
Apollo Studio Sandbox, etc. (Sandbox is a new feature that will allow
you to use Explorer and other Studio features without any need for a
Studio account.)
This commit adds a pair of new landing page plugins,
ApolloServerPluginLandingPageLocalDefault and
ApolloServerPluginLandingPageProductionDefault, which serves variants of
this landing page from a CDN.
> Introduce ApolloServerPluginLandingPageDefault

- docs/source/api/apollo-server.md
- docs/source/testing/testing.md
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server/src/__tests__/index.test.ts
It wasn't possible to use executeOperation with `apollo-server` otherwise,
because there's no user-accessible `start` in that package.
> Automatically call start() from the testing executeOperation()

- packages/apollo-datasource-rest/src/RESTDataSource.ts
- packages/apollo-datasource-rest/src/__tests__/RESTDataSource.test.ts
- packages/apollo-server-azure-functions/src/ApolloServer.ts
- packages/apollo-server-cache-redis/src/RedisClusterCache.ts
- packages/apollo-server-cloud-functions/src/ApolloServer.ts
- packages/apollo-server-core/src/__tests__/ApolloServerBase.test.ts
- packages/apollo-server-core/src/__tests__/logger.test.ts
- packages/apollo-server-errors/src/index.ts
- packages/apollo-server-express/src/__tests__/datasource.test.ts
- packages/apollo-server-fastify/src/__tests__/datasource.test.ts
- packages/apollo-server-koa/src/__tests__/datasource.test.ts
- packages/apollo-server-lambda/src/ApolloServer.ts
- packages/apollo-server/src/index.ts
- tsconfig.base.json
This is a nice new feature of TypeScript 4.3. When you're intentionally
overriding a superclass method, you can include `override` so that TS
can verify that you're actually overriding it properly (so that, eg, if
the superclass method gets renamed or its type changes, then an error
will occur). The new noImplicitOverride flag ensures you don't forget to
write `override` when you're overriding. Note that this only affects
subclassing (`extends`), not interface implementation. As far as I can
tell this has no effect on generated `.d.ts` files so it doesn't require
folks using AS to use TS 4.3.
> TS: enable noImplicitOverride, add overrides

- packages/apollo-server-types/src/index.ts
You can mutate it by calling methods like replace or restrict on it, but
let's not overwrite it.
> GraphQLRequestContext.overallCachePolicy should be readonly

- packages/apollo-server-core/src/plugin/landingPage/default/index.ts
Also pass through unknown keys, to make plugin release less tightly
coupled to splash page release.
See https://github.com/apollographql/studio-landing-page/pull/19
We still need to document this (see #5383 and #5373).
Fixes #5381.
> default landing page: support `footer`

- packages/apollo-server-azure-functions/src/ApolloServer.ts
- packages/apollo-server-hapi/README.md
- packages/apollo-server-hapi/src/ApolloServer.ts
- packages/apollo-server-integration-testsuite/src/index.ts
- packages/apollo-server-koa/src/__tests__/koaApollo.test.ts
In #5297 I attempted to make the default CORS behavior consistent across
integrations but did not write tests. Turns out that the Hapi default
behavior was slightly different (reflected `access-control-allow-origin`
rather than `*`), and the Azure Functions behavior was quite different.
This PR adds tests for the default CORS behavior, fixes Hapi to do
`ACAO: *` by default, and makes a few improvements to Azure Functions.
Specifically, for Azure Functions we:
- Stop stressing about what case we'll receive headers in and just
convert all header names to lower-case. Fixes #4178.
- Only apply dynamic `access-control-allow-headers` in OPTIONS (that's
the only time we need it) but do apply it if `cors` is unset. Also set
`vary: access-control-request-headers`, like the `cors` npm package
does. …
> Make default CORS behavior even more consistent

- docs/source/integrations/middleware.md
Not done but think these edits are all ok standalone
> First batch of edits to middleware docs

- docs/source/data/subscriptions.mdx
- docs/source/migration.mdx
> docs: update subscriptions docs for v3

- package-lock.json
While making a minor update in https://github.com/apollographql/apollo-server/pull/5445, I noticed that a clean `npm install` was actually changing the root lock file and figured I'd submit this to clean things up and avoid rouge changes in future PRs.
> Clean package-lock.json

- docs/source/data/data-sources.mdx
- docs/source/data/resolvers.mdx
- docs/source/monitoring/health-checks.md
- docs/source/performance/caching.md
- docs/source/proxy-configuration.md
- docs/source/schema/custom-scalars.md
- docs/source/schema/directives.md
- docs/source/schema/schema.md
- docs/source/schema/unions-interfaces.md
- docs/source/security/terminating-ssl.md
These are not AS3 regressions.
> Improvements to AS3 docs that are not related to differences from AS2

- CHANGELOG.md
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/types.ts
- packages/apollo-server-express/src/ApolloServer.ts
- packages/apollo-server-lambda/src/ApolloServer.ts
- packages/apollo-server-lambda/src/__tests__/ApolloServer.test.ts
- packages/apollo-server/src/index.ts
In AS3 we made apollo-server-lambda inherit from apollo-server-express,
but didn't realize that it also inherited the more precise TS typings on
its constructor that meant that its `context` function would take
Express-specific parameters (rather than the default unconstrained
parameter).
This change makes it easier for any ApolloServer subclass to declare its
context function typing, and updates apollo-server-express and
apollo-server-lambda to do so. The other integrations are left with the
vaguer defaults.
Tests didn't catch this before because they didn't pass a `context`
function *directly* to the Lambda ApolloServer constructor, just via a
function with a looser signature.
Fixes #5480.
> Fix Lambda `context` function typing

- .envrc
Most of the time, `nvm use` is good enough; `nvm install` is only needed the first time you use a given major version on your machine.
Without this, my `nvm` installation attempts to install everything I have defined in my personal configuration's default packages (`~/.nvm/default-packages) each time it's invoked.  (Often!)
> Use `nvm use` instead of `nvm install` if it works.

- CHANGELOG.md
- packages/apollo-server-core/src/plugin/cacheControl/__tests__/dynamicCacheControl.test.ts
- packages/apollo-server-core/src/plugin/cacheControl/index.ts
This also gives resolvers the ability to differentiate between a
`maxAge` that was explicitly set but happens to equal the default
`maxAge` and one that was not explicitly set.
Fixes #5488. Helpful for apollo/federation#870.
> cache control: don't apply default max age until after resolver runs

- packages/apollo-server/README.md
There are chances of someone starting to contribute might not see .nvmrc or possibly may not be even aware about the node version apollo-server uses and proceeds to do `npm install` with node version that might not play well for development so `nvm use` in docs before `npm install` instruction would help the contributing dev to choose the .nvmrc node version before doing `npm install`
> fix(README): add nvm use.

- CHANGELOG.md
- packages/apollo-server-core/src/plugin/cacheControl/index.ts
- packages/apollo-server-types/src/index.ts
This makes `info.cacheControl` available to TypeScript packages that
depend on `apollo-server-types` rather than only being declared deep
inside `apollo-server-core`. Additionally, it gives a name to type used
for `info.cacheControl`.
Intended for use cases like
https://github.com/apollographql/federation/pull/870
We've run into tricky issues with `declare module` before so if this
ends up causing more problems than it's worth, we may revert it.
Also change some more imports to `import type`.
> apollo-server-types: move info.cacheControl 'declare module' here

- CHANGELOG.md
- packages/apollo-server-micro/README.md
- packages/apollo-server-micro/src/ApolloServer.ts
- packages/apollo-server-micro/src/__tests__/ApolloServer.test.ts
ie, by default, serve 404 on root.
This makes it consistent with the other framework integrations. This
also means that if you're using the playground or local default landing
page, you won't manage to load a UI at an URL that doesn't also serve
GraphQL and then get confused when it can't talk to your server.
Also fixes #5513, a doc issue around CORS.
> apollo-server-micro: only serve landing page from graphql path

- docs/source/migration.mdx
The code in step 5 of the [subscription details](https://www.apollographql.com/docs/apollo-server/migration/#reenabling-subscriptions) in the migration guide for Apollo Server 3 currently does not assign the created `SubscriptionServer` instance to a variable, however an implied variable is used (`subscriptionServer.close()`). This PR assigns the created instance to a variable for clarity.
> docs: add variable assignment to subscription server instance

- CHANGELOG.md
- packages/apollo-server-core/src/requestPipeline.ts
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
It handles the unhandled user input errors mentioned in https://github.com/apollographql/apollo-server/issues/5353 and closes https://github.com/apollographql/apollo-server/issues/5353
> feat(UserInputError): handle unhandled errors.

- docs/source/api/plugin/usage-reporting.md
Hi! :smile: A part the documentation for the Usage Reporting Plugin mentions that the protected headers list is "above" a certain table, but it's actually [right below it](https://github.com/apollographql/apollo-server/tree/main/docs/source/api/plugin/usage-reporting.md#L383-L387) (from lines 383 to 387).
Sure hope this change isn't pedantic ᕕ( ᐛ )ᕗ. Just kinda lost a good 20+ minutes trying to find the list and re-reading everything, only to discover that the "above" word was just a typo.
If the patch is not welcomed let me know and I'll close the PR.
Have a nice day! :heart:
> Fix typo: change "above" to "below" in Usage Reporting Plugin docs

- docs/source/migration.mdx
A very small one, the error extensions links to localhost :)
> Fix broken error extensions link in migration docs

- docs/source/monitoring/metrics.md
One of the common questions in Studio's customer support is how the mechanics of the reporting plugin work and how often it sends data to Studio. The plugin is highly configurable, but the configuration isn't very discoverable, so this adds a little blurb about how the plugin works and links to the configuration docs from a more discoverable place.
> Add a blurb about the Usage Plugin's reporting frequency to the docs

- docs/source/data/resolvers.mdx
There is a link called [see the source](https://github.com/graphql/graphql-js/blob/master/src/execution/execute.js#L1147-L1195) in the [Fetching data > Resolvers > Default resolvers](https://www.apollographql.com/docs/apollo-server/data/resolvers/#default-resolvers) section of the docs that is broken.
The current (as of 2021-07-30) correct link to the `defaultFieldResolver` function is https://github.com/graphql/graphql-js/blob/master/src/execution/execute.ts#L999-L1015. This will obviously change as lines are added or removed above this function and linking directly to the current commit hash will lead to stale docs. The mermaid diagram summarizes the function so a direct link to it really isn't needed.
> Remove link to source for defaultFieldResolver function

- docs/source/performance/caching.md
This PR updates the docs page on caching to include directions on how to use the `@cacheControl` directive and AS3's new cache control features with federation. The related changes to federation will be merged into that repo with this PR:
https://github.com/apollographql/federation/pull/870
> Update caching docs to include federation support.

- .prettierignore
- packages/apollo-server-core/src/plugin/schemaReporting/operations.d.ts
We only run graphql-codegen manually, so we missed that the "prettier
all the things" PR made unnecessary changes to this file.
Note that there are real updates that happen as part of this too, due to schema
updates, small codegen upgrades, etc.
> Undo prettier on a generated file

- docs/source/migration.mdx
Options need to be wrapped in a `settings` object. Also removed the casted types in there since I couldn't find their definition, and they don't seem to be necessary anyways
> Fix snippet in migration docs for Playground plugin

- packages/apollo-datasource-rest/src/HTTPCache.ts
- packages/apollo-datasource-rest/src/RESTDataSource.ts
- packages/apollo-server-core/src/plugin/schemaIsFederated.ts
- packages/apollo-server-core/src/utils/dispatcher.ts
It should safe to use `typeof` & `instanceof` on any value including `null` and `undefined`.
Also `isObjectType` accepts any value so no need to prefix it with nullable check.
I spot these places during #5609
> Remove unnecessary boolean checks

- packages/apollo-datasource-rest/src/HTTPCache.ts
- packages/apollo-datasource-rest/src/RESTDataSource.ts
- packages/apollo-server-azure-functions/src/ApolloServer.ts
- packages/apollo-server-caching/src/InMemoryLRUCache.ts
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/plugin/traceTreeBuilder.ts
- packages/apollo-server-core/src/requestPipeline.ts
- packages/apollo-server-core/src/runHttpQuery.ts
- packages/apollo-server-core/src/utils/pluginTestHarness.ts
- packages/apollo-server-errors/src/index.ts
- packages/apollo-server-express/src/__tests__/ApolloServer.test.ts
- packages/apollo-server-fastify/src/__tests__/ApolloServer.test.ts
- packages/apollo-server-hapi/src/__tests__/ApolloServer.test.ts
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
- packages/apollo-server-koa/src/__tests__/ApolloServer.test.ts
- packages/apollo-server-lambda/src/__tests__/ApolloServer.test.ts
- packages/apollo-server-plugin-operation-registry/src/__tests__/ApolloServerPluginOperationRegistry.test.ts
- packages/apollo-server-plugin-response-cache/src/ApolloServerPluginResponseCache.ts
- packages/apollo-server/src/index.ts
Pure mechanical change, shouldn't affect anything 🙏
> Use optional chaining across the entire repo

- CHANGELOG.md
- packages/apollo-server-core/src/ApolloServer.ts
The ApolloServer documentation calls out a setting for `experimental_approximateDocumentStoreMiB` allowing you to set max size of the internal documentStore.
Current code for `initializeDocumentStore`:
```js
private initializeDocumentStore(): InMemoryLRUCache<DocumentNode> {
return new InMemoryLRUCache<DocumentNode>({
// Create ~about~ a 30MiB InMemoryLRUCache.  This is less than precise
// since the technique to calculate the size of a DocumentNode is
// only using JSON.stringify on the DocumentNode (and thus doesn't account
// for unicode characters, etc.), but it should do a reasonable job at
// providing a caching document store for most operations.
maxSize:
Math.pow(2, 20) * (this.experimental_approximateDocumentStoreMiB || 30),
sizeCalculator: approximateObjectSize,
});
}
```
That …
> Fixes experimental_approximateDocumentStoreMiB

- CHANGELOG.md
- docs/source/api/apollo-server.md
- packages/apollo-server-core/src/ApolloServer.ts
`stop()` is not designed to work properly if `start()` has not
previously succeeded (there's an XXX comment about this), and #5635 is
going to make early `stop()` calls into a hard error. This change
ensures that the signal handler won't cause that error to show up.
Also, serverless integrations don't use the same sort of process-based
shutdown as other environments (and you don't call `start` or `listen`
yourself), so registering these signal handlers isn't a great default.
(They start "listening" before the ApolloServer is started, so it would
be weird if after this change the signal handling depended on whether or
not a request had been processed or not.) Make stopOnTerminationSignals
> apollo-server-core: register signal handlers later and not on serverless

- packages/apollo-server-hapi/src/__tests__/ApolloServer.test.ts
These tests were constantly failing on my local machine since I have a custom
hostname but macOS doesn't resolve it to localhost by default.
Used `createServer` instead since it has way better heuristics for figuring out the correct URI.
> apollo-server-hapi: Switch remaining tests to use 'createServer' wrapper

- docs/source/api/apollo-server.md
Corrects mistake about `validationRules` in the docs so that it says it's an array instead of an object.
Resolves issue #5656.
> Change validationRules docs from object to array

- docs/static/_redirects
This branch updates our `_redirects` file to remove the `/docs/apollo-server` prefix from the `from` paths. This is necessary for our redirects to work since the change we made to the way docs sites are deployed in https://github.com/apollographql/apollo-server/pull/5632
> Remove path prefixes for server docs redirects

- docs/source/data/data-sources.mdx
- packages/apollo-datasource-rest/README.md
The Apollo Server data source documentation has code samples that contain URL injection vulnerabilities. 
When user (e.g. query) input is concatenated into a URL without being encoded, an attacker can manipulate server-side requests to unintended targets. This type of vulnerability is sometimes referred to as Web Parameter Tampering (https://www.owasp.org/index.php/Web_Parameter_Tampering) and also can be thought of as a limited form of Server Side Request Forgery / SSRF (https://www.owasp.org/index.php/Server_Side_Request_Forgery).
In the samples, raw query input is used to concatenate URLs used to invoke backend REST APIs. If an attacker passes input that contains URL control characters they can modify the URL being accessed in a way the GraphQL Server does not expect, potentially …
> Fix URL injection vulnerabilities in documentation

- docs/source/schema/unions-interfaces.md
Hi Guys,
I think that in the last commit (https://github.com/apollographql/apollo-server/pull/5420/commits/5b50f2cab7d225c00bb0c90a963fcd9310d17e15) of the related file docs/source/schema/unions-interfaces.md, not all occurrences of "schoolBooks" were replaced.
Thanks
> Corrects errors in the documentation of unions and interfaces

- CHANGELOG.md
- package-lock.json
- packages/apollo-server-koa/package.json
Peer dependencies should be more lax, unless there is a very good reason to block consumers from upgrading that peer dependency. There is no such reason here.
This conflict is introduced by having the version maintained and pinned through Renovate. This is very counter-productive. See #5749
> fix: Pinned koa peer dependency

- CHANGELOG.md
- packages/apollo-server-fastify/src/ApolloServer.ts
- packages/apollo-server-fastify/src/index.ts
This way a `context` function provided to `new ApolloServer` is typed correctly.
I copied this approach from the Express plugin: https://github.com/apollographql/apollo-server/blob/48d3ab205afc682d5304c7c1cae349e0e2a1ffd5/packages/apollo-server-express/src/ApolloServer.ts#L37-L56
> feat: type Fastify context properly

- CHANGELOG.md
- packages/apollo-server-core/src/utils/schemaManager.ts
Running the schema-derived data provider in `SchemaManager.ts` can be expensive. Currently, `SchemaManager` computes this twice for non-gateway modes of operation:
1. Once during `SchemaManager` construction (as the caller expects errors to be caught early here).
2. Once during `SchemaManager.start()` (as we naively call it within `SchemaManager.processSchemaLoadOrUpdateEvent()`).
This PR:
- Changes `SchemaManager.processSchemaLoadOrUpdateEvent()` to accept an optional `schemaDerivedData` argument, which (if provided) causes it to store that and skip calling the schema-derived data provider.
- Changes the constructor to store the results of calling the schema-derived-data provider in mode-specific state, so that it may be passed to `start()`.
Fixes #5729 .
> apollo-server-core: Stop computing schema-derived data twice for non-gateway modes of operation

- CHANGELOG.md
- packages/apollo-datasource-rest/src/RESTDataSource.ts
- packages/apollo-datasource-rest/src/__tests__/RESTDataSource.test.ts
This commit addresses issue [5724](https://github.com/apollographql/apollo-server/issues/5724).  It is a simple change to treat all content types ending with +json similar to how all content types beginning with application/json are automatically parsed as JSON.  The helps cover some other common types of JSON types beyond the original hard coded exception.
> Resolve Issue #5724: parse all content types ending with +json as json in rest data source

- CHANGELOG.md
- docs/source/api/apollo-server.md
- packages/apollo-datasource-rest/src/RESTDataSource.ts
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/__tests__/runHttpQuery.test.ts
- packages/apollo-server-core/src/graphqlOptions.ts
- packages/apollo-server-core/src/runHttpQuery.ts
- packages/apollo-server-core/src/types.ts
- packages/apollo-server-express/src/__tests__/ApolloServer.test.ts
- packages/apollo-server-fastify/src/__tests__/ApolloServer.test.ts
- packages/apollo-server-hapi/src/__tests__/ApolloServer.test.ts
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
- packages/apollo-server-koa/src/__tests__/ApolloServer.test.ts
- packages/apollo-server-micro/src/__tests__/ApolloServer.test.ts
- packages/apollo-server/src/__tests__/index.test.ts
Removes access to `process.env` from hot code paths. My understanding on this is admittedly somewhat limited, but there is a performance penalty that occurs when accessing `process.env` (or perhaps just `process`) because Node needs to drop down to C which is (apparently) quite expensive. The penalty wouldn't be noticeable as a one time thing, but for things that are running often at scale, it can really add up.
I _vaguely_ recall this being an issue in React SSR early on... remember reading something about this being discovered and remedied, leading to immediate perf improvements. Can't find the article about it... and now I'm wondering if my memory is failing me... but I recall this being the first thing that made me aware of the process.env penalty.
(Edit: I think it was this: …
> Remove access to process.env from hot code paths

- CHANGELOG.md
- docs/source/api/apollo-server.md
- packages/apollo-server-caching/src/InMemoryLRUCache.ts
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/__tests__/documentStore.test.ts
- packages/apollo-server-core/src/__tests__/runQuery.test.ts
- packages/apollo-server-core/src/graphqlOptions.ts
- packages/apollo-server-core/src/requestPipeline.ts
- packages/apollo-server-core/src/types.ts
This was discussed in https://github.com/apollographql/apollo-server/discussions/5634 . I wasn't sure if you wanted me to revoke the `experimental_approximateDocumentStoreMiB` or, since that would become a breaking change, if you wanted to keep it out of this PR. I kept it, so that it functions exactly as it did prior. If we are going to keep it, we should probably add a test to the documentStore test file to verify it's actually passing in correctly.
Couple key things I want to call out:
* Added a document entry, it's a little verbose, but this feature doesn't seem to warrant it's own page, and it really should be rarely used, so it seems good enough.
* I added a `DocumentStore` to `types.ts` this way we aren't re-specifying the contents of `documentStore` across many different files. …
> Disc 5634 pluggable document store

- docs/source/api/plugin/drain-http-server.md
The `http` import in the example was missing, generating an error.
> docs: Update Import for ApolloServerPluginDrainHttpServer

- CHANGELOG.md
- docs/source/api/apollo-server.mdx
- docs/source/requests.md
- packages/apollo-server-core/src/__tests__/runHttpQuery.test.ts
- packages/apollo-server-core/src/graphqlOptions.ts
- packages/apollo-server-core/src/runHttpQuery.ts
- packages/apollo-server-core/src/types.ts
- packages/apollo-server-integration-testsuite/src/index.ts
As per https://github.com/apollographql/apollo-server/issues/5686, add the ability to opt out of batches queries in a single HTTP request. This defaults to true for backwards compatibility reasons.
This new feature has a few benefits such as performance as the response in a batch would be bounded by the slowest query. It can also be used as an increased security measure like preventing bad actors from using batching to validate 2FA pin codes by using different permutations.
> Feature add allow batched http requests flag

- CHANGELOG.md
- packages/apollo-server-azure-functions/package.json
- packages/apollo-server-cloud-functions/package.json
- packages/apollo-server-cloudflare/package.json
- packages/apollo-server-core/package.json
- packages/apollo-server-errors/package.json
- packages/apollo-server-errors/src/__tests__/ApolloError.test.ts
- packages/apollo-server-errors/src/index.ts
- packages/apollo-server-express/package.json
- packages/apollo-server-fastify/package.json
- packages/apollo-server-hapi/package.json
- packages/apollo-server-koa/package.json
- packages/apollo-server-lambda/package.json
- packages/apollo-server-plugin-base/package.json
- packages/apollo-server-plugin-operation-registry/package.json
- packages/apollo-server-plugin-response-cache/package.json
- packages/apollo-server-types/package.json
- packages/apollo-server/package.json
The only change required is in `apollo-server-errors`.
Alternative to #5844
> Support for graphql@16

- CHANGELOG.md
- package-lock.json
- packages/apollo-datasource-rest/package.json
- packages/apollo-datasource/package.json
- packages/apollo-reporting-protobuf/package.json
- packages/apollo-server-azure-functions/package.json
- packages/apollo-server-cache-memcached/package.json
- packages/apollo-server-cache-redis/package.json
- packages/apollo-server-caching/package.json
- packages/apollo-server-cloud-functions/package.json
- packages/apollo-server-cloudflare/package.json
- packages/apollo-server-core/package.json
- packages/apollo-server-env/package.json
- packages/apollo-server-errors/package.json
- packages/apollo-server-express/package.json
- packages/apollo-server-fastify/package.json
- packages/apollo-server-hapi/package.json
- packages/apollo-server-integration-testsuite/package.json
- packages/apollo-server-koa/package.json
- packages/apollo-server-lambda/package.json
- packages/apollo-server-micro/package.json
- packages/apollo-server-plugin-base/package.json
- packages/apollo-server-plugin-operation-registry/package.json
- packages/apollo-server-plugin-response-cache/package.json
- packages/apollo-server-types/package.json
- packages/apollo-server/package.json
> Release 3.5.0

- docs/source/integrations/plugins-event-reference.md
`serverWillStop` section includes the sentence "When your `serverWillStart` handler is called, Apollo Server is in a state where it will no longer start to execute new GraphQL operations", which appears incorrect.
> Apparent typo in serverWillStop docs

- CHANGELOG.md
- packages/apollo-reporting-protobuf/generated/protobuf.d.ts
- packages/apollo-reporting-protobuf/generated/protobuf.js
- packages/apollo-reporting-protobuf/generated/reports.proto
- packages/apollo-reporting-protobuf/src/reports.proto
- packages/apollo-server-core/src/plugin/schemaReporting/operations.d.ts
- packages/apollo-server-core/src/plugin/usageReporting/__tests__/__snapshots__/stats.test.ts.snap
- packages/apollo-server-core/src/plugin/usageReporting/__tests__/stats.test.ts
- packages/apollo-server-core/src/plugin/usageReporting/options.ts
- packages/apollo-server-core/src/plugin/usageReporting/plugin.ts
- packages/apollo-server-core/src/plugin/usageReporting/stats.ts
See CHANGELOG for more details.
Also rerun GraphQL codegen (to reduce the number of instances of
"clientReferenceId" in the repo).
> usage reporting: remove client reference ID

- docs/source/testing/build-run-queries.mdx
See https://github.com/apollographql/apollo-server/issues/5341#issuecomment-973148345 — the previous wording could imply that we were actively recommending migration to GraphiQL (which isn't simple as we do not know of a landing page plugin for GraphiQL yet).
> docs: clarify wording around playground

- .circleci/config.yml
Node 17 has been the "Current" (though not LTS) release for a couple of
months. CI appears to pass against it, so let's keep it that way!
> CI: Test against NodeJS 17

- packages/apollo-server-core/src/plugin/usageReporting/__tests__/__snapshots__/defaultUsageReportingSignature.test.ts.snap
- packages/apollo-server-core/src/plugin/usageReporting/__tests__/defaultUsageReportingSignature.test.ts
In #5955 we inlined defaultUsageReportingSignature into
apollo-server-core from apollo-graphql but left its tests behind. This
brings the tests over too. The tests themselves including snapshots are
verbatim from apollo-graphql.
> apollo-server-core: copy signature tests left out of #5955

- docs/source/api/plugin/usage-reporting.md
This is currently a dead link but will be fixed before 3.6 is
released.
> docs: add link from fieldLevelInstrumentation to Studio docs

- docs/source/security/authentication.md
I changed the verb "transform" to the noun "transformation" in the comments of [the data model authorization example](https://www.apollographql.com/docs/apollo-server/security/authentication/#in-data-models) as the noun is grammatically correct here.
> Fix grammar error

- packages/apollo-server-core/src/plugin/usageReporting/plugin.ts
Fixes #5980
Remove reference to now removed dependency `apollo-graphql` from usageReporting plugin, use inlined `defaultUsageReportingSignature` instead.
> apollo-server-core(usageReporting): remove reference to apollo-graphql

- CHANGELOG.md
- package-lock.json
- packages/apollo-server-fastify/package.json
- packages/apollo-server-fastify/src/ApolloServer.ts
This package was being used only to stringify two small constant
objects. It has a major version update available and rather than
evaluate the CHANGELOG, we might as well just not use it.
(Honestly I think it would be fine to just use JSON.stringify here; I
don't see any justification in #1971 for why this particular use case
requires a faster stringification than all the other JSON
stringification we do in Apollo Server. But just in case this matters to
anybody, I went with the fastest possible way of converting a constant
object to string.)
This should replace #5985.
> apollo-server-fastify: drop dependency on `fast-json-stringify`

- docs/source/migration.mdx
We told folks who didn't want to update their schemaDirectives to use
graphql-tools directly, but graphql-tools has removed that old feature.
So now we should tell people to either pin an old version of
graphql-tools or rewrite to the new mapSchema API.
Fixes #5996.
> docs: update migration advice around schemaDirectives

- CHANGELOG.md
- docs/source/api/plugin/landing-pages.md
- packages/apollo-server-core/src/plugin/landingPage/default/index.ts
This PR is the final code change part of NEBULA-701 - updating apollo server to accept the `includeCookies` option from `LandingPageConfig`.
[Studio-ui PR with more context](https://github.com/mdg-private/studio-ui/pull/5554#issue-1093945527)
[JIRA](https://apollographql.atlassian.net/browse/NEBULA-701)
> NEBULA-701 Add includeCookies field to apollo-server

- docs/source/api/apollo-server.mdx
- docs/source/testing/mocking.md
Took a pass at editing the `Mocking` article. Didn't change any of the code, just tweaked and elaborated on the text.
> Docs: Mocking Page edits

- CHANGELOG.md
- packages/apollo-server-core/src/requestPipeline.ts
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
The original way handle required or non-nullable UserInputError is not considering List Type variable. It returns `INTERNAL_SERVER_ERROR` instead of `BAD_USER_INPUT`
The result of query
```graphql
query ( x: [String]!) {
hello(x:$x)
}
```
is
```js
{
errors: [
{
message: "Variable "$x" of required type "[String]!" was not provided.",
extensions: {
code: "INTERNAL_SERVER_ERROR"
}
}
]
}
```
should be
```js
{
errors: [
{
message: "Variable "$x" of required type "[String]!" was not provided.",
extensions: {
code: "BAD_USER_INPUT"
}
}
]
}
```
replace `message.startWith` and check node type with `message.match` to handle List type and single variable
> Invalid non-nullable or required List Type variable should return UserInputError

- package.json
Previously, if you had an empty-ish directory under `packages` (which
could easily happen when switching branches) between major versions,
`jest` would treat that empty-ish directory as a project without a config
file and throw an error.
> jest: only include projects with jest.config.js

- cspell-dict.txt
- docs/source/performance/apq.md
This alters the format of the `curl` commands we provide for testing/demonstrating APQ usage to URL encode the parameters when sending `GET` requests.
In particular, this commit choses to adopt [`curl`'s `--data-urlencode`] patterns rather than relying on un-URL-encoded passing of values.  While the documentation examples do not use any reserved query-string characters which could be mis-interpreted as a delimiter (i.e., `&`, `=`, etc.) — and thus can get away without it (per [RFC 3986 3.4])  — it likely creates a better precedent to do so.  Much in the same way as it's conceivable that some parameters in a URL don't need [`encodeURIComponent`] 
[`curl`'s `--data-urlencode`]: https://curl.se/docs/manpage.html#--data-urlencode
[RFC 3986 3.4]: …
> docs: Use URL encoding pattern in APQ examples

- docs/source/api/apollo-server.mdx
- docs/source/testing/testing.md
- docs/source/testing/testing.mdx
Did a first pass at editing the testing page!
I added:
1.  two new code examples to try and simplify the core ideas of testing
2. the `executeOperation` method to the main ApolloServer API Reference page 
Thank you for any and all feedback! ⭐
> Testing Article Edit and Add Examples

- CHANGELOG.md
- packages/apollo-server-core/src/plugin/traceTreeBuilder.ts
- packages/apollo-server-core/src/plugin/usageReporting/__tests__/plugin.test.ts
- packages/apollo-server-core/src/plugin/usageReporting/plugin.ts
In #5963 we added `!!metrics.captureTraces` to the condition for
considering sending an operation as a trace to Studio. This makes sense
for operations which start to execute (don't send something as a trace
if we didn't record a trace for it!) but if the reason `captureTraces`
is unset is because we never successfully resolved an operation, it
still can be interesting to send a trace, for the sake of the Errors
page.  So we allow sending traces for unexecutable operations (though it
still goes through our standard sampling algorithm).
In order to make sure the recently added Trace.fieldExecutionWeight is
set to the default value of 1 in this case, we set it when initially
creating the Trace rather than in didResolveOperation.
Fixes #6193.
> usage reporting: allow sending traces for unexecutable operations

- docs/source/data/subscriptions.mdx
> docs(subscription): unify authentication param naming

- docs/source/performance/caching.md
Making sure the language in the [Apollo Server docs](https://www.apollographql.com/docs/apollo-server/performance/caching/#using-with-federation) is the same as our [Apollo Federation docs](https://www.apollographql.com/docs/federation/performance/caching/).
> Docs: Update reference to `@apollo/federation` to use `@apollo/subgraph`

- CHANGELOG.md
- docs/source/api/apollo-server.mdx
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/__tests__/documentStore.test.ts
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
Apollo Server 3.4.0 introduced a new `documentStore` constructor option
(replacing the `experimental_approximateDocumentStoreMiB` option) which
allows you to customize an internal cache used by ApolloServer to
memoize the results of parsing and validating GraphQL operations. When
this option was combined with the `gateway` option, it was possible for
Apollo Server to attempt to execute invalid GraphQL operations.
Specifically, if a server processed an operation and then its schema was
updated with a change that made that operation no longer valid, the
server could still attempt to execute the operation again without
re-validating it against the new schema. (The problem only lasts until
the server is restarted.)
This release changes the semantics of the `documentStore` option so that
a …
> security: fix missing validation with `documentStore` + `gateway`

- CHANGELOG.md
- package-lock.json
- package.json
- packages/apollo-server-core/package.json
> Update to latest `@apollographql/apollo-tools` package

- CHANGELOG.md
- packages/apollo-server-azure-functions/package.json
- packages/apollo-server-cloud-functions/package.json
- packages/apollo-server-cloudflare/package.json
- packages/apollo-server-core/package.json
- packages/apollo-server-express/package.json
- packages/apollo-server-fastify/package.json
- packages/apollo-server-hapi/package.json
- packages/apollo-server-integration-testsuite/package.json
- packages/apollo-server-koa/package.json
- packages/apollo-server-lambda/package.json
- packages/apollo-server-micro/package.json
- packages/apollo-server/package.json
> Release 3.6.7

- docs/source/deployment/heroku.md
`If you don't provide a Procfile, attempts to...`
changed to
`If you don't provide a Procfile, Heroku attempts to...`
> Minor grammatical fix

- docs/source/integrations/middleware.mdx
This PR will remove the leading `$`'s from the `npm install`-lines, because they're not needed and reducing the usefulness of the "copy"-button. Also it will be more consistent because sometimes the leading `$`'s were there and sometimes not.
> Removes leading $ in install commands

- package-lock.json
- packages/server/package.json
- packages/server/src/__tests__/integration/apolloServerTests.ts
- packages/server/src/plugin/schemaReporting/index.ts
- packages/server/src/plugin/schemaReporting/schemaReporter.ts
- packages/server/src/plugin/usageReporting/options.ts
- packages/server/src/plugin/usageReporting/plugin.ts
The usage reporting and schema reporting plugins talk to Apollo servers
using (by default) `node-fetch`, but they provide `fetcher` options to
let you customize the fetching.
However, some fetch implementations like `make-fetch-happen` v10 didn't
actually work, because they don't know how to detect `Request`/`Headers`
objects provided by `node-fetch`.  In addition, `make-fetch-happen`'s
TypeScript types aren't quite compatible with `typeof fetch` from
`node-fetch`.
We've created a new `@apollo/utils.fetcher` which defines a more minimal
fetch API as `Fetcher`; both `node-fetch` and `make-fetch-happen` fit
this typing. We are careful now to only pass portable options to our
fetch call (which are the only ones allowed by our new `Fetcher` type).
Specifically, we don't pass …
> Improve ability to override fetcher; remove requestAgent option

- .circleci/config.yml
- package-lock.json
- packages/server/package.json
- packages/server/src/__tests__/integration/apolloServerTests.ts
Context: https://github.com/nodejs/node/pull/41431#discussion_r841272416
> test: fix failing integration tests on node@18

- package-lock.json
- packages/apollo-server-fastify/package.json
- packages/apollo-server-fastify/src/ApolloServer.ts
- packages/apollo-server-koa/src/ApolloServer.ts
The official plugins of `fastify` are now scoped, and the old names are deprecated. There should be no other breaking changes.
> fix(fastify): use scoped modules

- CHANGELOG.md
- package-lock.json
- packages/apollo-datasource-rest/package.json
- packages/apollo-datasource-rest/src/RESTDataSource.ts
- packages/apollo-datasource-rest/tsconfig.json
- packages/apollo-server-types/package.json
- packages/apollo-server/package.json
Some packages were depending on other packages that were only declared
as transitive dependencies. Clean this up by adding appropriate
dependencies (or in one case, just re-declaring ValueOrPromise and
dropping the apollo-server-types dependency).
The peer dep one is a bit funny.  But "Y has a peer dep on Z" means
"when you install Y you need to install Z", and so if X depends on Y,
then when you install X you need to install Z... so sure, that means X
needs to have a peer dep on Z too, I guess.
Fixes #6389.
Fixes #6390.
Fixes #6391.
Fixes #6392.
> Fix a bundle of dependency issues

- docs/source/requests.md
Just improving a bit consistency about using spaces between the colon and variable type
> POST request example: consistent spacing for variable type

- packages/server/src/ApolloServer.ts
- packages/server/src/__tests__/ApolloServer.test.ts
- packages/server/src/__tests__/integration/apolloServerTests.ts
- packages/server/src/types.ts
- packages/server/src/utils/schemaManager.ts
Removes cruft for supporting old versions (`< 0.35.0`) of the gateway via a deprecated update mechanism
**BREAKING**
* Stop exporting types: `SchemaChangeCallback`, `GraphQLService` (redundant, use `GatewayInterface` instead)
* Drop support for gateway versions below v0.35.0 (require `onSchemaLoadOrUpdate`) see: https://github.com/apollographql/federation/blob/main/gateway-js/CHANGELOG.md#v0350
Fixes #6195
> Remove support for old gateway versions (`version-4`)

- CHANGELOG.md
- cspell-dict.txt
- package-lock.json
- package.json
- packages/server/package.json
- packages/server/src/ApolloServer.ts
- packages/server/src/__tests__/integration/apolloServerTests.ts
- packages/server/src/__tests__/integration/httpServerTests.ts
- packages/server/src/preventCsrf.ts
- packages/server/src/types.ts
Unlike in AS3, this feature is on by default (and doesn't require
editing every framework integration).
Because it's on by default, we had to change a handful of tests to pass
apollo-require-preflight.
> CSRF prevention (from Apollo Server 3.7)

- docs/source/deployment/lambda.md
The docs are missing examples of how you can test your code locally before deploy. There is a certain structure to the HTTP request format so laying that out in the example can be helpful to get up and running.
https://www.serverless.com/framework/docs/providers/aws/cli-reference/invoke-local#local-function-invocation-with-a-data-file
> docs: update with instructions on how to run lambda locally

- cspell-dict.txt
- renovate.json5
See #6372, which in fact fails on Node v12.
> renovate: pin @hapi/boom

- docs/source/performance/caching.md
While Apollo's caching system is straight forward in the docs. Many people need to specify custom HTTP response headers to enable edge caching in their CDNs. For example in Vercel, it is recommended to to set `max-age=0` and use `s-maxage=$` instead. Apollo supports such configuration. But it's not clearly mentioned anywhere in docs. This PR adds a small paragraph and a code example in `docs/source/performance/caching.md` that explains achieving such a configuration in apollo-server.
> documentation: Mention custom cache headers with an example

- cspell-dict.txt
- packages/apollo-server-core/src/plugin/index.ts
- packages/apollo-server-core/src/plugin/landingPage/default/index.ts
- packages/apollo-server-core/src/plugin/landingPage/default/types.ts
[JIRA](https://apollographql.atlassian.net/browse/NEBULA-948)
[Decision Record 53
](https://apollographql.quip.com/Ri1kAEJ7zDFT/053-Decision-Record-embedded-Apollo-Sandbox-in-AS4)
**Context**
We are exposing embedded options on the Apollo Server default landing page configs. There is one flag `embed` that controls whether or not the default landing page is embedded. If the user is running on prod, and `embed` is truthy and there is a graphRef provided, the embedded Explorer will be rendered. If the user is running on local, or no graphRef is provided, and `embed` is true, the embedded Sandbox should be rendered. 
The code that is being fetched in this landing page is from a cdn bucket serving built files from this repo https://github.com/apollographql/embeddable-explorer. 
**This PR** …
> Embedded Landing Pages 

- packages/server/src/ApolloServer.ts
- packages/server/src/__tests__/runQuery.test.ts
- packages/server/src/externalTypes/requestPipeline.ts
- packages/server/src/index.ts
- packages/server/src/requestPipeline.ts
- packages/server/src/runHttpQuery.ts
There's a particular check for HttpQueryError that was added in #5287
just to make the "no mutations over GET" plugin work. But given that
that plugin is completely unconfigurable, it might as well just be part
of the request pipeline rather than a plugin. Doing that lets us
simplify sendErrorResponse to no longer have to know about
HttpQueryError for just that use case.
While we're at it, fixed a bug (which exists in AS3) where GET requests
with an invalid operation name threw a ReferenceError in the
checkOperationPlugin instead of the correct error. That's because the
type `GraphQLRequestContextDidResolveOperation` was incorrect:
`operation` is not in fact required at that point. Fix the type (and put
the appropriate `?` in `operation?.operation` in the new code location).
Also remove …
> Stop using HttpQueryError in requestPipeline

- packages/server/src/ApolloServer.ts
- packages/server/src/__tests__/ApolloServer.test.ts
- packages/server/src/__tests__/documentStore.test.ts
- packages/server/src/__tests__/integration/apolloServerTests.ts
- packages/server/src/__tests__/integration/httpServerTests.ts
- packages/server/src/__tests__/plugin/cacheControl/collectCacheControlHints.ts
- packages/server/src/__tests__/plugin/usageReporting/plugin.test.ts
- packages/server/src/__tests__/runQuery.test.ts
- packages/server/src/externalTypes/graphql.ts
- packages/server/src/externalTypes/http.ts
- packages/server/src/externalTypes/index.ts
- packages/server/src/externalTypes/requestPipeline.ts
- packages/server/src/plugin/cacheControl/index.ts
- packages/server/src/plugin/inlineTrace/index.ts
- packages/server/src/requestPipeline.ts
- packages/server/src/runHttpQuery.ts
- packages/server/src/types.ts
Previously, the GraphQLResponse type contains the fields that are
returned in the body of a GraphQL response, plus an `http` field with
statusCode and headers.
Now, we put the body fields (the "result") inside a `result` field next
to `http`. This lets us just use the graphql-js ExecutionResult and
FormattedExecutionResult types in a bunch of places as well. Among other
things, this set us up for an incremental delivery world where sometimes
there's an async iterator of these results instead of a single result.
Changes vs v3 include:
- The `GraphQLResponse` type as seen on plugin
`GraphQLRequestContext.response` has most of its fields move to a
`result` sub-object. Also, the types of values in the objects under
`data` and `extensions` become `unknown` instead of `any` (so
consumers may …
> Refactor GraphQLResponse type; drop formatResponse

- packages/server/src/ApolloServer.ts
- packages/server/src/__tests__/ApolloServer.test.ts
- packages/server/src/__tests__/express/integration.test.ts
- packages/server/src/__tests__/express/integrationServerless.test.ts
- packages/server/src/__tests__/integration/apolloServerTests.ts
- packages/server/src/__tests__/integration/httpServerTests.ts
- packages/server/src/__tests__/integration/index.ts
- packages/server/src/__tests__/standalone/integration.test.ts
- packages/server/src/externalTypes/plugins.ts
- packages/server/src/plugin/usageReporting/options.ts
- packages/server/src/plugin/usageReporting/plugin.ts
- packages/server/src/standalone/index.ts
- packages/server/src/utils/urlForHttpServer.ts
The main difference for Apollo Server between serverless and other
frameworks is that serverless frameworks typically need to provide a
request handler *synchronously* on startup. So our model of "you must
call `await server.start()` before your web server listens" doesn't
work.
(The reason we introduced that model (optionally in AS2.22 and required
in AS3) was that previously, it was easy to set up your server in a way
that if it failed to load its schema (eg, from Studio), it would still
start listening and just fail every operation forever. This model lets
your server fail fast if startup fails. However, it doesn't work for
serverless integrations.)
The other minor differences are that the default value of
stopOnTerminationSignals is false for serverless integrations and the
default …
> New API to support serverless frameworks

- packages/server/src/__tests__/integration/apolloServerTests.ts
- packages/server/src/plugin/landingPage/default/index.ts
- packages/server/src/plugin/landingPage/default/types.ts
There are no docs in this branch, right? So this is just the functional changes. 
Add a default of `embed:true` to the landing page config, so the embeds are rendered by default!
> AS4: default `embed` to `true` in landing pages

- CHANGELOG.md
- packages/apollo-server-core/src/plugin/traceTreeBuilder.ts
The comment explains this in detail. Basically, this "shouldn't happen"
error actually could happen. In theory, the times it could happen are
the exact times that the error itself would be swallowed rather than
becoming visible... but a graphql-js bug meant that sometimes they would
become visible anyway.
Fixes #4472.
> usage reporting: don't throw errors if willResolveField is called "late"

- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/__tests__/documentStore.test.ts
The `documentStore` didn't need to be changed to an `UnboundedCache` since it was previously bounded with a `maxSize`. This is undoing a mistake.
For reference: https://github.com/apollographql/apollo-server/blob/72f663e4881d45320e27c5c4a676f78c36d3c3fa/packages/apollo-server-core/src/ApolloServer.ts#L918
> Reinstate bounded `documentStore` (revert mistake)

- WIP/migration.mdx
- packages/server/package.json
- packages/server/src/__tests__/ApolloServer.test.ts
- packages/server/src/__tests__/integration/apolloServerTests.ts
- packages/server/src/gql.ts
- packages/server/src/index.ts
- packages/server/src/plugin/schemaReporting/schemaReporter.ts
In general, "import a package just to re-export its symbol" is a pattern
we're trying to avoid.
And using graphql-tag at all in servers isn't particular necessary,
compared to in clients:
- Putting your schema inline in TS (outside of simple tests) doesn't
have much advantage over using separate files
- Syntax highlighting can generally be accomplished via string constants
that start with `#graphql`
- APIs like `typeDefs` that take parsed documents also take strings
- graphql-tag caches the AST, which can be relevant in clients if you're
putting an operation inside a function but is not really relevant for
once-on-startup schemas
People who want to use `gql` can use `graphql-tag` directly.
Fixes #6527.
> Remove graphql-tag re-export

- packages/server/src/__tests__/tsconfig.json
- packages/server/src/plugin/schemaReporting/index.ts
- packages/server/src/plugin/schemaReporting/schemaReporter.ts
- packages/server/src/plugin/usageReporting/plugin.ts
- packages/server/src/tsconfig.json
- packages/server/tsconfig.json
- tsconfig.base.json
- tsconfig.build.json
Multiple tsconfig.json files seem to be required here; see
https://stackoverflow.com/questions/55753163/package-json-is-not-under-rootdir
Part of work towards ESM support.
> Stop using require to get package version

- .gitignore
- packages/server/.npmignore
- packages/server/package.json
- packages/server/plugin/cacheControl/package.json
- packages/server/plugin/disabled/package.json
- packages/server/plugin/drainHttpServer/package.json
- packages/server/plugin/inlineTrace/package.json
- packages/server/plugin/landingPage/default/package.json
- packages/server/plugin/landingPage/graphqlPlayground/package.json
- packages/server/plugin/schemaReporting/package.json
- packages/server/plugin/usageReporting/package.json
- packages/server/src/plugin/disabled/index.ts
- packages/server/standalone/package.json
- scripts/postcompile.mjs
- smoke-test/package.json
- smoke-test/prepare.sh
- smoke-test/smoke-test.cts
- smoke-test/smoke-test.mts
- smoke-test/smoke-test.sh
- smoke-test/tsconfig.cjs.json
- smoke-test/tsconfig.esm.json
There were a few problems with #6580, which added ESM builds and deep
imports to version-4.
The `exports` section of `packages/server/package.json` had two
mistakes: the `types` lines linked to files in the cjs directory but we
only placed them in the esm directory, and the `types` lines are
apparently supposed to appear first in each block.
However, it turned out that this didn't matter because tsc doesn't even
look in the `exports` section unless you set `moduleResolution` to
`node16` or `nodenext` in your tsconfig `compilerOptions`, and we
weren't! And it turns out doing that setting is a bit of a pain because
many packages don't currently work with that flag. So if we published
our package with the deep imports only listed in `exports` in
package.json, we'd break any TypeScript user …
> Fix ESM/CJS and deep imports

- packages/apollo-server-plugin-response-cache/src/ApolloServerPluginResponseCache.ts
- Rename BaseCacheKey and ContextualCacheKey with "Data" on end, since
the cache key is a string.
- Reintroduce CacheKey(Data) removed in #6655; make the
GenerateCacheKeyFunction type be defined in terms of it. Now calls to
the `const generateCacheKey` function are type-safe (ie, the second
arg is a CacheKeyData rather than unknown).
- Describe generateCacheKey hook as a method rather than a field, like
the other hooks in Options.
> Follow-up to #6655

- CHANGELOG.md
- docs/source/performance/caching.md
- packages/apollo-reporting-protobuf/package.json
- packages/apollo-server-azure-functions/package.json
- packages/apollo-server-cloud-functions/package.json
- packages/apollo-server-cloudflare/package.json
- packages/apollo-server-core/package.json
- packages/apollo-server-express/package.json
- packages/apollo-server-fastify/package.json
- packages/apollo-server-hapi/package.json
- packages/apollo-server-integration-testsuite/package.json
- packages/apollo-server-koa/package.json
- packages/apollo-server-lambda/package.json
- packages/apollo-server-micro/package.json
- packages/apollo-server-plugin-base/package.json
- packages/apollo-server-plugin-response-cache/package.json
- packages/apollo-server-plugin-response-cache/src/ApolloServerPluginResponseCache.ts
- packages/apollo-server-types/package.json
- packages/apollo-server/package.json
> Release 3.10.0

- packages/server/src/__tests__/tsconfig.json
- tsconfig.base.json
- tsconfig.test.base.json
- Node 14 as minimum requirement lets us target es2020 (see eg
https://github.com/tsconfig/bases/blob/main/bases/node14.json)
- Stuff like array and asynciterable is just built in to es2020
by now as far as I can tell
- We don't appear to need dom in our tests any more (for @apollo/client)
probably because the test does deep imports into @apollo/client
> tsconfig: simplify and update

- WIP/migration.mdx
- packages/plugin-response-cache/src/ApolloServerPluginResponseCache.ts
- packages/server/src/ApolloServer.ts
- packages/server/src/__tests__/ApolloServer.test.ts
- packages/server/src/__tests__/logger.test.ts
- packages/server/src/externalTypes/graphql.ts
- packages/server/src/externalTypes/plugins.ts
- packages/server/src/httpBatching.ts
- packages/server/src/plugin/inlineTrace/index.ts
- packages/server/src/plugin/schemaReporting/index.ts
- packages/server/src/plugin/usageReporting/plugin.ts
- packages/server/src/requestPipeline.ts
- packages/server/src/runHttpQuery.ts
This change does two things, which we originally thought were kind of
connected but maybe aren't.
First, we switch the implementation of contravariance from a hacky
`__forceTContextToBeContravariant` field to the new TS 4.7 variance
annotations. But in fact, instead of making it contravariant, we make it
invariant: `ApolloServer<X>` can only be assigned to `ApolloServer<Y>`
when X and Y are the same. This is because:
- An `ApolloServer<{foo: number}>` is not a `ApolloServer<{}>`, because
you can invoke `executeOperation` on the latter with an empty context
object, which would confuse the former (this is the contravariance we
already had).
- An `ApolloServer<{}>` is not a `ApolloServer<{foo: number}>`, because
you can invoke `addPlugin` on the latter with a plugin whose methods
expect to …
> Make AS/ASP invariant in TContext; move logger/cache to server in plugins

- packages/server/src/errors.ts
- packages/server/src/requestPipeline.ts
We now ensure various thrown things are Errors or GraphQLErrors as
appropriate.
> requestPipeline: clean up some casts around error types

- packages/integration-testsuite/src/httpServerTests.ts
- packages/server/src/runHttpQuery.ts
Previously, we calculated the Content-Length HTTP response header in
runHttpQuery, which runs once for each GraphQL operation. When using
HTTP batching, we failed to recalculate Content-Length for the full
response, and so we sent a Content-Length that was too small.
In practice, many HTTP servers will recalculate Content-Length anyway.
For example, Express's `res.send` (which we use in expressMiddleware in
AS4, though we did not use it in AS3) will override the Content-Length
that you set, which is why tests did not fail previously (and the added
batching test does not fail even without the fix). Lambda/API Gateway
also overrides Content-Length. (We discovered this while working on a
proof of concept for Lambda support, whose test suite used a mock Lambda
server that used http.Server …
> Fix content-length calculation for batch queries

- packages/integration-testsuite/src/httpServerTests.ts
- packages/plugin-response-cache/src/__tests__/integration.test.ts
- packages/server/src/__tests__/ApolloServer.test.ts
- packages/server/src/__tests__/plugin/cacheControl/cacheControlPlugin.test.ts
- packages/server/src/__tests__/standalone/standaloneSpecific.test.ts
- packages/server/src/express4/index.ts
- packages/server/src/externalTypes/http.ts
- packages/server/src/httpBatching.ts
- packages/server/src/runHttpQuery.ts
Instead of being an object whose exactly semantics are framework-defined
(what does specifying a parameter twice look like? can you construct
weird nested structures by putting brackets in parameter names?) just
receive the raw search string from the URL so that Apollo Server can
parse it in a consistent way. This also means we can consistently reject
requests that specify `query` more than once, say.
Also fix a few tests that listen on port 4000 instead of an ephemeral
port.
> HTTPGraphQLRequest.searchParams -> HTTPGraphQLRequest.search

- docs/source/getting-started.mdx
Replacing the broken CodeSandbox link with a Github link for now.
> add github link for now

- docs/source/api/apollo-server.mdx
- docs/source/api/plugin/cache-control.md
- docs/source/api/plugin/drain-http-server.mdx
- docs/source/api/plugin/inline-trace.md
- docs/source/api/plugin/schema-reporting.md
- docs/source/api/plugin/usage-reporting.md
- docs/source/builtin-plugins.md
- docs/source/data/data-sources.mdx
- docs/source/data/errors.mdx
- docs/source/data/file-uploads.mdx
- docs/source/data/resolvers.mdx
- docs/source/data/subscriptions.mdx
- docs/source/deployment/azure-functions.mdx
- docs/source/deployment/gcp-functions.mdx
- docs/source/deployment/lambda.md
- docs/source/getting-started.mdx
- docs/source/integrations/middleware.mdx
- docs/source/integrations/plugins.md
- docs/source/monitoring/health-checks.md
- docs/source/monitoring/metrics.md
- docs/source/performance/apq.md
- docs/source/performance/cache-backends.mdx
- docs/source/proxy-configuration.md
- docs/source/schema/creating-directives.mdx
- docs/source/schema/custom-scalars.md
- docs/source/schema/unions-interfaces.md
- docs/source/security/authentication.md
- docs/source/security/cors.mdx
- docs/source/security/terminating-ssl.mdx
Folks might run into CORS issues from the getting started apollo server doc. Now we can provide them with a quick answer: embed the Sandbox instead of using our hosted one!
> ✍️ add embed sandbox option to Getting Started doc

- packages/apollo-server-core/src/determineApolloConfig.ts
This request updates the error message when these two variables are specified. Ran into this today and was a little confused by the messaging. Thank you!
> Update error message when graph ref and variant are specified

- .changeset/lazy-emus-hunt.md
- packages/integration-testsuite/src/apolloServerTests.ts
- packages/integration-testsuite/src/httpServerTests.ts
Fastify's JSON parser returns errors directly in these cases rather than
letting our middleware react to the lack of parsing.
> integration-testsuite: relax error expectations

- CHANGELOG.md
- packages/apollo-server-core/src/plugin/usageReporting/options.ts
Note that the `const fieldLevelInstrumentation` which this got assigned
to actually already inferred (roughly) the correct type because the type
got merged with a number-returning function from another case.
> Usage reporting: fix TS declaration of fieldLevelInstrumentation

- .changeset/spicy-lions-deliver.md
- packages/server/src/plugin/usageReporting/options.ts
Usage reporting: fix TS declaration of fieldLevelInstrumentation
Note that the `const fieldLevelInstrumentation` which this got assigned
to actually already inferred (roughly) the correct type because the type
got merged with a number-returning function from another case.
> Port #6763 from AS3

- smoke-test/package.json
See: https://github.com/yargs/yargs-parser/issues/452
We should remove the dependency altogether once this is resolved, as we don't actually depend on it.
> Fix smoke test, pin `yargs-parser` for now

- .changeset/small-suits-compare.md
- docs/source/migration.mdx
- packages/integration-testsuite/src/apolloServerTests.ts
- packages/integration-testsuite/src/httpServerTests.ts
- packages/server/src/ApolloServer.ts
- packages/server/src/__tests__/ApolloServer.test.ts
- packages/server/src/__tests__/errors.test.ts
- packages/server/src/__tests__/runQuery.test.ts
- packages/server/src/errorNormalize.ts
- packages/server/src/errors/index.ts
- packages/server/src/externalTypes/constructor.ts
- packages/server/src/externalTypes/graphql.ts
- packages/server/src/requestPipeline.ts
This PR does a few things:
(a) Moves `error.extensions.exception.stacktrace` to
`error.extensions.stacktrace`.
(b) Removes the rest of `error.extensions.exception`. This contained
enumerable properties of the original error, which could lead to
surprising information leakage.
(c) Documents that change and provides a `formatError` hook
in the migration guide to maintain AS3 behavior.
(d) Provide an `unwrapResolverError` function in `@apollo/server/errors`
to help get back the original error in the resolver error case, which is
a helpful part of the documented `formatError` recommendations
(since the old error formatting put stuff from that unwrapped error
on the `exception` extension).
(e) Gets rid of the `declare module` which made …
> Error extensions improvements

- .circleci/config.yml
- package.json
Changes that don't touch packages don't require changesets.
If you made a change to a package that you don't want to show up as a
changeset, just run `changeset --empty` like the error says.
(This does assume that your remote is named `origin`. We pass
`origin/version-4` instead of `version-4` because that way CI doesn't
have to actually create a local `version-4` branch. We don't set
`baseBranch` to `origin/version-4` in config.json because enforcing the
remote name even on `changeset add` users seems bad.)
> CI: require changesets before merging into version-4

- .changeset/old-insects-smash.md
- docs/source/migration.mdx
- packages/server/src/ApolloServer.ts
- packages/server/src/externalTypes/constructor.ts
This is prompted by the @graphql-tools/schema v9 upgrade, which gets rid
of `parseOptions` and rolls it directly into arguments to
`makeExecutableSchema`. But the status quo doesn't make much sense
anyway, as a comment already noted. So let's just make this option do
only one thing.
> v4: don't pass parseOptions to makeExecutableSchema

- .changeset/stale-sheep-search.md
- packages/server/src/__tests__/plugin/landingPage/getEmbeddedExplorerHTML.test.ts
- packages/server/src/__tests__/plugin/landingPage/getEmbeddedSandboxHTML.test.ts
- packages/server/src/plugin/landingPage/default/getEmbeddedHTML.ts
- packages/server/src/plugin/landingPage/default/index.ts
See
https://github.com/apollographql/apollo-server/security/advisories/GHSA-2fvv-qxrq-7jq6
for details.
This removes the curl command from the no-bundle fallback on the default
landing page.
> Port GHSA-2fvv-qxrq-7jq6 fix from v3

- .changeset/twenty-cooks-repair.md
- docs/source/migration.mdx
- packages/integration-testsuite/src/apolloServerTests.ts
- packages/server/src/ApolloServer.ts
- packages/server/src/plugin/inlineTrace/index.ts
- packages/server/src/plugin/traceTreeBuilder.ts
- packages/server/src/plugin/usageReporting/index.ts
- packages/server/src/plugin/usageReporting/options.ts
- packages/server/src/plugin/usageReporting/plugin.ts
- packages/server/src/utils/UnreachableCaseError.ts
We replace the `rewriteError` option with `sendErrorsInTraces` (usage
reporting) and `includeErrors` (inline trace), which takes `{unmodified:
true}`, `{masked:true}`, and `{transform}` variants. This is similar to
`sendVariableValues` and `sendHeaders`.
Like those two options, this now defaults to a more redacted version:
`{masked: true}`. This will reduce unintentional reporting of PII.
Part of #6051.
Paired with @bonnici.
> usage reporting/inline trace plugins: mask errors, change option name

- .changeset/ninety-tips-unite.md
- packages/integration-testsuite/src/apolloServerTests.ts
Added some unit tests to cover the new error reporting options introduced in https://github.com/apollographql/apollo-server/pull/6794. The transform case was already covered but I added two new tests for the unmodified and masked options.
> Added unit tests for masked and unmodified error logging options

- .changeset/famous-parents-argue.md
- docs/source/integrations/building-integrations.md
- packages/integration-testsuite/src/apolloServerTests.ts
- packages/integration-testsuite/src/httpServerTests.ts
- packages/plugin-response-cache/src/ApolloServerPluginResponseCache.ts
- packages/server/src/ApolloServer.ts
- packages/server/src/__tests__/ApolloServer.test.ts
- packages/server/src/express4/index.ts
- packages/server/src/externalTypes/http.ts
- packages/server/src/httpBatching.ts
- packages/server/src/requestPipeline.ts
- packages/server/src/runHttpQuery.ts
- packages/server/src/utils/makeGatewayGraphQLRequestContext.ts
This matches the name in the Fetch Response API, so that
`requestContext.response.http.status` does not have to change between
AS3 and AS4. I think the previous rename was inspired by the Node HTTP
response object's field name, but there are enough adjustments for AS4;
let's avoid this little one.
> Rename HTTPGraphQLHead.statusCode to status

- docs/source/migration.mdx
When working to upgrade our own server, it became more clear that we
need to explicitly say that folks with custom GraphQLDataSource
implementations need to adjust their types too.
> migration: more gateway details

- docs/source/config.json
Looping back to this, I like Trevor's "Server frameworks" suggestion for the name of the sidebar section.
> Renaming "integrations" sidebar section to "Server frameworks" 

- .github/workflows/release-pr.yml
- package-lock.json
- package.json
Otherwise the `version` lines in package-lock.json don't get updated
until the next time you run `npm i`. (That's why this PR has random
package-lock.json changes!)
> changeset: run `npm i` when making versioning PR

- .changeset/wet-kiwis-play.md
- docs/source/migration.mdx
- packages/integration-testsuite/src/apolloServerTests.ts
- packages/plugin-response-cache/src/ApolloServerPluginResponseCache.ts
- packages/server/src/ApolloServer.ts
- packages/server/src/__tests__/ApolloServer.test.ts
- packages/server/src/__tests__/logger.test.ts
- packages/server/src/externalTypes/constructor.ts
- packages/server/src/externalTypes/graphql.ts
- packages/server/src/externalTypes/index.ts
- packages/server/src/externalTypes/plugins.ts
- packages/server/src/plugin/cacheControl/index.ts
- packages/server/src/plugin/disabled/index.ts
- packages/server/src/plugin/drainHttpServer/index.ts
- packages/server/src/plugin/inlineTrace/index.ts
- packages/server/src/plugin/landingPage/default/index.ts
- packages/server/src/plugin/landingPage/graphqlPlayground/index.ts
- packages/server/src/plugin/schemaReporting/index.ts
- packages/server/src/plugin/usageReporting/plugin.ts
Previously on `version-4`, we had made `ApolloServerPlugin<TContext>`
"invariant" in `TContext` via the new `in out` annotation. That's
because we had added a `server` field to `GraphQLRequestContext` and
`GraphQLServerContext`.
The issue here is that because you can invoke
`server.executeOperation(op, contextValue)`, then a
`ApolloServerPlugin<BaseContext>` was not assignable to
`ApolloServerPlugin<SomeSpecificContext>`, because the former was able
to call `requestContext.executeOperation(op, {})`, and a server whose
context has additional required fields could not load this plugin. This
essentially meant that you couldn't have a single object (not created by
a generic function or generic class) that was a plugin that works with
any server, even if it doesn't actually care about context …
> Plugins: no server; interface contravariant; no factory functions

- .changeset/ninety-panthers-accept.md
- docs/source/migration.mdx
- package-lock.json
- packages/integration-testsuite/package.json
- packages/integration-testsuite/src/apolloServerTests.ts
- packages/integration-testsuite/tsconfig.json
- packages/plugin-landing-page-graphql-playground/README.md
- packages/plugin-landing-page-graphql-playground/package.json
- packages/plugin-landing-page-graphql-playground/src/index.ts
- packages/plugin-landing-page-graphql-playground/tsconfig.cjs.json
- packages/plugin-landing-page-graphql-playground/tsconfig.json
- packages/server/package.json
- packages/server/plugin/landingPage/graphqlPlayground/package.json
- scripts/postcompile.mjs
- smoke-test/smoke-test.cjs
- smoke-test/smoke-test.cts
- smoke-test/smoke-test.mjs
- smoke-test/smoke-test.mts
- tsconfig.build.json
GraphQL Playground was unmaintained when we released Apollo Server 3,
and the Apollo Server team has had to put significant work into fixing
security issues in GraphQL Playground. While we will still publish a
landing page plugin to enable folks upgrading from AS2 to not have to
immediately retrain their users on how to use Apollo Sandbox or another
interface, we remove it from the main `@apollo/server` package and move
it to its own `@apollo/server-plugin-landing-page-graphql-playground`
package. This lets us remove the Playground HTML package's dependencies
(like `xss`) from Apollo Server's main package.
Fixes #6109.
> Move ApolloServerPluginLandingPageGraphQLPlayground to new package

- CHANGELOG.md
- docs/source/data/data-sources.mdx
- packages/apollo-datasource-rest/README.md
- packages/apollo-datasource-rest/src/RESTDataSource.ts
- packages/apollo-datasource-rest/src/__tests__/RESTDataSource.test.ts
Rename property for RESTDataSource from `requestCacheEnabled` to `memoizeGetRequests`
From the initial PR, the name of the new property was a little confusing since there are actually two caches, but what is being cached is the response data in the end
Original PR https://github.com/apollographql/apollo-server/pull/6650
> Rename property for RESTDataSource

- .changeset/chatty-baboons-search.md
- package-lock.json
- packages/server/package.json
This should unblock Renovate getting us to the latest 0.x gateway.
> Upgrade @apollo/server-gateway-interface to laxer version

- .changeset/spotty-days-eat.md
- packages/server/src/__tests__/runQuery.test.ts
- packages/server/src/requestPipeline.ts
Reproduction in first commit, resolution with test updates in second commit.
`executionDidEnd` hooks are currently called within both the try and catch clauses of the same block. This means that if a hook throws, they'll be called _again_ in the catch.
Similar to changes made for `parsingDidEnd` in https://github.com/apollographql/apollo-server/issues/6679, we now call the `executionDidEnd` hooks _after_ the try/catch and within the catch. This ensures they'll only ever be called once.
Fixes #6567
> Ensure `executionDidEnd` hooks are only called once

- CHANGELOG.md
- packages/apollo-server-fastify/src/ApolloServer.ts
I'm trying to use this module with `fastify@4`, but we never got a response. Adding the `return` statements fixed that issue. It's somewhat mentioned in the migration guide (https://medium.com/@fastifyjs/fastify-v4-ga-59f2103b5f0e).
Note that this also works in fastify 3
> fix(fastify): return reply object from async handlers

- .changeset/healthy-glasses-reflect.md
- .changeset/many-plums-smile.md
- .changeset/short-lies-kneel.md
- .changeset/silly-icons-taste.md
- docs/source/data/errors.mdx
- docs/source/migration.mdx
- packages/integration-testsuite/src/apolloServerTests.ts
- packages/server/src/__tests__/plugin/usageReporting/plugin.test.ts
- packages/server/src/plugin/usageReporting/options.ts
- packages/server/src/plugin/usageReporting/plugin.ts
- packages/server/src/plugin/usageReporting/stats.ts
- We've decided to leave the usage reporting defaults in AS4 as "field
level instrumentation on for all operations, send some operations as
traces". But we'd like to at least provide a non-experimental
mechanism for entirely disabling sending traces to Studio. So there's
a new ApolloServerPluginUsageReporting: `sendTraces: false`.
- Rename the (new in AS4) usage reporting option `sendErrorsInTraces` to
`sendErrors`, because it does also affect error statistics in stats
reports if your `transform` function returns `null`.
- Remove Apollo-internal `internal_includeTracesContributingToStats`
option. This enabled some internal consistency monitoring which we are
no longer paying attention to.
- If you enable `debugPrintReports`, send the reports as `info` rather
than `warn`, which primarily …
> usage reporting: add sendTraces, rename sendErrorsInTraces, etc

- .changeset/witty-squids-vanish.md
- docs/source/data/errors.mdx
- docs/source/data/resolvers.mdx
- docs/source/migration.mdx
- packages/integration-testsuite/src/apolloServerTests.ts
- packages/integration-testsuite/src/httpServerTests.ts
- packages/server/src/ApolloServer.ts
- packages/server/src/__tests__/errors.test.ts
- packages/server/src/__tests__/runQuery.test.ts
- packages/server/src/errorNormalize.ts
- packages/server/src/internalErrorClasses.ts
- packages/server/src/requestPipeline.ts
- packages/server/src/runHttpQuery.ts
You can now add a `Partial<HTTPGraphqlHead>` as an `http` error
extension, which provides an easier way of setting HTTP response headers
or status codes. These are honored when thrown from resolvers and
`context` functions (and are also used internally to implement bad
request errors etc).
Multiple resolver errors can have `http` extensions to set status code
and distinct headers separately; we do not commit to the semantics of
what happens if multiple errors set the status code or set the same
header.
Now that you have more control over `context` error handling, simplify
the default behavior: if the error thrown from `context` is not a
`GraphQLError` with an `http` extension with a `status`, the default
status code is 500 rather than sometimes being 400 based on
`extensions.code`.
Only …
> New error extension `http` for setting status/headers in context, resolvers

- .github/workflows/docs-publish.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- .changeset/shaggy-schools-sparkle.md
- packages/server/src/plugin/usageReporting/plugin.ts
Noticed this typo when debugging some stats/trace related issues.
> Fix typo in usage reporting plugin log message

- .changeset/quick-beans-applaud.md
- packages/integration-testsuite/src/httpServerTests.ts
Working through the Koa integration with @matthew-gordon and we ran into this. The `koa-bodyparser` handles the response (`400 Bad Request`) and I take no issue with this. I relaxed the response message we require to allow for this in that particular test case.
> Relax "malformed JSON POST request" response requirement

- .changeset/stale-goats-serve.md
- jest.config.base.js
- packages/integration-testsuite/src/apolloServerTests.ts
- packages/integration-testsuite/src/httpServerTests.ts
- packages/server/src/__tests__/ApolloServer.test.ts
- packages/server/src/__tests__/errors.test.ts
- packages/server/src/__tests__/plugin/schemaReporting/schemaReporter.test.ts
- packages/server/src/__tests__/plugin/usageReporting/__snapshots__/stats.test.ts.snap
Ref: https://github.com/apollographql/apollo-server/pull/6850#issuecomment-1247157466
> Update jest snapshot format to future v29 default

- docs/source/integrations/building-integrations.md
In response to: [https://github.com/apollographql/apollo-server/pull/6863/files#r961153005](https://github.com/apollographql/apollo-server/pull/6863/files#r961155293)
> Add a note about prepending the word "start" to serverless functions

- .changeset/early-jokes-bathe.md
- packages/server/src/__tests__/runQuery.test.ts
- packages/server/src/externalTypes/graphql.ts
- packages/server/src/requestPipeline.ts
Previously it could mutate individual errors but now it can add or remove them too, and this is explicit.
Refactor error handling code in requestPipeline to make it clear that didEncounterErrors is always called before normalizeAndFormatErrors.
> didEncounterErrors is now allowed to modify requestContext.errors

- docs/source/integrations/plugins.md
A customer has brought up this issue as they were trying to debug how Apollo Server was handling plugins throwing errors. We should at least reference this issue if there are some known problems with the flow.
> [docs] Add footnote about known plugin error handling issues

- docs/source/api/apollo-server.mdx
- docs/source/migration.mdx
- docs/source/workflow/requests.md
- A bit more clarity about batching and HTTP headers in one place; not even bothering in another place (it seems a bit specific for the options reference, which links to the first place anyway)
- Revert accidental change to AS3 example
> Docs follow-up from #6936

- .changeset/real-games-dance.md
- package-lock.json
- packages/integration-testsuite/package.json
- packages/plugin-response-cache/package.json
- packages/server/package.json
Might as well require the latest and greatest when bumping our major version.
Fixes #6070.
> Bump minimum graphql-js to v16.6.0 from v16.5.0

- .changeset/witty-toes-grin.md
- docs/source/api/apollo-server.mdx
- packages/server/src/ApolloServer.ts
- packages/server/src/__tests__/ApolloServer.test.ts
- packages/server/src/externalTypes/graphql.ts
This lets you manually specify the these types when calling the method; typically you generate these types with a codegen tool like graphql-code-generator. This matches a common pattern used in client development.
This doesn't let you specify the types for incremental delivery responses; we could potentially add that later.
This also lets you use TypedQueryDocumentNode (from graphql-js) as the `query`; if you do so, we can infer the two generic types automatically. (This type is less popular than the earlier TypedDocumentNode from `@graphql-typed-document-node/core` and we should probably support the latter as well; in the interest of reducing dependencies we don't yet, but we can extend to support that later.)
Adapted from an original PR #6384 by @jacksenior.
> Add generics for data and variables to executeOperation

- CHANGELOG_historical.md
- CHANGELOG_v4_draft.md
- cspell.yaml
Note that this will actually end up in packages/server/CHANGELOG.md (when we're ready to publish the actual v4.0.0, we'll edit that file on the "Version Packages" PR to contain this text).
Rename top-level CHANGELOG.md to historical, and add recent v3 entries to it.
> Write CHANGELOG for v4

- .changeset/tasty-elephants-give.md
- packages/server/src/plugin/usageReporting/plugin.ts
A data structure in the usage reporting plugin would get a new entry each time the server's schema changed. Old entries would never be deleted, though their values would be shrunk to a minimum size.
It seems that this was not good enough and is producing notable memory leaks for some folks. So let's fix it!
The reason for the old behavior was to be really careful to never write to a report that may have already been taken out of the map and sent. Previously this was accomplished by having the main entry in the map never change. Now this is accomplished by making sure that we never write to the report any later than immediately (and synchronously) after we pull it out of the map.
Fixes #6983.
> usage reporting: fix memory leak

- .changeset/seven-avocados-compare.md
- docs/source/integrations/plugins-event-reference.mdx
- packages/integration-testsuite/src/apolloServerTests.ts
- packages/integration-testsuite/src/httpServerTests.ts
- packages/server/src/requestPipeline.ts
(Also make an existing vaguely related test a bit more clear.)
> Officially support throwing from didResolveOperation

- docs/source/performance/caching.md
- packages/integration-testsuite/src/httpServerTests.ts
Based on review by @trevor-scheer.
> Follow-up from #6986

- .changeset/clever-years-think.md
- .changeset/dull-timers-yawn.md
- docs/source/getting-started.mdx
- docs/source/migration.mdx
- package.json
- packages/integration-testsuite/package.json
- packages/plugin-response-cache/package.json
- packages/server/package.json
This makes two kinds of changes:
- Despite documenting that Apollo Server 4 requires Node 14, we inadvertently left the `engines` line in `@apollo/server` at `>= 12`. Fix this to require v14 as intended.
- AS4 requires `graphql@16.6.0`, and the minimum version of Node 14 supported by that version is v14.16.0, so there's no point in pretending we support v14.0.0. So adjust all of our engines lines to require v14.16.0. (We don't bother with the Playground plugin, which we're about to delete.)
> Fix Node.js `engines` to require Node v14.16.0

- docs/source/schema/schema.md
This request fixes an name mismatch in the "Schema basics" tutorial.  The section which focuses on creating explicit types for mutations references an earlier mutation which updates the user's email.  The name of the referenced mutation is `updateUserEmail`, however the example API response uses the value `updateUser` which, as I understand it, should match the mutation name.
> Response example matches mutation name

- .changeset/lovely-terms-compare.md
- packages/integration-testsuite/src/apolloServerTests.ts
- packages/server/src/ApolloServer.ts
- packages/server/src/errors/index.ts
This PR implements the feature discussed in #7033.
A new error enum `ApolloServerErrorCode.INTROSPECTION_DISABLED` was added and used when creating an introspection validation error.   This will allow better handling of this specific error condition for observers of `didEncounterErrors` events. 
I intend to use this to suppress logging of these errors when someone attempts to point a studio sandbox at my production servers and leaves schema auto-update on. :|
To make this work with the existing code, it is now possible to set any custom GraphQLError.extensions.code when calling `ValidationContext.reportError()`. Someone can now wire through their own validation error codes and see them on the `didEncounterErrors` events instead of them all being masked as GRAPHQL_VALIDATION_FAILED (which …
> Add INTROSPECTION_DISABLED error enum, set it on validation errors

- .changeset/slimy-apples-live.md
- packages/integration-testsuite/src/httpServerTests.ts
> Add test for invalid operation name code/message over GET

- .changeset/spicy-mayflies-lick.md
- packages/integration-testsuite/src/httpServerTests.ts
- packages/server/src/utils/makeGatewayGraphQLRequestContext.ts
The shim layer between AS4 and Gateway (which creates an argument for the Gateway's executor which looks like AS3's GraphQLRequestContext) did not copy changes to response headers or HTTP status back to the real GraphQLRequestContext. This PR makes the shimmed HTTP response object use the real response objects as backing storage.
Fixes #7069.
> Fix v4 regression: gateways should be able to set HTTP response metadata

- .changeset/shaggy-taxis-burn.md
- packages/integration-testsuite/src/httpServerTests.ts
- packages/server/src/httpBatching.ts
Previously, a `GET` request whose body was a JSON array with N elements would be interpreted as a batch of the operation specified in the query string repeated N times. Now we just ignore the body for `GET` requests and never treat them as batched. This matches the Apollo Server 3 behavior.
(You can try to sneak arrays into Apollo Server 3 GETs by using search parameters like `query[]=`, because AS3 uses the `querystring` npm package instead of the simpler W3C-style `URLSearchParams`. But that won't give you "an array of objects with keys like `query`"; it'll give you "an object with a `query` key whose value is an array", which isn't enough to make it trigger the batch code.)
Note that Apollo Client Web's batched HTTP link explicitly refuses to send batched operations over GET.
> Remove an edge case where GET requests could be treated as batched

- .changeset/many-teachers-remain.md
- packages/integration-testsuite/src/httpServerTests.ts
I'm currently building a Next.js integration for Apollo Server 4 over [here](https://github.com/apollo-server-integrations/apollo-server-integration-next).
To make sure the integration works properly with Next.js I'm reusing Next.js's [apiResolver](https://github.com/vercel/next.js/blob/canary/packages/next/server/api-utils/node.ts#L426), which handles parsing API route requests. I [managed to make every test](https://github.com/apollo-server-integrations/apollo-server-integration-next/pull/14) in `apollo-server-integrations-testsuite` pass except for one, `throws an error if POST JSON is malformed`. This test checks the error message in the server response when malformed JSON data is sent and matches it to two possible substrings, `Unexpected token f` and `Bad Request`.
Next.js's …
> Add allowed error message to integration testsuite's malformed JSON test

- docs/source/data/data-sources.mdx
Essentially, the link for RESTDataSource on [the Data Sources page](https://www.apollographql.com/docs/apollo-server/v2/data/data-sources) in the docs was **stale**. I've tracked down [the correct link](https://github.com/apollographql/datasource-rest) and updated the markdown. I hope that helps future visitors!
> Corrected broken link to RESTDataSource Github

- docs/source/data/fetching-rest.mdx
I also tweaked the beginning diagram to explicitly show the model of creating one subclass per REST API :)
> Describe the two layers of caching in `RESTDataSource`

- .changeset/metal-pigs-sleep.md
- packages/usage-reporting-protobuf/package.json
@apollo/usage-reporting-protobuf should define a main/module field in package.json, same as @apollo/server does. The "exports" field doesn't work everywhere yet still (ex. jest, or at least old versions of jest, don't respect it).
> Update usage-reporting-protobuf to have main field

- .changeset/purple-kiwis-lay.md
- .changeset/quick-weeks-shake.md
- package-lock.json
- packages/integration-testsuite/src/apolloServerTests.ts
- packages/server/package.json
- packages/server/src/plugin/usageReporting/options.ts
- packages/server/src/plugin/usageReporting/plugin.ts
- Drop references to unencoded and uncompressed versions of reports as soon as they are no longer needed, to hopefully allow garbage collection to be more effective during the HTTP POSTs.
- Simplify compression code to no longer require a workaround for Node v6 (we require Node v14!), and use `util.promisify`.
- Add a timeout to the report POST. The default is 30 seconds, which is
currently the timeout enforced by Apollo's load balancers; a smaller
number may be advisable for high traffic users facing memory
constraints. This uses the AbortController API (which should be
supported by most Fetcher implementations). We use the
`node-abort-controller` polyfill (same polyfill we chose for
`@apollo/gateway`) because Node's built-in global AbortController
requires an experimental flag in Node …
> Low-hanging fruit for performance improvements in usage reporting

- CHANGELOG.md
- package-lock.json
- packages/apollo-server-core/package.json
- packages/apollo-server-core/src/plugin/usageReporting/options.ts
- packages/apollo-server-core/src/plugin/usageReporting/plugin.ts
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
We only require Node 12 here but that's still enough for the zlib API change.
We don't bother to add `signal` to the `apollo-server-env` RequestInit. The integration test does show that it works with the default fetcher (`node-fetch` via `apollo-server-env`).
> Backport usage reporting improvements #7101 to AS3

- package-lock.json
- package.json
Looks like we removed the last direct reference in 30ba0e63f. (It has a major bump today, but why bother evaluating such a Renovate PR if we don't use it?)
> Remove dev dependency on `@graphql-tools/utils`

- .changeset/mighty-points-film.md
- package-lock.json
- packages/integration-testsuite/README.md
- packages/integration-testsuite/package.json
- packages/integration-testsuite/src/apolloServerTests.ts
- packages/server/package.json
- renovate.json5
The peer dependency arrangement of testsuite on server was problematic. In one sense, it seems reasonable since we want integration authors to bring their own AS package. However, bumping that peer dependency with every version update is technically a breaking change - and our release tooling (changeset) doesn't provide us a means to workaround the behavior where it major version bumps both packages.
For correctness and compliance with our tooling, a direct dependency addresses both concerns. We've also added an additional test which ensures that the versions match. The test really just validates that there's one install of @apollo/server (by using an instanceof check against the testsuite's ApolloServer constructor and the actual instance provided by the testsuite consumer).
Fixes #7109
> Integration testsuite direct dependency on Apollo Server

- .changeset/config.json
Changeset's default behavior is to update/narrow internal peer deps, which isn't desirable for the plugin response cache. This should keep the peer dep unchanged until a major version.
> Only update peer deps (response cache dep on AS) when out of range

- CHANGELOG.md
- packages/apollo-server-types/src/index.ts
We ran into issues where AS4 + old Gateway + transitively included AS3.11.0 would be surprised that this field wasn't provided. So just make it optional.
> Make newly-added GraphQLRequestContext.requestIsBatched field optional

- .changeset/clever-camels-judge.md
- packages/gateway-interface/src/index.ts
- packages/server/src/utils/makeGatewayGraphQLRequestContext.ts
This field was added today in v3.11.0 and v4.1.0. That means that if you
installed an older version of Gateway that gets its types from AS3
rather than from `@apollo/server-gateway-interface` it would suddenly
start expecting this field on its GraphQLRequestContext.
We fixed that problem by releasing v3.11.1 which makes the field
optional. But it still seems reasonable to provide it if it's
available... but we keep the field optional in the compatibility
interface so that new Gateway doesn't end up requiring new Server.
> Provide new requestIsBatched field to gateway compatibility layer

- docs/source/integrations/integration-index.mdx
We just released version v1.0.0 of [@as-integrations/next](https://www.npmjs.com/package/@as-integrations/next) so I was hoping we could add the integration to the docs.
> Add Next.js integration to docs

- cspell-dict.txt
- docs/source/config.json
- docs/source/migration.mdx
- docs/source/other-versions.mdx
- docs/source/previous-versions.mdx
This links to migration guides and provides the current release phase status on each version.
> docs: Add "previous versions" page

- docs/source/migration.mdx
- Change description of future to the present
- Update sample Lambda code to include `start` as recommended
- Replace some references to `integration-collaborators` issues with the integration index page now that more exist
> docs: some migration tweaks

- docs/source/api/express-middleware.mdx
- docs/source/api/plugin/landing-pages.mdx
- docs/source/api/plugin/usage-reporting.mdx
- docs/source/data/subscriptions.mdx
- docs/source/deployment/heroku.md
- docs/source/getting-started.mdx
- docs/source/monitoring/metrics.mdx
- docs/source/security/cors.mdx
- docs/source/workflow/build-run-queries.mdx
- docs/source/workflow/generate-types.mdx
Almost all of these are handled via redirects, but this gets them out of the broken link report
> Fix 'broken' links

- smoke-test/smoke-test.sh
gateway@0.54.0 no longer has `<18` in `engines.node` so installing `0.x` won't completely screw up on Node 18.
This should unblock npm v9 upgrade when we want to take it.
> smoke-test: remove weird --node-version hack

- .changeset/stale-ligers-impress.md
- docs/source/api/standalone.mdx
- packages/server/src/__tests__/standalone/standaloneSpecific.test.ts
- packages/server/src/standalone/index.ts
In `apollo-server`, the default limit for the `body-parser` package was `50mb`. This restores the previous limit and adds a test to confirm it remains at least > the default (100KiB).
> Increase default `body-parser` limit for standalone server

- .changeset/good-pets-begin.md
- .changeset/tidy-eggs-turn.md
- docs/source/migration.mdx
- package-lock.json
- packages/integration-testsuite/package.json
- packages/integration-testsuite/src/httpSpecTests.ts
- packages/integration-testsuite/src/index.ts
- packages/server/src/runHttpQuery.ts
This PR adds the spec audit suite from `graphql-http` (designed to validate compatibility with the "GraphQL over HTTP" specification) to the integration test suite. It expects all required (MUST) audits to pass, and for all optional (MAY/SHOULD) audits to pass that we haven't explicitly excepted.
All required audits already passed. Failing optional audits fell into three categories:
- Ignoring `operationName`, `variables`, and `extensions` when provided with incorrect types instead of returning a 400 error. The SHOULD here seemed reasonable and so this PR changes our POST handler to return 400s if incorrect types are provided here. As described in the changeset, this is backwards incompatible but we are comfortable making this choice today.
- Returning 400 errors for various error …
> Stricter JSON body validation; run graphql-over-HTTP test suite

- .changeset/tiny-deers-compare.md
- packages/integration-testsuite/src/apolloServerTests.ts
- packages/server/src/requestPipeline.ts
Adding `BAD_USER_INPUT` is a nice default (and overrides the inappropriate default of `INTERNAL_SERVER_ERROR`) but if somebody has set a `code` already, we shouldn't override.
(Note that there's a separate issue where graphql-js throws out extensions from the thrown error itself and only pays attention to extensions on the error's originalError; we're trying to fix that in https://github.com/graphql/graphql-js/pull/3785 but this is orthogonal.)
Fixes #7178.
> Don't override custom code extensions from scalar parseValue errors

- .changeset/red-cats-clap.md
- package-lock.json
- packages/integration-testsuite/package.json
- packages/server/src/runHttpQuery.ts
In v4.2.0 (#7171) we changed POST handling to be stricter if `operationName`, `variables`, or `extensions` were provided with a surprising data type. This was intended to pass more of the optional recommendations of the GraphQL Over HTTP spec as tested by the graphql-http audit suite. However, we were overzealous and also banned providing these parameters as an explicit `null`, which is documented by the spec as legitimate. (And some clients, such as FIXME, actually send `variables: null` in practice.)
We added explicit tests for this to the `graphql-http` test suite (https://github.com/graphql/graphql-http/pull/28) and this commit allows these `null`s again.
Fixes #7200.
> Fix v4.2.0 regression in `variables: null` (et al)

- docs/source/api/plugin/landing-pages.mdx
there is no include cookies toggle exposed to the sandbox user
> remove 'current user settings' on landing page docs

- .changeset/good-schools-glow.md
- packages/server/src/plugin/usageReporting/plugin.ts
support for `Cloudflare Workers`
ref: https://github.com/apollographql/apollo-server/issues/6034
> refactor: use Promise constructor to wrap builtin gzip

- .changeset/kind-drinks-carry.md
- packages/integration-testsuite/src/apolloServerTests.ts
- packages/server/src/runHttpQuery.ts
support for `Cloudflare Workers`
ref: https://github.com/apollographql/apollo-server/issues/6034
> refactor: remove WHATWG URL, URLSearchParams imports, use globals

- .changeset/fluffy-hats-guess.md
- cspell-dict.txt
- packages/server/src/__tests__/plugin/drainHttpServer/stoppable.test.ts
- packages/server/src/__tests__/plugin/drainHttpServer/stoppable/server.js
- packages/server/src/plugin/drainHttpServer/index.ts
- packages/server/src/plugin/drainHttpServer/stoppable.ts
We've had a lot of issues where `stoppable` tests are flaky because they depend on measuring the time that something takes and hoping it's relatively close to a particular timeout that's supposed to be "controlling" the observed behavior.
This PR refactors the internal Stoppable object so that instead of taking a millisecond timeout value, it takes a DOM-style AbortSignal. This object is only used by ApolloServerPluginDrainHttpServer; we move the setTimeout from inside Stoppable into that plugin, which now creates an AbortController polyfilled from `node-abort-controller` (like we already are in the usage reporting plugin; note that once we drop Node v14 support we can switch to the built-in implementation).
Now the Stoppable test can control the grace period directly via AbortSignals …
> De-flake `stoppable` tests

- .changeset/fifty-eyes-chew.md
- .changeset/selfish-buckets-mate.md
- .changeset/sour-kiwis-eat.md
- docs/source/api/apollo-server.mdx
- package-lock.json
- packages/gateway-interface/package.json
- packages/integration-testsuite/package.json
- packages/plugin-response-cache/package.json
- packages/server/package.json
- packages/server/src/ApolloServer.ts
- packages/server/src/externalTypes/constructor.ts
- packages/server/src/requestPipeline.ts
- Explicitly allow people to pass `cache: 'bounded'`. Non-TS users upgrading from the recommended AS3.9+ configuration could do this by accident. Fixes #7240.
- Upgrade `@apollo/utils.keyvaluecache` so that the new `PrefixingKeyValueCache.cacheDangerouslyDoesNotNeedPrefixesForIsolation` feature lets you disable prefixing for the APQ and full response caches. Throw if you try to pass such a cache to `ApolloServer` itself because that cache is designed to be shared across features. Migrate off of PrefixingKeyValueCache for `documentStore` so that its prefixing can't be disabled. Fixes #6742.
> Two unrelated small cache improvements

- docs/source/data/fetching-data.mdx
A pull request to add a new package to the Open-source implementations. This is a typescript first Apollo Server 4 evolution of the SQLDataSource which allows developers to easily add DataLoaders to their Knex.js queries without bloating all the code.
The package can be seen here:
https://www.npmjs.com/package/@nic-jennings/sql-datasource
Github Repository is here:
https://github.com/nic-jennings/batched-sql-datasource
A write-up of the benefits can be seen here (Example was created  before the upgrade to Apollo Server 3):
https://betterprogramming.pub/batching-your-apollo-sql-datasources-is-invaluable-2d264a17df20
> Add BatchedSQLDataSource to Apollo Docs

- .changeset/quiet-pears-float.md
- packages/server/src/__tests__/plugin/schemaIsSubgraph.test.ts
- packages/server/src/plugin/schemaIsSubgraph.ts
Related to https://github.com/apollographql/apollo-federation-subgraph-compatibility/pull/302
We found a discrepancy in how libraries implement the federation specification (`_Service.sdl` is `String` in Federation 1 and is `String` in Federation 2). 
I'm doing this PR mostly to check how easy it would be to support both specs at once, if I understood correctly the code `schemaIsSubgraph` might also be used outside Apollo Server 😊
> Update `schemaIsSubgraph` to also support non nullable `_Service.sdl`

- docs/source/workflow/requests.md
> Add opt-in instructions for defer/stream usage

- docs/source/deployment/lambda.mdx
I was running into an error when trying to use the sample serverless event verbatim. Adding an empty object as query params fixed it for me.
Error:
```{
"statusCode": 400,
"body": "Search params not parsable from event"
}
``` 
Serverless version Framework Core: 3.22.0 (local) 3.26.0 (global)
> Add queryStringParams to sample event

- docs/source/using-federation/api/apollo-gateway.mdx
The link on the [gateway API reference](https://www.apollographql.com/docs/apollo-server/using-federation/api/apollo-gateway/#class-introspectandcompose) takes you to the [graph router page](https://www.apollographql.com/docs/federation/building-supergraphs/router#limitations-of-introspectandcompose) which doesn't actually contain that section. Updates link to the [gateway setup page](https://www.apollographql.com/docs/apollo-server/using-federation/apollo-gateway-setup#limitations-of-introspectandcompose) which has the section.
> Fix doc link for Limitations of IntrospectAndCompose

- .changeset/nine-shoes-train.md
- packages/integration-testsuite/src/httpServerTests.ts
We once broke this (by dropping support for `variables: null`). Let's be explicit.
Fixes #7202.
> Add integration test for Rover's introspection command

- .github/ISSUE_TEMPLATE/feature-request.md
- .github/PULL_REQUEST_TEMPLATE.md
I believe our intention is that people creating issues/PRs delete this
boilerplate text rather than keeping it in the description. However, if
they don't, it's basically invisible because it's interpreted as a
Markdown comment... but it still ends up in the actual merge commit
message if not explicitly deleted. By de-commenting it, it will be more
obvious if it is left in (and we can just delete it in the UI when we
look at the PR).
This is more relevant for PRs than feature request issues but I think
the point still stands.
> De-comment GitHub templates

- .github/workflows/release-pr.yml
Just one fewer place to change when we upgrade Node. Note that right now this changes us from using Node v16 to v18 for release-pr workflows. Supported since v3.5 of the workflow:
https://github.com/actions/setup-node/releases/tag/v3.5.0
> release-pr workflow: use Node version of project

- docs/source/api/express-middleware.mdx
Changing the type to a primitive in the TS example.
[`@typescript-eslint/ban-types`](https://typescript-eslint.io/rules/ban-types/) is part of the [`@typescript-eslint/recommended`](https://typescript-eslint.io/docs/linting/configs#recommended) plugin.
TS example in the docs use the `String` type, but should probably be using the `string` primitive.
> docs: change String type to primitive in TS example

- .changeset/fluffy-rats-fail.md
- packages/server/src/externalTypes/constructor.ts
- packages/server/src/externalTypes/index.ts
Hi there,
I'm developing an in-house graphql framework wrapping around the apollo server. In the framework, I'm trying to create different types (gateway, subgraph or standalone) of apollo server based on some config. Thus the framework need access to all these interfaces.
Thanks for reviewing this PR.
Cheers.
> expose ApolloServerOptions interfaces

- .changeset/blue-planets-juggle.md
- packages/server/src/express4/index.ts
The `expressMiddleware` handler uses a plain `Map` for the headers that results in case sensitive lookup on the headers. This makes the header `Apollo-Query-Plan-Experimental` ineffective when the ApolloServer is used with `expressMiddleware` handler.
Resolves apollographql/federation#2337
> Use HeaderMap instead of plain Map for headers

- .changeset/quiet-pears-float.md
- docs/source/api/plugin/inline-trace.mdx
- packages/integration-testsuite/src/apolloServerTests.ts
Fed v2 updated the subgraph spec to make `_Service.sdl` non-nullable. We should explain this thoroughly in our docs, test for both cases, and update a relevant recent changelog entry. Follow-up to #7274.
Addresses https://github.com/apollographql/apollo-server/pull/7274#discussion_r1061064648
> Expand on non-nullability of `_Service.sdl` field

- .changeset/great-kids-visit.md
- docs/source/integrations/building-integrations.md
- packages/server/src/__tests__/runQuery.test.ts
- packages/server/src/utils/HeaderMap.ts
Related: https://github.com/apollographql/apollo-server/pull/7313
This shouldn't have been allowed by the typings in the first place. Previously, a `Map` was compatible with `HeaderMap` according to TypeScript, so the error wasn't a typing error (when we wanted it to be). Adding an arbitrary class property to the `HeaderMap` class gives us the typing error we'd expect when a `Map` is used in lieu of a `HeaderMap`.
> Add arbitrary property to `HeaderMap` for type differentiation

- .changeset/sharp-boxes-shave.md
- package-lock.json
- packages/server/package.json
- renovate.json5
`node-abort-controller` just released `v3.1.0` with a breaking change that can be pulled in by current Apollo Server users (since the dependency is careted).
We should pin to the previous latest for now and see what comes of https://github.com/southpolesteve/node-abort-controller/issues/39
> Pin `node-abort-controller`

- .changeset/wicked-walls-jump.md
- packages/gateway-interface/src/index.ts
Precursor to:
https://github.com/apollographql/apollo-server/pull/7136
https://github.com/apollographql/federation/pull/2242
This interface needs to be published in order to properly land and publish the required change to gateway, which the Apollo Server change depends on.
> Update gateway metrics interface

- .changeset/tricky-camels-grin.md
- package-lock.json
- packages/integration-testsuite/package.json
- packages/integration-testsuite/src/httpSpecTests.ts
@enisdenjo kindly implemented an off-the-cuff feature request that I made via https://github.com/graphql/graphql-http/pull/49. Now we can filter our expected audit warnings in an explicit and stable way.
> Use new audit IDs from `graphql-http` for filtering acceptable warnings

- docs/source/schema/custom-scalars.mdx
Fixes #7351
The values passed by `serialize` and `parseValue` are of `unknown` type, so we can't assert otherwise in the signature.
> Update custom scalar docs

- .github/workflows/release-pr.yml
Our release GH action currently runs in forks as well. This is made particularly obvious by the fact that the action itself opens a PR which references a bunch of other PRs (so we get additional noise per fork on all of our closed PRs).
Ref: https://github.com/SimenB/apollo-server/pull/298#issuecomment-1404237690
This conditional prevents the action from running anywhere but this repo.
> Add conditional to workflow so it doesn't run on forks

- docs/source/data/fetching-rest.mdx
`willSendRequest` now has a path first argument, which our docs don't currently reflect.
Ref: apollographql/datasource-rest/#152
> Update RESTDataSource docs for correctness

- docs/source/deployment/lambda.mdx
With the v2.0.0 release of `@as-integrations/aws-lambda`, the docs needed updates to reflect the new syntax and requirements. This PR also describes more of the added functionality in the 2.0 release.
There was also an issue with the local event type that slipped through the cracks the first time around due to our runtime type-parsing. The local event we were using for testing was a `ProxyV1` event type, while the `httpApi` spun up by `serverless` was of the `ProxyV2` type. I normalized the example event and integration example to both be the new `V2` event type (as its now necessary to be explicit with v2.0.0). 
Fixes #7327 as `requestContext.http.method` was missing from the event as it was not required in `ProxyV1`, but is in `ProxyV2`
> [Docs] AS Integrations AWS Lambda 2.0.0 Update

- docs/source/data/context.mdx
This pr fixes a typo in which .graphql `String` syntax was used in a typescript file to define a typescript `string` type
> Update context doc

- docs/source/shared/integration-table.mdx
The Cloudflare Workers integration released in NPM. Therefore, I think we should add these package to the documentation.
> doc: Add Cloudflare Workers to the integration list

- .changeset/quick-teachers-tan.md
- packages/server/src/__tests__/plugin/landingPage/getEmbeddedExplorerHTML.test.ts
- packages/server/src/__tests__/plugin/landingPage/getEmbeddedSandboxHTML.test.ts
- packages/server/src/plugin/landingPage/default/getEmbeddedHTML.ts
[JIRA](https://apollographql.atlassian.net/browse/NEBULA-2011)
[Related embed PR](https://github.com/apollographql/embeddable-explorer/pull/215)
This code relies on several other PRs to be approved/merged, so I will keep it as a draft until it is ready.
Users are getting confused because the embedded sandbox doesn't show the `includeCookies` toggle. This toggle should be visible for AS4 users when they are in embedded sandbox.
This adjusts the way the getEmbeddedHTML helpers use the landing page config options. These options should stay the same and the user shouldn't experience any changes to how they need to configure their Apollo Server configuration.
Instead, we use the `includeCookies` value as an initial value for the cookie toggle in explorer, pass it to `initialState`, and turn …
> Show cookie toggle for embedded landing pages

- docs/source/data/fetching-rest.mdx
The docs for `@apollo/datasource-rest` are missing info about how to set a timeout. While this feature is not directly handled by the Apollo package and instead is really information about how to use the `fetch()` API, we can add this common use case here and link off to MDN for more info.
> [docs] Add docs on how to set a REST timeout

- docs/source/data/fetching-rest.mdx
The code blocks were missing a proper language tag added in https://github.com/apollographql/apollo-server/pull/7373
> [docs] Add codeblock syntax highlights

- docs/source/testing/testing.mdx
missing `response` before accessing `body`
`body.kind` does not exist, we must first access `response` to read the body
First, 🌠 thank you 🌠 for taking the time to consider a contribution to Apollo!
Here are some important details to follow:
* ⏰ Your time is important
To save your precious time, if the contribution you are making will take more
than an hour, please make sure it has been discussed in an issue first.
This is especially true for feature requests!
* 💡 Features
Feature requests can be created and discussed within a GitHub Issue.  Be
sure to search for existing feature requests (and related issues!) prior to
opening a new request.  If an existing issue covers the need, please upvote
that issue by using the 👍 emote, rather than opening a new issue.
* 🔌 Integrations
Apollo Server …
> Fixed typo in testing documentation

- docs/source/migration.mdx
In @apollo/datasource-rest you changed the type from WillSendRequestOptions to AugmentedRequest
This is a very small changed. You updated the documentation in @apollo/datasource-rest Readme, but not here :)
> Docs: Update type in Migration Documentation

- docs/source/api/apollo-server.mdx
This long config option is causing the table's width to exceed its limits, resulting in a really unpleasant hiding of all the useful content in a horizontal scroll window. This limits the width of the cell and forces the word to break to new line instead.
> docs: Add max-width to wide table cell to prevent overflow

- .vscode/tasks.json
Use the user's default via `$SHELL`
> Update vscode launch task to be friendly to non-bash users

- .changeset/kind-yaks-sneeze.md
- packages/server/src/__tests__/plugin/landingPage/getEmbeddedExplorerHTML.test.ts
- packages/server/src/plugin/landingPage/default/getEmbeddedHTML.ts
We added `hideCookieToggle` and `initialState.includeCookies` in the embedded Sandbox config. We then accidentally added `hideCookieToggle` to the embedded Explorer, and we should have only added it to the embedded Sandbox in this repo. 
This PR 
1. puts `includeCookies` back in the embedded Explorer
2. removes `hideCookieToggle` in the embedded Explorer
3. don't spread the entire config into the explorer config, name the arguments
4. remove redundant `?? undefined`s
```
Bug fix: tldr revert a previous change that stops passing includeCookies from the prod landing page config.
Who was affected? 
Any Apollo Server instance that passes a `graphRef` to a production landing page with a non-default `includeCookies` value that does not match the `Include cookies` setting on your registered …
```
> 🐛 Align apollo-server config with state of embeds

- .changeset/polite-poets-teach.md
- packages/server/src/__tests__/plugin/landingPage/getEmbeddedExplorerHTML.test.ts
- packages/server/src/__tests__/plugin/landingPage/getEmbeddedSandboxHTML.test.ts
- packages/server/src/plugin/landingPage/default/getEmbeddedHTML.ts
- packages/server/src/plugin/landingPage/default/index.ts
This pr should be rebased off of https://github.com/apollographql/apollo-server/pull/7432
[JIRA](https://apollographql.atlassian.net/browse/NEBULA-2161?atlOrigin=eyJpIjoiNjRiNTc1ZWIyNTE0NDU3ZWE4ZDZlN2FiOWNlMzI1OTUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
[Slack](https://apollograph.slack.com/archives/C025ENJA19Q/p1678288648578999)
This PR does 2 things
1. passes the packageVersion as query params in the <script tag that requests the embedded Explorer / Sandbox CDN bundle.
2. sends the packageVersion to the embedded Explorer & Sandbox, which are [set up to send these as query params to Studio](https://github.com/apollographql/embeddable-explorer/pull/221). This is redundant data capture just in case.
erm, run the landing pages locally, check the console & see that the version shows up correctly in …
> NEBULA-2161: send package version to embeds

- .changeset/angry-weeks-flash.md
- packages/server/src/__tests__/plugin/landingPage/getEmbeddedExplorerHTML.test.ts
- packages/server/src/__tests__/plugin/landingPage/getEmbeddedSandboxHTML.test.ts
- packages/server/src/plugin/landingPage/default/getEmbeddedHTML.ts
- packages/server/src/plugin/landingPage/default/index.ts
- packages/server/src/plugin/landingPage/default/types.ts
This should be rebased off of [this PR](https://github.com/apollographql/apollo-server/pull/7430), can you do that with forks?
[JIRA](https://apollographql.atlassian.net/browse/NEBULA-2126)
We recently added the ability to 
1. make the embedded Sandbox endpoint static
2. [pass through shared headers](https://apollographql.atlassian.net/browse/NEBULA-2069) https://github.com/apollographql/embeddable-explorer/issues/214
3. [Allow users to embed an operation from a collection](https://apollographql.atlassian.net/browse/NEBULA-2125)
4. [Allow users to decide not to poll for updates initially](https://github.com/apollographql/embeddable-explorer/issues/185)
[in the embeddable-explorer repo](https://github.com/apollographql/embeddable-explorer/pull/220)
So this PR allows users to set the above …
> NEBULA-2126: Add new config options to Sandbox & Explorer landing pages

- .changeset/angry-dogs-tease.md
- packages/plugin-response-cache/src/index.ts
This small change exposes all types used by the response cache plugin, and alow developers to use
```ts
import type { ApolloServerPluginResponseCacheOptions } from "@apollo/server-plugin-response-cache"
```
instead of
```ts
import type { ApolloServerPluginResponseCacheOptions } from "@apollo/server-plugin-response-cache/dist/esm/ApolloServerPluginResponseCache"
```
which is hard to use with ESM imports.
Additionally, it aligns nicer with the style of other packages in this, since it seems to be a pattern to keep everything in `index.ts`
Adjust the import/export in `index.ts`
```ts
export * from './ApolloServerPluginResponseCache.js';
```
> fix: export types form response cache plugin

- docs/source/api/apollo-server.mdx
- docs/source/data/errors.mdx
Hi all! I was working with error handling in my project and wasted a lot of time because I couldn't figure out why I can identify my original error with "instanceof". It wasn't until after some research on StackOverflow that I realized that the original error was wrapped in a GraphQLError. Can we add this detail to the documentation? Thanks, everyone in advance
> docs(format-error): add an explanation that the original error wrapped in GraphQLError

- .github/workflows/lock.yml
Copied from https://github.com/apollographql/apollo-client/pull/10500 (thanks @alessbell!)
Note: this only _locks_ PRs and issues which have already been closed. This does not autoclose anything.
> Add lock workflow to lock closed and stale issues/PRs

- docs/source/api/apollo-server.mdx
Hi all! After merging my previous PR #7443, I noticed that the links on the site are different from the markdown. I updated the link to the actual website page to fix the 404 Page Not Found error. I believe this should work now, but if you can double-check that this link is correct, that would be great! Thank you in advance
> docs(api): replace the markdown relative link with the website relative link

- docs/source/api/apollo-server.mdx
- docs/source/api/express-middleware.mdx
- docs/source/api/plugin/landing-pages.mdx
- docs/source/testing/mocking.mdx
We have a mix of 5# and 6# row cells in our docs. Aligning on 6# at @StephenBarlow's recommendation.
> Align on 6# for API table row cells

- .changeset/purple-paws-yell.md
- docs/source/api/apollo-server.mdx
- docs/source/data/errors.mdx
- docs/source/migration.mdx
- packages/server/src/ApolloServer.ts
- packages/server/src/__tests__/ApolloServer.test.ts
- packages/server/src/externalTypes/constructor.ts
- packages/server/src/requestPipeline.ts
Apollo Server v4 introduced a regression with respect to invalid `variables` and http status codes. AS4 incorrectly started responding with a 200 status code, where AS3 would respond with a 400 when the provided variables object failed variable coercion (during `graphql-js` `execute`).
Providing the following config to your AS4 constructor options will opt-in to the regression mitigation:
```ts
new ApolloServer({
// ...
status400WithErrorsAndNoData: true,
})
```
Fixes #7462
Related discussion #7460
TODO:
> fix: Introduce status code regression mitigation

- docs/source/getting-started.mdx
`npm init` doesn't set the type to module and walking through the quickstart for typescript ends with a typescript compile error
@StephenBarlow I'm curious if you think we should add a little note of why modules has to be set (cc @trevor-scheer)
> Set package.json type to module

- docs/source/data/subscriptions.mdx
https://github.com/enisdenjo/graphql-ws/pull/463
Now hosted on a proper website: https://the-guild.dev/graphql/ws.
> graphql-ws documentation has moved

- .changeset/sweet-planets-hang.md
- packages/server/src/__tests__/plugin/landingPage/getEmbeddedExplorerHTML.test.ts
- packages/server/src/__tests__/plugin/landingPage/getEmbeddedSandboxHTML.test.ts
- packages/server/src/plugin/landingPage/default/getEmbeddedHTML.ts
- packages/server/src/plugin/landingPage/default/index.ts
[Slack context](https://apollograph.slack.com/archives/CR62ZA5E0/p1682974036307769)
Pierre found that in Safari the AS embedded Sandbo str8 up doesn't work ?! How long has this been going on without us knowing? Shocked. 
Anyways, we needed to add a [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) for Safari to take these scripts seriously, and I did so via[ `<meta` tag.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta) using the `nonce` option. 
**To test**
Download the `apollo-server-typescript` code sandbox example & install & run on Safari.
> 🔓 🐛 safelist cdn scripts in meta tag in landing page

- docs/source/performance/cache-backends.mdx
Looks like in the docs, `InMemoryLRUCache` is written that it takes in ms for the ttl. This doesn't seem to be correct within the code itself:
[KeyValueCache takes in seconds](https://github.com/apollographql/apollo-utils/blob/main/packages/keyValueCache/src/KeyValueCache.ts#L9)
[InMemoryLRUCache converts the input into seconds](https://github.com/apollographql/apollo-utils/blob/main/packages/keyValueCache/src/InMemoryLRUCache.ts#L37)
> docs: LRU cache ttl from ms to seconds

- docs/source/performance/apq.md
small docs change that groups the example CDNs with `and` rather than `or`, because they all enable content caching
> docs: s/or/and when listing compatible CDNs

- docs/source/data/fetching-rest.mdx
The heading in the `fetching-rest.mdx` documentation Page was changed in this commit https://github.com/apollographql/apollo-server/commit/191c877aa71e3712c202adfd9757d85c8949ead4#diff-1b1e79b6e6a5fbc493fc168c6dbbdeca02d2ed996086f7b8608234458d3a2e82R147 but an internal link in the same document wasn't updated.
> docs: fix internal link to heading in fetching-rest.mdx

- .changeset/big-hairs-do.md
- package-lock.json
- packages/server/package.json
Previously, installing `@apollo/gateway` and `@apollo/server` could result in duplicate / differently versioned installs of `@apollo/usage-reporting-protobuf`. This is because the `@apollo/server-gateway-interface` package was updated to use the latest protobuf, but the `@apollo/utils.usagereporting` package was not. After this change, users should always end up with a single install of the protobuf package when installing both `@apollo/server` and `@apollo/gateway` latest versions.
> Update `@apollo/utils.usagereporting` dependency

- .changeset/pink-mugs-pump.md
- docs/source/api/plugin/landing-pages.mdx
- packages/server/src/plugin/landingPage/default/index.ts
- packages/server/src/plugin/landingPage/default/types.ts
#7539 introduced a `v4()` call from the `uuid` package which broke CF workers (https://github.com/apollo-server-integrations/apollo-server-integration-cloudflare-workers/issues/37). This change allows users to configure / precompute the `nonce` in advance to avoid making crypto-y calls on startup (which CF workers throws errors about).
> Allow landing page to be configured with a precomputed nonce (fix for CF workers)

- .changeset/lucky-experts-cheat.md
- package-lock.json
- package.json
- packages/integration-testsuite/package.json
specify it in the main package.json so to alleviate surprises in the future.
```
cookiejar  <2.1.4
Severity: moderate
cookiejar Regular Expression Denial of Service via Cookie.parse function - https://github.com/advisories/GHSA-h452-7996-h45h
fix available via `npm audit fix`
node_modules/cookiejar
```
`formidable` and `cookiejar` are only used by `superAgent` so we can just verify the current tests using `superAgent`
So Let's run every test!
> chore: small security fix to update superagent

- .eslintrc.cjs
Follow up of this PR -> https://github.com/apollographql/apollo-server/pull/7655
Here we are enabling a eslint rule to disallow this pattern in the future.
Does it work?:
> chore: Enforcing no extraneous dependencies in package.json

- docs/source/schema/unions-interfaces.md
Would solve [this issue](https://github.com/apollographql/apollo-client/issues/9904). I only mention the React case, since the other clients appear to infer this.
> Docs - More clearly point to special web client case

- .changeset/rude-monkeys-pay.md
- packages/server/src/__tests__/plugin/landingPage/plugin.test.ts
- packages/server/src/plugin/landingPage/default/index.ts
Follow-up to https://github.com/apollographql/apollo-server/security/advisories/GHSA-68jh-rf6x-836f
> Add missing `nonce` to `script` tag

- packages/server/README.md
* Update the documentation to include npm install commands for needed Typescript declaration files to prevent errors.
In the process of migrating from apollo-server-express to just using apollo-server v4 I was following the migration guide here: https://www.apollographql.com/docs/apollo-server/migration/#migrate-from-apollo-server-express and when I installed the `cors` package and imported it into my `index.ts` file I got the error shown in the readme.md file below. I believe it is important to include the corresponding Typescript commands to use for other users who will migrate to v4. 
Thanks!
> chore: update documentation to include install commands for typescript

- docs/source/schema/directives.md
This PR clarifies that while you can technically define custom directives across subgraphs you most likely don't want to.
> [docs] Clarify custom directives in subgraphs

- docs/source/migration.mdx
- docs/source/previous-versions.mdx
This updates the stated EOL date for Apollo Server 3 to October 22, 2024.
> Update EOL date

- scripts/deprecate-old-versions.sh
This script needs to run on every AS2/AS3 release and is responsible for ensuring the deprecation message sticks. Once this is approved I'll run this locally just to update the date in the message.
> Update npm deprecation message AS3

- .changeset/gentle-cycles-look.md
- cspell-dict.txt
- jest.config.base.js
- package-lock.json
- package.json
- packages/server/src/__tests__/plugin/inlineTrace/inlineTracePlugin.test.ts
- packages/server/src/plugin/inlineTrace/index.ts
- packages/server/src/plugin/traceTreeBuilder.ts
- packages/server/src/plugin/usageReporting/plugin.ts
Fixes https://github.com/apollographql/apollo-server/issues/4476
Currently, when errors occur while resolving a list item, the trace builder fails to place the error at the correct path and just defaults to the root node with a warning message:
> `Could not find node with path x.y.1, defaulting to put errors on root node.`
This change places these errors at their correct paths and removes the log.
> Fix trace placement for errors occurring in lists

- docs/source/data/subscriptions.mdx
Updating the docs to add Solace PubSub+ as a supported integration for GraphQL subscriptions.
> Update subscriptions.mdx to document support for Solace 

- packages/server/README_landingpages.md
To clarify how this works, there was confusion today
> create README for technical details of landing pages

- docs/source/api/plugin/schema-reporting.mdx
Advise schema reporting plugin users to consider using Rover for a more consistent publishing experience and document how reporting works across multiple deployment instances
> [docs] Update schema-reporting plugin docs

- docs/source/api/plugin/usage-reporting.mdx
- docs/source/monitoring/metrics.mdx
This PR calls out than an enterprise plan is necessary to report metrics from Apollo Server to GraphOS.
> Add enterprise callout

- .gitleaks.toml
This PR updates the Apollo-custom Gitleaks allowlist file at the root of the repo. 
Specifically, this PR allowlists 3 detected values which are linked in comments in the modified TOML file. 
A recent update to the version of Gitleaks the Apollo Security team is using caused additional values to be detected. We have confirmed that these values are not actually secrets. We would like to ignore these detections in the future to prevent noise.
> Update list of benign-positive secret detections

- docs/source/workflow/generate-types.mdx
Fix undefined `MyContext` type in docs
> fix: undefined MyContext

- .changeset/cool-dancers-tickle.md
- docs/source/api/plugin/landing-pages.mdx
- packages/integration-testsuite/src/apolloServerTests.ts
- packages/server/src/__tests__/plugin/landingPage/getEmbeddedExplorerHTML.test.ts
- packages/server/src/__tests__/plugin/landingPage/getEmbeddedSandboxHTML.test.ts
- packages/server/src/plugin/landingPage/default/index.ts
- packages/server/src/plugin/landingPage/default/types.ts
I published these buckets once already. Circle CI changes [here](https://github.com/apollographql/embeddable-explorer/pull/280)
in AS5 we want to pin embeddable code versions. Question - should we pin up to patch decimal, not just major? Just in case?
> Landing Pages: switch from `_latest` to `v*` cdn buckets to pin major versions of landing pages

- .changeset/late-donuts-think.md
- packages/server/src/plugin/schemaReporting/schemaReporter.ts
Fixes #7768
In `packages/server/src/plugin/schemaReporting/schemaReporter.ts`, `SchemaReporter.pollTimer` is typed as `NodeJS.Timer`, it is actually a `NodeJS.Timeout`, so using node 18> types it is incompatible
with `clearTimeout()`.
> Fix type of `SchemaReporter.pollTimer`

- docs/source/api/apollo-server.mdx
- packages/apollo-server-core/src/ApolloServer.ts
- packages/apollo-server-core/src/graphqlOptions.ts
- packages/apollo-server-core/src/requestPipeline.ts
- packages/apollo-server-core/src/runHttpQuery.ts
- packages/apollo-server-core/src/types.ts
- packages/apollo-server-integration-testsuite/src/ApolloServer.ts
This adds a `disableValidation` option to apollo-server-core which will skip the validation step for graphql operations.
> Add dangerouslyDisableValidation option to apollo-server-core

- .changeset/blue-laws-grab.md
- docs/source/api/apollo-server.mdx
- packages/integration-testsuite/src/apolloServerTests.ts
- packages/server/src/ApolloServer.ts
- packages/server/src/externalTypes/constructor.ts
- packages/server/src/requestPipeline.ts
This adds a `disableValidation` option to @apollo/server which will skip the validation step for graphql operations.
> Add dangerouslyDisableValidation option to @apollo/server

- .changeset/fair-squids-unite.md
- packages/server/src/plugin/usageReporting/plugin.ts
Fixes #7798 
In src/plugin/usageReporting/plugin.ts reportTimer is typed as NodeJS.Timer, it is actually a timeout, so using node 18> types it is incompatible with clearInterval()
> Fix type of ApolloServerPluginUsageReporting reportTimer

- .changeset/thirty-hairs-change.md
- packages/server/src/ApolloServer.ts
- packages/server/src/__tests__/ApolloServer.test.ts
- packages/server/src/externalTypes/constructor.ts
- packages/server/src/runHttpQuery.ts
Previously `stringifyResult` had to be synchronous, despite only ever being called from the async context of `runHttpQuery`. This is an issue when the custom stringification function provided by the user through the constructor has to be async, for example when working with very large POJOs one could use [json-stream-stringify](https://github.com/Faleij/json-stream-stringify) because `JSON.stringify` would throw a `RangeError` with `Invalid string length`, the implementation using this library would be:
```ts
stringifyResult: async (value) => {
const stringifyStream = new JsonStreamStringify(value);
let stringified = '';
for await (const chunk of stringifyStream) {
stringified += chunk;
}
return `${stringified}\n`;
}
```
As can be seen here, this requires an async context within the …
> feat: allow `stringifyResult` to return a `Promise<string>`

- docs/source/migration.mdx
Found during a migration from Apollo v3 to Apollo v4 that the health check was returning a false positive before adding the apollo-require-preflight: true header
First, 🌠 thank you 🌠 for taking the time to consider a contribution to Apollo!
Here are some important details to follow:
* ⏰ Your time is important
To save your precious time, if the contribution you are making will take more
than an hour, please make sure it has been discussed in an issue first.
This is especially true for feature requests!
* 💡 Features
Feature requests can be created and discussed within a GitHub Issue.  Be
sure to search for existing feature requests (and related issues!) prior to
opening a new request.  If an existing issue covers the need, please upvote
that issue by using the 👍 emote, rather than opening a …
> Minor improvement to Migration to Apollo Server 4

- docs/source/data/subscriptions.mdx
`graphql-amqp-subscriptions` has already been linked for quite a while on https://github.com/apollographql/graphql-subscriptions
> Add graphql-amqp-subscriptions to docs

- docs/source/integrations/mern.mdx
Going through the MERN Stack tutorial https://www.apollographql.com/docs/apollo-server/integrations/mern
I downloaded the code from the [pre-requisite tutorial](https://www.mongodb.com/languages/mern-stack-tutorial) because that's what _this_ tutorial builds off of. I noticed a few inconsistencies:
- This tutorial uses TS but the MongoDB tutorial uses JS.
- File name inconsistencies 
- Imports
The CodeSandbox example at the end is in TS, but I think that's ok to leave as-is because it can stand-alone on its own.
> Docs: content updates to match MongoDB tutorial

- docs/source/getting-started.mdx
Standardizes button used for CodeSandbox external link, from [this](https://www.apollographql.com/docs/apollo-server/getting-started#complete-example) to [this](https://deploy-preview-7838--apollo-server-docs.netlify.app/getting-started#complete-example)
> docs: Standardize Edit in CodeSandbox button

- docs/source/security/authentication.mdx
Add links to Router docs for those who may land on the page from external or internal direct links
> [docs] Update authentication docs with link to Router

- docs/source/workflow/generate-types.mdx
This change fixes the typescript error in the example of splitting resolvers in multiple files. The `books` and `addBooks` must no be wrapped with a `Queries` or `Mutation` object.
Wrong (screenshot taken from the official docs)
Correct without `Queries` parent key (extracted from the working exampled linked at the end of the markdown file)
> Docs: Fix generate-types syntax

- .changeset/long-crabs-reply.md
- packages/server/src/__tests__/utils/schemaInstrumentation.test.ts
- packages/server/src/utils/schemaInstrumentation.ts
Paired with @bbeesley.
Updates whenResultIsFinished to call callback also on Promise of Array of Promises.
Fixes (partially) https://github.com/apollographql/apollo-server/issues/5372 and https://github.com/apollographql/apollo-server/issues/4667.
The test case we're fixing is `'passes result of Promise of Array of Promises to the callback'`, the other tests test existing behaviour.
The existing bug prevented us from dynamically setting cache hints in the reference resolver depending on the result of an asynchronous operation. We discovered the bug within an integration test. If you @glasser have an idea how to add an integration test and would like to add it, that would be amazing!
> [fix] whenResultIsFinished works on Promise of Array of Promises

- .changeset/bright-needles-suffer.md
- packages/server/src/__tests__/plugin/subscriptionCallback/index.test.ts
- packages/server/src/plugin/subscriptionCallback/index.ts
This PR addresses #7842 .
When configured with an HTTP callback, a terminated subscription does not fully clean up its resources immediately. Namely, the async generator that the subscription object uses is not closed (i.e. `return()` is not called). This means anything that is await-ing that promise will be waiting until the next message comes through the subscription.
The desired behavior is that calling `terminateSubscription` will also end the async generator.
To do this, the async generator is stored as a field in the subscription object, and its `return()` method is called in the `terminateSubscription` method.
> Fix client delay when subscription is terminated

- .changeset/large-ladybugs-breathe.md
- packages/server/src/__tests__/plugin/subscriptionCallback/index.test.ts
- packages/server/src/plugin/subscriptionCallback/index.ts
Currently, the error handling for subscription events is not well-defined in the GraphQL spec, but that doesn't mean we shouldn't handle them! The existing behavior is that an error thrown from a subscription's generator will go uncaught and crash the whole server.
For a transient failure, it may be preferable for consumers that we simply return an error response and continue waiting for more data from the iterator, in case the producer recovers and resumes producing valid data. However, Node's AsyncGenerator terminates once an error is thrown, even if you manually loop calling `iterator.next()`.
This change wraps the iterator consumption in a `try/catch` and closes the subscription when an error is encountered. Propagating the error up to the subscriber will allow them to decide if they …
> Handle failed subscription payloads

- docs/source/data/subscriptions.mdx
I recently work on graphql-pg-subscription package. I see you already add a package that name is graphql-postgres-subscription, which is not properly maintained. It has not typescript support, maxListener support and has large payload problem. So that's why I build this open source package for adding pubsub class with postgres interface.
I will happy if you add this package into your docs. Thanks Apollo Teams.
> Add graphql-pg-subscription package link (A pubsub class for postgres database interface)

- docs/source/integrations/plugins-event-reference.mdx
I couldn't find any articles or docs on how to do this as I was attempting myself to debug an issue for a customer
> [docs] Update docs on where response extensions can be mutated

- .changeset/pretty-buckets-develop.md
- docs/source/api/apollo-server.mdx
- packages/server/package.json
- packages/server/plugin/disableSuggestions/package.json
- packages/server/src/ApolloServer.ts
- packages/server/src/__tests__/plugin/disableSuggestions/disableSuggestions.test.ts
- packages/server/src/externalTypes/constructor.ts
- packages/server/src/internalPlugin.ts
- packages/server/src/plugin/disableSuggestions/index.ts
It was previously discussed (see: https://github.com/apollographql/apollo-server/issues/3919) to wait for https://github.com/graphql/graphql-js/issues/2247 to close, however, that issue has not moved in years and in the mean time libraries and frameworks seem to have opted for implementing their own solutions (E.g. https://github.com/Escape-Technologies/graphql-armor/blob/main/packages/plugins/block-field-suggestions/src/index.ts).
This should be a very low impact change that achieves the goal that would also be easy enough to rip out if this gets properly implemented in graphql-js later.
Adds `hideSchemaDetailsFromClientErrors` option to ApolloServer to allow hiding of these suggestions.
Before: `Cannot query field "helloo" on type "Query". Did you mean "hello"?`
After: `Cannot query …
> Hide "did you mean" suggestions via internal plugin to avoid leaking schema information

- docs/source/performance/cache-backends.mdx
The `@apollo/utils.keyvadapter` package was updated in https://github.com/apollographql/apollo-utils/pull/461 to be compatible with Keyv v5. The primary change is that the `Keyv` constructor takes a store instead of a string.
The constructor can be invoked in two ways:
```
// passed as first argument
new Keyv(new KeyvRedis("redis://..."))
// passed as store
new Keyv({ store: new KeyvRedis("redis://...") })
```
This updates the Redis examples in the documentation to match the new API. For simplicity, I've stuck to the first format.
> Update redis connection docs to match latest Keyv API

- docs/source/getting-started.mdx
- docs/source/using-federation/apollo-subgraph-setup.mdx
Remove outdated `// preserve-line` comments
> docs: delete preserve-line comments

- .changeset/young-guests-joke.md
- package-lock.json
- package.json
- packages/integration-testsuite/package.json
- packages/server/package.json
`@apollo/server` depends on `express` which depends on `cookie`. Versions of `express` older than v4.21.1 depend on a version of `cookie` vulnerable to CVE-2024-47764. Users of older `express` versions who call `res.cookie()` or `res.clearCookie()` may be vulnerable to this issue.
However, Apollo Server does not call this function directly, and it does not expose any object to user code that allows TypeScript users to call this function without an unsafe cast.
The only way that this direct dependency can cause a vulnerability for users of Apollo Server is if you call `startStandaloneServer` with a context function that calls Express-specific methods such as `res.cookie()` or `res.clearCookies()` on the response object, which is a violation of the TypeScript types provided by …
> deps: upgrade express to v4.21.1 to quiet automated scans

- renovate.json5
Apollo Server 4 claims to support Node v14 and v16 (which are EOL), but many of our dependencies do not in their recent versions. Tell Renovate not to try to upgrade them.
(At some point we'll put out an AS5 which drops support for these old Node versions, which will let us upgrade all our deps again.)
> renovate: pin some packages for Node version reasons

- renovate.json5
This is like #7967 but without losing formatting and comments.
Note that for node-fetch, we don't actually need patterns, just names.
> renovate: update config to newer configuration versions

- jest.config.base.js
- package-lock.json
- package.json
- renovate.json5
At some point the version of Jest we ran didn't support prettier 3, but now it does.
> tests: drop prettier-2

- renovate.json5
v5 isn't "latest" yet for express itself but it will be soon and it is already for the DefinitelyTyped packages.
See #7928.
> renovate: keep Express at v4

- .changeset/khaki-socks-obey.md
- cspell-dict.txt
- package-lock.json
- package.json
- packages/integration-testsuite/package.json
- packages/plugin-response-cache/package.json
- packages/server/package.json
For compatibility with Next.js Turbopack.
Fixes #8004.
> Upgrade `@apollo/utils.createhash`

- .changeset/thick-seals-tan.md
- docs/source/migration.mdx
- packages/server/src/__tests__/express4/expressSpecific.test.ts
This is a change to ensure that users that migrate to v4 do not run `next()` when the response was already sent.
> docs(migration): return after sending 400

- .changeset/cuddly-tables-turn.md
- packages/server/src/ApolloServer.ts
- packages/server/src/__tests__/validationRules/recursiveSelectionsLimit.test.ts
- packages/server/src/errors/index.ts
- packages/server/src/externalTypes/constructor.ts
- packages/server/src/requestPipeline.ts
- packages/server/src/validationRules/NoIntrospection.ts
- packages/server/src/validationRules/RecursiveSelectionsLimit.ts
- packages/server/src/validationRules/index.ts
Add optional validation to reject operations with many recursive selections
Adds a new graphql-js validation rule to reject operations that recursively request selections above a specified maximum, which is disabled by default. Use configuration option `maxRecursiveSelections=true` to enable with a maximum of 10,000,000, or `maxRecursiveSelections=<number>` for a custom maximum. Enabling this validation can help avoid performance issues with configured validation rules or plugins.
> Add optional validation to reject operations with many recursive selections

- renovate.json5
We are starting on AS5 which will drop this old Node requirement (#7515) but are not there yet!
> renovate: pin more packages that lack Node v14 support

- .changeset/stupid-insects-love.md
- docs/source/api/express-middleware.mdx
- docs/source/api/plugin/drain-http-server.mdx
- docs/source/api/standalone.mdx
- docs/source/data/subscriptions.mdx
- docs/source/deployment/lambda.mdx
- docs/source/integrations/building-integrations.md
- docs/source/integrations/integration-index.mdx
- docs/source/integrations/mern.mdx
- docs/source/migration.mdx
- docs/source/security/cors.mdx
- docs/source/security/terminating-ssl.mdx
- packages/server/README.md
The built-in `expressMiddleware` in `@apollo/server/express4` only supports Express v4, and that's not going to change. But Express v5 is now released.
So we have released separate packages `@as-integrations/express4` and `@as-integrations/express5`. The next major version of Apollo Server will drop the hard-coded built-in integrations, putting all JS web frameworks on the same playing field where you have to install a small integration package to use it.
This PR:
- Documents that the two new packages exist (and that the old export does still work)
- Changes most examples to use the new Express v5 integration
- Changes the AS3 to AS4 migration guide to use the new Express v4 integration (assuming that anyone migrating from AS3 is not on the brand-new version of Express)
Fixes #7928.
> docs: support Express v5, recommend new separate Express packages

- .changeset/clear-dryers-eat.md
- packages/plugin-response-cache/src/ApolloServerPluginResponseCache.ts
- packages/server/src/plugin/usageReporting/plugin.ts
- packages/server/src/requestPipeline.ts
when logger needs to access function context
(e.g. like `pino` does need)
to fix we must properly bind logger .warn/.error method reference on promise when passing it into .catch()
---
Hi, this is a small bugfix. We have been seeing a GraphQL Gateway Node process crash with `unhandledRejection` error when server is under heavy load, couple times a quarter maybe.
Originally I pointed the finger to https://github.com/pinojs/pino/issues/1962 , but the solution is not there.
After discussion, we found potential culprit(s) here. Please review?
> fix(promises): avoid unhandledRejection errors

- docs/source/shared/integration-table.mdx
Include integration with Google Cloud Functions
This was documented in v3 but disappeared from the list of integrations in v4. Googling for it was, ironically, an exercise in frustration.
Eventually happened on https://github.com/apollo-server-integrations/apollo-server-integration-google-cloud-functions
This package is different from the other supported integrations in that it's not prefixed with `@as/` but instead with `/apollo-server-integrations` which seems surprisingly similar, but different. Not sure if this is truly a supported integration or not.
> docs: Add Google Cloud Functions integration

- .codesandbox/ci.json
- .github/ISSUE_TEMPLATE/bug.yml
Having trouble updating it for newer Node versions (not sure how to log in to our org), and the future of the company seems a bit unclear (recent acquisition, CodeSandbox CI seems totally unmaintained). We're on GitHub; people can figure out how to make Git repos.
Fixes #7925.
> Drop reference to old Codesandbox from issue template
